import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  root: { display: "block" },
  list: {
    alignItems: "center",
    display: "flex",
    flexWrap: "wrap",
    gap: "2px",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  item: { alignItems: "center", display: "inline-flex", minWidth: 0 },
  interactive: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorSurfaceInteractiveHover,
      "[data-visual-state=hover]": tokens.colorSurfaceInteractiveHover,
    },
    appearance: "none",
    borderColor: "transparent",
    borderStyle: "solid",
    borderWidth: 0,
    borderRadius: "6px",
    color: tokens.colorContentSecondary,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    gap: "6px",
    height: "24px",
    justifyContent: "center",
    lineHeight: "19.5px",
    margin: 0,
    minWidth: 0,
    outline: "none",
    paddingBlock: "2px",
    paddingInline: "4px",
    textDecoration: "none",
    transition: "background-color 120ms ease, color 120ms ease",
    "::selection": { backgroundColor: "transparent" },
    ":focus-visible": { boxShadow: `0 0 0 2px ${tokens.colorFocusRing}` },
    "[data-visual-state=focus-visible]": {
      boxShadow: `0 0 0 2px ${tokens.colorFocusRing}`,
    },
    ":disabled": { cursor: "default", opacity: 0.4 },
    "[aria-disabled=true]": { cursor: "default", opacity: 0.4 },
  },
  page: {
    alignItems: "center",
    borderRadius: "6px",
    color: tokens.colorContentPrimary,
    display: "inline-flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 500,
    gap: "6px",
    height: "24px",
    lineHeight: "19.5px",
    minWidth: 0,
    paddingBlock: "2px",
    paddingInline: "4px",
  },
  separator: {
    alignItems: "center",
    color: tokens.colorContentTertiary,
    display: "inline-flex",
    flexShrink: 0,
    height: "24px",
    justifyContent: "center",
    width: "12px",
  },
  separatorIcon: { height: "9.25px", width: "5.25px" },
  ellipsis: { fontSize: "13px", lineHeight: "19.5px", minWidth: "22px" },
  icon: {
    alignItems: "center",
    color: tokens.colorContentTertiary,
    display: "inline-flex",
    flexShrink: 0,
    height: "14px",
    justifyContent: "center",
    width: "14px",
  },
});
