import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  stage: {
    alignItems: "center",
    display: "flex",
    height: "520px",
    justifyContent: "center",
    overflow: "hidden",
    padding: "10px",
    "@media (max-width: 720px)": { padding: "8px" },
  },
  frame: {
    borderColor: "var(--color-border-tertiary)",
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: "9px",
    height: "500px",
    overflow: "hidden",
    width: "100%",
  },
  page: {
    marginInline: "auto",
    maxWidth: "690px",
    padding: "34px 28px 50px",
    width: "100%",
    "@media (max-width: 720px)": { padding: "24px 18px" },
  },
  pageHeading: {
    borderBottomColor: "var(--console-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    paddingBottom: "24px",
  },
  pageTitle: { fontSize: "20px", fontWeight: 600, lineHeight: 1.3, margin: "8px 0 4px" },
  pageDescription: { color: "var(--console-muted)", fontSize: "12px", lineHeight: 1.5, margin: 0 },
  path: { color: "var(--console-muted)", fontSize: "11px" },
  pageSection: { marginTop: "26px" },
  sectionTitle: { fontSize: "14px", fontWeight: 600, margin: "0 0 12px" },
  focus: {
    borderBottomColor: "var(--console-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    paddingBlock: "22px 24px",
  },
  focusLabel: { color: "var(--console-muted)", fontSize: "11px" },
  focusTitle: { fontSize: "17px", fontWeight: 600, margin: "5px 0" },
  focusDescription: { color: "var(--console-muted)", fontSize: "12px", lineHeight: 1.5, margin: 0 },
  rows: { display: "grid" },
  row: {
    alignItems: "center",
    borderBottomColor: "var(--console-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: "12px",
    justifyContent: "space-between",
    minHeight: "54px",
  },
  rowCopy: { display: "grid", gap: "3px", minWidth: 0 },
  rowTitle: { fontSize: "12px", fontWeight: 550 },
  rowDetail: {
    color: "var(--console-muted)",
    fontSize: "11px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowArrow: { color: "var(--console-accent)", fontSize: "15px" },
  sidebarIdentity: {
    alignItems: "center",
    display: "flex",
    gap: "10px",
    padding: "4px 8px 12px",
  },
  sidebarIdentityCopy: { display: "grid", gap: "2px" },
  sidebarIdentityTitle: { fontSize: "13px", fontWeight: 600 },
  sidebarIdentityDetail: { color: "var(--console-muted)", fontSize: "11px" },
  sidebarFooter: {
    borderTopColor: "var(--console-line)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--console-text)",
    fontSize: "11px",
    fontWeight: 600,
    marginTop: "130px",
    padding: "12px 8px",
  },
  sidebarFooterDetail: {
    color: "var(--console-muted)",
    display: "block",
    fontWeight: 400,
    marginTop: "2px",
  },
  featured: {
    paddingTop: "24px",
  },
  featuredTitle: { fontSize: "14px", fontWeight: 600, margin: "22px 0 10px" },
  featuredArt: {
    alignItems: "center",
    background: "linear-gradient(115deg, #6b68bc, #c3a1d5 48%, #879dc7)",
    borderRadius: "14px",
    color: "white",
    display: "flex",
    gap: "11px",
    height: "105px",
    justifyContent: "center",
  },
  featuredArtLabel: {
    backgroundColor: "#ffffffde",
    borderRadius: "20px",
    color: "#38304a",
    fontSize: "12px",
    padding: "8px 13px",
  },
});
