import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  stage: {
    "--page-layout-glyph-muted": "var(--color-content-tertiary)",
    "--page-layout-glyph-strong": "var(--color-content-secondary)",
    "--page-layout-rail-surface": "var(--color-surface-level3)",
    "--page-layout-workspace-chevron": "var(--color-content-tertiary)",
    alignItems: "center",
    boxSizing: "border-box",
    display: "flex",
    height: "500px",
    justifyContent: "center",
    overflow: "hidden",
    paddingBlock: "12px",
    "@media (max-width: 1100px)": { minHeight: "430px" },
  },
  lightStage: {
    "--color-content-primary": "#000",
    "--color-content-secondary": "#333",
    "--color-content-tertiary": "#707070",
    "--color-sidebar-item-active": "#e1e1e1",
    "--color-sidebar-item-hover": "#e7e7e7",
    "--color-surface-sidebar": "#ececec",
    "--page-layout-glyph-muted": "#707070",
    "--page-layout-glyph-strong": "#333",
    "--page-layout-rail-surface": "var(--color-surface-sidebar)",
    "--page-layout-workspace-chevron": "#64666a",
  },
  darkStage: {
    "--color-sidebar-item-active": "#282828",
    "--color-sidebar-item-hover": "#181818",
    "--color-surface-sidebar": "#0a0a0a",
  },
  previewContainer: {
    alignItems: "center",
    display: "flex",
    height: "100%",
    justifyContent: "center",
    minWidth: 0,
    width: "100%",
  },
  previewViewport: {
    aspectRatio: "16 / 9",
    overflow: "hidden",
    position: "relative",
    width: "min(100%, 846.222px)",
  },
  compactPreviewViewport: {
    aspectRatio: "390 / 720",
    height: "100%",
    maxWidth: "100%",
    width: "auto",
  },
  scaleLayer: {
    height: "720px",
    left: 0,
    position: "absolute",
    top: 0,
    transformOrigin: "top left",
    width: "1280px",
  },
  compactScaleLayer: { width: "390px" },
  shell: {
    backgroundColor: "var(--color-surface-sidebar)",
    display: "grid",
    fontFamily: "var(--font-sans)",
    gridTemplateColumns: "244px minmax(0, 1fr)",
    gridTemplateRows: "minmax(0, 1fr) 36px",
    height: "720px",
    overflow: "hidden",
    position: "relative",
    width: "1280px",
  },
  compactShell: {
    gridTemplateColumns: "48px minmax(0, 1fr)",
    width: "390px",
  },
  sidebarRoot: {
    height: "720px",
    minHeight: 0,
    minWidth: 0,
    width: "196px",
  },
  compactSidebarRoot: {
    height: "720px",
    insetBlock: 0,
    insetInlineStart: "48px",
    overflow: "hidden",
    position: "absolute",
    width: "196px",
    zIndex: 20,
  },
  navigationRegion: {
    display: "flex",
    gridColumn: "1",
    gridRow: "1 / -1",
    height: "720px",
    minHeight: 0,
    width: "244px",
  },
  compactNavigationRegion: { width: "48px" },
  compactNavigationScrim: {
    backgroundColor: "var(--color-surface-scrim)",
    borderWidth: 0,
    insetBlock: 0,
    insetInline: "48px 0",
    opacity: 1,
    padding: 0,
    pointerEvents: "auto",
    position: "absolute",
    transitionDuration: "180ms",
    transitionProperty: "opacity",
    transitionTimingFunction: "cubic-bezier(0.23, 1, 0.32, 1)",
    zIndex: 10,
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "120ms" },
  },
  closedCompactNavigationScrim: { opacity: 0, pointerEvents: "none" },
  primaryRailRoot: {
    flex: "0 0 48px",
    height: "720px",
    minHeight: 0,
    width: "48px",
  },
  primaryRail: {
    alignItems: "center",
    backgroundColor: "var(--page-layout-rail-surface)",
    borderInlineEndColor: "var(--color-border-translucent)",
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: "0.5px",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    height: "720px",
    paddingBlock: "14px 12px",
    width: "48px",
  },
  railWorkspace: {
    alignItems: "center",
    backgroundColor: "var(--color-action-primary)",
    borderColor: "var(--color-border-translucent)",
    borderRadius: "9px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    color: "var(--color-action-primary-content)",
    cursor: "pointer",
    display: "flex",
    fontFamily: "var(--font-sans)",
    fontSize: "11px",
    fontWeight: 600,
    height: "28px",
    justifyContent: "center",
    lineHeight: "16px",
    padding: 0,
    width: "28px",
  },
  railAreas: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    marginBlockStart: "22px",
  },
  railButton: {
    borderRadius: "var(--radius-rounded)",
    color: "var(--color-content-tertiary)",
  },
  activeRailButton: {
    backgroundColor: "var(--color-surface-selected)",
    color: "var(--color-content-primary)",
  },
  railGlyph: { color: "currentColor" },
  railFooter: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    marginBlockStart: "auto",
  },
  railProfile: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-interactive)",
    borderColor: "var(--color-border-secondary)",
    borderRadius: "50%",
    borderStyle: "solid",
    borderWidth: "0.5px",
    color: "var(--color-content-secondary)",
    cursor: "pointer",
    display: "flex",
    fontFamily: "var(--font-sans)",
    fontSize: "8px",
    fontWeight: 600,
    height: "26px",
    justifyContent: "center",
    padding: 0,
    width: "26px",
  },
  contextSidebarPanel: {
    "--size-sidebar": "196px",
    width: "196px",
  },
  compactSidebarPanel: {
    borderInlineEndColor: "var(--color-border-translucent)",
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: "0.5px",
    display: "flex",
    transitionDuration: "200ms",
    transitionProperty: "opacity, transform",
    transitionTimingFunction: "cubic-bezier(0.32, 0.72, 0, 1)",
    willChange: "transform",
    "@media (prefers-reduced-motion: reduce)": {
      transform: "none",
      transitionDuration: "120ms",
    },
  },
  openCompactSidebarPanel: {
    opacity: 1,
    pointerEvents: "auto",
    transform: "translateX(0)",
    "@media (prefers-reduced-motion: reduce)": { opacity: 1, transform: "none" },
  },
  closedCompactSidebarPanel: {
    opacity: 1,
    pointerEvents: "none",
    transform: "translateX(-100%)",
    "@media (prefers-reduced-motion: reduce)": { opacity: 0, transform: "none" },
  },
  contextNavigationTitle: {
    color: "var(--color-content-primary)",
    fontSize: "13px",
    fontWeight: 600,
    lineHeight: "20px",
    marginInlineStart: "10px",
  },
  contextNavigationItem: {
    borderRadius: "var(--radius-rounded)",
    fontSize: "12px",
    fontWeight: 400,
  },
  selectedContextNavigationItem: {
    boxShadow: "inset 0 0 0 0.5px var(--color-border-translucent)",
  },
  contextNavigationSection: {
    gap: "3px",
    marginBlockStart: "18px",
    width: "100%",
  },
  contextNavigationSectionHeader: {
    backgroundColor: { default: "transparent", ":hover": "transparent" },
    height: "24px",
    paddingInline: "10px 4px",
    width: "100%",
  },
  contextNavigationSectionLabel: {
    color: "var(--color-content-tertiary)",
    fontSize: "10px",
    fontWeight: 600,
    letterSpacing: "0.04em",
    lineHeight: "14px",
    textTransform: "uppercase",
  },
  contextNavigationSectionAction: {
    insetBlockStart: 0,
    right: "2px",
  },
  contextNavigationSectionContent: {
    width: "100%",
  },
  onePixelRowOffset: { marginTop: "1px" },
  sidebarGlyph: {
    "--page-layout-glyph-height": "14px",
    "--page-layout-glyph-image": "none",
    "--page-layout-glyph-width": "14px",
    color: "var(--page-layout-glyph-muted)",
    display: "inline-block",
    flex: "0 0 auto",
    height: "16px",
    position: "relative",
    width: "16px",
    "::before": {
      backgroundColor: "currentColor",
      content: '""',
      display: "block",
      height: "var(--page-layout-glyph-height)",
      left: "50%",
      maskImage: "var(--page-layout-glyph-image)",
      maskPosition: "center",
      maskRepeat: "no-repeat",
      maskSize: "100% 100%",
      position: "absolute",
      top: "50%",
      transform: "translate(-50%, -50%)",
      WebkitMaskImage: "var(--page-layout-glyph-image)",
      WebkitMaskPosition: "center",
      WebkitMaskRepeat: "no-repeat",
      WebkitMaskSize: "100% 100%",
      width: "var(--page-layout-glyph-width)",
    },
    "::after": {
      backgroundColor: "currentColor",
      content: '""',
      display: "none",
      position: "absolute",
    },
  },
  nestedGlyph: {
    height: "14px",
    width: "14px",
    "::before": { transform: "translate(-50%, -50%) scale(.875)" },
  },
  strongGlyph: { color: "var(--page-layout-glyph-strong)" },
  addGlyph: { "--page-layout-glyph-image": 'url("/page-layout-icons/add.svg")' },
  agentGlyph: {
    "--page-layout-glyph-height": "12.4528px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/agent.svg")',
    "--page-layout-glyph-width": "11.9725px",
  },
  backGlyphMask: {
    "--page-layout-glyph-height": "9.48814px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/back.svg")',
    "--page-layout-glyph-width": "5.48118px",
  },
  billingGlyph: {
    "--page-layout-glyph-height": "10px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/billing.svg")',
  },
  chatHistoryGlyph: {
    "--page-layout-glyph-image": 'url("/page-layout-icons/chat-history.svg")',
  },
  codeReviewsGlyph: {
    "--page-layout-glyph-height": "14.0223px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/code-reviews.svg")',
    "--page-layout-glyph-width": "14.9994px",
  },
  connectedGlyph: {
    "--page-layout-glyph-height": "12px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/connected.svg")',
    "--page-layout-glyph-width": "12px",
  },
  createGlyph: { "--page-layout-glyph-image": 'url("/page-layout-icons/create.svg")' },
  createTeamGlyph: {
    "--page-layout-glyph-height": "16px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/create-team.svg")',
    "--page-layout-glyph-width": "16px",
  },
  helpGlyph: {
    "--page-layout-glyph-image": 'url("/page-layout-icons/help.svg")',
    color: "var(--color-content-tertiary)",
  },
  homeGlyph: {
    "--page-layout-glyph-height": "12.5751px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/home.svg")',
    "--page-layout-glyph-width": "10.6875px",
  },
  inboxGlyph: {
    "--page-layout-glyph-image": 'url("/page-layout-icons/inbox.svg")',
    "--page-layout-glyph-width": "14.0009px",
  },
  issuesGlyph: { "--page-layout-glyph-image": 'url("/page-layout-icons/issues.svg")' },
  labelGlyph: {
    "--page-layout-glyph-height": "10px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/label.svg")',
    "--page-layout-glyph-width": "14.25px",
  },
  membersGlyph: {
    "--page-layout-glyph-height": "14.0325px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/members.svg")',
    "--page-layout-glyph-width": "14.0086px",
  },
  moreGlyph: {
    "--page-layout-glyph-height": "3px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/more.svg")',
    "--page-layout-glyph-width": "13px",
  },
  notificationsGlyph: {
    "--page-layout-glyph-image": 'url("/page-layout-icons/notifications.svg")',
  },
  preferencesGlyph: {
    "--page-layout-glyph-height": "11.0005px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/preferences.svg")',
  },
  profileGlyph: {
    "--page-layout-glyph-height": "13.9998px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/profile.svg")',
    "--page-layout-glyph-width": "12.0006px",
  },
  projectGlyph: {
    "--page-layout-glyph-height": "14.0015px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/project.svg")',
    "--page-layout-glyph-width": "13px",
  },
  searchGlyph: { "--page-layout-glyph-image": 'url("/page-layout-icons/search.svg")' },
  settingsSearchGlyph: {
    "--page-layout-glyph-height": "16px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/settings-search.svg")',
    "--page-layout-glyph-width": "16px",
  },
  slaGlyph: {
    "--page-layout-glyph-height": "13.5259px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/sla.svg")',
    "--page-layout-glyph-width": "12px",
  },
  templateGlyph: {
    "--page-layout-glyph-image": 'url("/page-layout-icons/template.svg")',
  },
  viewsGlyph: {
    "--page-layout-glyph-height": "12.0069px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/views.svg")',
    "--page-layout-glyph-width": "13.9822px",
  },
  workspaceChevronGlyph: {
    "--page-layout-glyph-height": "8px",
    "--page-layout-glyph-image": 'url("/page-layout-icons/workspace-chevron.svg")',
    "--page-layout-glyph-width": "8px",
    color: "var(--page-layout-workspace-chevron)",
  },
  teamGlyph: {
    "::before": {
      height: "6px",
      left: "3.4048px",
      maskImage: 'url("/page-layout-icons/team-top.svg")',
      top: "3px",
      transform: "none",
      WebkitMaskImage: 'url("/page-layout-icons/team-top.svg")',
      width: "10.3894px",
    },
    "::after": {
      backgroundColor: "currentColor",
      display: "block",
      height: "3.7px",
      left: "3.7008px",
      maskImage: 'url("/page-layout-icons/team-bottom.svg")',
      maskPosition: "center",
      maskRepeat: "no-repeat",
      maskSize: "100% 100%",
      top: "9.3008px",
      WebkitMaskImage: 'url("/page-layout-icons/team-bottom.svg")',
      WebkitMaskPosition: "center",
      WebkitMaskRepeat: "no-repeat",
      WebkitMaskSize: "100% 100%",
      width: "8.6px",
    },
  },
  securityGlyph: {
    "::before": {
      height: "5.41702px",
      left: "4.2736px",
      maskImage: 'url("/page-layout-icons/security-top.svg")',
      top: "1px",
      transform: "none",
      WebkitMaskImage: 'url("/page-layout-icons/security-top.svg")',
      width: "5.303px",
    },
  },
  securityPart: {
    backgroundColor: "currentColor",
    display: "block",
    maskPosition: "center",
    maskRepeat: "no-repeat",
    maskSize: "100% 100%",
    position: "absolute",
    WebkitMaskPosition: "center",
    WebkitMaskRepeat: "no-repeat",
    WebkitMaskSize: "100% 100%",
  },
  securityRight: {
    height: "12.0063px",
    left: "8.9984px",
    maskImage: 'url("/page-layout-icons/security-right.svg")',
    top: "2.9984px",
    WebkitMaskImage: 'url("/page-layout-icons/security-right.svg")',
    width: "6.002px",
  },
  securityBottom: {
    height: "6.52285px",
    left: "1px",
    maskImage: 'url("/page-layout-icons/security-bottom.svg")',
    top: "7.4768px",
    WebkitMaskImage: 'url("/page-layout-icons/security-bottom.svg")',
    width: "9.01px",
  },
  favoriteGlyph: { color: "#c240f0" },
  backGlyph: { height: "14px", width: "14px" },
  main: {
    backgroundColor: "var(--color-surface-canvas)",
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    gridColumn: "2",
    gridRow: "1",
    margin: "8px 8px 0 0",
    minHeight: 0,
    minWidth: 0,
    overflow: "auto",
  },
  compactMain: { gridColumn: "2" },
  utilityBar: {
    alignItems: "center",
    display: "flex",
    gap: "2px",
    gridColumn: "2",
    gridRow: "2",
    justifyContent: "flex-end",
    minWidth: 0,
    padding: "4px 10px 4px 8px",
  },
  utilityButton: {
    borderRadius: "8px",
    color: "var(--color-content-secondary)",
    fontFamily: "var(--font-sans)",
    fontSize: "12px",
    fontWeight: 500,
    gap: "6px",
    lineHeight: "14.5px",
    padding: "0 12px 0 10px",
    width: "76.921875px",
  },
  chatHistoryButton: { borderRadius: "8px" },
  applicationHeader: {
    backgroundColor: "transparent",
    flex: "none",
  },
  compactHidden: { display: "none" },
  compactTabsRow: { overflowX: "auto", scrollbarWidth: "none" },
  pageHeaderGlyph: { color: "var(--color-content-secondary)" },
  applicationBody: {
    display: "grid",
    gap: "24px",
    gridTemplateColumns: "minmax(0, 1fr) 244px",
    paddingBlock: "24px",
    paddingInline: "8px",
  },
  compactApplicationBody: {
    display: "block",
    paddingBlock: "16px",
  },
  applicationBodyWide: {
    paddingBlock: "24px",
    paddingInline: "8px",
  },
  compactApplicationBodyWide: {
    overflowX: "auto",
    paddingBlock: "16px",
  },
  workArea: {
    minWidth: 0,
  },
  workRows: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  workRow: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": "var(--color-surface-overlay-hover)" },
    borderRadius: "8px",
    borderWidth: 0,
    cursor: "pointer",
    display: "grid",
    fontFamily: "var(--font-sans)",
    gap: "10px",
    gridTemplateColumns: "8px minmax(0, 1fr) auto",
    minHeight: "52px",
    paddingBlock: "7px",
    paddingInline: "10px",
    textAlign: "left",
    width: "100%",
  },
  selectedWorkRow: { backgroundColor: "var(--color-surface-selected)" },
  workRowMarker: {
    backgroundColor: "var(--color-content-tertiary)",
    borderRadius: "50%",
    height: "6px",
    width: "6px",
  },
  workRowCopy: { display: "flex", flexDirection: "column", minWidth: 0 },
  workRowLabel: {
    color: "var(--color-content-primary)",
    fontSize: "13px",
    fontWeight: 500,
    lineHeight: "20px",
  },
  workRowMeta: {
    color: "var(--color-content-tertiary)",
    fontSize: "11px",
    lineHeight: "16px",
  },
  workRowStatus: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-level3)",
    borderRadius: "var(--radius-rounded)",
    color: "var(--color-content-secondary)",
    display: "inline-flex",
    fontSize: "10px",
    height: "22px",
    lineHeight: "14px",
    paddingInline: "9px",
  },
  contextPanel: {
    alignSelf: "start",
    backgroundColor: "var(--color-surface-panel)",
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    overflow: "hidden",
  },
  contextHeader: { padding: "15px 16px 14px" },
  contextHeadingRow: {
    alignItems: "flex-start",
    display: "flex",
    gap: "12px",
    justifyContent: "space-between",
  },
  contextTitle: {
    color: "var(--color-content-primary)",
    fontSize: "14px",
    fontWeight: 600,
    lineHeight: "20px",
    margin: 0,
    minWidth: 0,
  },
  contextStatus: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-level3)",
    borderRadius: "var(--radius-rounded)",
    color: "var(--color-content-secondary)",
    display: "inline-flex",
    flexShrink: 0,
    fontSize: "10px",
    height: "22px",
    lineHeight: "14px",
    paddingInline: "8px",
  },
  contextDescription: {
    color: "var(--color-content-tertiary)",
    fontSize: "11px",
    lineHeight: "17px",
    margin: "7px 0 0",
  },
  contextDetailsSection: {
    borderBlockStartColor: "var(--color-border-tertiary)",
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: "0.5px",
    padding: "12px 16px 8px",
  },
  contextSectionLabel: {
    color: "var(--color-content-tertiary)",
    fontSize: "10px",
    fontWeight: 500,
    letterSpacing: "0.02em",
    lineHeight: "14px",
    margin: "0 0 5px",
    textTransform: "uppercase",
  },
  contextDetails: {
    display: "flex",
    flexDirection: "column",
    margin: 0,
  },
  contextDetail: {
    alignItems: "center",
    display: "grid",
    fontSize: "11px",
    gap: "12px",
    gridTemplateColumns: "64px minmax(0, 1fr)",
    minHeight: "30px",
    lineHeight: "16px",
    margin: 0,
  },
  contextTerm: { color: "var(--color-content-tertiary)" },
  contextValue: {
    color: "var(--color-content-secondary)",
    margin: 0,
    overflow: "hidden",
    textAlign: "right",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  contextFooter: {
    borderBlockStartColor: "var(--color-border-tertiary)",
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: "0.5px",
    display: "flex",
    justifyContent: "flex-end",
    padding: "8px",
  },
  contextAction: { minWidth: "auto" },
  dataTable: {
    borderCollapse: "collapse",
    borderBlockStartColor: "var(--color-border-tertiary)",
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: "0.5px",
    width: "100%",
  },
  dataTableCell: {
    fontWeight: "inherit",
    padding: 0,
    textAlign: "start",
  },
  compactDataTable: { minWidth: "620px" },
  dataTableHeader: {
    alignItems: "center",
    color: "var(--color-content-tertiary)",
    display: "grid",
    fontSize: "10px",
    fontWeight: 500,
    gridTemplateColumns: "minmax(220px, 1fr) 180px 120px 96px",
    height: "34px",
    letterSpacing: "0.02em",
    paddingInline: "10px",
    textTransform: "uppercase",
  },
  dataTableRow: {
    alignItems: "center",
    borderBlockStartColor: "var(--color-border-tertiary)",
    borderBlockStartStyle: "solid",
    borderBlockStartWidth: "0.5px",
    color: "var(--color-content-primary)",
    display: "grid",
    fontSize: "12px",
    gridTemplateColumns: "minmax(220px, 1fr) 180px 120px 96px",
    height: "48px",
    paddingInline: "10px",
  },
  dataTableProject: { alignItems: "center", display: "flex", fontWeight: 500, gap: "9px" },
  projectMark: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-level3)",
    borderRadius: "6px",
    color: "var(--color-content-secondary)",
    display: "inline-flex",
    fontSize: "9px",
    height: "22px",
    justifyContent: "center",
    width: "22px",
  },
  dataTableSecondary: { color: "var(--color-content-tertiary)" },
  tableStatus: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-level3)",
    borderRadius: "var(--radius-rounded)",
    color: "var(--color-content-secondary)",
    display: "inline-flex",
    fontSize: "10px",
    height: "22px",
    paddingInline: "9px",
  },
  settingsSidebarPanel: { "--color-content-tertiary": "#707172", padding: 0, position: "relative" },
  backButton: {
    color: "var(--color-content-secondary)",
    fontFamily: "var(--font-sans)",
    fontSize: "13px",
    fontWeight: 500,
    gap: "6px",
    height: "28px",
    justifyContent: "flex-start",
    left: "16px",
    lineHeight: "19.5px",
    padding: "0 12px 0 6px",
    position: "absolute",
    top: "16.25px",
    width: "112.2266px",
    zIndex: 2,
  },
  settingsSearch: {
    color: "var(--color-content-secondary)",
    height: "28px",
    left: "12px",
    position: "absolute",
    top: "56.5px",
    width: "172px",
    zIndex: 2,
  },
  settingsSearchIcon: { left: "7.5px", position: "absolute", top: "5.5px", zIndex: 1 },
  settingsSearchInput: {
    backgroundColor: "var(--color-surface-canvas, #fafafa)",
    borderColor: "var(--color-border-secondary, #d4d4d4)",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: "0 1px 0.5px rgb(0 0 0 / 4%), 0 3px 3px rgb(0 0 0 / 2%)",
    boxSizing: "border-box",
    color: "var(--color-content-primary)",
    fontFamily: "var(--font-sans)",
    fontSize: "13px",
    fontWeight: 500,
    height: "100%",
    lineHeight: "19.5px",
    outline: "none",
    padding: "0 8px 0 31.5px",
    width: "100%",
    "::placeholder": { color: "var(--color-content-tertiary)", opacity: 1 },
    ":focus-visible": { outline: "1px solid var(--color-focus-ring)", outlineOffset: "-1px" },
  },
  settingsNavigation: {
    boxSizing: "border-box",
    height: "635.5px",
    left: 0,
    overflowY: "auto",
    padding: "29px 12px 32px",
    position: "absolute",
    scrollbarWidth: "none",
    top: "84.5px",
    width: "196px",
  },
  settingsGroup: { marginTop: "16px" },
  firstSettingsGroup: { marginTop: 0 },
  settingsGroupLabel: {
    color: "var(--color-content-tertiary)",
    display: "block",
    fontSize: "12px",
    fontWeight: 500,
    height: "16px",
    lineHeight: "15.5px",
    paddingLeft: "10px",
  },
  settingsMenu: { marginTop: "5.5px" },
  settingsEmptyState: {
    color: "var(--color-content-tertiary)",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "18px",
    margin: "12px 10px",
  },
});

export const glyphStyles = {
  add: styles.addGlyph,
  agent: styles.agentGlyph,
  back: styles.backGlyphMask,
  billing: styles.billingGlyph,
  "chat-history": styles.chatHistoryGlyph,
  "code-reviews": styles.codeReviewsGlyph,
  connected: styles.connectedGlyph,
  create: styles.createGlyph,
  "create-team": styles.createTeamGlyph,
  help: styles.helpGlyph,
  home: styles.homeGlyph,
  inbox: styles.inboxGlyph,
  issues: styles.issuesGlyph,
  label: styles.labelGlyph,
  members: styles.membersGlyph,
  more: styles.moreGlyph,
  notifications: styles.notificationsGlyph,
  preferences: styles.preferencesGlyph,
  profile: styles.profileGlyph,
  project: styles.projectGlyph,
  search: styles.searchGlyph,
  security: styles.securityGlyph,
  "settings-search": styles.settingsSearchGlyph,
  sla: styles.slaGlyph,
  team: styles.teamGlyph,
  template: styles.templateGlyph,
  views: styles.viewsGlyph,
  "workspace-chevron": styles.workspaceChevronGlyph,
} as const;
