import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: {
    borderColor: "var(--color-border-tertiary)",
    borderRadius: "var(--radius-panel)",
    borderStyle: "solid",
    borderWidth: "1px",
    height: "208px",
    overflow: "hidden",
    width: "min(100%, 480px)",
  },
  frame: { display: "flex", height: "100%" },
  rightFrame: { flexDirection: "row-reverse" },
  panel: {
    backgroundColor: "var(--color-surface-sidebar)",
    borderColor: "var(--color-border-tertiary)",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
    padding: "12px 8px",
    width: "168px",
  },
  rightPanel: { borderLeftStyle: "solid", borderLeftWidth: "1px", borderRightWidth: 0 },
  header: {
    color: "var(--color-content-tertiary)",
    fontSize: "11px",
    lineHeight: "16px",
    padding: "4px 8px 12px",
  },
  content: { flex: 1 },
  menu: { listStyle: "none", margin: 0, padding: 0 },
  item: {
    backgroundColor: "transparent",
    borderRadius: "var(--radius-navigation)",
    borderStyle: "none",
    color: "var(--color-content-secondary)",
    cursor: "pointer",
    display: "flex",
    fontFamily: "var(--font-sans)",
    fontSize: "13px",
    height: "32px",
    paddingInline: "8px",
    textAlign: "left",
    width: "100%",
  },
  selectedItem: {
    backgroundColor: "var(--color-surface-selected)",
    color: "var(--color-content-primary)",
  },
  inset: {
    backgroundColor: "var(--color-surface-canvas)",
    color: "var(--color-content-primary)",
    flex: 1,
    minWidth: 0,
    padding: "12px",
  },
  trigger: {
    backgroundColor: "transparent",
    borderColor: "var(--color-border-control)",
    borderRadius: "var(--radius-control)",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--color-content-primary)",
    cursor: "pointer",
    fontFamily: "var(--font-sans)",
    fontSize: "12px",
    height: "28px",
    paddingInline: "10px",
  },
  note: {
    color: "var(--color-content-tertiary)",
    fontSize: "12px",
    lineHeight: "18px",
    marginBlock: "18px 0",
  },
});
