import * as stylex from "@stylexjs/stylex";

export const stageStyles = stylex.create({
  canvas: {
    alignItems: "center",
    borderRadius: 0,
    display: "flex",
    height: "100%",
    justifyContent: "center",
    padding: 0,
    position: "relative",
    width: "100%",
  },
  column: { flexDirection: "column", gap: "8px" },
  disclosureList: { display: "flex", flexDirection: "column", gap: "8px" },
  fullWidth: { width: "100%" },
  sidebarPreview: { height: "720px" },
  dialogField: { width: "304px" },
  popoverChevron: { transition: "transform 120ms ease-out" },
  popoverChevronOpen: { transform: "rotate(180deg)" },
  markerRed: { color: "#eb5757" },
  markerPurple: { color: "#bb87fc" },
  markerBlue: { color: "#4ea7fc" },
  pageHeader: { paddingTop: 0 },
  settingsRow: { paddingInline: "16px" },
  tabs: { flexDirection: "column", gap: "24px" },
  resizeHandle: { padding: "20px" },
  tooltip: { minHeight: "208px" },
  popover: { minHeight: "208px" },
  workspaceMenu: { alignItems: "flex-start", paddingTop: "16px" },
  sidebar: { height: "744px", paddingTop: "12px" },
  dialog: { paddingTop: 0 },
  commandMenu: { height: "420px", overflow: "hidden", paddingTop: 0 },
  avatar: { alignItems: "center", gap: "64px", paddingTop: 0 },
  surface: { alignItems: "center", paddingTop: 0 },
  demoButton: { zIndex: 1 },
  resizeDemo: {
    backgroundColor: "var(--color-surface-panel)",
    border: "0.5px solid var(--color-border-tertiary)",
    borderRadius: "var(--radius-control)",
    display: "flex",
    height: "168px",
    overflow: "hidden",
    position: "relative",
    width: "min(100%, 560px)",
  },
  resizeDemoHorizontal: { flexDirection: "column" },
  resizePane: {
    backgroundColor: "var(--color-surface-sidebar)",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    gap: "4px",
    minHeight: 0,
    minWidth: 0,
    padding: "16px",
  },
  resizeContent: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    gap: "4px",
    minHeight: 0,
    minWidth: 0,
    padding: "16px",
  },
  resizeTitle: {
    color: "var(--color-content-primary)",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
  },
  resizeDescription: {
    color: "var(--color-content-tertiary)",
    fontSize: "11px",
    lineHeight: "16px",
  },
  commandMenuPanel: { transform: "scale(0.78)", transformOrigin: "center" },
});
