import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  root: { width: "fit-content" },
  list: {
    alignItems: "center",
    display: "flex",
    gap: "4px",
    height: "28px",
  },
  tab: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: {
      default: tokens.colorNavigationTabBg,
      ":hover": tokens.colorNavigationTabBgHover,
      ":active": tokens.colorNavigationTabBgHover,
      "[data-visual-state=hover]": tokens.colorNavigationTabBgHover,
      "[data-visual-state=pressed]": tokens.colorNavigationTabBgHover,
      "[data-active]": tokens.colorNavigationTabBgSelected,
    },
    borderColor: {
      default: tokens.colorNavigationTabEdge,
      ":hover": tokens.colorNavigationTabEdgeHover,
      ":active": tokens.colorNavigationTabEdgeHover,
      "[data-visual-state=hover]": tokens.colorNavigationTabEdgeHover,
      "[data-visual-state=pressed]": tokens.colorNavigationTabEdgeHover,
      "[data-active]": tokens.colorNavigationTabEdge,
    },
    borderRadius: tokens.radiusRounded,
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxSizing: "border-box",
    color: {
      default: tokens.colorNavigationTabFg,
      ":hover": tokens.colorNavigationTabFgHover,
      ":active": tokens.colorNavigationTabFgHover,
      "[data-visual-state=hover]": tokens.colorNavigationTabFgHover,
      "[data-visual-state=pressed]": tokens.colorNavigationTabFgHover,
      "[data-active]": tokens.colorNavigationTabFgSelected,
    },
    cursor: { default: "pointer", ":disabled": "default" },
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: tokens.fontSans,
    fontSize: "12px",
    fontWeight: 500,
    height: "28px",
    justifyContent: "center",
    lineHeight: "16px",
    opacity: { default: 1, "[data-disabled]:not([data-active])": 0.6 },
    outline: {
      default: "none",
      ":focus-visible": `1px solid ${tokens.colorFocusRing}`,
      "[data-visual-state=focus-visible]": `1px solid ${tokens.colorFocusRing}`,
    },
    outlineOffset: "-1px",
    paddingBlock: 0,
    paddingInline: "10px",
    position: "relative",
    transitionDuration: "150ms",
    transitionProperty: "background-color, border-color, color, opacity",
    transitionTimingFunction: "ease-out",
    whiteSpace: "nowrap",
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
  panel: { outline: "none" },
});
