import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  root: { width: "fit-content" },
  list: {
    alignItems: "center",
    borderBottomColor: tokens.colorBorderTertiary,
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: tokens.space4,
    minHeight: tokens.sizeControlDefault,
  },
  compactList: { borderBottomWidth: 0, gap: tokens.spaceHalf },
  tab: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "solid",
    borderWidth: 0,
    borderBottomColor: {
      default: "transparent",
      "[data-active]": tokens.colorNavigationTabFgSelected,
    },
    borderBottomStyle: "solid",
    borderBottomWidth: "2px",
    boxSizing: "border-box",
    color: {
      default: tokens.colorNavigationTabFg,
      ":hover": tokens.colorNavigationTabFgHover,
      ":active": tokens.colorNavigationTabFgHover,
      "[data-visual-state=hover]": tokens.colorNavigationTabFgHover,
      "[data-visual-state=pressed]": tokens.colorNavigationTabFgHover,
      "[data-active]": tokens.colorNavigationTabFgSelected,
    },
    cursor: { default: "pointer", ":disabled": "default" },
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: tokens.fontSans,
    fontSize: tokens.typeLabelSize,
    fontWeight: 500,
    minHeight: tokens.sizeControlDefault,
    justifyContent: "center",
    lineHeight: tokens.typeLabelLineHeight,
    marginBottom: "-1px",
    opacity: { default: 1, "[data-disabled]:not([data-active])": 0.6 },
    outline: {
      default: "none",
      ":focus-visible": `1px solid ${tokens.colorFocusRing}`,
      "[data-visual-state=focus-visible]": `1px solid ${tokens.colorFocusRing}`,
    },
    outlineOffset: "-1px",
    paddingBlock: 0,
    paddingInline: "2px",
    transitionDuration: tokens.motionFeedback,
    transitionProperty: "border-color, color, opacity",
    transitionTimingFunction: "ease-out",
    whiteSpace: "nowrap",
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
  compactTab: {
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorNavigationTabBgHover,
      ":active": tokens.colorNavigationTabBgHover,
      "[data-visual-state=hover]": tokens.colorNavigationTabBgHover,
      "[data-visual-state=pressed]": tokens.colorNavigationTabBgHover,
      "[data-active]": tokens.colorNavigationTabBgSelected,
    },
    borderBottomWidth: 0,
    borderRadius: tokens.radiusNavigation,
    fontSize: tokens.typeNavigationSize,
    fontWeight: tokens.typeNavigationWeight,
    gap: tokens.spaceInlineIconGap,
    height: tokens.sizeControlDefault,
    lineHeight: tokens.typeNavigationLineHeight,
    marginBottom: 0,
    paddingInline: tokens.space3,
    transitionProperty: "background-color, color, opacity",
  },
  panel: { outline: "none" },
});
