// Adapted from HeroUI v3.2.6 (e385ac2), Apache-2.0.
import * as stylex from "@stylexjs/stylex";
import { tokens } from "../../tokens.stylex.const.js";
const settledIndicator = stylex.keyframes({
  "0%": { opacity: 0, scale: ".92" },
  "75%": { opacity: 1 },
  "100%": { opacity: 1, scale: "1" },
});
export const toastStyles = stylex.create({
  viewport: {
    position: "fixed",
    zIndex: tokens.zIndexToast,
    pointerEvents: "none",
    width: {
      default: "calc(100vw - 32px)",
      "@media (min-width: 640px)": "var(--toast-width, 356px)",
    },
    outline: "none",
    outlineWidth: { default: 0, ":focus-visible": 2 },
    outlineStyle: "solid",
    outlineColor: tokens.focus,
    outlineOffset: 2,
  },
  root: {
    boxSizing: "border-box",
    position: "absolute",
    bottom: { default: 0, ':is([data-placement^="top"])': "auto" },
    top: { default: "auto", ':is([data-placement^="top"])': 0 },
    insetInline: 0,
    display: "flex",
    alignItems: "flex-start",
    gap: 6,
    paddingInline: 16,
    paddingBlock: 12,
    borderRadius: "min(32px, var(--radius-3xl))",
    backgroundColor: tokens.surface,
    color: tokens.overlayForeground,
    boxShadow: tokens.shadowOverlay,
    zIndex: "calc(100 - var(--toast-index))",
    "--toast-direction": { default: -1, ':is([data-placement^="top"])': 1 },
    "--toast-title-color": {
      default: tokens.overlayForeground,
      ':is([data-variant="accent"])': tokens.accentSoftForeground,
      ':is([data-variant="success"])': tokens.successSoftForeground,
      ':is([data-variant="warning"])': tokens.warningSoftForeground,
      ':is([data-variant="danger"])': tokens.dangerSoftForeground,
    },
    "--toast-indicator-color": {
      default: tokens.overlayForeground,
      ':is([data-variant="success"])': tokens.successSoftForeground,
      ':is([data-variant="warning"])': tokens.warningSoftForeground,
      ':is([data-variant="danger"])': tokens.dangerSoftForeground,
    },
    "--toast-content-opacity": {
      default: 1,
      ":not([data-frontmost]):not([data-expanded]):not([data-layout-expanded])": 0,
    },
    "--toast-close-opacity": {
      default: 0,
      ":hover:is([data-frontmost],[data-expanded],[data-layout-expanded])": 1,
      ":focus-within": 1,
      ":is([data-ending-style],[data-limited])": 0,
    },
    height: {
      default: "var(--toast-height, auto)",
      ":not([data-frontmost]):not([data-expanded]):not([data-layout-expanded])":
        "var(--front-height, var(--toast-height, auto))",
    },
    outlineWidth: { default: 0, ":focus-visible": 2 },
    outlineStyle: "solid",
    outlineColor: tokens.focus,
    outlineOffset: 2,
    overflow: {
      default: "visible",
      ":not([data-frontmost]):not([data-expanded]):not([data-layout-expanded])": "hidden",
    },
    transform: {
      default:
        "translate(var(--toast-swipe-movement-x, 0px), calc(var(--toast-swipe-movement-y, 0px) + var(--toast-direction) * var(--toast-index) * 12px)) scale(calc(1 - var(--toast-index) * .05))",
      ":is([data-expanded],[data-layout-expanded])":
        "translate(var(--toast-swipe-movement-x, 0px), calc(var(--toast-swipe-movement-y, 0px) + var(--toast-direction) * var(--toast-offset-y)))",
      ":is([data-starting-style])": "translateY(calc(var(--toast-direction) * -100%))",
      ":is([data-ending-style])[data-frontmost]":
        "translateY(calc(var(--toast-direction) * -100%))",
      ":is([data-ending-style]):not([data-frontmost])":
        "translateY(calc(var(--toast-direction) * var(--toast-offset-y))) scale(.96)",
      ':is([data-ending-style])[data-swipe-direction="right"]': "translateX(calc(100% + 32px))",
      ':is([data-ending-style])[data-swipe-direction="left"]': "translateX(calc(-100% - 32px))",
      ':is([data-ending-style])[data-swipe-direction="up"]': "translateY(calc(-100% - 32px))",
      ':is([data-ending-style])[data-swipe-direction="down"]': "translateY(calc(100% + 32px))",
    },
    transformOrigin: { default: "bottom center", ':is([data-placement^="top"])': "top center" },
    opacity: { default: 1, ":is([data-ending-style],[data-limited])": 0 },
    pointerEvents: { default: "auto", ":is([data-limited])": "none" },
    transitionProperty: "transform, opacity, height",
    transitionDuration: {
      default: "350ms, 150ms, 350ms",
      ":is([data-ending-style])": "250ms, 150ms, 250ms",
      ":is([data-swiping])": "0ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionTimingFunction: tokens.easeOutFluid,
    "::after": {
      content: { default: "none", ":is([data-expanded],[data-layout-expanded])": '""' },
      position: "absolute",
      zIndex: -1,
      insetInline: 0,
      top: { default: -13, ':is([data-placement^="top"])': 0 },
      bottom: { default: 0, ':is([data-placement^="top"])': -13 },
    },
  },
  content: {
    display: "flex",
    flexDirection: "column",
    flexGrow: 1,
    minWidth: 0,
    alignItems: "flex-start",
    alignSelf: "center",
    opacity: "var(--toast-content-opacity, 1)",
    transition: {
      default: "opacity 200ms var(--ease-out-fluid)",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  title: {
    fontSize: 14,
    lineHeight: "20px",
    fontWeight: 500,
    margin: 0,
    color: "var(--toast-title-color, var(--overlay-foreground))",
  },
  description: { fontSize: 14, color: tokens.muted, margin: 0 },
  indicator: {
    display: "flex",
    flexShrink: 0,
    padding: 4,
    userSelect: "none",
    color: "var(--toast-indicator-color, var(--overlay-foreground))",
    opacity: "var(--toast-content-opacity, 1)",
    animationName: {
      default: "none",
      ':is([data-swapped="true"])': settledIndicator,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
    animationDuration: "200ms",
    animationTimingFunction: tokens.easeOutFluid,
  },
  close: {
    position: "absolute",
    insetInlineEnd: -4,
    top: -4,
    width: 20,
    height: 20,
    cursor: tokens.cursorInteractive,
    borderRadius: tokens.radiusLg,
    backgroundColor: { default: tokens.default, "@media (min-width: 640px)": tokens.overlay },
    color: tokens.defaultForeground,
    borderWidth: { default: 0, "@media (min-width: 640px)": 1 },
    borderStyle: "solid",
    borderColor: tokens.border,
    opacity: "var(--toast-close-opacity, 0)",
    transition: {
      default: "opacity 150ms var(--ease-smooth)",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  action: {
    marginTop: { default: 8, "@media (min-width: 640px)": 0 },
    cursor: tokens.cursorInteractive,
  },
  positioner: { zIndex: tokens.zIndexToast },
  arrow: { fill: tokens.surface, width: 12, height: 12 },
  success: { color: tokens.successSoftForeground },
  warning: { color: tokens.warningSoftForeground },
  danger: { color: tokens.dangerSoftForeground },
  accent: { color: tokens.accentSoftForeground },
  bottom: { bottom: 16, left: "50%", transform: "translateX(-50%)" },
  "bottom-start": { bottom: 16, insetInlineStart: 16 },
  "bottom-end": { bottom: 16, insetInlineEnd: 16 },
  top: { top: 16, left: "50%", transform: "translateX(-50%)" },
  "top-start": { top: 16, insetInlineStart: 16 },
  "top-end": { top: 16, insetInlineEnd: 16 },
});
