import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  inputGroup: {
    alignItems: "center",
    borderRadius: "8px",
    boxSizing: "border-box",
    display: "flex",
    gap: "14px",
    height: "36px",
    outline: {
      default: "none",
      ":focus-within": `1px solid ${tokens.colorFocusRing}`,
      '[data-visual-state="focus-visible"]': `1px solid ${tokens.colorFocusRing}`,
    },
    outlineOffset: "-1px",
    paddingLeft: "14px",
    paddingRight: "12px",
    position: "relative",
    width: "207px",
    zIndex: 60,
  },
  input: {
    backgroundColor: "transparent",
    borderStyle: "none",
    color: tokens.colorContentPrimary,
    flex: 1,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    height: "36px",
    lineHeight: "19.5px",
    minWidth: 0,
    outline: "none",
    padding: 0,
    "::placeholder": { color: tokens.colorContentPrimary, opacity: 1 },
  },
  shortcut: {
    alignItems: "center",
    borderColor: tokens.colorBorderPopover,
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: tokens.fontSans,
    fontSize: "11px",
    fontWeight: 400,
    height: "17px",
    justifyContent: "center",
    lineHeight: "12.1px",
    minWidth: "18px",
    paddingInline: "3px",
  },
  positioner: { outline: 0, zIndex: 50 },
  popup: {
    backgroundColor: tokens.colorSurfacePopover,
    borderColor: tokens.colorBorderPopover,
    borderRadius: tokens.radiusPopover,
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow:
      "0 6px 18px rgba(0,0,0,0.02), 0 3px 9px rgba(0,0,0,0.04), 0 1px 1px rgba(0,0,0,0.04)",
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    minWidth: "207px",
    outline: 0,
    overflow: "hidden",
    transformOrigin: "var(--transform-origin)",
  },
  list: { outline: 0, paddingBottom: "6px", paddingTop: "42px" },
  item: {
    alignItems: "center",
    borderRadius: tokens.radiusControl,
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    cursor: { default: "default", "[data-disabled]": "not-allowed" },
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 500,
    gap: "10.5px",
    height: "32px",
    isolation: "isolate",
    lineHeight: "19.5px",
    marginInline: 0,
    outline: 0,
    paddingLeft: "15px",
    paddingRight: "18px",
    position: "relative",
    userSelect: "none",
    "::before": {
      backgroundColor: {
        default: "transparent",
        ":hover": tokens.colorSurfaceOverlayHover,
        "[data-highlighted]": tokens.colorSurfaceOverlayHover,
        "[data-selected][data-highlighted]": "transparent",
        "[data-selected][data-highlighted][data-pointer-hovered]": tokens.colorSurfaceOverlayHover,
        "[data-disabled]:hover": "transparent",
        "[data-disabled][data-highlighted]": "transparent",
        '[data-highlighted][data-visual-state="default"]': "transparent",
        '[data-visual-state="disabled"]': "transparent",
        '[data-visual-state="hover"]': tokens.colorSurfaceOverlayHover,
        '[data-visual-state="selected"]': "transparent",
        '[data-visual-state="selected-hover"]': tokens.colorSurfaceOverlayHover,
      },
      borderRadius: tokens.radiusControl,
      bottom: 0,
      content: "''",
      left: "6px",
      pointerEvents: "none",
      position: "absolute",
      right: "6px",
      top: 0,
      zIndex: -1,
    },
  },
  itemDisabled: { opacity: 0.45 },
  itemIndicator: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      "[data-selected]": tokens.colorSwitchTrackOn,
    },
    borderColor: {
      default: tokens.colorBorderPopover,
      "[data-selected]": tokens.colorSwitchTrackOn,
    },
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxSizing: "border-box",
    color: {
      default: "transparent",
      "[data-selected]": "#ffffff",
    },
    display: "inline-flex",
    flexShrink: 0,
    height: "14px",
    justifyContent: "center",
    width: "14px",
  },
  indicatorSvg: { height: "10px", strokeWidth: "2.25px", width: "10px" },
  marker: { flexShrink: 0, height: "9px", width: "9px" },
  itemText: { flex: 1, marginLeft: "1px", minWidth: 0 },
  empty: {
    boxSizing: "border-box",
    color: tokens.colorContentTertiary,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    lineHeight: "19.5px",
    minHeight: "114px",
    padding: "54px 14px 18px",
  },
  status: {
    boxSizing: "border-box",
    color: tokens.colorContentTertiary,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    lineHeight: "19.5px",
    minHeight: "126px",
    padding: "54px 14px 30px",
  },
  groupLabel: {
    color: tokens.colorContentTertiary,
    fontFamily: tokens.fontSans,
    fontSize: "11px",
    lineHeight: "16px",
    padding: "6px 14px 2px",
  },
  separator: {
    backgroundColor: tokens.colorBorderTertiary,
    height: "0.5px",
    marginBlock: "4px",
    marginInline: "14px",
  },
  clear: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    color: tokens.colorContentSecondary,
    cursor: "pointer",
    display: "inline-flex",
    justifyContent: "center",
    padding: 0,
  },
  iconSvg: { height: "14px", strokeWidth: "1.5px", width: "14px" },
  chip: {
    alignItems: "center",
    backgroundColor: tokens.colorSurfaceInteractive,
    borderRadius: tokens.radiusControl,
    color: tokens.colorContentPrimary,
    display: "inline-flex",
    fontFamily: tokens.fontSans,
    fontSize: "12px",
    gap: "4px",
    lineHeight: "18px",
    paddingInline: "6px",
  },
});
