import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  trigger: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-control)",
    borderColor: "var(--color-border-control)",
    borderRadius: "10px",
    borderStyle: "solid",
    borderWidth: "1px",
    color: "var(--color-content-tertiary)",
    cursor: "pointer",
    display: "flex",
    fontSize: "13px",
    gap: "9px",
    height: "34px",
    left: "50%",
    paddingInline: "11px",
    position: "absolute",
    textAlign: "left",
    transform: "translateX(-50%)",
    width: "min(350px, calc(100% - 560px))",
    ":hover": {
      borderColor: "var(--color-border-secondary)",
      color: "var(--color-content-secondary)",
    },
    ":focus-visible": { outline: "2px solid var(--color-focus-ring)", outlineOffset: "2px" },
    "@media (max-width: 1180px)": {
      left: "auto",
      marginInlineStart: "auto",
      position: "relative",
      transform: "none",
      width: "min(290px, 40%)",
    },
    "@media (max-width: 640px)": {
      flex: "0 0 32px",
      height: "32px",
      justifyContent: "center",
      padding: 0,
      width: "32px",
    },
  },
  searchIcon: { flex: "none", height: "15px", strokeWidth: 1.8, width: "15px" },
  triggerLabel: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    "@media (max-width: 640px)": { display: "none" },
  },
  shortcut: {
    color: "var(--color-content-tertiary)",
    fontFamily: "inherit",
    fontSize: "11px",
    fontWeight: 400,
    marginInlineStart: "auto",
    whiteSpace: "nowrap",
    "@media (max-width: 800px)": { display: "none" },
  },
  backdrop: { backgroundColor: "#0009" },
  viewport: {
    alignItems: "flex-start",
    paddingBlockStart: "min(18vh, 148px)",
    paddingInline: "16px",
  },
  popup: {
    backgroundColor: "var(--color-surface-popover)",
    borderColor: "var(--color-border-popover)",
    borderRadius: "12px",
    borderStyle: "solid",
    borderWidth: "1px",
    boxShadow: "0 18px 48px #0006",
    maxHeight: "min(70vh, 560px)",
    overflow: "hidden",
    padding: 0,
    width: "min(100%, 560px)",
  },
  title: { height: "1px", overflow: "hidden", position: "absolute", width: "1px" },
  inputRow: {
    alignItems: "center",
    borderBottom: "1px solid var(--color-border-tertiary)",
    color: "var(--color-content-tertiary)",
    display: "flex",
    gap: "10px",
    height: "52px",
    paddingInline: "17px",
  },
  input: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--color-content-primary)",
    flex: "1 1 auto",
    fontFamily: "inherit",
    fontSize: "14px",
    minWidth: 0,
    outline: "none",
  },
  close: {
    backgroundColor: "transparent",
    borderRadius: "7px",
    color: "var(--color-content-tertiary)",
    flex: "0 0 28px",
    height: "28px",
    padding: 0,
    width: "28px",
    ":hover": {
      backgroundColor: "var(--color-surface-interactive-hover)",
      color: "var(--color-content-primary)",
    },
    ":focus-visible": { outline: "2px solid var(--color-focus-ring)", outlineOffset: "1px" },
  },
  results: { maxHeight: "min(52vh, 420px)", overflowY: "auto", padding: "7px" },
  result: {
    alignItems: "center",
    borderRadius: "7px",
    color: "var(--color-content-primary)",
    display: "flex",
    fontSize: "13px",
    gap: "12px",
    justifyContent: "space-between",
    minHeight: "34px",
    paddingInline: "11px",
    textDecoration: "none",
    ":hover": { backgroundColor: "var(--color-surface-interactive-hover)" },
    ":focus-visible": { backgroundColor: "var(--color-surface-selected)", outline: "none" },
  },
  resultSection: {
    color: "var(--color-content-tertiary)",
    fontSize: "11px",
    textTransform: "capitalize",
  },
  empty: { color: "var(--color-content-secondary)", fontSize: "13px", margin: "16px 12px" },
  footer: {
    borderTop: "1px solid var(--color-border-tertiary)",
    color: "var(--color-content-tertiary)",
    fontSize: "11px",
    margin: 0,
    padding: "9px 16px",
  },
});
