import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  standardContent: {
    marginInline: "auto",
    maxWidth: "1188px",
    padding: "48px 52px 80px 56px",
    width: "100%",
    "@media (max-width: 720px)": { padding: "28px 16px 48px" },
  },
  componentContent: {
    padding: "32px 52px 40px 56px",
    "@media (max-width: 720px)": { padding: "28px 16px 48px" },
  },
  documentContent: {
    marginInline: "auto",
    maxWidth: "1188px",
    padding: "40px 52px 48px 56px",
    width: "100%",
    "@media (max-width: 720px)": { padding: "28px 16px 48px" },
  },
  workspaceContent: {
    height: "100%",
    maxWidth: "none",
    paddingBlockEnd: "24px",
    paddingBlockStart: "16px",
    paddingInline: "24px",
    "@media (max-width: 900px)": {
      height: "auto",
    },
    "@media (max-width: 720px)": {
      paddingBlock: "16px",
      paddingInline: "16px",
    },
  },
  tokensContent: {
    paddingBlock: 0,
    paddingInline: "24px",
    "@media (max-width: 720px)": {
      paddingBlock: 0,
      paddingInline: "16px",
    },
  },
  themeLabContent: {
    paddingBlock: 0,
    paddingInline: "16px",
    "@media (max-width: 720px)": {
      paddingBlock: 0,
      paddingInline: "12px",
    },
  },
  documentLayout: {
    alignItems: "flex-start",
    display: "flex",
    gap: "100px",
    width: "1080px",
    "@media (max-width: 1320px)": { gap: "48px", width: "100%" },
    "@media (max-width: 900px)": { display: "block" },
  },
  workspaceLayout: {
    height: "100%",
    width: "100%",
    "@media (max-width: 900px)": {
      height: "auto",
    },
  },
  documentMain: {
    display: "flex",
    flex: "none",
    flexDirection: "column",
    gap: "48px",
    minWidth: 0,
    width: "760px",
    "@media (max-width: 1320px)": { width: "min(760px, 100%)" },
    "@media (max-width: 720px)": { width: "100%" },
  },
  workspaceMain: {
    flex: "1 1 auto",
    gap: 0,
    height: "100%",
    width: "100%",
    "@media (max-width: 900px)": {
      height: "auto",
    },
  },
  hero: {
    display: "flex",
    flex: "none",
    flexDirection: "column",
    gap: "8px",
    maxWidth: "760px",
    width: "100%",
  },
  heroEyebrow: {
    color: "var(--color-content-tertiary)",
    fontSize: "11px",
    fontWeight: 500,
    lineHeight: "16px",
    margin: 0,
    width: "100%",
  },
  heroTitle: {
    color: "var(--docs-fg-primary)",
    fontSize: "28px",
    fontWeight: 600,
    lineHeight: "36px",
    margin: 0,
    maxWidth: "760px",
    width: "100%",
  },
  heroDescription: {
    color: "var(--color-content-secondary)",
    fontSize: "14px",
    lineHeight: "22px",
    margin: 0,
    maxWidth: "720px",
    width: "100%",
  },
  heroMetadata: {
    color: "var(--color-content-tertiary)",
    fontSize: "11px",
    lineHeight: "16px",
    margin: 0,
    maxWidth: "720px",
    width: "100%",
  },
  componentOverview: {
    height: "auto",
    minHeight: "168px",
    width: "100%",
  },
  componentTitle: {
    color: "var(--docs-fg-primary)",
    fontSize: "30px",
    fontWeight: 600,
    lineHeight: "38px",
    marginBlock: "12px 0",
    marginInline: 0,
    minHeight: "38px",
    width: "min(560px, 100%)",
  },
  componentEyebrow: {
    color: "var(--docs-fg-primary)",
    fontSize: "10px",
    fontWeight: 500,
    height: "16px",
    letterSpacing: "0.02em",
    lineHeight: "16px",
    margin: 0,
    width: "min(580px, 100%)",
  },
  componentDescription: {
    color: "var(--color-content-secondary)",
    fontSize: "13px",
    height: "auto",
    lineHeight: "20px",
    margin: "12px 0 0",
    minHeight: "20px",
    width: "min(720px, 100%)",
  },
  componentMetadata: {
    display: "flex",
    flexWrap: "wrap",
    gap: "6px 18px",
    marginTop: "12px",
  },
  metadataPill: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 0,
    boxShadow: "none",
    color: "var(--color-content-tertiary)",
    display: "inline-flex",
    fontSize: "11px",
    height: "18px",
    lineHeight: "18px",
    paddingInline: 0,
  },
});
