import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: { height: "auto", marginTop: "24px", width: "100%" },
  heading: {
    alignItems: "center",
    display: "flex",
    height: "28px",
    justifyContent: "space-between",
    width: "100%",
  },
  title: {
    color: "var(--color-content-primary)",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "20px",
    margin: 0,
  },
  actions: {
    alignItems: "center",
    display: "flex",
    flex: "0 0 auto",
    gap: "8px",
    height: "28px",
    justifyContent: "flex-end",
    marginLeft: "auto",
    width: "auto",
  },
  body: {
    display: "grid",
    gap: "16px",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 360px)",
    height: "256px",
    marginTop: "12px",
    width: "100%",
    "@media (max-width: 1100px)": { gridTemplateColumns: "minmax(0, 1fr)", height: "auto" },
  },
  templateBody: {
    gridTemplateColumns: "minmax(0, 1fr)",
    gridTemplateRows: "548px 200px",
    height: "764px",
    "@media (max-width: 1100px)": { gridTemplateRows: "auto", height: "auto" },
  },
  sidebarBody: { height: "790px" },
  commandMenuBody: { height: "488px" },
  stage: {
    backgroundColor: "var(--color-surface-translucent)",
    border: 0,
    borderRadius: "8px",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-translucent)",
    height: "256px",
    overflow: "hidden",
    padding: "14px 16px",
    width: "100%",
  },
  templateStage: { height: "548px", "@media (max-width: 1100px)": { height: "auto" } },
  sidebarStage: { height: "790px" },
  commandMenuStage: { height: "488px" },
  inspector: {
    backgroundColor: "var(--color-surface-translucent)",
    border: 0,
    borderRadius: "8px",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-translucent)",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    height: "256px",
    overflow: "hidden",
    padding: "12px 16px",
    width: "100%",
  },
  templateInspector: { height: "200px", "@media (max-width: 1100px)": { height: "auto" } },
  sidebarInspector: { height: "790px" },
  commandMenuInspector: { height: "488px" },
});
