import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: { width: "100%" },
  header: {
    alignItems: "center",
    display: "flex",
    height: "32px",
    justifyContent: "space-between",
    width: "100%",
    "@media (max-width: 900px)": { height: "44px" },
  },
  headerTitle: {
    color: "var(--color-content-primary)",
    fontSize: "11px",
    fontWeight: 500,
    lineHeight: "18px",
  },
  divider: {
    backgroundColor: "var(--color-border-translucent)",
    height: "0.5px",
    marginBlock: "4px",
    width: "100%",
  },
  list: { display: "flex", flexDirection: "column", gap: "4px", width: "100%" },
  row: {
    alignItems: "center",
    display: "flex",
    height: "28px",
    justifyContent: "space-between",
    gap: "12px",
    width: "100%",
    "@media (max-width: 900px)": { height: "44px" },
  },
  label: {
    color: "var(--color-content-secondary)",
    fontSize: "11px",
    fontWeight: 400,
    lineHeight: "18px",
  },
  selectTrigger: {
    color: "var(--color-content-primary)",
    fontFamily: '"IBM Plex Sans", var(--font-sans)',
    fontSize: "12px",
    height: "28px",
    justifyContent: "space-between",
    lineHeight: "18px",
    paddingInline: "10px 8px",
    width: "164px",
    "@media (max-width: 900px)": { height: "44px" },
  },
  selectValue: {
    fontFamily: '"IBM Plex Sans", var(--font-sans)',
    fontSize: "12px",
    fontWeight: 400,
    lineHeight: "18px",
  },
  selectPopup: { height: "auto", maxHeight: "224px", minWidth: "164px", width: "164px" },
  selectItem: {
    color: "var(--color-content-primary)",
    fontFamily: '"IBM Plex Sans", var(--font-sans)',
    fontSize: "12px",
    fontWeight: 400,
    height: "32px",
    lineHeight: "18px",
    "@media (max-width: 900px)": { height: "44px" },
  },
  textField: { display: "block", maxWidth: "none", width: "164px" },
  textControl: {
    color: "var(--color-content-secondary)",
    fontSize: "11px",
    height: "28px",
    lineHeight: "18px",
    padding: "5px 10px",
    "@media (max-width: 900px)": { height: "44px" },
  },
});
