import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  theme: {
    "--docs-neutral-0": "#fdfdfc",
    "--docs-neutral-50": "#fbfbfa",
    "--docs-neutral-100": "#f8f8f7",
    "--docs-neutral-150": "#f3f3f1",
    "--docs-neutral-200": "#eeeeec",
    "--docs-neutral-250": "#e8e8e5",
    "--docs-neutral-300": "#dededb",
    "--docs-neutral-400": "#cecec9",
    "--docs-neutral-500": "#7e8278",
    "--docs-neutral-600": "#5f625b",
    "--docs-neutral-700": "#454841",
    "--docs-neutral-750": "#353832",
    "--docs-neutral-800": "#2b2d29",
    "--docs-neutral-850": "#242622",
    "--docs-neutral-875": "#20221f",
    "--docs-neutral-900": "#1b1d1a",
    "--docs-neutral-925": "#151613",
    "--docs-neutral-950": "#111210",
    "--docs-neutral-975": "#0a0b0a",
    "--docs-fg-primary": "#1d1e1c",
    "--docs-main": "var(--docs-neutral-100)",
    "--docs-sidebar": "var(--docs-neutral-200)",
    "--docs-sidebar-active": "var(--docs-neutral-300)",
    "--docs-sidebar-hover": "var(--docs-neutral-250)",
    "--docs-page-border": "var(--docs-neutral-300)",
    "--docs-structural-border": "var(--docs-neutral-250)",
    "--color-action-primary": "var(--docs-neutral-850)",
    "--color-action-primary-content": "#fafbf8",
    "--color-action-primary-hover": "#151714",
    "--color-border-control": "var(--docs-neutral-400)",
    "--color-border-control-focus": "#bdbdb7",
    "--color-border-dialog": "var(--docs-neutral-300)",
    "--color-border-menu-separator": "var(--docs-neutral-250)",
    "--color-border-popover": "var(--docs-neutral-300)",
    "--color-border-secondary": "#d3d3cf",
    "--color-border-tertiary": "var(--docs-neutral-250)",
    "--color-border-translucent": "#20231e14",
    "--color-content-primary": "#252723",
    "--color-content-secondary": "var(--docs-neutral-600)",
    "--color-content-tertiary": "var(--docs-neutral-500)",
    "--color-surface-canvas": "var(--docs-neutral-100)",
    "--color-surface-control": "var(--docs-neutral-0)",
    "--color-surface-dialog": "var(--docs-neutral-0)",
    "--color-surface-elevated": "var(--docs-neutral-0)",
    "--color-surface-interactive": "var(--docs-neutral-0)",
    "--color-surface-interactive-hover": "var(--docs-neutral-150)",
    "--color-surface-level3": "var(--docs-neutral-200)",
    "--color-surface-overlay-hover": "var(--docs-neutral-150)",
    "--color-surface-panel": "var(--docs-neutral-50)",
    "--color-surface-popover": "var(--docs-neutral-0)",
    "--color-surface-quaternary": "var(--docs-neutral-200)",
    "--color-surface-read-only": "var(--docs-neutral-100)",
    "--color-surface-selected": "var(--docs-neutral-250)",
    "--color-surface-sidebar": "var(--docs-sidebar)",
    "--color-surface-subtle": "var(--docs-neutral-100)",
    "--color-surface-surface": "var(--docs-neutral-50)",
    "--color-surface-translucent": "#fdfdfca8",
    backgroundColor: "var(--docs-sidebar)",
    color: "var(--color-content-primary)",
    minHeight: "100vh",
  },
  darkTheme: {
    "--docs-neutral-800": "#393a3d",
    "--docs-neutral-825": "#28292b",
    "--docs-neutral-850": "#232325",
    "--docs-neutral-875": "#1f1f1f",
    "--docs-neutral-900": "#1a1a1b",
    "--docs-neutral-925": "#191a1b",
    "--docs-neutral-950": "#121213",
    "--docs-neutral-975": "#0a0a0a",
    "--docs-neutral-1000": "#000000",
    "--docs-fg-primary": "#ffffff",
    "--docs-main": "var(--docs-neutral-950)",
    "--docs-sidebar": "var(--docs-neutral-975)",
    "--docs-sidebar-active": "var(--docs-neutral-850)",
    "--docs-sidebar-hover": "#18181a",
    "--docs-page-border": "#212224",
    "--docs-structural-border": "#212224",
    "--color-action-primary": "#e5e5e6",
    "--color-action-primary-content": "var(--docs-neutral-925)",
    "--color-action-primary-hover": "#ffffff",
    "--color-border-control": "#48494c",
    "--color-border-control-focus": "#3e424d",
    "--color-border-dialog": "var(--docs-neutral-875)",
    "--color-border-menu-separator": "#333333",
    "--color-border-popover": "#3f4044",
    "--color-border-secondary": "#333333",
    "--color-border-tertiary": "var(--docs-neutral-875)",
    "--color-border-translucent": "#ffffff08",
    "--color-content-primary": "#f7f8f8",
    "--color-content-secondary": "#d4d4d4",
    "--color-content-tertiary": "#8a8f98",
    "--color-surface-canvas": "var(--docs-neutral-1000)",
    "--color-surface-control": "var(--docs-neutral-925)",
    "--color-surface-dialog": "var(--docs-neutral-925)",
    "--color-surface-elevated": "var(--docs-neutral-975)",
    "--color-surface-interactive": "var(--docs-neutral-1000)",
    "--color-surface-interactive-hover": "var(--docs-neutral-875)",
    "--color-surface-level3": "var(--docs-neutral-925)",
    "--color-surface-overlay-hover": "var(--docs-neutral-800)",
    "--color-surface-panel": "var(--docs-neutral-900)",
    "--color-surface-popover": "var(--docs-neutral-825)",
    "--color-surface-quaternary": "#28282c",
    "--color-surface-read-only": "var(--docs-neutral-975)",
    "--color-surface-selected": "var(--docs-neutral-875)",
    "--color-surface-sidebar": "var(--docs-sidebar)",
    "--color-surface-subtle": "var(--docs-neutral-975)",
    "--color-surface-surface": "var(--docs-neutral-1000)",
    "--color-surface-translucent": "#ffffff0d",
  },
  shell: {
    backgroundColor: "var(--docs-sidebar)",
    display: "grid",
    gridTemplateColumns: "244px minmax(0, 1fr)",
    height: "100vh",
    minHeight: "100vh",
  },
  sidebarRoot: {
    backgroundColor: "var(--docs-sidebar)",
    height: "100vh",
    minHeight: 0,
    overflow: "hidden",
    position: "sticky",
    top: 0,
    width: "244px",
  },
  sidebarPanel: {
    "--color-sidebar-item-hover": "var(--docs-sidebar-hover)",
    "--color-surface-interactive-hover": "var(--docs-sidebar-hover)",
    backgroundColor: "var(--docs-sidebar)",
    height: "100%",
    minHeight: 0,
    padding: "12px",
    width: "244px",
  },
  sidebarHeader: {
    alignItems: "stretch",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    gap: "8px",
    height: "80px",
    margin: 0,
    padding: 0,
    width: "100%",
  },
  brandRow: {
    alignItems: "center",
    display: "flex",
    height: "28px",
    justifyContent: "space-between",
  },
  brand: { color: "var(--docs-fg-primary)", fontSize: "14px", fontWeight: 500, lineHeight: "20px" },
  version: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-translucent)",
    borderRadius: "var(--radius-rounded)",
    color: "var(--color-content-secondary)",
    display: "inline-flex",
    fontSize: "10px",
    height: "20px",
    justifyContent: "center",
    lineHeight: "14px",
    minWidth: "37px",
    padding: "3px 8px",
  },
  searchButton: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-translucent)",
    borderRadius: "var(--radius-rounded)",
    borderWidth: 0,
    boxShadow: "inset 0 0 0 0.5px var(--color-border-translucent)",
    color: "var(--color-content-secondary)",
    cursor: "pointer",
    display: "flex",
    fontSize: "12px",
    height: "32px",
    justifyContent: "space-between",
    lineHeight: "16px",
    padding: "0 8px 0 10px",
    textAlign: "left",
    width: "100%",
  },
  searchHint: {
    backgroundColor: "transparent",
    borderWidth: 0,
    fontFamily: 'ui-monospace, "SFMono-Regular", Consolas, monospace',
    fontSize: "10px",
    fontWeight: 400,
    lineHeight: "14px",
  },
  sidebarContent: { minHeight: 0, paddingInline: 0 },
  nav: { display: "flex", flexDirection: "column", gap: "12px", width: "220px" },
  navGroup: { width: "220px" },
  navGroupCompact: { display: "flex", flexDirection: "column", gap: "2px" },
  disclosureRoot: { width: "220px" },
  disclosureItem: { overflow: "visible", width: "220px" },
  navSection: { gap: "2px", marginTop: 0, width: "220px" },
  navSectionHeader: { height: "28px", margin: 0, padding: 0, width: "220px" },
  navSectionContent: { margin: 0, padding: 0, width: "220px" },
  navSectionContentInner: { margin: 0 },
  navSectionContentStart: { paddingLeft: 0, paddingTop: "2px" },
  navHeading: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: "var(--radius-rounded)",
    borderWidth: 0,
    color: "var(--color-content-secondary)",
    cursor: "pointer",
    display: "flex",
    fontFamily: "var(--font-sans)",
    fontSize: "12px",
    fontWeight: 400,
    gap: "6px",
    height: "28px",
    lineHeight: "20px",
    marginLeft: 0,
    padding: "0 9px 0 10px",
    textAlign: "left",
    transition: "background-color 120ms ease-out, color 120ms ease-out",
    width: "220px",
    ":hover": { backgroundColor: "var(--docs-sidebar-hover)" },
    ":focus-visible": {
      boxShadow: "inset 0 0 0 1px var(--color-focus-ring)",
      outline: "none",
      position: "relative",
      zIndex: 1,
    },
  },
  navItem: {
    alignItems: "center",
    borderRadius: "var(--radius-rounded)",
    color: "var(--color-content-secondary)",
    display: "flex",
    fontSize: "12px",
    fontWeight: 400,
    height: "28px",
    lineHeight: "20px",
    padding: "0 9px 0 24px",
    textDecoration: "none",
    width: "220px",
    ":focus-visible": {
      boxShadow: "inset 0 0 0 1px var(--color-focus-ring)",
      outline: "none",
      position: "relative",
      zIndex: 1,
    },
  },
  selectedNavItem: {
    backgroundColor: "var(--docs-sidebar-active)",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-translucent)",
    color: "var(--docs-fg-primary)",
  },
  mainInset: { height: "100vh", minWidth: 0, padding: "8px 8px 8px 0" },
  mainSurface: {
    backgroundColor: "var(--docs-main)",
    borderRadius: "10px",
    boxShadow: "inset 0 0 0 0.5px var(--docs-page-border)",
    display: "flex",
    flexDirection: "column",
    height: "calc(100vh - 16px)",
    minHeight: 0,
    overflow: "hidden",
  },
  header: {
    alignItems: "center",
    display: "flex",
    flex: "0 0 56px",
    height: "56px",
    justifyContent: "space-between",
    padding: "0 16px 0 24px",
    width: "100%",
  },
  breadcrumb: {
    alignItems: "center",
    color: "var(--color-content-secondary)",
    display: "flex",
    fontSize: "11px",
    height: "24px",
    lineHeight: "16px",
  },
  breadcrumbList: { gap: "4px" },
  breadcrumbPart: {
    boxSizing: "border-box",
    fontSize: "11px",
    height: "24px",
    lineHeight: "16px",
    padding: 0,
  },
  breadcrumbLink: {
    backgroundColor: { default: "transparent", ":hover": "transparent" },
    borderRadius: 0,
    color: "var(--color-content-secondary)",
    fontWeight: 400,
  },
  breadcrumbPage: { color: "var(--color-content-primary)", fontWeight: 500 },
  breadcrumbLabel: { alignItems: "center", display: "inline-flex" },
  headerActions: { alignItems: "center", display: "flex", gap: "8px" },
  headerButton: { width: "86px" },
  scroll: {
    flex: "1 1 auto",
    minHeight: 0,
    overflowX: "hidden",
    overflowY: "auto",
    scrollbarGutter: "stable",
    width: "100%",
  },
  workspaceScroll: {
    overflow: "hidden",
    scrollbarGutter: "auto",
    "@media (max-width: 900px)": { overflowY: "auto", scrollbarGutter: "stable" },
  },
});
