import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: {
    display: "flex",
    flex: "none",
    flexDirection: "column",
    gap: "8px",
    width: "220px",
  },
  desktopRoot: { "@media (max-width: 1240px)": { display: "none" } },
  mobileRoot: {
    backgroundColor: "var(--color-surface-subtle)",
    borderRadius: "8px",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-tertiary)",
    display: "none",
    overflow: "hidden",
    width: "100%",
    "@media (min-width: 901px) and (max-width: 1240px)": { width: "220px" },
    "@media (max-width: 1240px)": { display: "block" },
  },
  mobileSummary: {
    alignItems: "center",
    color: "var(--color-content-secondary)",
    cursor: "pointer",
    display: "flex",
    fontSize: "12px",
    fontWeight: 500,
    height: "36px",
    justifyContent: "space-between",
    lineHeight: "18px",
    listStyle: "none",
    paddingInline: "12px",
    ":focus-visible": {
      boxShadow: "inset 0 0 0 1px var(--color-focus-ring)",
      outline: "none",
    },
  },
  mobileChevron: { height: "14px", width: "14px" },
  mobileNavigation: { padding: "0 6px 6px" },
  mobileItems: { display: "flex", flexDirection: "column", gap: "1px" },
  mobileItem: {
    borderRadius: "6px",
    color: "var(--color-content-tertiary)",
    fontSize: "12px",
    lineHeight: "18px",
    padding: "7px 8px",
    textDecoration: "none",
    ":hover": { backgroundColor: "var(--color-surface-interactive-hover)" },
    ":focus-visible": {
      boxShadow: "inset 0 0 0 1px var(--color-focus-ring)",
      outline: "none",
    },
  },
  nestedMobileItem: { paddingLeft: "18px" },
  activeMobileItem: {
    backgroundColor: "var(--color-surface-selected)",
    color: "var(--color-content-primary)",
  },
  label: {
    color: "var(--color-content-tertiary)",
    fontSize: "11px",
    fontWeight: 500,
    lineHeight: "16px",
    margin: 0,
    width: "220px",
  },
  items: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    position: "relative",
    width: "220px",
  },
  item: {
    alignItems: "center",
    borderRadius: "var(--radius-control)",
    color: "var(--color-content-tertiary)",
    display: "flex",
    fontSize: "12px",
    height: "28px",
    lineHeight: "18px",
    padding: "0 8px 0 18px",
    textDecoration: "none",
    transition: "background-color 120ms ease-out, color 120ms ease-out",
    width: "220px",
    ":hover": {
      backgroundColor: "var(--color-surface-interactive-hover)",
    },
    ":focus-visible": {
      boxShadow: "inset 0 0 0 1px var(--color-focus-ring)",
      outline: "none",
    },
    "@media (prefers-reduced-motion: reduce)": {
      transitionDuration: "0ms",
    },
  },
  nestedItem: { paddingLeft: "28px" },
  activeItem: {
    color: "var(--color-content-primary)",
  },
  indicator: {
    backgroundColor: "var(--color-content-primary)",
    borderRadius: "1px",
    height: "16px",
    left: "8px",
    opacity: 0,
    pointerEvents: "none",
    position: "absolute",
    top: 0,
    transform: "translateY(6px)",
    transition:
      "transform 180ms cubic-bezier(0.22, 1, 0.36, 1), height 150ms ease-out, opacity 120ms ease-out",
    width: "2px",
    willChange: "transform",
    zIndex: 1,
    "@media (prefers-reduced-motion: reduce)": {
      transitionDuration: "0ms",
    },
  },
  readyIndicator: {
    opacity: 1,
  },
});
