import * as stylex from "@stylexjs/stylex";

const mono = '"IBM Plex Mono", monospace';

export const styles = stylex.create({
  explorer: {
    display: "grid",
    gap: "24px",
    gridTemplateColumns: "minmax(420px, 1fr) 320px",
    height: "100%",
    minHeight: 0,
    width: "100%",
    "@media (max-width: 1120px)": {
      gap: "16px",
      gridTemplateColumns: "minmax(360px, 1fr) 280px",
    },
    "@media (max-width: 900px)": {
      gridTemplateColumns: "minmax(0, 1fr)",
      height: "auto",
    },
  },
  panel: {
    backgroundColor: "var(--color-surface-translucent)",
    borderRadius: "var(--radius-panel)",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-translucent)",
    minWidth: 0,
  },
  browser: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    overflow: "hidden",
    "@media (max-width: 900px)": {
      minHeight: "560px",
    },
  },
  browserHeader: {
    alignItems: "center",
    borderBottom: "0.5px solid var(--color-border-translucent)",
    display: "flex",
    flex: "0 0 auto",
    gap: "20px",
    justifyContent: "space-between",
    padding: "16px",
    "@media (max-width: 560px)": {
      alignItems: "stretch",
      flexDirection: "column",
      gap: "10px",
    },
  },
  browserTitleGroup: {
    alignItems: "baseline",
    display: "flex",
    gap: "8px",
  },
  browserTitle: {
    color: "var(--color-content-primary)",
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "20px",
    margin: 0,
  },
  browserCount: {
    color: "var(--color-content-tertiary)",
    fontSize: "10px",
    lineHeight: "14px",
  },
  search: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-control)",
    borderRadius: "var(--radius-control)",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-control)",
    color: "var(--color-content-tertiary)",
    display: "flex",
    gap: "7px",
    height: "30px",
    paddingInline: "8px",
    width: "min(280px, 48%)",
    ":focus-within": {
      boxShadow: "inset 0 0 0 1px var(--color-focus-ring)",
    },
    "@media (max-width: 560px)": {
      width: "100%",
    },
  },
  searchInput: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--color-content-primary)",
    flex: 1,
    fontSize: "11px",
    lineHeight: "16px",
    minWidth: 0,
    outline: 0,
    "::placeholder": {
      color: "var(--color-content-tertiary)",
    },
    "::-webkit-search-cancel-button": {
      display: "none",
    },
  },
  searchHint: {
    color: "var(--color-content-tertiary)",
    fontFamily: mono,
    fontSize: "9px",
    fontWeight: 400,
  },
  treeScroller: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    padding: "8px",
    scrollbarWidth: "thin",
  },
  treeList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  treeItem: {
    position: "relative",
  },
  treeGroup: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    position: "relative",
    "::before": {
      backgroundColor: "var(--color-border-translucent)",
      bottom: 0,
      content: '""',
      left: "19px",
      position: "absolute",
      top: 0,
      width: "0.5px",
    },
  },
  nestedTreeGroup: {
    "::before": {
      left: "35px",
    },
  },
  treeRow: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: "var(--radius-control)",
    borderWidth: 0,
    color: "var(--color-content-secondary)",
    cursor: "pointer",
    display: "grid",
    gap: "6px",
    gridTemplateColumns: "14px 14px minmax(0, 1fr) auto",
    height: "28px",
    padding: "0 8px 0 calc(6px + var(--tree-depth, 0) * 16px)",
    position: "relative",
    textAlign: "left",
    width: "100%",
    ":hover": {
      backgroundColor: "var(--color-surface-interactive-hover)",
      color: "var(--color-content-primary)",
    },
    ":focus-visible": {
      boxShadow: "inset 0 0 0 1px var(--color-focus-ring)",
      outline: "none",
      zIndex: 1,
    },
  },
  selectedRow: {
    backgroundColor: "var(--color-surface-selected)",
    color: "var(--color-content-primary)",
  },
  chevron: {
    alignItems: "center",
    color: "var(--color-content-tertiary)",
    display: "inline-flex",
    justifyContent: "center",
  },
  swatch: {
    borderRadius: "3px",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-secondary)",
    height: "11px",
    width: "11px",
  },
  treeLabel: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  groupLabel: {
    fontSize: "11px",
    fontWeight: 500,
    lineHeight: "16px",
  },
  tokenLabel: {
    fontFamily: mono,
    fontSize: "10px",
    lineHeight: "14px",
  },
  treeMetadata: {
    color: "var(--color-content-tertiary)",
    fontFamily: mono,
    fontSize: "9px",
    justifySelf: "end",
    lineHeight: "14px",
  },
  inlineValue: {
    maxWidth: "132px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    "@media (max-width: 560px)": {
      display: "none",
    },
  },
  details: {
    alignSelf: "stretch",
    height: "100%",
    minHeight: 0,
    overflowY: "auto",
    padding: "14px",
    scrollbarWidth: "thin",
    "@media (max-width: 900px)": {
      height: "auto",
      overflow: "visible",
      width: "100%",
    },
  },
  eyebrow: {
    color: "var(--color-content-tertiary)",
    fontSize: "10px",
    fontWeight: 500,
    letterSpacing: "0.02em",
    lineHeight: "14px",
    margin: "0 0 4px",
    textTransform: "uppercase",
  },
  detailsTitle: {
    color: "var(--color-content-primary)",
    fontSize: "18px",
    fontWeight: 600,
    lineHeight: "24px",
    margin: 0,
  },
  pathCrumbs: {
    display: "flex",
    flexWrap: "wrap",
    gap: "4px",
    marginTop: "6px",
  },
  pathCrumb: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-translucent)",
    borderRadius: "var(--radius-rounded)",
    color: "var(--color-content-secondary)",
    display: "inline-flex",
    fontFamily: mono,
    fontSize: "9px",
    height: "20px",
    lineHeight: "14px",
    paddingInline: "7px",
  },
  previewCanvas: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-control)",
    borderRadius: "var(--radius-panel)",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-translucent)",
    display: "flex",
    height: "112px",
    justifyContent: "center",
    marginTop: "12px",
    overflow: "hidden",
  },
  colorPreview: {
    borderRadius: "17px",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-secondary), 0 8px 24px rgba(0, 0, 0, 0.08)",
    height: "56px",
    width: "56px",
  },
  typePreview: {
    color: "var(--color-content-primary)",
    fontSize: "56px",
    lineHeight: 1,
  },
  blockPreview: {
    backgroundColor: "var(--color-action-primary)",
    height: "56px",
    width: "56px",
  },
  radiusPreview: {
    boxShadow: "inset 0 0 0 1px var(--color-border-primary)",
  },
  measurePreview: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  measureBar: {
    backgroundColor: "var(--color-action-primary)",
    borderRadius: "4px",
    display: "block",
    height: "8px",
    maxWidth: "160px",
    minWidth: "2px",
  },
  measureCode: {
    color: "var(--color-content-secondary)",
    fontFamily: mono,
    fontSize: "10px",
  },
  modeSection: {
    marginTop: "10px",
  },
  fieldLabel: {
    color: "var(--color-content-tertiary)",
    fontSize: "9px",
    fontWeight: 500,
    letterSpacing: "0.04em",
    lineHeight: "14px",
  },
  modeControl: {
    marginTop: "6px",
  },
  detailsList: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
    margin: "10px 0 0",
  },
  detailsEntry: {
    minWidth: 0,
  },
  detailsTerm: {
    color: "var(--color-content-tertiary)",
    fontSize: "9px",
    fontWeight: 500,
    letterSpacing: "0.04em",
    lineHeight: "14px",
    margin: 0,
  },
  detailsDefinition: {
    margin: "2px 0 0",
  },
  copyValue: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: "var(--radius-control)",
    borderWidth: 0,
    color: "var(--color-content-primary)",
    cursor: "pointer",
    display: "flex",
    gap: "8px",
    justifyContent: "space-between",
    minHeight: "18px",
    padding: "1px 5px",
    textAlign: "left",
    width: "100%",
    ":hover": {
      backgroundColor: "var(--color-surface-interactive-hover)",
    },
    ":focus-visible": {
      boxShadow: "inset 0 0 0 1px var(--color-focus-ring)",
      outline: "none",
    },
  },
  copyCode: {
    color: "inherit",
    fontFamily: mono,
    fontSize: "10px",
    lineHeight: "16px",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  plainValue: {
    color: "var(--color-content-primary)",
    fontFamily: mono,
    fontSize: "10px",
    lineHeight: "16px",
  },
  emptyState: {
    alignItems: "center",
    color: "var(--color-content-tertiary)",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    justifyContent: "center",
    minHeight: "360px",
  },
  emptyMessage: {
    fontSize: "11px",
    margin: "10px 0",
  },
  clearSearch: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--color-content-primary)",
    cursor: "pointer",
    fontSize: "11px",
  },
  visuallyHidden: {
    clip: "rect(0 0 0 0)",
    clipPath: "inset(50%)",
    height: "1px",
    overflow: "hidden",
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
});
