/**
 * Derived from HeroUI v3.2.6. Copyright 2026 HeroUI.
 * SPDX-License-Identifier: Apache-2.0
 * Modified: StyleX styles; shared source popover geometry with select.
 */
import * as stylex from "@stylexjs/stylex";
import { tokens } from "../../tokens.stylex.const.js";
import { selectStyles } from "../select/select.styles.js";

export const comboBoxStyles = stylex.create({
  inputGroup: {
    position: "relative",
    isolation: "isolate",
    display: "inline-flex",
    alignItems: "center",
    minWidth: 0,
  },
  input: {
    flex: 1,
    minWidth: 0,
    width: "100%",
    paddingBlock: ".5rem",
    paddingInlineStart: ".75rem",
    paddingInlineEnd: "1.75rem",
    color: tokens.fieldForeground,
    fontSize: { default: "1rem", "@media (min-width: 640px)": ".875rem" },
    lineHeight: "1.25rem",
    "::placeholder": { color: tokens.fieldPlaceholder },
  },
  field: {
    boxSizing: "border-box",
    minHeight: "2.25rem",
    borderRadius: tokens.fieldRadius,
    borderWidth: tokens.borderWidthField,
    borderStyle: "solid",
    borderColor: {
      default: tokens.fieldBorder,
      ":hover:not(:focus-within, [data-invalid], :has(input[data-invalid]))":
        tokens.fieldBorderHover,
      ":focus-within": tokens.fieldBorderFocus,
      ":is([data-invalid], :has(input[data-invalid]))": tokens.danger,
    },
    backgroundColor: {
      default: tokens.fieldBackground,
      ":hover:not(:focus-within, [data-invalid], :has(input[data-invalid]))": tokens.fieldHover,
      ":focus-within": tokens.fieldFocus,
      ":is([data-invalid], :has(input[data-invalid]))": tokens.fieldFocus,
    },
    color: tokens.fieldForeground,
    boxShadow: tokens.fieldShadow,
    outline: {
      default: "none",
      ":focus-within": `2px solid ${tokens.focus}`,
    },
    outlineOffset: 2,
    opacity: {
      default: 1,
      ":is(:disabled, [data-disabled], :has(input:disabled))": tokens.disabledOpacity,
    },
    transition: {
      default: `background-color 150ms ${tokens.easeSmooth}, border-color 150ms ${tokens.easeSmooth}, box-shadow 150ms ${tokens.easeOut}`,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  secondary: {
    backgroundColor: {
      default: tokens.default,
      ":hover:not(:focus-within, [data-invalid], :has(input[data-invalid]))": tokens.defaultHover,
      ":focus-within": tokens.default,
      ":is([data-invalid], :has(input[data-invalid]))": tokens.default,
    },
    boxShadow: "none",
  },
  groupedInput: {
    boxSizing: "border-box",
    border: 0,
    borderRadius: 0,
    backgroundColor: "transparent",
    boxShadow: "none",
    outline: "none",
    ":autofill": {
      WebkitTextFillColor: tokens.fieldForeground,
      caretColor: tokens.fieldForeground,
      boxShadow: "0 0 0 1000px transparent inset",
      transition: "background-color 9999s ease-in-out 0s",
    },
  },
  trigger: {
    position: "absolute",
    insetInlineEnd: 0,
    insetBlock: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "1.75rem",
    border: "none",
    backgroundColor: "transparent",
    color: { default: tokens.fieldPlaceholder, ":hover": tokens.fieldForeground },
    outline: { default: "none", ":focus-visible": `2px solid ${tokens.focus}` },
    outlineOffset: 2,
    borderRadius: tokens.radiusMd,
    cursor: { default: "pointer", ":is([data-disabled])": "default" },
  },
  standaloneTrigger: {
    opacity: { default: 1, ":is([data-disabled])": tokens.disabledOpacity },
  },
  icon: {
    width: "1rem",
    height: "1rem",
    display: "flex",
    transform: { default: "rotate(0deg)", ":is([data-popup-open])": "rotate(180deg)" },
    transition: {
      default: `transform 150ms ${tokens.easeSmooth}`,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  value: { fontSize: ".875rem", color: tokens.fieldForeground, overflowWrap: "break-word" },
  clear: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "1.25rem",
    height: "1.25rem",
    padding: ".25rem",
    border: "none",
    borderRadius: tokens.radiusXl,
    backgroundColor: { default: "transparent", ":hover": tokens.defaultHover },
    color: tokens.muted,
    cursor: "pointer",
    outline: { default: "none", ":focus-visible": `2px solid ${tokens.focus}` },
    outlineOffset: 2,
    "::after": { content: '""', position: "absolute", inset: -2 },
  },
  chips: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: ".25rem" },
  chip: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    gap: ".25rem",
    paddingInline: ".5rem",
    paddingBlock: ".25rem",
    backgroundColor: tokens.default,
    color: tokens.defaultForeground,
    borderRadius: tokens.radiusXl,
    fontSize: ".75rem",
    fontWeight: 500,
    lineHeight: "1rem",
    outline: { default: "none", ":focus-visible": `2px solid ${tokens.focus}` },
    outlineOffset: 2,
  },
  chipRemove: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: ".75rem",
    height: ".75rem",
    padding: 0,
    border: "none",
    backgroundColor: "transparent",
    color: "inherit",
    cursor: "pointer",
    "::after": {
      content: '""',
      position: "absolute",
      width: 24,
      height: 24,
      top: "50%",
      left: "50%",
      transform: "translate(-50%, -50%)",
    },
  },
  empty: { padding: ".75rem", textAlign: "center", fontSize: ".875rem", color: tokens.muted },
});

export const comboBoxSharedStyles = selectStyles;
