import {
  SelectRoot,
  SelectTrigger,
  SelectValue,
  SelectIndicator,
  SelectPortal,
  SelectPositioner,
  SelectPopover,
  SelectList,
  SelectItem,
  SelectItemText,
  SelectItemIndicator,
  SelectLabel,
  SelectGroup,
  SelectGroupLabel,
  SelectSeparator,
  SelectArrow,
  SelectScrollUpArrow,
  SelectScrollDownArrow,
  SelectBackdrop,
} from "./select.js";
export const Select = Object.assign(SelectRoot, {
  Root: SelectRoot,
  Trigger: SelectTrigger,
  Value: SelectValue,
  Indicator: SelectIndicator,
  Icon: SelectIndicator,
  Portal: SelectPortal,
  Positioner: SelectPositioner,
  Popover: SelectPopover,
  Popup: SelectPopover,
  List: SelectList,
  Item: SelectItem,
  ItemText: SelectItemText,
  ItemIndicator: SelectItemIndicator,
  Label: SelectLabel,
  Group: SelectGroup,
  GroupLabel: SelectGroupLabel,
  Separator: SelectSeparator,
  Arrow: SelectArrow,
  ScrollUpArrow: SelectScrollUpArrow,
  ScrollDownArrow: SelectScrollDownArrow,
  Backdrop: SelectBackdrop,
});
export * from "./select.js";
