// Adapted from HeroUI v3.2.6 (e385ac202b2cdb94b1bf6fa76d32c31c8259cc5e), Apache-2.0.
// Layout utilities translated from the pinned documentation examples.
import * as stylex from "@stylexjs/stylex";

export const s = stylex.create({
  column: { display: "flex", flexDirection: "column" },
  column1: { display: "flex", flexDirection: "column", gap: 4 },
  column2: { display: "flex", flexDirection: "column", gap: 8 },
  column3: { display: "flex", flexDirection: "column", gap: 12 },
  column4: { display: "flex", flexDirection: "column", gap: 16 },
  column8: { display: "flex", flexDirection: "column", gap: 32 },
  row2: { display: "flex", alignItems: "center", gap: 8 },
  row3: { display: "flex", alignItems: "center", gap: 12 },
  row4: { display: "flex", alignItems: "center", gap: 16 },
  row6: { display: "flex", alignItems: "center", gap: 24 },
  row8: { display: "flex", alignItems: "center", gap: 32 },
  wrap2: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8 },
  wrap3: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 12 },
  wrap4: { display: "flex", flexWrap: "wrap", gap: 16 },
  centeredColumn2: { display: "flex", flexDirection: "column", alignItems: "center", gap: 8 },
  centeredColumn6: { display: "flex", flexDirection: "column", alignItems: "center", gap: 24 },
  startColumn6: { display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 24 },
  startRow3: { display: "flex", alignItems: "flex-start", gap: 12 },
  full: { width: "100%" },
  fullAuto: { width: { default: "100%", "@media (min-width: 640px)": "auto" } },
  maxMd: { width: "100%", maxWidth: 448 },
  maxXl: { width: "100%", maxWidth: 576 },
  alertStack: { display: "grid", width: "100%", maxWidth: 576, gap: 16 },
  scroll: { overflowX: "auto" },
  matrixCell: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    width: 130,
  },
  avatarCell: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    width: 80,
  },
  labelCell: { width: 96, flexShrink: 0 },
  relative: { position: "relative" },
  relativeForeground: { position: "relative", zIndex: 10 },
  gap1: { gap: 4 },
  gap3: { gap: 12 },
  mt1: { marginTop: 4 },
  mobile2: {
    marginTop: 8,
    display: { default: "inline-flex", "@media (min-width: 640px)": "none" },
  },
  mobile3: {
    marginTop: 12,
    display: { default: "inline-flex", "@media (min-width: 640px)": "none" },
  },
  desktopBlock: { display: { default: "none", "@media (min-width: 640px)": "block" } },
  desktopInline: {
    position: "relative",
    flexShrink: 0,
    display: { default: "none", "@media (min-width: 640px)": "inline-flex" },
  },
  textXs: { fontSize: 12, lineHeight: "16px" },
  textSm: { fontSize: 14, lineHeight: "20px" },
  textBase: { fontSize: 16, lineHeight: "24px" },
  muted: { color: "var(--muted)" },
  foreground: { color: "var(--foreground)" },
  accent: { color: "var(--accent)" },
  primary: { color: "var(--primary)" },
  warning: { color: "var(--warning)" },
  medium: { fontWeight: 500 },
  semibold: { fontWeight: 600 },
  capitalize: { textTransform: "capitalize" },
  uppercase: { textTransform: "uppercase" },
  tracking: { letterSpacing: "0.025em" },
  centerText: { textAlign: "center" },
  icon4: { width: 16, height: 16 },
  icon5: { width: 20, height: 20 },
  icon6: { width: 24, height: 24 },
  icon8: { width: 32, height: 32 },
  iconDot: { width: 10, height: 10 },
  shrink0: { flexShrink: 0 },
  roundLg: { borderRadius: 8 },
  roundedAvatar: { width: 56, height: 56, borderRadius: 12 },
  avatarTiny: { width: 20, height: 20 },
  avatarMini: { width: 16, height: 16 },
  card200: { width: 200, gap: 8 },
  card320: { width: 320 },
  card400: { width: 400 },
  imageCommunity: {
    pointerEvents: "none",
    aspectRatio: "1",
    width: 56,
    borderRadius: 16,
    objectFit: "cover",
    userSelect: "none",
  },
  horizontal: {
    width: "100%",
    alignItems: "stretch",
    flexDirection: { default: "column", "@media (min-width: 768px)": "row" },
  },
  imageFrame: {
    position: "relative",
    height: { default: 140, "@media (min-width: 640px)": 120 },
    width: { default: "100%", "@media (min-width: 640px)": 120 },
    flexShrink: 0,
    overflow: "hidden",
    borderRadius: 16,
  },
  imageCover: { position: "absolute", inset: 0, height: "100%", width: "100%", objectFit: "cover" },
  imageZoom: {
    pointerEvents: "none",
    position: "absolute",
    inset: 0,
    height: "100%",
    width: "100%",
    transform: "scale(1.25)",
    objectFit: "cover",
    userSelect: "none",
  },
  flexContent: { display: "flex", flex: 1, flexDirection: "column", gap: 12 },
  titleInset: { paddingInlineEnd: 32 },
  close: { position: "absolute", insetInlineEnd: 12, top: 12 },
  footer: {
    marginTop: "auto",
    display: "flex",
    width: "100%",
    flexDirection: { default: "column", "@media (min-width: 640px)": "row" },
    alignItems: { default: "flex-start", "@media (min-width: 640px)": "center" },
    justifyContent: { default: null, "@media (min-width: 640px)": "space-between" },
    gap: 12,
  },
  formFooter: { marginTop: 16, display: "flex", flexDirection: "column", gap: 8 },
  list: {
    marginTop: 8,
    listStylePosition: "inside",
    listStyleType: "disc",
    fontSize: 14,
    lineHeight: "20px",
  },
  space1: { marginTop: 4 },
  space2: { marginTop: 8 },
  space3: { marginTop: 12 },
  space4: { marginTop: 16 },
  kbdPanel: { borderRadius: 8, backgroundColor: "var(--surface)", padding: 16 },
  kbdHeading: { marginBottom: 8, fontSize: 14, lineHeight: "20px", fontWeight: 600 },
  kbdAccent: {
    borderRadius: 8,
    backgroundColor: "var(--accent-soft)",
    paddingInline: 10,
    color: "var(--accent-soft-foreground)",
  },
  kbdDefault: {
    borderRadius: 8,
    backgroundColor: "var(--default)",
    paddingInline: 10,
    color: "var(--muted)",
  },
  surface: {
    display: "flex",
    minWidth: 320,
    flexDirection: "column",
    gap: 12,
    borderRadius: 24,
    padding: 24,
  },
  surfaceForm: {
    display: "flex",
    minWidth: 320,
    flexDirection: "column",
    gap: 16,
    borderRadius: 24,
    padding: 24,
  },
  border: { borderWidth: 1, borderStyle: "solid", borderColor: "var(--border)" },
  surfaceCustom: {
    width: "100%",
    maxWidth: 384,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "color-mix(in oklab, var(--accent) 15%, transparent)",
    backgroundImage:
      "linear-gradient(to bottom right in oklab, color-mix(in oklab, var(--accent) 8%, transparent), var(--surface), var(--surface-secondary))",
    padding: 16,
  },
  chipDraft: {
    borderRadius: 9999,
    backgroundColor: "var(--default-soft)",
    paddingInline: 12,
    color: "var(--default-soft-foreground)",
  },
  chipReview: {
    borderRadius: 9999,
    backgroundColor: "var(--warning-soft)",
    paddingInline: 12,
    color: "var(--warning-soft-foreground)",
  },
  chipPublished: {
    borderRadius: 9999,
    backgroundColor: "var(--success-soft)",
    paddingInline: 12,
    color: "var(--success-soft-foreground)",
  },
  badgeNumber: { minWidth: 20, fontWeight: 600, fontVariantNumeric: "tabular-nums" },
  gradientFallback: {
    borderStyle: "none",
    backgroundImage:
      "linear-gradient(to bottom right in oklab, oklch(65.6% 0.241 354.308), oklch(62.7% 0.265 303.9))",
    color: "white",
  },
  gridOuter: { display: "flex", width: "100%", alignItems: "center", justifyContent: "center" },
  grid: {
    display: "grid",
    width: "100%",
    maxWidth: 672,
    gridTemplateColumns: "repeat(12, minmax(0, 1fr))",
    gap: 16,
    padding: 16,
  },
  gridRow: {
    gridColumn: "span 12 / span 12",
    display: "grid",
    gridTemplateColumns: "repeat(12, minmax(0, 1fr))",
    gap: 16,
  },
  gridHalf: {
    gridColumn: { default: "span 12 / span 12", "@media (min-width: 1024px)": "span 6 / span 6" },
    display: "grid",
    gridTemplateColumns: "repeat(12, minmax(0, 1fr))",
    gap: 16,
  },
  span12: { gridColumn: "span 12 / span 12" },
  firstCard: {
    gridColumn: "span 12 / span 12",
    display: "flex",
    height: "auto",
    minHeight: 152,
    flexDirection: { default: "column", "@media (min-width: 640px)": "row" },
  },
  smallCard: {
    gridColumn: { default: "span 12 / span 12", "@media (min-width: 640px)": "span 6 / span 6" },
    gap: 8,
  },
  robotCard: {
    gridColumn: { default: "span 12 / span 12", "@media (min-width: 1024px)": "span 6 / span 6" },
    minHeight: 200,
    overflow: "hidden",
    borderRadius: 24,
  },
  robotLarge: {
    position: "relative",
    gridColumn: { default: "span 12 / span 12", "@media (min-width: 768px)": "span 8 / span 8" },
    height: { default: 250, "@media (min-width: 640px)": 300, "@media (min-width: 768px)": 350 },
  },
  robotStack: {
    gridColumn: { default: "span 12 / span 12", "@media (min-width: 768px)": "span 4 / span 4" },
    display: "flex",
    flexDirection: "column",
    gap: { default: 8, "@media (min-width: 768px)": 0 },
    justifyContent: { default: null, "@media (min-width: 768px)": "space-between" },
    paddingBlock: { default: null, "@media (min-width: 768px)": 8 },
  },
  eventCard: { display: "flex", flexDirection: "row", gap: 12, padding: 4 },
  eventImage: {
    aspectRatio: "1",
    height: { default: 64, "@media (min-width: 640px)": 80 },
    width: { default: 64, "@media (min-width: 640px)": 80 },
    flexShrink: 0,
    borderRadius: 12,
    objectFit: "cover",
    userSelect: "none",
  },
  eventContent: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    justifyContent: "center",
    gap: 4,
  },
  z10: { zIndex: 10 },
  white: { color: "white" },
  black: { color: "black" },
  black50: { color: "color-mix(in oklab, black 50%, transparent)" },
  black60: { color: "color-mix(in oklab, black 60%, transparent)" },
  black70: { color: "color-mix(in oklab, black 70%, transparent)" },
  whiteButton: { backgroundColor: "white", color: "black" },
  robotFooter: {
    zIndex: 10,
    marginTop: "auto",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  robotLargeFooter: {
    zIndex: 10,
    marginTop: "auto",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  responsiveTitle: {
    paddingInlineEnd: 32,
    fontSize: { default: 14, "@media (min-width: 640px)": 16 },
    lineHeight: { default: "20px", "@media (min-width: 640px)": "24px" },
  },
  responsiveXs: {
    fontSize: { default: 12, "@media (min-width: 640px)": 14 },
    lineHeight: { default: "16px", "@media (min-width: 640px)": "20px" },
  },
  responsiveBase: {
    fontSize: { default: 16, "@media (min-width: 640px)": 18 },
    lineHeight: { default: "24px", "@media (min-width: 640px)": "28px" },
  },
  leading4: { lineHeight: "16px" },
});
