/** HeroUI v3.2.6 RadioGroup demo layout adaptations. Apache-2.0. */
import * as stylex from "@stylexjs/stylex";
export const styles = stylex.create({
  field: { display: "flex", flexDirection: "column", minWidth: 0, width: "100%" },
  column: { display: "flex", flexDirection: "column", gap: 16 },
  description: {
    fontSize: { default: 14, ":is([data-slot='radio'] *)": 12 },
    lineHeight: { default: "20px", ":is([data-slot='radio'] *)": "16px" },
    paddingInlineStart: { default: 0, ":is([data-slot='radio'] > *)": 28 },
    minWidth: 0,
    overflowWrap: "break-word",
    color: "var(--muted)",
  },
  medium: { fontWeight: 500 },
  check: { fontSize: 12, lineHeight: 1, color: "var(--background)" },
  horizontal: { flexDirection: "row", flexWrap: "wrap", gap: 16 },
  surface: { width: "100%", borderRadius: 24, padding: 24 },
  variants: { display: "flex", flexDirection: "column", gap: 32 },
  variant: { display: "flex", flexDirection: "column", gap: 8 },
  variantLabel: { fontSize: 14, fontWeight: 500, color: "var(--muted)" },
  submit: { marginTop: 8, width: "fit-content" },
  billing: { width: "100%", maxWidth: 384, gap: 12 },
  billingRadio: { marginBlockStart: 0 },
  billingLabel: {
    fontWeight: 500,
    color: {
      default: "var(--foreground)",
      ":is([data-slot='radio'][data-checked] *)": "var(--success-soft-foreground)",
    },
  },
  billingText: { display: "flex", flexDirection: "column", gap: 2 },
  billingDescription: {
    fontSize: 12,
    lineHeight: "16px",
    color: {
      default: "var(--muted)",
      ":is([data-slot='radio'][data-checked] *)":
        "color-mix(in oklab, var(--success-soft-foreground) 80%, transparent)",
    },
  },
  billingCard: {
    display: "flex",
    width: "100%",
    alignItems: "flex-start",
    gap: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: "color-mix(in oklab, var(--success) 10%, transparent)",
      ":is([data-slot='radio'][data-checked] *)":
        "color-mix(in oklab, var(--success) 30%, transparent)",
    },
    backgroundColor: {
      default: "color-mix(in oklab, var(--success-soft) 30%, transparent)",
      ":hover": "var(--success-soft-hover)",
      ":is([data-slot='radio'][data-checked] *)": "var(--success-soft)",
      ":is([data-slot='radio'][data-checked]:hover *)": "var(--success-soft-hover)",
    },
    paddingInline: 16,
    paddingBlock: 12,
    transitionProperty: "background-color, border-color",
    transitionDuration: "150ms",
    outline: {
      default: null,
      ":is([data-slot='radio']:focus-visible *)":
        "2px solid color-mix(in oklab, var(--success) 15%, transparent)",
    },
  },
  billingControl: {
    marginTop: 2,
    width: 20,
    height: 20,
    flexShrink: 0,
    borderRadius: "50%",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: "var(--border)",
      ":is([data-slot='radio'][data-checked] *)": "transparent",
    },
    backgroundColor: {
      default: "var(--default)",
      ":is([data-slot='radio'][data-checked] *)": "var(--success)",
      ":is([data-slot='radio'][data-checked]:active *)": "var(--success-hover)",
    },
    boxShadow: "none",
  },
  billingIndicator: { borderRadius: "50%" },
  billingDot: {
    width: "100%",
    height: "100%",
    borderRadius: "50%",
    backgroundColor: "var(--default)",
    scale: "1",
    transition: {
      default: "scale 200ms var(--ease-out), background-color 200ms var(--ease-out)",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  billingDotChecked: {
    backgroundColor: "var(--success-foreground)",
    scale: {
      default: ".5",
      ":is([data-slot='radio']:active *)": ".57",
    },
  },
  checkout: {
    display: "flex",
    width: "100%",
    flexDirection: "column",
    alignItems: "center",
    gap: 40,
    "--accent": "#006FEE",
    "--accent-foreground": "#fff",
    "--accent-hover": "#006FEE",
    "--border-width": "2px",
    "--border-width-field": "2px",
    "--focus": "#006FEE",
  },
  section: { display: "flex", width: "100%", maxWidth: 512, flexDirection: "column", gap: 16 },
  deliveryGrid: {
    display: "grid",
    columnGap: 16,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 768px)": "repeat(3, minmax(0, 1fr))",
    },
  },
  paymentGrid: {
    display: "grid",
    columnGap: 16,
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 768px)": "repeat(2, minmax(0, 1fr))",
    },
  },
  deliveryCard: {
    position: "relative",
    display: "flex",
    width: "100%",
    flexDirection: "column",
    gap: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: "transparent",
      ":is([data-slot='radio'][data-checked] *)": "var(--accent)",
      ":is([data-slot='radio']:focus-visible *)": "var(--accent)",
    },
    backgroundColor: {
      default: "var(--surface)",
      ":is([data-slot='radio'][data-checked] *)":
        "color-mix(in oklab, var(--accent) 10%, transparent)",
      ":is([data-slot='radio']:focus-visible *)":
        "color-mix(in oklab, var(--accent) 10%, transparent)",
    },
    paddingInline: 20,
    paddingBlock: 16,
    transitionProperty: "background-color, border-color",
    transitionDuration: "150ms",
  },
  paymentCard: {
    position: "relative",
    display: "flex",
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: {
      default: "transparent",
      ":is([data-slot='radio'][data-checked] *)": "var(--accent)",
    },
    backgroundColor: {
      default: "var(--surface)",
      ":is([data-slot='radio'][data-checked] *)":
        "color-mix(in oklab, var(--accent) 10%, transparent)",
    },
    paddingInline: 20,
    paddingBlock: 16,
    transitionProperty: "background-color, border-color",
    transitionDuration: "150ms",
  },
  checkoutControl: { position: "absolute", insetInlineEnd: 16, top: 12, width: 20, height: 20 },
  checkoutText: { display: "flex", flexDirection: "column", gap: 4 },
  price: { fontSize: 14, fontWeight: 600 },
  paymentHeading: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  icon: { width: 24, height: 24, flexShrink: 0 },
});
