import * as stylex from "@stylexjs/stylex";

export const tokens = stylex.defineConsts({
  colorActionDanger: "var(--color-action-danger, #dc2626)",
  colorActionDangerHover: "var(--color-action-danger-hover, #e5484d)",
  colorActionPrimary: "var(--color-action-primary, #282a30)",
  colorActionPrimaryContent: "var(--color-action-primary-content, #fafafa)",
  colorActionPrimaryHover: "var(--color-action-primary-hover, #1f2024)",
  colorBorderDialog: "var(--color-border-dialog, #d4d4d4)",
  colorBorderPrimary: "var(--color-border-primary, #707172)",
  colorBorderSecondary: "var(--color-border-secondary, #d4d4d4)",
  colorBorderTertiary: "var(--color-border-tertiary, #eaeaea)",
  colorBorderTranslucent: "var(--color-border-translucent, #00000014)",
  colorBorderTransparent: "var(--color-border-transparent, #00000000)",
  colorContentInverse: "var(--color-content-inverse, #ffffff)",
  colorContentPrimary: "var(--color-content-primary, #282a30)",
  colorContentSecondary: "var(--color-content-secondary, #333333)",
  colorContentTertiary: "var(--color-content-tertiary, #6f6e77)",
  colorFocusRing: "var(--color-focus-ring, #5e6ad2)",
  colorInteractionPressedOverlay: "var(--color-interaction-pressed-overlay, #00000014)",
  colorSidebarItemActive: "var(--color-sidebar-item-active, #eaeaea)",
  colorSidebarItemHover: "var(--color-sidebar-item-hover, #f5f5f5)",
  colorStatusErrorBorder: "var(--color-status-error-border, #dc2626)",
  colorStatusErrorContent: "var(--color-status-error-content, #dc2626)",
  colorSurfaceCanvas: "var(--color-surface-canvas, #fafafa)",
  colorSurfaceDialog: "var(--color-surface-dialog, #ffffff)",
  colorSurfaceElevated: "var(--color-surface-elevated, #ffffff)",
  colorSurfaceInteractive: "var(--color-surface-interactive, #ffffff)",
  colorSurfaceInteractiveHover: "var(--color-surface-interactive-hover, #f5f5f5)",
  colorSurfaceLevel3: "var(--color-surface-level3, #f0f0f0)",
  colorSurfaceQuaternary: "var(--color-surface-quaternary, #eeedf0)",
  colorSurfaceReadOnly: "var(--color-surface-read-only, #fafafa)",
  colorSurfaceScrim: "var(--color-surface-scrim, #00000052)",
  colorSurfaceSelected: "var(--color-surface-selected, #f5f5f5)",
  colorSurfaceSidebar: "var(--color-surface-sidebar, #eeedf0)",
  colorSurfaceSubtle: "var(--color-surface-subtle, #fafafa)",
  colorSurfaceSurface: "var(--color-surface-surface, #ffffff)",
  colorSurfaceTranslucent: "var(--color-surface-translucent, #ffffff)",
  fontButton: "var(--font-button, \"IBM Plex Sans\", \"Inter\", ui-sans-serif, sans-serif)",
  fontSans: "var(--font-sans, \"Inter\", ui-sans-serif, system-ui, sans-serif)",
  opacityDisabled: "var(--opacity-disabled, 0.5)",
  opacityEnabled: "var(--opacity-enabled, 1)",
  radiusControl: "var(--radius-control, 8px)",
  radiusOverlay: "var(--radius-overlay, 8px)",
  radiusPanel: "var(--radius-panel, 10px)",
  radiusPopover: "var(--radius-popover, 12px)",
  radiusRounded: "var(--radius-rounded, 999px)",
  sizeBorderControl: "var(--size-border-control, 0.5px)",
  sizeBorderDialog: "var(--size-border-dialog, 0.5px)",
  sizeControlCompact: "var(--size-control-compact, 28px)",
  sizeControlDefault: "var(--size-control-default, 32px)",
  sizeDialog: "var(--size-dialog, 480px)",
  sizeIconButtonCompact: "var(--size-icon-button-compact, 24px)",
  sizeIconButtonDefault: "var(--size-icon-button-default, 28px)",
  sizeIconDefault: "var(--size-icon-default, 14px)",
  sizeInputDefault: "var(--size-input-default, 32px)",
  sizeSidebar: "var(--size-sidebar, 244px)",
  space1: "var(--space-1, 4px)",
  space2: "var(--space-2, 8px)",
  space3: "var(--space-3, 12px)",
  space4: "var(--space-4, 16px)",
  space6: "var(--space-6, 24px)",
});
