import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  root: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderBottomColor: tokens.colorBorderTertiary,
    borderBottomStyle: "solid",
    borderBottomWidth: "0.5px",
    boxSizing: "border-box",
    display: "flex",
    fontFamily: tokens.fontSans,
    gap: "12px",
    height: "65px",
    opacity: { default: 1, '[data-disabled="true"]': 0.4 },
    paddingBlock: "10px",
    paddingInline: "16px",
    transitionDuration: tokens.motionFeedback,
    transitionProperty: "opacity",
    transitionTimingFunction: "ease-out",
    width: "100%",
  },
  copy: {
    alignItems: "flex-start",
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
    overflow: "hidden",
    whiteSpace: "nowrap",
  },
  title: {
    color: tokens.colorContentPrimary,
    fontFamily: tokens.fontSans,
    fontSize: tokens.typeLabelSize,
    fontWeight: 500,
    lineHeight: "19.5px",
    margin: 0,
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  interactiveLabel: {
    cursor: { default: "pointer", '[aria-disabled="true"]': "default" },
  },
  description: {
    color: tokens.colorContentTertiary,
    fontFamily: tokens.fontSans,
    fontSize: tokens.typeMetadataSize,
    fontWeight: 400,
    lineHeight: tokens.typeMetadataLineHeight,
    margin: 0,
    maxWidth: "100%",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  control: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    justifyContent: "flex-end",
  },
});
