import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  panel: {
    backgroundColor: tokens.colorSurfacePopover,
    borderColor: tokens.colorBorderPopover,
    borderRadius: tokens.radiusPopover,
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: `0 ${tokens.elevationDialogDetailY} ${tokens.elevationDialogDetailBlur} ${tokens.elevationDialogDetail}, 0 ${tokens.elevationDialogSoftY} ${tokens.elevationDialogSoftBlur} ${tokens.elevationDialogSoft}, 0 ${tokens.elevationDialogMidY} ${tokens.elevationDialogMidBlur} ${tokens.elevationDialogMid}, 0 ${tokens.elevationDialogKeyY} ${tokens.elevationDialogKeyBlur} ${tokens.elevationDialogKey}, 0 ${tokens.elevationDialogAmbientY} ${tokens.elevationDialogAmbientBlur} ${tokens.elevationDialogAmbient}`,
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    height: "450px",
    overflow: "hidden",
    width: "min(720px, calc(100vw - 32px))",
  },
  search: {
    alignItems: "center",
    borderBottomColor: tokens.colorBorderTertiary,
    borderBottomStyle: "solid",
    borderBottomWidth: "0.5px",
    boxSizing: "border-box",
    display: "flex",
    gap: "12px",
    height: "40px",
    marginInline: "5.5px",
    marginTop: "5.5px",
    paddingInline: "12px",
  },
  input: {
    backgroundColor: "transparent",
    borderStyle: "none",
    color: tokens.colorContentPrimary,
    flex: 1,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    lineHeight: "normal",
    minWidth: 0,
    outline: "none",
    padding: 0,
    "::placeholder": { color: tokens.colorContentTertiary, opacity: 1 },
  },
  searchHint: {
    color: tokens.colorContentTertiary,
    flexShrink: 0,
    fontFamily: tokens.fontSans,
    fontSize: "12px",
    lineHeight: "18px",
  },
  list: { outline: 0, padding: "0 5.5px 5.5px" },
  groupLabel: {
    color: tokens.colorContentSecondary,
    fontFamily: tokens.fontSans,
    fontSize: "12px",
    fontWeight: 500,
    height: "35.5px",
    lineHeight: "18px",
    marginInline: "5.5px",
    padding: "10.5px 12px 7px",
    boxSizing: "border-box",
  },
  item: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      "[data-highlighted]": tokens.colorSurfaceOverlayHover,
      '[data-visual-state="highlighted"]': tokens.colorSurfaceOverlayHover,
    },
    borderRadius: tokens.radiusControl,
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    cursor: { default: "default", "[data-disabled]": "not-allowed" },
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: "15px",
    fontWeight: 400,
    gap: "12px",
    height: "46px",
    lineHeight: "22.5px",
    outline: 0,
    paddingInline: "12px",
    userSelect: "none",
  },
  itemDisabled: { opacity: tokens.opacityDisabled },
  itemIcon: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  itemText: { flex: 1, minWidth: 0 },
  shortcut: {
    alignItems: "center",
    borderColor: tokens.colorBorderTertiary,
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxSizing: "border-box",
    color: tokens.colorContentSecondary,
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: tokens.fontSans,
    fontSize: "11px",
    fontWeight: 500,
    height: "22px",
    justifyContent: "center",
    lineHeight: "13px",
    minWidth: "20px",
    paddingInline: "5px",
  },
  empty: {
    color: tokens.colorContentTertiary,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    lineHeight: "19.5px",
    marginInline: "5.5px",
    padding: "25.5px 12px",
  },
  separator: {
    backgroundColor: tokens.colorBorderTertiary,
    height: "0.5px",
    marginInline: "12px",
  },
});
