import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  panel: {
    backgroundColor: tokens.colorSurfacePopover,
    borderRadius: tokens.radiusPopover,
    boxShadow: `0 1px 2px ${tokens.elevationPanelDetail}, 0 6px 20px ${tokens.elevationOverlayAmbient}`,
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    display: "flex",
    flexDirection: "column",
    height: "auto",
    maxHeight: "min(450px, calc(100vh - 32px))",
    overflow: "hidden",
    width: "min(720px, calc(100vw - 32px))",
  },
  search: {
    alignItems: "center",
    borderBottomColor: tokens.colorBorderTertiary,
    borderBottomStyle: "solid",
    borderBottomWidth: "0.5px",
    boxSizing: "border-box",
    display: "flex",
    gap: "9px",
    height: "42px",
    marginInline: "7px",
    paddingInline: "9px",
  },
  input: {
    backgroundColor: "transparent",
    borderStyle: "none",
    color: tokens.colorContentPrimary,
    flex: 1,
    fontFamily: tokens.fontSans,
    fontSize: tokens.typeLabelSize,
    fontWeight: 400,
    lineHeight: "normal",
    minWidth: 0,
    outline: "none",
    padding: 0,
    "::placeholder": { color: tokens.colorContentTertiary, opacity: 1 },
  },
  searchHint: {
    color: tokens.colorContentTertiary,
    flexShrink: 0,
    fontFamily: tokens.fontSans,
    fontSize: tokens.typeMetadataSize,
    lineHeight: tokens.typeMetadataLineHeight,
  },
  list: { minHeight: 0, outline: 0, overflowY: "auto", padding: "2px 6px 6px" },
  groupLabel: {
    color: tokens.colorContentTertiary,
    fontFamily: tokens.fontSans,
    fontSize: tokens.typeMetadataSize,
    fontWeight: 500,
    height: "28px",
    lineHeight: tokens.typeMetadataLineHeight,
    marginInline: "6px",
    padding: "7px 9px 4px",
    boxSizing: "border-box",
  },
  item: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorSurfaceOverlayHover,
      "[data-highlighted]": tokens.colorSurfaceOverlayHover,
      '[data-visual-state="highlighted"]': tokens.colorSurfaceOverlayHover,
      "[data-disabled]:hover": "transparent",
    },
    borderRadius: tokens.radiusControl,
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    cursor: { default: "default", "[data-disabled]": "not-allowed" },
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: tokens.typeLabelSize,
    fontWeight: 400,
    gap: "10px",
    height: "36px",
    lineHeight: tokens.typeLabelLineHeight,
    outline: 0,
    paddingInline: "10px",
    userSelect: "none",
  },
  itemDisabled: { opacity: tokens.opacityDisabled },
  itemIcon: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  itemText: { flex: 1, minWidth: 0 },
  shortcut: {
    alignItems: "center",
    borderColor: tokens.colorBorderTertiary,
    borderRadius: "4px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxSizing: "border-box",
    color: tokens.colorContentSecondary,
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: tokens.fontSans,
    fontSize: tokens.typeMetadataSize,
    fontWeight: 500,
    height: "22px",
    justifyContent: "center",
    lineHeight: "13px",
    minWidth: "20px",
    paddingInline: "5px",
  },
  empty: {
    color: tokens.colorContentTertiary,
    fontFamily: tokens.fontSans,
    fontSize: tokens.typeLabelSize,
    lineHeight: "19.5px",
    marginInline: "5.5px",
    padding: "25.5px 12px",
    ":empty": { display: "none" },
  },
  separator: {
    backgroundColor: tokens.colorBorderTertiary,
    height: "0.5px",
    marginInline: "12px",
  },
});
