import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  stage: {
    alignItems: "center",
    display: "flex",
    height: "520px",
    justifyContent: "center",
    overflow: "hidden",
    padding: "10px",
    "@media (max-width: 720px)": { padding: "8px" },
  },
  frame: {
    borderColor: "var(--color-border-tertiary)",
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: "9px",
    height: "500px",
    overflow: "hidden",
    width: "100%",
  },
  page: {
    marginInline: "auto",
    maxWidth: "690px",
    padding: "34px 28px 50px",
    width: "100%",
    "@media (max-width: 720px)": { padding: "24px 18px" },
  },
  pageHeading: {
    borderBottomColor: "var(--console-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    paddingBottom: "24px",
  },
  pageTitle: { fontSize: "20px", fontWeight: 600, lineHeight: 1.3, margin: "8px 0 4px" },
  pageDescription: { color: "var(--console-muted)", fontSize: "12px", lineHeight: 1.5, margin: 0 },
  path: { color: "var(--console-muted)", fontSize: "11px" },
  pageSection: { marginTop: "26px" },
  sectionTitle: { fontSize: "14px", fontWeight: 600, margin: "0 0 12px" },
  focus: {
    borderBottomColor: "var(--console-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    paddingBlock: "22px 24px",
  },
  focusLabel: { color: "var(--console-muted)", fontSize: "11px" },
  focusTitle: { fontSize: "17px", fontWeight: 600, margin: "5px 0" },
  focusDescription: { color: "var(--console-muted)", fontSize: "12px", lineHeight: 1.5, margin: 0 },
  rows: { display: "grid" },
  row: {
    alignItems: "center",
    borderBottomColor: "var(--console-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    gap: "12px",
    justifyContent: "space-between",
    minHeight: "54px",
  },
  rowCopy: { display: "grid", gap: "3px", minWidth: 0 },
  rowTitle: { fontSize: "12px", fontWeight: 550 },
  rowDetail: {
    color: "var(--console-muted)",
    fontSize: "11px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  rowArrow: { color: "var(--console-accent)", fontSize: "15px" },
  sidebarFooter: {
    borderTopColor: "var(--console-line)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--console-text)",
    fontSize: "11px",
    fontWeight: 600,
    marginTop: "130px",
    padding: "12px 8px",
  },
  sidebarFooterDetail: {
    color: "var(--console-muted)",
    display: "block",
    fontWeight: 400,
    marginTop: "2px",
  },
  marketplace: {
    minHeight: "100%",
    padding: "70px 24px 80px",
    width: "100%",
    "@media (max-width: 720px)": { padding: "46px 20px 60px" },
  },
  marketplaceContent: { marginInline: "auto", maxWidth: "700px", width: "100%" },
  marketplaceTitle: {
    fontSize: "23px",
    fontWeight: 500,
    lineHeight: 1.3,
    margin: "0 0 29px",
    textAlign: "center",
    "@media (max-width: 900px)": { fontSize: "19px" },
  },
  marketSearch: {
    alignItems: "center",
    backgroundColor: "var(--console-raised)",
    borderColor: "var(--console-market-search-line)",
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: "13px",
    color: "var(--console-muted)",
    display: "flex",
    gap: "13px",
    height: "40px",
    marginBottom: "28px",
    paddingInline: "16px",
    width: "100%",
    "@media (max-width: 900px)": { height: "36px" },
  },
  marketSearchInput: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--console-text)",
    flex: 1,
    fontFamily: "inherit",
    fontSize: "14px",
    minWidth: 0,
    outline: "none",
    "::placeholder": { color: "var(--console-muted)" },
    "@media (max-width: 900px)": { fontSize: "13.5px" },
  },
  marketHero: {
    backgroundColor: "#bcb8fa",
    backgroundImage: "url('/console-workspace/marketplace-ribbon.png')",
    backgroundPosition: "center",
    backgroundSize: "cover",
    borderRadius: "18px",
    height: "249px",
    overflow: "hidden",
    position: "relative",
    "@media (max-width: 720px)": { height: "215px" },
  },
  heroChips: {
    alignItems: "flex-end",
    display: "flex",
    flexDirection: "column",
    gap: "11px",
    inset: 0,
    justifyContent: "center",
    paddingRight: "28px",
    position: "absolute",
    transform: "translateX(-90px)",
    "@media (max-width: 900px)": {
      alignItems: "stretch",
      paddingInline: "16px",
      transform: "none",
    },
  },
  heroChip: {
    alignItems: "center",
    backgroundColor: "white",
    borderRadius: "999px",
    boxShadow: "0 2px 10px #32316a12",
    color: "#26252a",
    display: "flex",
    fontSize: "12px",
    gap: "11px",
    height: "48px",
    minWidth: "415px",
    paddingInline: "11px",
    "@media (max-width: 900px)": {
      fontSize: "11px",
      minWidth: 0,
      overflow: "hidden",
      width: "100%",
    },
  },
  secondHeroChip: {
    transform: "translateX(24px)",
    "@media (max-width: 900px)": { transform: "none" },
  },
  thirdHeroChip: {
    transform: "translateX(46px)",
    "@media (max-width: 900px)": { transform: "none" },
  },
  chipBrand: {
    alignItems: "center",
    backgroundColor: "#f6f6f7",
    borderRadius: "999px",
    display: "inline-flex",
    flex: "none",
    fontSize: "13px",
    fontWeight: 500,
    gap: "6px",
    height: "28px",
    paddingInline: "8px",
    whiteSpace: "nowrap",
    "@media (max-width: 900px)": { fontSize: "11.5px" },
  },
  profilesBrand: { backgroundColor: "#f9f6fd", color: "#a356d5" },
  observeBrand: { backgroundColor: "#f2faf9", color: "#4aa6a0" },
  chipDescription: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  marketFeaturedTitle: {
    fontSize: "20px",
    fontWeight: 500,
    margin: "41px 0 27px 17px",
    "@media (max-width: 900px)": { fontSize: "17px" },
  },
  marketFeaturedList: {
    columnGap: "48px",
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 260px), 1fr))",
    paddingInlineStart: "17px",
    rowGap: "26px",
    "@media (max-width: 900px)": { gridTemplateColumns: "1fr" },
  },
  marketFeaturedItem: {
    alignItems: "flex-start",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--console-text)",
    cursor: "pointer",
    display: "flex",
    gap: "20px",
    minWidth: 0,
    padding: "10px 0",
    textAlign: "left",
    ":hover": { color: "var(--console-accent)" },
  },
  marketFeaturedIcon: {
    alignItems: "center",
    borderColor: "var(--console-line)",
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: "14px",
    display: "flex",
    flex: "0 0 50px",
    height: "50px",
    justifyContent: "center",
    width: "50px",
  },
  marketFeaturedCopy: { flex: 1, minWidth: 0 },
  marketFeaturedName: { display: "block", fontSize: "16.5px", fontWeight: 500 },
  marketFeaturedDetail: {
    color: "var(--console-secondary)",
    display: "block",
    fontSize: "14px",
    marginTop: "6px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    "@media (max-width: 900px)": { fontSize: "12px", marginTop: "4px" },
  },
  marketFeaturedArrow: { color: "var(--console-muted)", flex: "none", marginTop: "7px" },
  marketEmpty: { color: "var(--console-muted)", fontSize: "13px", margin: "0 0 0 17px" },
});
