// HeroUI v3.2.6 table.css adaptation, Apache-2.0.
import * as stylex from "@stylexjs/stylex";
import { tokens } from "../../tokens.stylex.const.js";
export const tableStyles = stylex.create({
  root: {
    boxSizing: "border-box",
    position: "relative",
    display: "grid",
    width: "100%",
    overflow: "clip",
    gridTemplateColumns: "minmax(0, 1fr)",
  },
  primary: {
    backgroundColor: tokens.surfaceSecondary,
    paddingInline: 4,
    paddingBottom: 4,
    borderRadius: `min(32px, calc(${tokens.radius} * 2.5))`,
  },
  scrollContainer: { position: "relative", overflow: "auto", scrollbarGutter: "auto" },
  content: { width: "100%", borderCollapse: "separate", borderSpacing: 0, fontSize: 14 },
  header: { backgroundColor: tokens.surfaceSecondary },
  column: {
    boxSizing: "border-box",
    position: "relative",
    paddingInline: 16,
    paddingBlock: 10,
    textAlign: "start",
    fontSize: 12,
    fontWeight: 500,
    color: tokens.muted,
    outline: "none",
    boxShadow: { default: "none", ":focus-visible": `inset 0 0 0 2px ${tokens.focus}` },
    "::after": {
      content: {
        default: '""',
        ":last-child": "none",
        ":has([data-slot='table-column-resizer'])": "none",
      },
      pointerEvents: "none",
      position: "absolute",
      insetInlineEnd: 0,
      top: "50%",
      height: 16,
      width: 1,
      transform: "translateY(-50%)",
      borderRadius: tokens.radiusSm,
      backgroundColor: tokens.separator,
    },
  },
  sortableColumn: {
    cursor: tokens.cursorInteractive,
    color: { default: tokens.muted, ":hover": tokens.foreground },
  },
  secondaryColumn: {
    backgroundColor: tokens.surfaceSecondary,
    borderStartStartRadius: { default: 0, ":first-child": `min(32px, ${tokens.radius2xl})` },
    borderEndStartRadius: { default: 0, ":first-child": `min(32px, ${tokens.radius2xl})` },
    borderStartEndRadius: { default: 0, ":last-child": `min(32px, ${tokens.radius2xl})` },
    borderEndEndRadius: { default: 0, ":last-child": `min(32px, ${tokens.radius2xl})` },
  },
  body: { boxShadow: tokens.shadowSurface },
  secondaryBody: { boxShadow: "none" },
  row: { position: "relative", height: "100%" },
  cell: {
    boxSizing: "border-box",
    height: "100%",
    paddingInline: 16,
    paddingBlock: 12,
    verticalAlign: "middle",
    fontSize: 14,
    color: tokens.foreground,
    backgroundColor: {
      default: tokens.surface,
      ":is(tr:hover > td)": `color-mix(in oklch, ${tokens.surface} 40%, transparent)`,
    },
    borderBottom: `1px solid color-mix(in oklch, ${tokens.separatorTertiary} 50%, transparent)`,
    outline: "none",
    boxShadow: { default: "none", ":focus-visible": `inset 0 0 0 2px ${tokens.focus}` },
    borderStartStartRadius: {
      default: 0,
      ":is(tr:first-child > td:first-child)": `min(32px, ${tokens.radius2xl})`,
    },
    borderStartEndRadius: {
      default: 0,
      ":is(tr:first-child > td:last-child)": `min(32px, ${tokens.radius2xl})`,
    },
    borderEndStartRadius: {
      default: 0,
      ":is(tr:last-child > td:first-child)": `min(32px, ${tokens.radius2xl})`,
    },
    borderEndEndRadius: {
      default: 0,
      ":is(tr:last-child > td:last-child)": `min(32px, ${tokens.radius2xl})`,
    },
  },
  secondaryCell: {
    backgroundColor: {
      default: "transparent",
      ":is(tr:hover > td)": `color-mix(in oklch, ${tokens.default} 50%, transparent)`,
    },
    borderStartStartRadius: 0,
    borderStartEndRadius: 0,
    borderEndStartRadius: 0,
    borderEndEndRadius: 0,
  },
  selectedCell: { backgroundColor: `color-mix(in oklch, ${tokens.surface} 10%, transparent)` },
  disabled: { opacity: tokens.disabledOpacity, cursor: tokens.cursorDisabled },
  footer: { display: "flex", alignItems: "center", paddingInline: 16, paddingBlock: 10 },
  sortableColumnHeader: { display: "flex", alignItems: "center", justifyContent: "space-between" },
  sortableColumnIndicator: {
    display: "inline-grid",
    width: 12,
    height: 12,
    placeContent: "center",
    transitionProperty: "transform",
    transitionDuration: { default: "100ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: tokens.easeOut,
  },
  descending: { transform: "rotate(180deg)" },
  columnResizer: {
    position: "absolute",
    insetInlineEnd: 0,
    top: "50%",
    height: 16,
    width: 1,
    transform: "translateY(-50%)",
    borderRadius: tokens.radiusSm,
    backgroundColor: {
      default: tokens.separator,
      ":hover": tokens.accent,
      ":focus-visible": tokens.focus,
    },
    boxSizing: "content-box",
    paddingInline: 8,
    backgroundClip: "content-box",
    borderWidth: 0,
    outline: "none",
    cursor: "col-resize",
    touchAction: "none",
  },
  loadMoreContent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingBlock: 8,
  },
});
