import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";
import { resizeHandleState } from "../resize-handle/resize-handle.stylex.js";

export const styles = stylex.create({
  root: {
    backgroundColor: tokens.colorSurfaceCanvas,
    fontFamily: tokens.fontSans,
    maxWidth: "100%",
    overflow: "auto",
    position: "relative",
  },
  table: {
    borderCollapse: "separate",
    borderSpacing: 0,
    color: tokens.colorContentPrimary,
    fontSize: tokens.typeLabelSize,
    lineHeight: tokens.typeBodyLineHeight,
    tableLayout: "fixed",
  },
  header: {},
  body: {},
  footer: {},
  row: {
    backgroundColor: tokens.colorSurfaceCanvas,
  },
  bodyRow: { ":hover": { backgroundColor: tokens.colorSurfaceInteractiveHover } },
  groupRow: { backgroundColor: tokens.colorSurfaceCanvas },
  groupCell: {
    boxSizing: "border-box",
    color: tokens.colorContentSecondary,
    fontSize: tokens.typeLabelSize,
    fontWeight: 500,
    height: "36px",
    paddingBlock: 0,
    paddingInline: 0,
    textAlign: "left",
    whiteSpace: "nowrap",
  },
  groupSurface: {
    alignItems: "center",
    backgroundColor: tokens.colorSurfaceInteractiveHover,
    borderRadius: tokens.radiusRow,
    display: "flex",
    height: "32px",
    marginBlock: "2px",
  },
  groupContent: { display: "inline-flex", left: tokens.space3, position: "sticky" },
  groupCount: { color: tokens.colorContentTertiary, fontWeight: 400, marginLeft: tokens.space2 },
  selectedRow: {
    backgroundColor: tokens.colorSurfaceSelected,
    ":hover": { backgroundColor: tokens.colorSurfaceSelected },
  },
  cell: {
    boxSizing: "border-box",
    height: "48px",
    maxWidth: 0,
    overflow: "hidden",
    paddingBlock: 0,
    paddingInline: tokens.space3,
    textAlign: "left",
    verticalAlign: "middle",
    whiteSpace: "nowrap",
  },
  head: {
    backgroundColor: tokens.colorSurfaceCanvas,
    color: tokens.colorContentTertiary,
    fontSize: tokens.typeMetadataSize,
    fontWeight: 400,
    height: "32px",
    position: "sticky",
    top: 0,
    overflow: "visible",
    zIndex: 40,
  },
  pinnedHead: { zIndex: 60 },
  bodyCell: {
    backgroundColor: "inherit",
    ":first-child": {
      borderBottomLeftRadius: tokens.radiusRow,
      borderTopLeftRadius: tokens.radiusRow,
    },
    ":last-child": {
      borderBottomRightRadius: tokens.radiusRow,
      borderTopRightRadius: tokens.radiusRow,
    },
  },
  joinsPrevious: {
    ":first-child": { borderTopLeftRadius: 0 },
    ":last-child": { borderTopRightRadius: 0 },
  },
  joinsNext: {
    ":first-child": { borderBottomLeftRadius: 0 },
    ":last-child": { borderBottomRightRadius: 0 },
  },
  pinnedCell: { position: "sticky", zIndex: 10 },
  footCell: {
    backgroundColor: tokens.colorSurfaceCanvas,
    borderBottomWidth: 0,
    color: tokens.colorContentTertiary,
    height: "38px",
    position: "sticky",
    bottom: 0,
    zIndex: 20,
  },
  pinnedFootCell: { zIndex: 40 },
  mutedCell: { color: tokens.colorContentTertiary },
  headContent: {
    alignItems: "center",
    display: "flex",
    gap: tokens.space2,
    minWidth: 0,
  },
  sortButton: {
    backgroundColor: { default: "transparent", ":hover": tokens.colorSurfaceInteractiveHover },
    borderRadius: tokens.radiusRounded,
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    font: "inherit",
    height: "28px",
    marginLeft: `calc(-1 * ${tokens.space2})`,
    paddingInline: tokens.space2,
    ":focus-visible": {
      backgroundColor: tokens.colorSurfaceInteractiveHover,
      outlineColor: tokens.colorFocusRing,
      outlineStyle: "solid",
      outlineWidth: "2px",
    },
  },
  headIcon: {
    alignItems: "center",
    color: tokens.colorContentTertiary,
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  ellipsis: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  resizeHandle: {
    position: "absolute",
    right: 0,
    top: 0,
    zIndex: 100,
  },
  resizeGuide: {
    backgroundColor: resizeHandleState.color,
    backgroundImage: "none",
    bottom: "auto",
    height: "var(--lenso-resize-guide-height)",
    top: 0,
  },
});
