import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  root: {
    backgroundColor: tokens.colorSurfaceCanvas,
    borderColor: tokens.colorBorderTertiary,
    borderStyle: "solid",
    borderWidth: tokens.sizeBorderControl,
    fontFamily: tokens.fontSans,
    maxWidth: "100%",
    overflow: "auto",
    position: "relative",
  },
  table: {
    borderCollapse: "separate",
    borderSpacing: 0,
    color: tokens.colorContentPrimary,
    fontSize: tokens.typeBodySize,
    lineHeight: tokens.typeBodyLineHeight,
    tableLayout: "fixed",
  },
  header: {},
  body: {},
  footer: {},
  row: {
    backgroundColor: tokens.colorSurfaceCanvas,
    ":hover": { backgroundColor: tokens.colorSurfaceInteractiveHover },
  },
  selectedRow: { backgroundColor: tokens.colorSurfaceSelected },
  cell: {
    borderBottomColor: tokens.colorBorderTertiary,
    borderBottomStyle: "solid",
    borderBottomWidth: tokens.sizeBorderControl,
    borderRightColor: tokens.colorBorderTertiary,
    borderRightStyle: "solid",
    borderRightWidth: tokens.sizeBorderControl,
    boxSizing: "border-box",
    height: "40px",
    maxWidth: 0,
    overflow: "hidden",
    paddingBlock: 0,
    paddingInline: tokens.space3,
    textAlign: "left",
    verticalAlign: "middle",
    whiteSpace: "nowrap",
  },
  head: {
    backgroundColor: tokens.colorSurfaceCanvas,
    color: tokens.colorContentTertiary,
    fontWeight: 400,
    position: "sticky",
    top: 0,
    zIndex: 20,
  },
  pinnedHead: { zIndex: 40 },
  bodyCell: { backgroundColor: "inherit" },
  pinnedCell: { position: "sticky", zIndex: 10 },
  footCell: {
    backgroundColor: tokens.colorSurfaceCanvas,
    borderBottomWidth: 0,
    color: tokens.colorContentTertiary,
    height: "44px",
    position: "sticky",
    bottom: 0,
    zIndex: 20,
  },
  pinnedFootCell: { zIndex: 40 },
  mutedCell: { color: tokens.colorContentTertiary },
  headContent: {
    alignItems: "center",
    display: "flex",
    gap: tokens.space2,
    minWidth: 0,
  },
  headIcon: {
    alignItems: "center",
    color: tokens.colorContentTertiary,
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  ellipsis: {
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  resizeHandle: {
    borderWidth: 0,
    bottom: 0,
    cursor: "col-resize",
    margin: 0,
    position: "absolute",
    right: 0,
    top: 0,
    width: "6px",
    ":hover": { backgroundColor: tokens.colorFocusRing },
    ":focus-visible": { backgroundColor: tokens.colorFocusRing, outline: "none" },
  },
});
