/** HeroUI v3.2.6 derived work. Copyright NextUI Inc. Apache-2.0. Modified for StyleX. */
import * as stylex from "@stylexjs/stylex";
import { tokens } from "../../tokens.stylex.const.js";
export const calendarStyles = stylex.create({
  root: { position: "relative", width: 252, maxWidth: 252, containerType: "inline-size" },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingInline: 2,
    paddingBottom: 16,
  },
  heading: { flex: 1, fontSize: 14, fontWeight: 500 },
  navButton: {
    display: "flex",
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: tokens.radius2xl,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: tokens.accentSoftForeground,
    cursor: "pointer",
    padding: 0,
  },
  hovered: { backgroundColor: tokens.default },
  pressed: { transform: "scale(.95)" },
  navIcon: { width: 16, height: 16 },
  rtlIcon: { transform: "rotate(180deg)" },
  focused: { outline: "2px solid", outlineColor: tokens.focus, outlineOffset: 2 },
  disabled: { opacity: tokens.disabledOpacity },
  navHidden: { visibility: "hidden", pointerEvents: "none" },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(7,1fr)",
    width: "100%",
    opacity: 1,
    visibility: "visible",
    transitionProperty: "opacity,visibility",
    transitionDuration: { default: "150ms,0ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: tokens.easeSmooth,
  },
  dayGrid: { display: "flex", flexDirection: "column" },
  section: { display: "contents" },
  row: { display: "contents" },
  daySection: { display: "grid", gridTemplateColumns: "repeat(7,1fr)", width: "100%" },
  dayBody: { marginTop: 4 },
  gridHidden: {
    visibility: "hidden",
    pointerEvents: "none",
    opacity: 0,
    transitionDelay: { default: "0ms,150ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
  },
  headerCell: {
    paddingBottom: 8,
    fontSize: 12,
    fontWeight: 500,
    color: tokens.muted,
    textAlign: "center",
  },
  cell: {
    position: "relative",
    display: "flex",
    aspectRatio: "1 / 1",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: tokens.radius3xl,
    textAlign: "center",
    fontSize: 14,
    fontWeight: 500,
    outline: "none",
    cursor: "pointer",
  },
  today: { backgroundColor: tokens.accentSoft, color: tokens.accentSoftForeground },
  selected: { backgroundColor: tokens.accent, color: tokens.accentForeground },
  selectedHovered: { backgroundColor: tokens.accentHover },
  outside: { color: tokens.muted, opacity: 0.5 },
  unavailable: { opacity: tokens.disabledOpacity, textDecoration: "line-through" },
  indicator: {
    position: "absolute",
    bottom: 4,
    left: "50%",
    width: 3,
    height: 3,
    transform: "translateX(-50%)",
    borderRadius: 2,
    backgroundColor: tokens.muted,
  },
  selectedIndicator: { backgroundColor: tokens.accentForeground },
  range: {
    backgroundColor: tokens.accentSoft,
    color: tokens.accentSoftForeground,
    borderRadius: 0,
  },
  rangeStart: { borderStartStartRadius: tokens.radius3xl, borderEndStartRadius: tokens.radius3xl },
  rangeEnd: { borderStartEndRadius: tokens.radius3xl, borderEndEndRadius: tokens.radius3xl },
});
