import * as stylex from "@stylexjs/stylex";

export const colors = stylex.create({
  columns: {
    display: "flex",
    flexDirection: { default: "row", "@media (max-width: 639px)": "column" },
    gap: 16,
  },
  stack: { display: "flex", flexDirection: "column", gap: 8 },
  column: { display: "flex", flexDirection: "column", flex: 1, minWidth: 0, gap: 8 },
  row: {
    display: "flex",
    flexWrap: { default: "nowrap", "@media (max-width: 639px)": "wrap" },
    gap: 8,
  },
  nestedRow: {
    display: "flex",
    flexDirection: { default: "row", "@media (max-width: 639px)": "column" },
    gap: 8,
  },
  panel: (background: string) => ({
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minWidth: 0,
    gap: 6,
    borderRadius: 12,
    padding: 12,
    backgroundColor: background,
    position: "relative",
    overflow: "hidden",
  }),
  header: (background: string) => ({
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    gap: 8,
    paddingInline: 16,
    paddingBlock: 12,
    borderRadius: 12,
    borderWidth: 0,
    backgroundColor: background,
    cursor: "pointer",
    textAlign: "start",
    font: "inherit",
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: 2 },
  }),
  block: (background: string) => ({
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    width: "100%",
    minWidth: 0,
    gap: 0,
    borderRadius: 12,
    borderWidth: 0,
    paddingInline: 16,
    paddingBlock: 10,
    backgroundColor: background,
    font: "inherit",
    textAlign: "start",
    cursor: "pointer",
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: 2 },
  }),
  swatch: {
    minHeight: 56,
    flex: { default: 1, "@media (max-width: 639px)": "1 1 100%" },
    paddingBlock: 8,
  },
  border: { borderWidth: 1, borderStyle: "solid", borderColor: "var(--border)" },
  contrast: (background: string) => ({
    backgroundClip: "text",
    backgroundColor: background,
    color: "transparent",
    filter: "invert(1) grayscale(1) contrast(100)",
  }),
  label: { fontSize: 14, lineHeight: "20px", fontWeight: 500, letterSpacing: "-0.025em" },
  labelGroup: { display: "flex", flexDirection: "column" },
  panelLabel: { fontSize: 16, lineHeight: "24px", fontWeight: 500, letterSpacing: "-0.025em" },
  softPanel: (background: string) => ({
    backgroundColor: "var(--surface)",
    backgroundImage: `linear-gradient(${background}, ${background})`,
  }),
  foreground: { color: "var(--foreground)" },
  tooltip: { maxWidth: 320 },
  tooltipText: {
    fontFamily: "ui-monospace, monospace",
    fontSize: 12,
    lineHeight: 1.625,
    whiteSpace: "pre-wrap",
    margin: 0,
  },
  title: { fontSize: 18, lineHeight: "28px", fontWeight: 500, letterSpacing: "-0.025em" },
  themeText: { fontSize: 12, lineHeight: "16px", fontWeight: 500 },
  token: {
    display: { default: "none", "@media (max-width: 639px)": "block" },
    fontFamily: "ui-monospace, monospace",
    fontSize: 10,
    lineHeight: 1.25,
    opacity: 0.6,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  chip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    alignSelf: "flex-start",
    backgroundColor: "var(--default)",
    color: "var(--foreground)",
    borderRadius: 999,
    paddingInline: 8,
    height: 24,
    fontSize: 12,
  },
  formAside: {
    display: "flex",
    flexDirection: { default: "column", "@media (max-width: 639px)": "row" },
    width: { default: 160, "@media (max-width: 639px)": "100%" },
    gap: 8,
    minWidth: 0,
  },
  fill: { flex: 1, height: "100%" },
});
