import * as stylex from "@stylexjs/stylex";

// HeroUI v3.2.6 DesignThemeSelector geometry, Apache-2.0.
// Modified: semantic StyleX maps and visible native keyboard focus.
export const docsThemePicker = stylex.create({
  trigger: { fontSize: 12, color: "var(--muted)" },
  triggerLayout: { display: "inline-flex" },
  namedTrigger: {
    gap: 6,
    paddingInlineStart: { default: 8, "@media (max-width: 639px)": 0 },
    paddingInlineEnd: { default: 10, "@media (max-width: 639px)": 0 },
    minWidth: 0,
    borderWidth: 0,
    backgroundColor: { default: "var(--default)", "@media (max-width: 639px)": "transparent" },
  },
  bucket: { color: "var(--foreground)", flexShrink: 0 },
  avatar: {
    width: { default: 14, "@media (max-width: 639px)": 20 },
    height: { default: 14, "@media (max-width: 639px)": 20 },
    flexShrink: 0,
    borderRadius: "50%",
  },
  triggerLabel: { display: { default: "inline", "@media (max-width: 639px)": "none" } },
  popup: {
    boxSizing: "border-box",
    width: 248,
    maxWidth: "calc(100vw - 24px)",
    borderRadius: 24,
    padding: 16,
    overflow: "visible",
  },
  hidden: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
  presets: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 12,
    padding: 0,
    overflow: "visible",
  },
  item: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    gap: 6,
    padding: 0,
    paddingBlock: 0,
    paddingInlineStart: 0,
    paddingInlineEnd: 0,
    marginBlockStart: { default: 0, ":is([role='listbox'] > :not(:first-child))": 0 },
    overflow: "visible",
    backgroundColor: {
      default: "transparent",
      ":hover": "transparent",
      ':is([data-selected="true"])': "transparent",
    },
    color: "var(--muted)",
    outlineOffset: 4,
  },
  selectedItem: { color: "var(--foreground)" },
  image: {
    width: 36,
    height: 36,
    flexShrink: 0,
    borderRadius: "50%",
    backgroundColor: "var(--surface)",
  },
  selectedImage: {
    boxShadow: "0 0 0 2px var(--surface), 0 0 0 4px var(--accent)",
  },
  label: { fontSize: 10, fontWeight: 500, textTransform: "capitalize" },
  details: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--separator)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  description: { display: "flex", flexDirection: "column", gap: 2 },
  vibrantLabel: { fontSize: 12, color: "var(--foreground)" },
  vibrantHint: { fontSize: 10, color: "var(--muted)" },
  edit: {
    marginTop: 12,
    borderRadius: 999,
    fontSize: 13,
    fontWeight: 500,
    color: "var(--muted)",
    boxSizing: "border-box",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: 32,
    gap: 8,
    paddingInline: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    textDecoration: "none",
    ":hover": { backgroundColor: "var(--default)", textDecoration: "none" },
  },
});
