import * as stylex from "@stylexjs/stylex";

// Adapted from HeroUI v3.2.6 apps/docs/src/app/global.css and notebook layouts.
// Apache-2.0. Tailwind utilities are translated to compiled StyleX.
export const styles = stylex.create({
  body: {
    margin: 0,
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    fontFamily: "var(--font-inter), ui-sans-serif, system-ui, sans-serif",
    fontSize: 16,
    lineHeight: 1.5,
    WebkitFontSmoothing: "antialiased",
    fontSynthesis: "none",
    // The source Inter has fixed text optical metrics; retain those with the newer opsz-capable font.
    fontOpticalSizing: "none",
    textRendering: "optimizeLegibility",
    minHeight: "100dvh",
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 30,
    display: "flex",
    flexDirection: "column",
    gap: { default: 4, "@media (max-width: 767px)": 0 },
    backgroundColor: "var(--background)",
    gridColumn: "1 / -1",
    "::after": {
      content: '""',
      position: "absolute",
      left: "50%",
      bottom: 0,
      width: "100vw",
      transform: "translateX(-50%)",
      height: 1,
      backgroundColor: "var(--separator)",
    },
  },
  brand: {
    color: "var(--foreground)",
    fontWeight: 700,
    fontSize: 26,
    textDecoration: "none",
    letterSpacing: "-0.04em",
  },
  sectionBar: {
    display: "flex",
    alignItems: "end",
    gap: { default: 12, "@media (max-width: 767px)": 4 },
    height: 40,
    paddingInline: { default: 24, "@media (max-width: 767px)": 16 },
    overflowX: "auto",
    scrollbarWidth: "none",
  },
  row: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 16 },
  link: {
    color: "var(--foreground)",
    textDecoration: "none",
    borderRadius: 6,
    outlineColor: "var(--focus)",
    ":hover": { color: "var(--accent)" },
    ":focus-visible": { outlineStyle: "solid", outlineWidth: 2, outlineOffset: 3 },
  },
  muted: { color: "var(--muted)", fontSize: 13 },
  shell: {
    display: "grid",
    gridTemplateColumns: {
      default: "220px minmax(0, 1fr) 268px",
      "@media (max-width: 1279px)": "220px minmax(0, 1fr)",
      "@media (max-width: 767px)": "minmax(0, 1fr)",
    },
    maxWidth: 1400,
    marginInline: "auto",
    minHeight: "calc(100dvh - 32px)",
  },
  sidebar: {
    gridColumn: 1,
    gridRow: "2 / span 2",
    position: "sticky",
    top: 100,
    height: "calc(100dvh - 132px)",
    boxSizing: "border-box",
    overflowY: "auto",
    paddingTop: 24,
    paddingInlineStart: 16,
    paddingInlineEnd: 16,
    paddingBottom: 16,
    fontSize: 14,
    lineHeight: "20px",
    display: { default: "block", "@media (max-width: 767px)": "none" },
    scrollbarWidth: "thin",
    scrollbarColor: {
      default: "transparent transparent",
      ":hover": "var(--scrollbar) transparent",
      ":focus-within": "var(--scrollbar) transparent",
    },
    overscrollBehavior: "contain",
  },
  desktop: { display: { default: "block", "@media (max-width: 767px)": "none" } },
  mobile: { display: { default: "none", "@media (max-width: 767px)": "block" } },
  navigation: { display: "flex", flexDirection: "column", gap: 2 },
  navHeading: {
    marginTop: { default: 16, ":first-child": 0 },
    marginBottom: 0,
    paddingInline: 8,
    fontWeight: 500,
    fontSize: 14,
    color: "var(--foreground)",
  },
  navLink: {
    padding: 8,
    minHeight: 20,
    textDecoration: "none",
    color: "var(--muted)",
    fontSize: 14,
    lineHeight: "20px",
    borderRadius: 8,
    outlineColor: "var(--focus)",
    wordBreak: "keep-all",
    overflowWrap: "break-word",
    ":hover": {
      backgroundColor: "color-mix(in oklch, var(--foreground) 4%, transparent)",
      color: "var(--foreground)",
    },
    ":focus-visible": { outlineStyle: "solid", outlineWidth: 2 },
  },
  active: {
    backgroundColor: "var(--surface)",
    color: "var(--foreground)",
    boxShadow: "var(--surface-shadow)",
  },
  content: {
    gridColumn: { default: 2, "@media (max-width: 767px)": 1 },
    gridRow: { default: 2, "@media (max-width: 1279px)": 3 },
    marginTop: { default: 0, "@media (max-width: 1279px)": 16 },
    paddingTop: { default: 32, "@media (max-width: 1279px)": 16 },
    paddingBottom: 24,
    paddingInline: {
      default: 48,
      "@media (max-width: 1279px)": 24,
      "@media (max-width: 767px)": 24,
    },
    minWidth: 0,
  },
  article: { minWidth: 0, overflowWrap: "anywhere" },
  title: {
    fontSize: 28,
    fontWeight: 600,
    letterSpacing: "normal",
    lineHeight: 1.5,
    margin: 0,
  },
  description: { fontSize: 16, color: "var(--muted)", marginTop: 16, marginBottom: 24 },
  h2: {
    fontSize: 24,
    fontWeight: 600,
    letterSpacing: "normal",
    lineHeight: 1.333333,
    marginTop: 32,
    marginBottom: 24,
    scrollMarginTop: 160,
  },
  h3: { fontSize: 20, fontWeight: 600, marginTop: 24, marginBottom: 12, scrollMarginTop: 160 },
  paragraph: { marginBlock: 16, fontSize: 14, lineHeight: 1.714 },
  proseLink: {
    color: "var(--foreground)",
    fontWeight: 500,
    textDecoration: "underline",
    textUnderlineOffset: 3,
    ":hover": { textDecorationColor: "var(--accent)" },
  },
  inlineCode: {
    fontSize: "0.875em",
    fontFamily: "ui-monospace, monospace",
    backgroundColor: "var(--default)",
    borderRadius: 4,
    paddingInline: 4,
    paddingBlock: 2,
  },
  pre: {
    fontSize: 13,
    lineHeight: 1.428571,
    fontFamily:
      'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    backgroundColor: "var(--default)",
    borderWidth: 0,
    borderRadius: 12,
    paddingBlock: 14,
    paddingInline: 24,
    overflowX: "auto",
    whiteSpace: "pre",
    marginBlock: 16,
  },
  tableScroll: { overflowX: "auto", marginBlock: 24 },
  table: { borderCollapse: "collapse", width: "100%", textAlign: "start", fontSize: 13 },
  cell: {
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--border)",
    paddingBlock: 12,
    paddingInline: 12,
    verticalAlign: "top",
  },
  callout: {
    backgroundColor: "var(--surface-secondary)",
    borderRadius: 12,
    paddingBlock: 12,
    paddingInline: 20,
    marginBlock: 24,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
  },
  preview: {
    marginBlock: 16,
  },
  previewBody: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 350,
    boxSizing: "border-box",
    padding: { default: 40, "@media (max-width: 639px)": 16 },
    borderInlineWidth: 1,
    borderTopWidth: 1,
    borderBottomWidth: 0,
    borderStyle: "solid",
    borderColor: "var(--separator)",
    borderStartStartRadius: 12,
    borderStartEndRadius: 12,
    overflow: "hidden",
  },
  sourceSummary: { paddingBlock: 12, paddingInline: 20, cursor: "pointer", fontWeight: 500 },
  sourceNotice: { paddingBlock: 16, paddingInline: 20, color: "var(--muted)", fontSize: 13 },
  toc: {
    gridColumn: 3,
    gridRow: 2,
    width: 240,
    position: "sticky",
    top: 100,
    alignSelf: "start",
    display: { default: "block", "@media (max-width: 1279px)": "none" },
    height: "calc(100dvh - 132px)",
    overflowY: "auto",
    paddingTop: 24,
    paddingInlineStart: 16,
    paddingInlineEnd: 16,
    boxSizing: "border-box",
    fontSize: 14,
    lineHeight: "20px",
  },
  input: {
    width: "100%",
    boxSizing: "border-box",
    backgroundColor: "var(--field-background)",
    color: "var(--field-foreground)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    padding: 10,
    borderRadius: 10,
    font: "inherit",
    outlineColor: "var(--focus)",
  },
  select: {
    backgroundColor: "var(--surface)",
    color: "var(--foreground)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 8,
    padding: 6,
    font: "inherit",
  },
  skip: {
    position: "fixed",
    insetInlineStart: 12,
    top: { default: -100, ":focus": 12 },
    padding: 12,
    backgroundColor: "var(--surface)",
    color: "var(--foreground)",
    zIndex: 100,
  },
  image: { maxWidth: "100%", height: "auto", borderRadius: 12 },
  grid: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (max-width: 600px)": "1fr",
    },
    gap: 16,
    marginBlock: 24,
  },
  footer: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--border)",
    marginTop: 48,
    paddingTop: 24,
    color: "var(--muted)",
    fontSize: 12,
  },
});
