// HeroUI e385ac2 homepage geometry, Apache-2.0; adapted to Lenso identity.
// Copyright 2025 NextUI Inc.
import * as stylex from "@stylexjs/stylex";

export const home = stylex.create({
  main: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    minWidth: 0,
  },
  hero: { paddingTop: 48, paddingInline: 16, textAlign: "center" },
  heroContent: { maxWidth: 672, marginInline: "auto" },
  release: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    minHeight: 24,
    paddingInline: 8,
    paddingBlock: 4,
    borderRadius: 999,
    fontSize: 12,
    lineHeight: "16px",
    color: "var(--accent-soft-foreground)",
    backgroundColor: "var(--accent-soft)",
    textDecorationLine: "none",
  },
  title: {
    display: "flex",
    flexDirection: "column",
    marginTop: { default: 8, "@media (min-width: 1024px)": 16 },
    marginBottom: 0,
    fontSize: {
      default: 30,
      "@media (min-width: 640px) and (max-width: 1023px)": 36,
      "@media (min-width: 1024px)": 48,
    },
    lineHeight: { default: "36px", "@media (min-width: 1024px)": "48px" },
    fontWeight: 700,
    letterSpacing: "-0.025em",
    color: "var(--foreground)",
    textWrap: "balance",
  },
  titleMuted: { color: "color-mix(in oklch, var(--muted) 70%, transparent)" },
  description: {
    margin: 0,
    fontSize: { default: 16, "@media (min-width: 768px)": 18 },
    lineHeight: { default: "24px", "@media (min-width: 768px)": "28px" },
    color: "var(--muted)",
    textWrap: "balance",
  },
  ctas: { display: "flex", justifyContent: "center", flexWrap: "wrap", marginTop: 16, gap: 12 },
  cta: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    height: 36,
    minHeight: 36,
    paddingInline: 16,
    paddingBlock: 0,
    borderRadius: 999,
    fontSize: 14,
    lineHeight: "20px",
    fontWeight: 500,
    textDecorationLine: "none",
  },
  primary: {
    color: "var(--accent-foreground)",
    backgroundColor: "var(--accent)",
    ":hover": { backgroundColor: "color-mix(in oklch, var(--accent) 90%, var(--foreground))" },
  },
  outline: {
    color: "var(--foreground)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    ":hover": { backgroundColor: "var(--default)" },
  },
  repository: {
    display: "flex",
    width: "fit-content",
    marginInline: "auto",
    alignItems: "center",
    gap: 8,
    marginTop: 16,
    color: "var(--muted)",
    fontSize: 12,
    lineHeight: "16px",
    textDecorationLine: "none",
  },
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: 8,
    paddingBlock: 12,
    paddingInline: 16,
    fontSize: 12,
    lineHeight: "20px",
    color: "var(--muted)",
  },
  footerLink: { fontSize: 12, color: "var(--muted)", textDecorationLine: "none" },
});
