import * as stylex from "@stylexjs/stylex";

// HeroUI v3.2.6 notebook/header/page adaptations, Apache-2.0.
// Upstream's paid-product banner is replaced with independent-source attribution.
export const notebook = stylex.create({
  banner: {
    height: 32,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    fontSize: 12,
    backgroundColor: "var(--default)",
    color: "var(--foreground)",
    paddingInline: 12,
  },
  bannerLink: { color: "inherit", textDecoration: "none", whiteSpace: "nowrap" },
  bannerBadge: {
    backgroundColor: "var(--accent)",
    color: "var(--accent-foreground)",
    borderRadius: 999,
    paddingInline: 8,
    fontSize: 11,
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  bannerDetail: { display: { default: "inline", "@media (max-width: 767px)": "none" } },
  headerBody: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    height: { default: 56, "@media (max-width: 767px)": 52 },
    paddingInline: { default: 24, "@media (max-width: 767px)": 16 },
  },
  identity: { display: "flex", alignItems: "center", gap: 16, flex: "1 1 0", minWidth: 0 },
  version: {
    display: { default: "flex", "@media (max-width: 1023px)": "none" },
    alignItems: "center",
    gap: 6,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: "var(--muted)",
    padding: 4,
    font: "inherit",
    fontSize: 14,
    cursor: "pointer",
    borderRadius: 8,
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: 2 },
  },
  actions: { display: "flex", alignItems: "center", gap: 8, flex: "1 1 0", justifyContent: "end" },
  headerDesktop: { display: { default: "flex", "@media (max-width: 767px)": "none" } },
  headerMobile: { display: { default: "none", "@media (max-width: 767px)": "flex" }, gap: 4 },
  searchContainer: {
    flex: "0 1 400px",
    width: "100%",
    maxWidth: 400,
    minWidth: 0,
    marginInlineEnd: { default: 48, "@media (max-width: 1023px)": 0 },
  },
  searchTrigger: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flex: "0 1 400px",
    width: "100%",
    height: 32,
    boxSizing: "border-box",
    borderWidth: 0,
    borderRadius: "var(--field-radius)",
    backgroundColor: "var(--field-background)",
    boxShadow: "var(--field-shadow)",
    color: "var(--muted)",
    paddingInline: 12,
    paddingBlock: 4,
    font: "inherit",
    fontSize: 14,
    textAlign: "start",
    cursor: "pointer",
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: 2 },
  },
  searchLabel: { flexGrow: 1 },
  key: {
    font: "inherit",
    fontSize: 12,
    lineHeight: "20px",
    borderRadius: 4,
    backgroundColor: "var(--default)",
    paddingInline: 4,
  },
  iconButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 36,
    height: 36,
    minWidth: 36,
    padding: 8,
    borderWidth: 0,
    borderRadius: 999,
    boxSizing: "border-box",
    backgroundColor: "var(--default)",
    color: "var(--muted)",
    textDecoration: "none",
    cursor: "pointer",
    ":hover": { color: "var(--foreground)", backgroundColor: "var(--surface-tertiary)" },
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: 2 },
  },
  tab: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    paddingInline: 4,
    paddingTop: 4,
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomStyle: "solid",
    borderBottomColor: "transparent",
    color: "var(--muted)",
    fontSize: 14,
    fontWeight: 500,
    textDecoration: "none",
    whiteSpace: "nowrap",
    ":hover": { color: "var(--foreground)" },
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: -2 },
  },
  selectedTab: { color: "var(--foreground)", borderBottomColor: "var(--accent)" },
  framework: {
    display: { default: "inline-flex", "@media (max-width: 767px)": "none" },
    alignItems: "center",
    gap: 6,
    marginInlineStart: "auto",
    marginBottom: 6,
    backgroundColor: "var(--surface)",
    boxShadow: "var(--surface-shadow)",
    borderRadius: 999,
    paddingInline: 16,
    paddingBlock: 3,
    fontSize: 14,
    whiteSpace: "nowrap",
  },
  themeGroup: {
    display: "inline-flex",
    alignItems: "center",
    gap: 0,
    padding: 4,
    borderWidth: 0,
    borderRadius: 999,
    backgroundColor: "var(--default)",
  },
  themeButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: 26,
    height: 26,
    minHeight: 26,
    minWidth: 26,
    padding: 6,
    backgroundColor: "transparent",
    color: "var(--muted)",
    borderRadius: 999,
    borderWidth: 0,
    cursor: "pointer",
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: 2 },
  },
  themeActive: { backgroundColor: "var(--surface)", color: "var(--foreground)" },
  menu: {
    backgroundColor: "var(--surface)",
    color: "var(--foreground)",
    borderRadius: 12,
    padding: 4,
    minWidth: 180,
    boxShadow: "var(--overlay-shadow)",
    zIndex: 60,
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: 8,
    borderRadius: 8,
    fontSize: 14,
    color: "inherit",
    textDecoration: "none",
    outline: "none",
    cursor: "pointer",
    backgroundColor: { default: "transparent", ":focus": "var(--default)" },
  },
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 50,
    backgroundColor: "color-mix(in oklch, var(--background) 70%, transparent)",
    backdropFilter: "blur(4px)",
  },
  searchPopup: {
    position: "fixed",
    left: "50%",
    top: "15vh",
    transform: {
      default: "translateX(-50%) scale(1)",
      ":is([data-starting-style],[data-ending-style])": "translateX(-50%) scale(.98)",
    },
    zIndex: 51,
    display: "flex",
    flexDirection: "column",
    width: "min(560px, calc(100vw - 32px))",
    maxWidth: 560,
    maxHeight: "70dvh",
    boxSizing: "border-box",
    borderRadius: 16,
    padding: 0,
    gap: 0,
    backgroundColor: "var(--surface)",
    color: "var(--foreground)",
    boxShadow: "var(--overlay-shadow)",
    outline: "none",
  },
  searchBar: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: 16,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--separator)",
  },
  searchInput: {
    width: "100%",
    minWidth: 0,
    borderWidth: 0,
    padding: 4,
    backgroundColor: "transparent",
    color: "var(--foreground)",
    font: "inherit",
    outline: "none",
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: 2, borderRadius: 4 },
  },
  searchResults: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    overflowY: "auto",
    padding: 12,
  },
  searchResult: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 8,
    fontSize: 14,
    color: "var(--foreground)",
    textDecoration: "none",
    ":hover": { backgroundColor: "var(--default)" },
    ":focus-visible": { backgroundColor: "var(--default)", outline: "2px solid var(--focus)" },
  },
  searchHelp: {
    margin: 0,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--separator)",
    padding: 12,
    color: "var(--muted)",
    fontSize: 12,
  },
  hidden: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
  drawer: {
    position: "fixed",
    insetBlock: 0,
    insetInlineEnd: 0,
    insetInlineStart: "auto",
    top: 0,
    transform: {
      default: "translateX(0)",
      ":is([data-starting-style],[data-ending-style])": "translateX(100%)",
      ":dir(rtl):is([data-starting-style],[data-ending-style])": "translateX(-100%)",
    },
    opacity: { default: 1, ":is([data-starting-style],[data-ending-style])": 1 },
    width: "85%",
    maxWidth: 380,
    maxHeight: "100dvh",
    height: "100dvh",
    boxSizing: "border-box",
    zIndex: 51,
    display: "flex",
    flexDirection: "column",
    padding: 16,
    gap: 16,
    borderRadius: 0,
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    boxShadow: "var(--overlay-shadow)",
    overflow: "hidden",
    outline: "none",
  },
  drawerHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8 },
  staticClose: { position: "static", top: "auto", insetInlineEnd: "auto" },
  drawerScroll: { minHeight: 0, overflowY: "auto", flexGrow: 1 },
  drawerSections: { display: "flex", flexDirection: "column", gap: 2, marginBottom: 16 },
  tocTitle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    color: "var(--muted)",
    margin: 0,
    fontWeight: 400,
    fontSize: 14,
  },
  tocLink: {
    display: "block",
    fontSize: 13,
    lineHeight: "20px",
    color: "var(--muted)",
    textDecoration: "none",
    paddingBlock: 6,
    paddingInlineStart: 12,
    paddingInlineEnd: 8,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: "transparent",
    ":hover": { color: "var(--foreground)" },
    ":focus-visible": { outline: "2px solid var(--focus)" },
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tocNested: { paddingInlineStart: 24 },
  tocActive: { borderInlineStartColor: "var(--foreground)", color: "var(--foreground)" },
  tocNavigation: { marginTop: 12, overflowY: "auto", maxHeight: "calc(100dvh - 180px)" },
  tocMobile: {
    display: { default: "none", "@media (max-width: 1279px)": "block" },
    gridColumn: { default: "2 / -1", "@media (max-width: 767px)": "1 / -1" },
    gridRow: 2,
    position: "sticky",
    top: { default: 100, "@media (max-width: 767px)": 92 },
    zIndex: 20,
    backgroundColor: "var(--background)",
    borderBottomWidth: 0,
  },
  tocTrigger: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 10,
    height: 40,
    boxSizing: "border-box",
    paddingInline: 24,
    borderWidth: 0,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--separator)",
    backgroundColor: "transparent",
    color: "var(--muted)",
    font: "inherit",
    fontSize: 14,
    textAlign: "start",
    cursor: "pointer",
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: -2 },
  },
  tocContent: { paddingInline: 24, paddingBottom: 12, maxHeight: "50dvh", overflowY: "auto" },
  headingRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  pageAction: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    font: "inherit",
    fontSize: 14,
    paddingInline: 16,
    paddingBlock: 8,
    borderWidth: 0,
    borderRadius: 999,
    backgroundColor: "var(--default)",
    color: "var(--foreground)",
    cursor: "pointer",
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: 2 },
  },
  pageActionGroup: {
    display: "inline-flex",
    alignItems: "center",
    borderRadius: 999,
    backgroundColor: "var(--default)",
  },
  pageActionMain: { paddingInlineEnd: 12, borderStartEndRadius: 0, borderEndEndRadius: 0 },
  pageActionMenu: {
    width: 36,
    height: 36,
    padding: 8,
    borderWidth: 0,
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: "var(--separator)",
    backgroundColor: "transparent",
    color: "var(--muted)",
    borderStartEndRadius: 999,
    borderEndEndRadius: 999,
    cursor: "pointer",
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: -2 },
  },
  sourceLinks: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 32,
  },
  sourceLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "20px",
    paddingInline: 12,
    paddingBlock: { default: 6, "@media (max-width: 767px)": 8 },
    borderRadius: 999,
    backgroundColor: "var(--default)",
    color: "var(--foreground)",
    textDecoration: "none",
    ":hover": { backgroundColor: "var(--surface-tertiary)" },
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: 2 },
  },
  pageFooter: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 16,
    marginTop: 32,
  },
  footerLink: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: 16,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--separator)",
    borderRadius: 12,
    fontSize: 14,
    color: "var(--foreground)",
    textDecoration: "none",
    ":hover": { backgroundColor: "var(--default)" },
    ":focus-visible": { outline: "2px solid var(--focus)" },
  },
  footerNext: { textAlign: "end", gridColumn: 2 },
  previewCode: {
    borderTopWidth: 1,
    borderInlineWidth: 1,
    borderBottomWidth: 1,
    borderTopStyle: "solid",
    borderInlineStyle: "solid",
    borderBottomStyle: "solid",
    borderTopColor: "var(--separator)",
    borderInlineColor: "var(--separator)",
    borderBottomColor: "var(--separator)",
    borderEndStartRadius: 12,
    borderEndEndRadius: 12,
  },
  codePane: { position: "relative" },
  codeCopy: {
    position: "absolute",
    top: 8,
    insetInlineEnd: 8,
    backgroundColor: "transparent",
    zIndex: 1,
  },
  codeLine: { display: "block", minHeight: "1.428571em", whiteSpace: "pre" },
  lineNumber: {
    display: "inline-block",
    width: 24,
    marginInlineStart: -16,
    marginInlineEnd: 8,
    color: "var(--muted)",
    opacity: 0.5,
    fontSize: 12,
    userSelect: "none",
    textAlign: "end",
  },
  previewPre: { margin: 0, borderRadius: 0, backgroundColor: "transparent", maxHeight: "75vh" },
  previewAttribution: {
    margin: 0,
    paddingBlock: 8,
    paddingInline: 16,
    fontSize: 11,
    color: "var(--muted)",
  },
});
