import * as stylex from "@stylexjs/stylex";

// Fumadocs UI 16.9.0 search dialog (MIT) + HeroUI e385ac2 final CSS
// (Apache-2.0), adapted to StyleX over native Fuma/Radix dialog parts.
// Original MIT notice: ../components/fumadocs/LICENSE.FUMADOCS.
const backdropIn = stylex.keyframes({
  from: { backdropFilter: "blur(0px) saturate(0%)", backgroundColor: "transparent", opacity: 0 },
  to: {
    backdropFilter: "blur(8px) saturate(180%)",
    backgroundColor: "var(--docs-search-backdrop)",
    opacity: 1,
  },
});
const backdropOut = stylex.keyframes({
  from: {
    backdropFilter: "blur(8px) saturate(180%)",
    backgroundColor: "var(--docs-search-backdrop)",
    opacity: 1,
  },
  to: { backdropFilter: "blur(0px) saturate(0%)", backgroundColor: "transparent", opacity: 0 },
});

export const search = stylex.create({
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: 50,
    "--docs-search-backdrop": {
      default: "rgba(255, 255, 255, 0.4)",
      ":is(.dark *)": "rgba(0, 0, 0, 0.4)",
    },
    backgroundColor: "var(--docs-search-backdrop)",
    backdropFilter: "blur(8px) saturate(180%)",
    animationName: { default: backdropIn, ":is([data-state=closed])": backdropOut },
    animationDuration: { default: "200ms", ":is([data-state=closed])": "150ms" },
    animationTimingFunction: "ease-out",
    animationFillMode: "both",
    "@media (prefers-reduced-motion: reduce)": { animationDuration: "0ms", animationName: "none" },
  },
  popup: {
    position: "fixed",
    left: "50%",
    top: { default: 16, "@media (min-width: 768px)": "max(16px, calc(50% - 250px))" },
    width: "calc(100% - 1rem)",
    maxWidth: 640,
    maxHeight: {
      default: "calc(100dvh - 32px)",
      "@media (min-width: 768px)": "calc(100dvh - max(16px, calc(50% - 250px)) - 16px)",
    },
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    zIndex: 50,
    padding: 0,
    gap: 0,
    borderWidth: 0,
    borderRadius: 12,
    overflow: "hidden",
    backgroundColor: "var(--surface)",
    color: "var(--foreground)",
    boxShadow: "0 25px 50px -12px rgb(0 0 0 / 0.5)",
    outline: "none",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: 12,
    flexShrink: 0,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "var(--separator)",
  },
  icon: { flexShrink: 0, color: "var(--muted)" },
  close: {
    position: "static",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 0,
    width: "auto",
    height: "auto",
    padding: 0,
    borderWidth: 0,
    borderRadius: "var(--radius-lg)",
    backgroundColor: "transparent",
    color: "var(--muted)",
    font: "inherit",
    cursor: "pointer",
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: 2 },
  },
  list: {
    display: "flex",
    flexDirection: "column",
    flex: "0 1 auto",
    minHeight: 0,
    overflow: "hidden",
    height: "var(--fd-animated-height)",
    transitionProperty: "height",
    transitionDuration: "150ms",
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
  viewport: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    flex: "1 1 0%",
    minHeight: 0,
    overflowY: "auto",
    maxHeight: 460,
    padding: 4,
    overscrollBehavior: "contain",
  },
  options: { display: "flex", flexDirection: "column", flexShrink: 0 },
  result: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexShrink: 0,
    paddingInline: 10,
    paddingBlock: 8,
    borderWidth: 0,
    borderRadius: 8,
    backgroundColor: {
      default: "transparent",
      ":is([aria-current=true])": "var(--default)",
    },
    color: "var(--foreground)",
    font: "inherit",
    fontSize: 14,
    lineHeight: "20px",
    textAlign: "start",
    cursor: "pointer",
    overflow: "hidden",
    ":focus-visible": { outline: "2px solid var(--focus)", outlineOffset: -2 },
  },
  empty: { paddingBlock: 48, textAlign: "center", color: "var(--muted)", fontSize: 14 },
});
