// Adapted from HeroUI v3.2.6 CodePanel (e385ac2), Apache-2.0.
// Modified: compiled StyleX, native Modal placement and compact export options.
import * as stylex from "@stylexjs/stylex";

export const themeBuilderCode = stylex.create({
  backdrop: {
    zIndex: 9999,
    backgroundColor: "rgb(0 0 0 / 40%)",
    backdropFilter: "blur(4px)",
  },
  panel: {
    position: "fixed",
    top: "50%",
    insetInlineEnd: { default: 24, "@media (max-width: 767px)": 16 },
    zIndex: 9999,
    display: "flex",
    flexDirection: "column",
    height: "88vh",
    width: { default: "45%", "@media (max-width: 767px)": "calc(100% - 32px)" },
    maxWidth: "none",
    maxHeight: "88vh",
    padding: 0,
    overflow: "hidden",
    borderRadius: 12,
    backgroundColor: "color-mix(in oklch, var(--surface) 94%, transparent)",
    color: "var(--foreground)",
    boxShadow: "0 20px 25px -5px rgb(0 0 0 / 10%), 0 8px 10px -6px rgb(0 0 0 / 10%)",
    backdropFilter: "blur(12px)",
    transform: {
      default: "translateY(-50%)",
      ":is([data-starting-style],[data-ending-style])": "translate(100%, -50%)",
    },
    transitionDuration: { default: "400ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: "cubic-bezier(0.16, 1, 0.3, 1)",
  },
  header: {
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "space-between",
    paddingInline: 24,
    paddingBlock: 12,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "color-mix(in oklch, var(--separator) 50%, transparent)",
  },
  title: {
    margin: 0,
    fontSize: 14,
    fontWeight: 500,
    color: "color-mix(in oklch, var(--foreground) 60%, transparent)",
  },
  actions: { display: "flex", alignItems: "center", gap: 4 },
  icon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 32,
    height: 32,
    minWidth: 32,
    paddingInline: 0,
    paddingBlock: 0,
    borderWidth: 0,
    borderRadius: 6,
    cursor: "pointer",
    color: {
      default: "color-mix(in oklch, var(--foreground) 40%, transparent)",
      ":hover": "color-mix(in oklch, var(--foreground) 60%, transparent)",
    },
    backgroundColor: {
      default: "transparent",
      ":hover": "color-mix(in oklch, var(--foreground) 5%, transparent)",
    },
    outline: { default: "none", ":focus-visible": "2px solid var(--focus)" },
    outlineOffset: 2,
    transitionProperty: "color, background-color",
    transitionDuration: { default: "150ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
  },
  scroll: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    overscrollBehavior: "contain",
    paddingInline: 16,
    paddingBlock: 8,
    outline: { default: "none", ":focus-visible": "2px solid var(--focus)" },
    outlineOffset: -2,
  },
  pre: {
    margin: 0,
    paddingBlock: 8,
    width: "max-content",
    minWidth: "100%",
    fontFamily: "var(--font-mono, ui-monospace, monospace)",
    fontSize: 13,
    lineHeight: 1.7,
    whiteSpace: "normal",
    userSelect: "text",
  },
  line: { display: "flex", minHeight: "1.7em" },
  lineNumber: {
    flexShrink: 0,
    width: "3ch",
    paddingInlineEnd: 16,
    textAlign: "end",
    color: "color-mix(in oklch, var(--foreground) 35%, transparent)",
    userSelect: "none",
  },
  lineSource: { whiteSpace: "pre" },
  token: (color: string) => ({ color }),
  options: {
    flexShrink: 0,
    maxHeight: "35%",
    overflow: "auto",
    paddingInline: 24,
    paddingBlock: 10,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "color-mix(in oklch, var(--separator) 50%, transparent)",
    fontSize: 12,
    color: "var(--muted)",
  },
  summary: {
    cursor: "pointer",
    outline: { default: "none", ":focus-visible": "2px solid var(--focus)" },
    outlineOffset: 2,
  },
  settings: { display: "flex", flexDirection: "column", gap: 10, paddingTop: 12 },
  label: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 8 },
  select: {
    fontSize: 12,
    paddingInline: 8,
    paddingBlock: 4,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    borderRadius: 6,
    backgroundColor: "var(--surface)",
    color: "var(--foreground)",
  },
  file: { fontSize: 12, maxWidth: "100%", minWidth: 0 },
  hint: { margin: 0, lineHeight: 1.5 },
  hidden: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
});
