import * as stylex from "@stylexjs/stylex";

export const mail = stylex.create({
  root: {
    width: "100%",
    height: "100%",
    minWidth: 0,
    minHeight: 0,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    fontFamily: "var(--font-sans)",
    fontSize: 13,
    textAlign: "start",
  },
  workspace: {
    display: "grid",
    gridTemplateColumns: {
      default: "240px 360px minmax(0, 1fr)",
      "@media (max-width: 1100px)": "64px 360px minmax(0, 1fr)",
      "@media (max-width: 767px)": "minmax(0, 1fr)",
    },
    gridTemplateRows: {
      default: "minmax(0, 1fr)",
      "@media (max-width: 767px)": "48px minmax(0, 1fr)",
    },
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
  },
  rail: {
    display: { default: "flex", "@media (max-width: 767px)": "none" },
    flexDirection: "column",
    minHeight: 0,
    borderInlineEnd: "1px solid var(--border)",
    paddingInline: 8,
  },
  profile: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    height: 64,
    flexShrink: 0,
    paddingInline: { default: 8, "@media (max-width: 1100px)": 0 },
    justifyContent: { default: "start", "@media (max-width: 1100px)": "center" },
    borderBottom: "1px solid var(--border)",
  },
  studio: { margin: 0, fontSize: 14, fontWeight: 600 },
  small: { margin: 0, fontSize: 11, lineHeight: 1.6 },
  muted: { color: "var(--muted)" },
  compactText: { display: { default: "block", "@media (max-width: 1100px)": "none" } },
  folders: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    paddingBlock: 12,
    borderBottom: "1px solid var(--border)",
  },
  folder: { height: 36, width: "100%", justifyContent: "start", gap: 10, minWidth: 0 },
  folderText: { flex: 1, textAlign: "start" },
  activeFolder: { backgroundColor: "var(--default)", color: "var(--default-foreground)" },
  count: {
    marginInlineStart: "auto",
    fontSize: 11,
    fontVariantNumeric: "tabular-nums",
    color: "var(--muted)",
  },
  railFooter: {
    marginBlockStart: "auto",
    paddingBlock: 12,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  compose: { height: 32 },
  mobileHeader: {
    display: { default: "none", "@media (max-width: 767px)": "flex" },
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    paddingInline: 8,
    borderBottom: "1px solid var(--border)",
  },
  navPopup: { width: 224, maxWidth: "calc(100vw - 24px)", padding: 12 },
  list: {
    display: "flex",
    flexDirection: "column",
    minWidth: 0,
    minHeight: 0,
    overflow: "hidden",
    borderInlineEnd: { default: "1px solid var(--border)", "@media (max-width: 767px)": "none" },
  },
  listHidden: { display: { default: "flex", "@media (max-width: 767px)": "none" } },
  listHeader: { padding: 8, flexShrink: 0 },
  messageList: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    minHeight: 0,
    padding: 8,
    flex: 1,
    overflowY: "auto",
    overflowX: "hidden",
    borderRadius: 0,
    backgroundColor: "transparent",
  },
  messageRow: {
    display: "flex",
    alignItems: "start",
    gap: 10,
    width: "100%",
    minWidth: 0,
    height: 76,
    minHeight: 76,
    flexShrink: 0,
    marginBlockStart: 0,
    padding: 10,
    borderRadius: "var(--radius-xl)",
    textAlign: "start",
    whiteSpace: "normal",
    outline: { default: "none", ":focus-visible": "2px solid var(--focus)" },
    outlineOffset: 2,
    backgroundColor: { default: "transparent", ":hover": "var(--default)" },
  },
  selectedRow: { backgroundColor: "var(--surface)", boxShadow: "var(--surface-shadow)" },
  messageCopy: { display: "flex", flexDirection: "column", gap: 3, flex: 1, minWidth: 0 },
  senderLine: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 8,
    minWidth: 0,
  },
  sender: {
    fontSize: 12,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  time: { fontSize: 10, color: "var(--muted)", whiteSpace: "nowrap", flexShrink: 0 },
  subject: {
    fontSize: 12,
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  excerpt: {
    fontSize: 12,
    fontWeight: 400,
    color: "var(--muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  threadFrame: { minWidth: 0, minHeight: 0, display: "flex", padding: 8, overflow: "hidden" },
  threadHidden: { display: { default: "flex", "@media (max-width: 767px)": "none" } },
  thread: {
    width: "100%",
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    overflowX: "hidden",
    overflowWrap: "anywhere",
    backgroundColor: "var(--surface)",
    color: "var(--surface-foreground)",
    borderRadius: "var(--radius-2xl)",
    boxShadow: "var(--surface-shadow)",
  },
  threadToolbar: {
    display: "flex",
    justifyContent: "end",
    flexWrap: "wrap",
    gap: 4,
    padding: 16,
    borderBottom: "1px solid var(--border)",
  },
  back: {
    marginInlineEnd: "auto",
    display: { default: "none", "@media (max-width: 767px)": "inline-flex" },
  },
  article: {
    padding: { default: 40, "@media (max-width: 1100px)": 24, "@media (max-width: 767px)": 16 },
  },
  threadSubject: { margin: "0 0 24px", fontSize: 16, lineHeight: 1.4, fontWeight: 600 },
  identity: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 10, fontSize: 12 },
  identityCopy: { display: "flex", flexDirection: "column", minWidth: 0, flex: 1 },
  avatar: { width: 36, height: 36, flexShrink: 0 },
  body: { marginBlock: 24, fontSize: 14, lineHeight: "22px", whiteSpace: "pre-line" },
  reply: { marginBlock: 20, paddingBlock: 16, borderTop: "1px solid var(--border)" },
  replyBody: { margin: "8px 0 0", whiteSpace: "pre-wrap", fontSize: 14, lineHeight: "22px" },
  empty: { padding: 24, margin: 0, color: "var(--muted)", lineHeight: 1.7 },
  status: {
    display: "block",
    padding: "6px 8px",
    flexShrink: 0,
    margin: 0,
    fontSize: 11,
    color: "var(--muted)",
    overflowWrap: "anywhere",
  },
  composeForm: { display: "flex", flexDirection: "column", gap: 16, minWidth: 0 },
  actions: { display: "flex", justifyContent: "end", flexWrap: "wrap", gap: 8 },
  popup: { minWidth: 0, maxWidth: "calc(100vw - 32px)" },
});
