import * as stylex from "@stylexjs/stylex";

export const chat = stylex.create({
  root: {
    display: "flex",
    height: "100%",
    minHeight: 0,
    width: "100%",
    minWidth: 0,
    overflow: "hidden",
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    fontFamily: "var(--font-sans)",
    fontSize: 14,
    lineHeight: "22px",
    textAlign: "start",
  },
  desktopRail: {
    display: { default: "none", "@media (min-width: 768px)": "flex" },
    width: 240,
    flexShrink: 0,
    minHeight: 0,
    borderInlineEnd: "1px solid var(--border)",
  },
  navigation: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    minHeight: 0,
    minWidth: 0,
  },
  identity: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    height: 64,
    flexShrink: 0,
    paddingInline: 20,
  },
  identityTitle: { margin: 0, fontSize: 14, fontWeight: 600, lineHeight: "20px" },
  small: { margin: 0, fontSize: 12, lineHeight: "18px" },
  muted: { color: "var(--muted)" },
  railContent: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    padding: 12,
    minHeight: 0,
    overflowY: "auto",
  },
  railAction: {
    width: "100%",
    height: 36,
    justifyContent: "start",
    flexShrink: 0,
    fontWeight: 400,
    paddingInline: 12,
  },
  recentTitle: {
    margin: 0,
    marginTop: 24,
    marginBottom: 8,
    paddingInline: 12,
    fontSize: 12,
    fontWeight: 500,
    color: "var(--muted)",
  },
  channelList: { display: "flex", flexDirection: "column", gap: 4, padding: 0, minWidth: 0 },
  channelRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    height: 36,
    minHeight: 36,
    paddingBlock: 0,
    paddingInline: 12,
    marginBlockStart: { default: 0, ":is([role='listbox'] > :not(:first-child))": 0 },
    fontSize: 13,
    borderRadius: 999,
  },
  rowTitle: { minWidth: 0, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  selectedChannel: { backgroundColor: "var(--default)", fontWeight: 500 },
  localNote: {
    margin: 0,
    marginTop: "auto",
    padding: 20,
    color: "var(--muted)",
    fontSize: 11,
    lineHeight: "18px",
  },
  conversation: { display: "flex", flexDirection: "column", flex: 1, minWidth: 0, minHeight: 0 },
  conversationHeader: {
    display: "flex",
    alignItems: "center",
    gap: { default: 4, "@media (min-width: 768px)": 12 },
    height: 64,
    flexShrink: 0,
    paddingInline: { default: 16, "@media (min-width: 768px)": 24 },
    borderBottom: "1px solid var(--border)",
  },
  headerTitle: { minWidth: 0, flex: 1 },
  channelTitle: {
    margin: 0,
    fontSize: 14,
    fontWeight: 600,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerSubtitle: {
    margin: 0,
    fontSize: 11,
    lineHeight: "16px",
    color: "var(--muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  headerAction: {
    height: 36,
    minWidth: 36,
    flexShrink: 0,
    fontSize: 12,
    paddingInline: { default: 0, "@media (min-width: 768px)": 12 },
    borderRadius: 999,
  },
  desktopActionText: { display: { default: "none", "@media (min-width: 768px)": "inline" } },
  menuButton: { width: 36, height: 36, minWidth: 36, padding: 0, flexShrink: 0 },
  searchPopup: {
    width: 280,
    maxWidth: "calc(100vw - 32px)",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  navigationPopup: {
    width: 280,
    maxWidth: "calc(100vw - 24px)",
    maxHeight: "min(600px, calc(100dvh - 100px))",
    overflowY: "auto",
    padding: 0,
  },
  backButton: { margin: 12, width: "calc(100% - 24px)" },
  messagePane: {
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflowY: "auto",
    overscrollBehavior: "contain",
    outline: { default: "none", ":focus-visible": "2px solid var(--focus)" },
    outlineOffset: -2,
  },
  thread: {
    width: "100%",
    maxWidth: 768,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 24,
    margin: 0,
    marginInline: "auto",
    paddingBlock: 32,
    paddingInline: { default: 16, "@media (min-width: 768px)": 24 },
    listStyleType: "none",
  },
  message: { display: "flex", alignItems: "start", minWidth: 0 },
  ownMessage: {
    justifyContent: "end",
    paddingInlineEnd: { default: 0, "@media (min-width: 768px)": 16 },
  },
  answer: {
    width: "100%",
    minWidth: 0,
    paddingInlineStart: { default: 0, "@media (min-width: 768px)": 60 },
    paddingInlineEnd: { default: 0, "@media (min-width: 768px)": 48 },
    boxSizing: "border-box",
  },
  sampleLabel: {
    margin: 0,
    marginBottom: 8,
    fontSize: 10,
    lineHeight: "16px",
    color: "var(--muted)",
    letterSpacing: "0.04em",
  },
  messageText: {
    margin: 0,
    fontSize: 14,
    lineHeight: "22px",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  },
  ownBubble: {
    maxWidth: "85%",
    backgroundColor: "var(--default)",
    color: "var(--default-foreground)",
    borderRadius: "var(--radius-xl)",
    paddingBlock: 10,
    paddingInline: 14,
  },
  document: {
    marginTop: 16,
    width: "100%",
    maxWidth: 340,
    padding: 16,
    gap: 12,
    boxShadow: "none",
    backgroundColor: "var(--default)",
    borderRadius: "var(--radius-xl)",
  },
  documentList: { margin: 0, paddingInlineStart: 20, fontSize: 13, lineHeight: "22px" },
  copyButton: { marginTop: 8, paddingInline: 6, height: 28, fontSize: 11, color: "var(--muted)" },
  emptyState: { margin: 0, padding: 24, textAlign: "center", color: "var(--muted)", fontSize: 14 },
  composerDock: {
    paddingInline: { default: 16, "@media (min-width: 768px)": 24 },
    paddingBottom: 16,
    paddingTop: 8,
    flexShrink: 0,
  },
  composer: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    minWidth: 0,
    maxWidth: 720,
    boxSizing: "border-box",
    marginInline: "auto",
    padding: 12,
    height: 112,
    backgroundColor: "var(--surface)",
    borderRadius: "var(--radius-2xl)",
    boxShadow: "var(--surface-shadow)",
  },
  textarea: {
    minWidth: 0,
    minHeight: 44,
    height: 44,
    resize: "none",
    fontSize: 14,
    lineHeight: "22px",
    paddingInline: 0,
    paddingBlock: 0,
    borderWidth: 0,
    boxShadow: { default: "none", ":focus": "0 0 0 2px var(--focus)" },
    backgroundColor: "transparent",
    borderRadius: 0,
  },
  composerFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    minWidth: 0,
  },
  roundButton: {
    width: 36,
    minWidth: 36,
    height: 36,
    paddingInline: 0,
    paddingBlock: 0,
    borderRadius: 999,
  },
  hiddenFile: { display: "none" },
  composerNote: {
    margin: 0,
    marginTop: 8,
    fontSize: 11,
    lineHeight: "16px",
    textAlign: "center",
    color: "var(--muted)",
  },
  importError: {
    margin: 0,
    marginTop: 8,
    fontSize: 12,
    textAlign: "center",
    color: "var(--danger)",
  },
  visuallyHidden: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
});
