/**
 * HeroUI v3.2.6 docs color-picker/** and accent-color-selector.tsx.
 * Copyright NextUI Inc. SPDX-License-Identifier: Apache-2.0.
 * Modified for StyleX and native Lenso/RAC state attributes.
 */
import * as stylex from "@stylexjs/stylex";

const shadow = "0 10px 15px -3px rgb(0 0 0 / .1), 0 4px 6px -4px rgb(0 0 0 / .1)";
const focus = "0 0 0 2px var(--background), 0 0 0 4px var(--focus)";

export const picker = stylex.create({
  trigger: {
    position: "relative",
    display: "flex",
    width: 24,
    height: 24,
    minWidth: 0,
    minHeight: 0,
    flexShrink: 0,
    padding: 0,
    border: 0,
    borderRadius: "50%",
    overflow: "visible",
    backgroundColor: "transparent",
    boxShadow: { default: "none", ":focus-visible": focus },
  },
  rainbow: {
    width: "100%",
    height: "100%",
    borderRadius: "50%",
    zIndex: 0,
    backgroundImage:
      "conic-gradient(from 0deg, #F8AECF, #FBC7A3, #F7E8A4, #D7F5B0, #B5F3D2, #A3EAF7, #A8C9FF, #C9B8FF, #F8AECF)",
  },
  triggerRing: {
    position: "absolute",
    inset: 0,
    zIndex: 10,
    borderRadius: "50%",
    border: "2px solid rgb(255 255 255 / .5)",
    boxSizing: "border-box",
    pointerEvents: "none",
  },
  popup: {
    width: 248,
    borderRadius: 20,
    padding: 0,
    boxSizing: "border-box",
  },
  content: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    paddingInline: 8,
    paddingTop: 16,
    paddingBottom: 8,
  },
  carousel: { display: "flex", alignItems: "center", gap: 8 },
  pageButton: {
    width: 20,
    height: 20,
    minWidth: 20,
    minHeight: 0,
    flexShrink: 0,
    borderRadius: "50%",
    padding: 0,
  },
  // Preserve the source carousel footprint while keeping its 4px focus ring
  // inside the clipping window (the source's 22px row only supplies 3px).
  viewport: {
    position: "relative",
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    padding: 1,
    margin: -1,
  },
  pages: (page: number) => ({
    display: "flex",
    transform: `translateX(-${page * 100}%)`,
    transitionProperty: "transform",
    transitionDuration: { default: "300ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: "cubic-bezier(0, 0, .2, 1)",
  }),
  page: { display: "flex", height: 22, width: "100%", flexShrink: 0, justifyContent: "center" },
  swatches: { display: "flex", alignItems: "center", justifyContent: "flex-start", gap: 6 },
  swatch: {
    width: 16,
    height: 16,
    borderRadius: "50%",
    outline: "none",
    boxSizing: "border-box",
    transitionProperty: "box-shadow",
    transitionDuration: { default: "150ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
  },
  selectedSwatch: { boxShadow: "0 0 0 1px var(--background), 0 0 0 2px var(--foreground)" },
  focusedSwatch: { boxShadow: focus },
  swatchColor: { width: "100%", height: "100%", borderRadius: "50%", cursor: "pointer" },
  area: {
    width: 232,
    height: 232,
    maxWidth: "none",
    flexShrink: 0,
    borderRadius: 16,
    border: "1px solid var(--border)",
    boxSizing: "border-box",
    boxShadow: "none",
    backgroundColor: { default: null, "@media (forced-colors: active)": "GrayText" },
  },
  areaThumb: {
    width: 24,
    height: 24,
    borderRadius: "50%",
    borderWidth: 2,
    transitionProperty: "none",
    boxShadow: { default: shadow, ':is([data-focus-visible="true"])': `${focus}, ${shadow}` },
    backgroundColor: { default: null, "@media (forced-colors: active)": "Canvas" },
  },
  hueRow: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  slider: {
    display: "flex",
    flexDirection: "column",
    width: "100%",
    height: 20,
    maxWidth: 184,
    minWidth: 0,
    flex: 1,
    gap: 4,
  },
  track: {
    width: "100%",
    height: 32,
    flexShrink: 1,
    borderRadius: 999,
    boxShadow: "none",
    "::before": { display: "none" },
    "::after": { display: "none" },
    backgroundColor: { default: null, "@media (forced-colors: active)": "GrayText" },
  },
  sliderThumb: {
    width: 16,
    height: 16,
    borderRadius: "50%",
    borderWidth: 1.5,
    boxShadow: { default: shadow, ':is([data-focus-visible="true"])': `${focus}, ${shadow}` },
  },
  shuffle: { width: 32, height: 32, minWidth: 32, flexShrink: 0, padding: 0, borderRadius: "50%" },
  field: { borderRadius: 12 },
  input: { width: "100%", flex: 1, paddingInline: 16, fontSize: 14 },
  suffix: {
    borderInlineStart: "1px solid var(--separator)",
    paddingInline: 0,
    alignSelf: "stretch",
  },
  formatTrigger: {
    height: "100%",
    minWidth: 88,
    borderRadius: 0,
    border: 0,
    backgroundColor: { default: "transparent", ":hover": "transparent" },
    paddingInline: 12,
    boxShadow: "none",
  },
});
