import * as stylex from "@stylexjs/stylex";

export const dashboard = stylex.create({
  root: {
    containerType: "inline-size",
    containerName: "dashboard",
    display: "flex",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    width: "100%",
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    fontFamily: "var(--font-sans)",
    fontSize: 13,
    lineHeight: 1.5,
  },
  shell: { display: "flex", width: "100%", minWidth: 0, minHeight: 0 },
  sidebar: {
    display: { default: "flex", "@container dashboard (width < 768px)": "none" },
    flexDirection: "column",
    flexShrink: 0,
    boxSizing: "border-box",
    width: { default: 240, "@container dashboard (width < 1200px)": 64 },
    minHeight: 0,
    backgroundColor: "var(--background)",
    borderInlineEnd: "1px solid var(--separator)",
    paddingInline: 12,
  },
  mobileNav: { display: { default: "none", "@container dashboard (width < 768px)": "block" } },
  identity: { height: 64, display: "flex", alignItems: "center", gap: 10, flexShrink: 0 },
  railLabel: {
    display: { default: "block", "@container dashboard (768px <= width < 1200px)": "none" },
    minWidth: 0,
  },
  identityName: { display: "block", fontWeight: 600, fontSize: 14 },
  muted: { color: "var(--muted)", fontSize: 12 },
  nav: { display: "flex", flexDirection: "column", gap: 4, paddingBlockStart: 20 },
  navButton: {
    justifyContent: "start",
    width: "100%",
    gap: 12,
    minHeight: 40,
    paddingInline: 10,
    fontSize: 14,
  },
  selected: { backgroundColor: "var(--default)", color: "var(--default-foreground)" },
  sidebarFooter: {
    marginBlockStart: "auto",
    paddingBlock: 16,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  main: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    paddingInline: 20,
    paddingBlockEnd: 20,
  },
  header: {
    minHeight: 64,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  greeting: {
    margin: 0,
    fontSize: 20,
    fontWeight: 600,
    lineHeight: 1.3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    minWidth: 0,
  },
  headerTitle: { display: "flex", alignItems: "center", gap: 8, minWidth: 0, flex: 1 },
  actions: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap", minWidth: 0 },
  compact: { height: 32, minHeight: 32, fontSize: 12, paddingInline: 12, borderRadius: 999 },
  iconButton: { width: 32, height: 32, minHeight: 32, flexShrink: 0 },
  toolbar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 40,
    gap: 8,
    flexWrap: "wrap",
    marginBlockEnd: 16,
    marginBlockStart: 16,
  },
  segmented: {
    display: "flex",
    gap: 2,
    padding: 3,
    borderWidth: 0,
    margin: 0,
    minWidth: 0,
    borderRadius: 999,
    backgroundColor: "var(--default)",
  },
  segmentSelected: {
    backgroundColor: "var(--surface)",
    boxShadow: "var(--surface-shadow)",
    color: "var(--surface-foreground)",
  },
  reportPanel: { padding: 0, marginTop: 0, minWidth: 0 },
  inactiveReport: { display: "none" },
  select: {
    minHeight: 32,
    height: 32,
    fontSize: 12,
    borderRadius: 999,
    paddingInline: 10,
    maxWidth: "100%",
  },
  metrics: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      "@container dashboard (480px < width < 1000px)": "repeat(2, minmax(0, 1fr))",
      "@container dashboard (width <= 480px)": "minmax(0, 1fr)",
    },
    gap: 12,
    margin: 0,
    marginBlockEnd: 16,
  },
  card: {
    backgroundColor: "var(--surface)",
    color: "var(--surface-foreground)",
    boxShadow: "var(--surface-shadow)",
    borderRadius: "var(--radius-2xl)",
    minWidth: 0,
  },
  metric: {
    height: 100,
    padding: 16,
    boxSizing: "border-box",
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    gridTemplateRows: "20px 1fr",
    columnGap: 8,
    alignItems: "end",
  },
  metricLabel: { color: "var(--muted)", fontSize: 14, gridColumn: "1 / -1", alignSelf: "start" },
  metricValue: {
    margin: 0,
    fontSize: 26,
    fontWeight: 600,
    lineHeight: 1.3,
    fontVariantNumeric: "tabular-nums",
    gridColumn: 1,
    gridRow: 2,
  },
  change: {
    margin: 0,
    fontSize: 11,
    display: "flex",
    alignItems: "center",
    gap: 4,
    color: "var(--success-soft-foreground)",
    backgroundColor: "var(--success-soft)",
    borderRadius: 999,
    paddingInline: 6,
    paddingBlock: 2,
    alignSelf: "center",
    gridColumn: 2,
    gridRow: 2,
  },
  expenseChange: { color: "var(--danger-soft-foreground)", backgroundColor: "var(--danger-soft)" },
  charts: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(2, minmax(0, 1fr))",
      "@container dashboard (width < 1000px)": "minmax(0, 1fr)",
    },
    gap: 12,
    marginBlockEnd: 16,
  },
  figure: {
    margin: 0,
    height: { default: 316, "@container dashboard (width <= 480px)": 360 },
    padding: 20,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  sectionTitle: { fontSize: 16, fontWeight: 600, margin: 0 },
  summaryGrid: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(3, minmax(0, 1fr))",
      "@container dashboard (width <= 480px)": "repeat(2, minmax(0, 1fr))",
    },
    gap: 8,
  },
  summaryValue: { fontSize: 18, fontWeight: 600, fontVariantNumeric: "tabular-nums" },
  plot: {
    width: "100%",
    height: 168,
    minHeight: 0,
    flex: 1,
    overflow: "visible",
    direction: "ltr",
  },
  gridLine: { stroke: "var(--separator)", strokeWidth: 1, strokeDasharray: "3 4" },
  tick: { fill: "var(--muted)", fontSize: 11, fontFamily: "var(--font-sans)" },
  bar: { fill: "var(--accent)" },
  line: {
    fill: "none",
    stroke: "var(--accent)",
    strokeWidth: 3,
    strokeLinecap: "round",
    strokeLinejoin: "round",
  },
  softLine: { stroke: "color-mix(in oklch, var(--accent) 40%, var(--surface))" },
  legend: { display: "flex", gap: 16, fontSize: 11, color: "var(--muted)" },
  legendItem: { display: "flex", alignItems: "center", gap: 5 },
  dot: { width: 7, height: 7, borderRadius: 999, backgroundColor: "var(--accent)" },
  softDot: { backgroundColor: "color-mix(in oklch, var(--accent) 40%, var(--surface))" },
  teamHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
    marginBlockEnd: 12,
    marginBlockStart: 12,
  },
  teamTitle: { margin: 0, fontSize: 16, fontWeight: 600 },
  search: {
    width: 220,
    maxWidth: "100%",
    minWidth: 0,
    height: 32,
    minHeight: 32,
    fontSize: 12,
    borderRadius: 999,
  },
  tableViewport: { overflowX: "auto", minWidth: 0 },
  tableRoot: { minWidth: 0, width: "100%" },
  table: {
    width: "100%",
    fontSize: 13,
    whiteSpace: "nowrap",
    padding: 0,
  },
  th: { height: 36, textAlign: "start" },
  tr: { height: 56 },
  td: { height: 56, paddingInline: 16 },
  member: { display: "flex", alignItems: "center", gap: 10 },
  memberCopy: { display: "flex", flexDirection: "column" },
  worker: {
    color: "var(--foreground)",
    fontSize: 13,
  },
  empty: { padding: 20, textAlign: "center", color: "var(--muted)" },
  disclosure: { margin: 0, fontSize: 11, color: "var(--muted)", overflowWrap: "anywhere" },
  popover: { padding: 16, maxWidth: "min(320px, calc(100vw - 32px))" },
  fields: { display: "flex", flexDirection: "column", gap: 12 },
  field: { display: "flex", flexDirection: "column", gap: 5, fontSize: 13 },
  checkbox: { paddingBlock: 6 },
  status: { display: "block", marginBlockStart: 12, fontSize: 12, color: "var(--muted)" },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
});
