// HeroUI v3.2.6, e385ac202b2cdb94b1bf6fa76d32c31c8259cc5e, Apache-2.0.
// Copyright 2025 NextUI Inc.
// Adapted from apps/docs/src/components/demo: utility geometry becomes StyleX.
import * as stylex from "@stylexjs/stylex";

export const preview = stylex.create({
  grid: {
    display: "grid",
    width: "fit-content",
    maxWidth: "100%",
    marginInline: "auto",
    marginBlock: "auto",
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 768px)": "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 1024px)": "auto auto auto",
    },
    gap: 32,
    color: "var(--foreground)",
    fontFamily: "var(--font-sans)",
  },
  column: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    maxWidth: 360,
    minWidth: 0,
    gap: 40,
  },
  left: { order: { default: 2, "@media (min-width: 768px)": 1 } },
  center: { order: { default: 1, "@media (min-width: 768px)": 2 } },
  right: {
    order: 3,
    display: "grid",
    gridColumn: {
      default: "span 1",
      "@media (min-width: 768px)": "span 2",
      "@media (min-width: 1024px)": "span 1",
    },
    gridTemplateColumns: {
      default: "minmax(0, 1fr)",
      "@media (min-width: 768px)": "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 1024px)": "minmax(0, 1fr)",
    },
    gridTemplateRows: {
      default: "repeat(2, minmax(0, 1fr))",
      "@media (min-width: 768px)": "auto auto",
    },
    maxWidth: { default: null, "@media (min-width: 1024px)": 360 },
    minWidth: 0,
    justifyItems: "center",
    alignSelf: "start",
    gap: 20,
  },
  signupPlacement: { gridRow: "span 2" },
  width256: { width: 256, maxWidth: "100%" },
  full: { width: "100%" },
  start: { alignItems: "start" },
  description: { marginTop: 2 },
  field: { display: "flex", flexDirection: "column", alignItems: "start", gap: 4 },
  controls: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    gap: 32,
  },
  radios: { flexDirection: "row", gap: 32 },
  slider: { paddingInline: 4 },
  tab: { gap: 6 },
  centerRow: { display: "flex", width: "100%", justifyContent: "center" },
  otp: {
    display: "flex",
    width: 280,
    maxWidth: "100%",
    flexDirection: "column",
    alignItems: "start",
    justifyContent: "center",
    gap: 8,
  },
  otpHeading: { display: "flex", flexDirection: "column", alignItems: "start", gap: 4 },
  resend: { display: "flex", alignItems: "center", gap: 5, paddingInline: 4, paddingTop: 4 },
  resendLink: { color: "var(--foreground)" },
  buttons: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", columnGap: 12, rowGap: 8 },
  actionSurface: {
    width: 256,
    maxWidth: "100%",
    borderRadius: "min(32px, var(--radius-3xl))",
    boxShadow: "var(--shadow-surface)",
  },
  actionList: { width: "100%", padding: 8 },
  actionIcon: {
    display: "flex",
    height: 32,
    alignItems: "start",
    justifyContent: "center",
    paddingTop: 1,
  },
  mutedIcon: { width: 16, height: 16, flexShrink: 0, color: "var(--muted)" },
  dangerIcon: { width: 16, height: 16, flexShrink: 0, color: "var(--danger)" },
  actionCopy: { display: "flex", flexDirection: "column" },
  shortcut: { marginInlineStart: "auto" },
  profile: {
    width: { default: "100%", "@media (min-width: 1280px)": 400 },
    alignItems: "start",
    justifyContent: "center",
  },
  profileHeader: { width: "100%", flexDirection: "row", justifyContent: "space-between" },
  profileIdentity: { display: "flex", alignItems: "center", gap: 12 },
  profileName: { display: "flex", alignItems: "center", gap: 2 },
  badgeStroke: { mixBlendMode: "overlay" },
  profileHandle: { letterSpacing: "-0.025em" },
  profileContent: { flexDirection: "row", textAlign: "start" },
  bio: { paddingInlineStart: 1 },
  footer: { gap: 8 },
  stat: { display: "flex", gap: 4 },
  alert: {
    width: { default: "100%", "@media (min-width: 1280px)": 400 },
    alignItems: "center",
  },
  textStart: { textAlign: "start" },
  alertTitle: { lineHeight: "20px" },
  notifications: { display: "flex", gap: 32, padding: 16, textAlign: "start" },
  notificationCopy: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "start",
    gap: 4,
    marginTop: -2,
  },
  signup: {
    width: 320,
    maxWidth: "100%",
    alignItems: "start",
    justifyContent: "center",
    padding: 20,
  },
  signupHeader: { width: "100%", alignItems: "center", justifyContent: "center", gap: 8 },
  close: { position: "absolute", insetInlineEnd: 12, top: 12 },
  signupContent: { width: "100%", gap: 8 },
  trial: { textAlign: "center", textWrap: "balance" },
  divider: { display: "flex", width: "100%", alignItems: "center", gap: 8, paddingBlock: 8 },
  separator: { flex: 1 },
  or: { textAlign: "center", textTransform: "uppercase" },
  groups: {
    display: "flex",
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    gap: 16,
  },
  group: { width: "100%", flex: 1 },
  groupAvatar: { width: 56, height: 56, borderRadius: 12 },
  groupFooterAvatar: { width: 16, height: 16 },
  unsaved: {
    height: 208,
    width: { default: "100%", "@media (min-width: 1200px)": 340 },
    alignItems: "start",
    justifyContent: "center",
    padding: 20,
  },
  unsavedHeader: {
    width: "100%",
    alignItems: "start",
    justifyContent: "center",
    gap: 8,
    paddingInline: 4,
  },
  unsavedFooter: { width: "100%", alignItems: "center", gap: 8, paddingInline: 2, paddingTop: 12 },
  text: { margin: 0, fontSize: 14, lineHeight: "20px" },
  small: { fontSize: 12, lineHeight: "16px" },
  medium: { fontWeight: 500 },
  semibold: { fontWeight: 600 },
  name: { lineHeight: "16px" },
  muted: { color: "var(--muted)" },
});
