import * as stylex from "@stylexjs/stylex";

// HeroUI v3.2.6 themes page and controls, Apache-2.0.
// Modified: compiled StyleX and native Base UI / React Aria contracts.
export const builder = stylex.create({
  scope: { height: "100dvh", minHeight: "100dvh", fontFamily: "var(--font-sans)" },
  page: {
    position: "relative",
    display: "grid",
    gridTemplateRows: {
      default: "72px minmax(0, 1fr) auto",
      "@media (max-width: 1199px)": "68px minmax(0, 1fr) auto",
    },
    height: "100dvh",
    minHeight: "100dvh",
    boxSizing: "border-box",
    paddingInline: { default: 24, "@media (max-width: 639px)": 16 },
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    fontFamily: "var(--font-sans)",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    maxWidth: 1400,
    height: 56,
    position: "sticky",
    top: 0,
    zIndex: 50,
    backgroundColor: "var(--background)",
    marginInline: "auto",
    gap: 12,
  },
  row: { display: "flex", alignItems: "center", gap: 12 },
  headerActions: {
    width: { default: 244, "@media (max-width: 1199px)": "auto" },
    justifyContent: "flex-end",
  },
  brand: {
    fontSize: 26,
    fontWeight: 700,
    letterSpacing: "-0.04em",
    color: "inherit",
    textDecoration: "none",
    whiteSpace: "nowrap",
  },
  desktop: { display: { default: "flex", "@media (max-width: 1199px)": "none" } },
  notPhone: { display: { default: "flex", "@media (max-width: 639px)": "none" } },
  icon: {
    width: 36,
    height: 36,
    minWidth: 36,
    paddingInline: 0,
    paddingBlock: 0,
    borderRadius: 999,
  },
  divider: { width: 1, height: 24, backgroundColor: "var(--separator)" },
  mode: {
    display: "flex",
    gap: 0,
    backgroundColor: "var(--default)",
    borderRadius: 999,
    padding: 2,
  },
  modeButton: {
    width: 26,
    height: 28,
    minWidth: 26,
    paddingInline: 0,
    paddingBlock: 0,
    borderRadius: 999,
  },
  selectedMode: { backgroundColor: "var(--surface)", boxShadow: "var(--surface-shadow)" },
  tabs: { padding: 4, gap: 0, borderRadius: 999 },
  tab: { paddingInline: 16, borderRadius: 999, height: 32, fontSize: 14 },
  content: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    minWidth: 0,
    maxWidth: 1400,
    width: "100%",
    marginInline: "auto",
  },
  previewNavigation: {
    position: { default: "absolute", "@media (max-width: 1199px)": "relative" },
    top: { default: 8, "@media (max-width: 1199px)": "auto" },
    left: { default: "50%", "@media (max-width: 1199px)": "auto" },
    transform: { default: "translateX(-50%)", "@media (max-width: 1199px)": "none" },
    zIndex: 51,
    overflowX: "auto",
    paddingBlock: 4,
    flexShrink: 0,
  },
  application: { height: "100%", flex: "1 1 0", minWidth: 0, minHeight: 0, display: "flex" },
  templatePanel: {
    marginTop: 0,
    padding: 0,
    minWidth: 0,
    minHeight: 0,
    height: "100%",
    display: "flex",
    flexDirection: "column",
    flexShrink: 0,
  },
  inactivePreview: { display: "none" },
  frame: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    borderRadius: "var(--radius-2xl)",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "color-mix(in oklch, var(--border) 50%, transparent)",
    overflow: "auto",
    scrollbarWidth: "none",
  },
  preview: {
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    flexShrink: 0,
    minHeight: "100%",
    paddingInline: 16,
    paddingBlock: 32,
    boxSizing: "border-box",
    position: "relative",
  },
  footer: {
    display: { default: "flex", "@media (max-width: 639px)": "none" },
    flexDirection: { default: "row", "@media (max-width: 1200px)": "column" },
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    paddingBlock: 24,
    marginInline: "auto",
    maxWidth: 1100,
  },
  footerGroup: { display: "flex", alignItems: "center", gap: 16 },
  control: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    width: 160,
    minWidth: 0,
    flexShrink: 0,
  },
  accentControl: { width: { default: 192, "@media (max-width: 1279px)": 160 } },
  baseControl: { width: { default: 160, "@media (max-width: 1279px)": 128 } },
  colorRow: { gap: 8 },
  label: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 14,
    fontWeight: 500,
    minHeight: 24,
    "--builder-lock-opacity": { default: 0, ":hover": 1, ":focus-within": 1 },
  },
  lock: {
    display: "inline-flex",
    justifyContent: "center",
    alignItems: "center",
    paddingInline: 0,
    paddingBlock: 0,
    width: 16,
    minWidth: 16,
    height: 20,
    opacity: "var(--builder-lock-opacity)",
  },
  locked: { opacity: 1 },
  controlButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: 160,
    height: 36,
    paddingInline: 12,
    borderRadius: "var(--field-radius)",
    backgroundColor: "var(--field-background)",
    color: "var(--field-foreground)",
    boxShadow: "var(--field-shadow)",
    fontWeight: 400,
    fontSize: 14,
  },
  muted: { color: "var(--muted)" },
  choiceTrigger: {
    display: "grid",
    gridTemplateColumns: "40px minmax(0, 1fr) 40px",
    paddingInline: 0,
    paddingBlock: 0,
    fontFamily: "var(--font-sans)",
    lineHeight: "20px",
  },
  choicePrefix: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
    minWidth: 0,
  },
  choiceSuffix: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "stretch",
    color: "var(--muted)",
  },
  choiceValue: {
    textAlign: "start",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  gradientRoot: { width: { default: 160, "@media (max-width: 1279px)": 128 }, gap: 0, minWidth: 0 },
  gradientControl: { height: 24 },
  gradientTrack: (background: string) => ({
    width: "100%",
    height: 24,
    borderRadius: 999,
    backgroundImage: background,
    backgroundColor: "transparent",
    "::before": { display: "none" },
    "::after": { display: "none" },
  }),
  sliderThumb: {
    width: 16,
    height: 16,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "white",
    backgroundColor: "transparent",
    boxShadow: "0 0 0 1px rgb(0 0 0 / 10%)",
  },
  popover: {
    width: 300,
    padding: 12,
    borderRadius: "var(--radius-3xl)",
    maxHeight: "min(500px, calc(100dvh - 64px))",
    overflowY: "auto",
  },
  presetPopover: { width: 228, boxSizing: "border-box", padding: 16 },
  radiusPopover: { width: 304, boxSizing: "border-box" },
  optionHeading: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    paddingInlineStart: 8,
    marginBottom: 8,
  },
  stack: { display: "flex", flexDirection: "column", gap: 12, minWidth: 0 },
  title: { fontSize: 12, fontWeight: 500, margin: 0 },
  fontHeading: { fontSize: 14, fontWeight: 500, margin: 0 },
  hint: { fontSize: 12, color: "var(--muted)", margin: 0 },
  options: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 8,
    paddingInline: 0,
  },
  option: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    width: "100%",
    height: 83,
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--separator)",
    backgroundColor: "transparent",
    color: "var(--foreground)",
    padding: 8,
  },
  selectedOption: { borderColor: "var(--foreground)" },
  optionSymbol: { fontSize: 20, lineHeight: "28px", fontWeight: 600 },
  optionCaption: {
    fontSize: 12,
    lineHeight: "16px",
    textTransform: "capitalize",
    color: "var(--muted)",
  },
  fontGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 8,
    padding: 0,
    maxHeight: 224,
    overflowY: "auto",
  },
  fontCard: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: 5,
    height: 83,
    padding: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--separator)",
  },
  fontName: {
    fontSize: 10,
    maxWidth: 80,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--muted)",
  },
  presets: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: 12,
    padding: 0,
    overflow: "visible",
  },
  preset: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    gap: 6,
    minWidth: 0,
    padding: 0,
    paddingBlock: 0,
    paddingInlineStart: 0,
    paddingInlineEnd: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
  },
  selectedPreset: {
    "--preset-ring": "0 0 0 2px var(--surface), 0 0 0 4px var(--accent)",
    "--preset-label-color": "var(--foreground)",
  },
  presetImage: {
    display: "block",
    width: 36,
    height: 36,
    borderRadius: 999,
    boxShadow: "var(--preset-ring, none)",
  },
  presetName: { fontSize: 10, fontWeight: 500, color: "var(--preset-label-color, var(--muted))" },
  themeDetails: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--separator)",
  },
  themeDescription: { display: "flex", flexDirection: "column", gap: 2, minWidth: 0 },
  themeLabel: { fontSize: 12, lineHeight: "16px", fontWeight: 500 },
  themeHint: { fontSize: 10, lineHeight: "15px", color: "var(--muted)" },
  randomHint: {
    marginTop: 16,
    marginBottom: 0,
    fontSize: 12,
    lineHeight: "16px",
    color: "var(--muted)",
  },
  mobilePresets: {
    display: "flex",
    gap: 16,
    overflowX: "auto",
    paddingInline: 16,
    paddingBlock: 4,
    scrollbarWidth: "none",
    flexShrink: 0,
  },
  mobilePreset: { width: 52, minWidth: 52, flexShrink: 0 },
  mobileThemeInput: {
    flex: 1,
    justifyContent: "space-between",
    height: 36,
    paddingInline: 12,
    borderRadius: 12,
    backgroundColor: "var(--field-background)",
    boxShadow: "var(--field-shadow)",
    fontWeight: 400,
  },
  status: {
    position: "fixed",
    bottom: 4,
    insetInlineStart: 16,
    maxWidth: "calc(100vw - 32px)",
    fontSize: 12,
    zIndex: 100,
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    borderRadius: 4,
  },
  hidden: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
  },
  mobileFooter: {
    display: { default: "none", "@media (max-width: 639px)": "flex" },
    position: "fixed",
    bottom: 0,
    insetInline: 0,
    height: 65,
    paddingInline: 24,
    backgroundColor: "var(--background)",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "var(--separator)",
    zIndex: 30,
  },
  phoneSpace: { display: { default: "none", "@media (max-width: 639px)": "block" }, height: 80 },
  sheet: {
    backgroundColor: "var(--background)",
    position: "fixed",
    insetInlineStart: 0,
    insetInlineEnd: 0,
    bottom: 0,
    top: "auto",
    width: "100vw",
    maxWidth: "none",
    height: 320,
    transform: "none",
    margin: 0,
    display: "flex",
    flexDirection: "column",
    gap: 16,
    paddingInline: 0,
    paddingTop: 16,
    paddingBottom: 20,
    borderStartStartRadius: 24,
    borderStartEndRadius: 24,
    borderEndStartRadius: 0,
    borderEndEndRadius: 0,
    maxHeight: "85dvh",
    overflowY: "auto",
  },
  sheetBackdrop: { backgroundColor: "rgba(0, 0, 0, 0.2133)" },
  sheetHandle: {
    width: 36,
    height: 6,
    flexShrink: 0,
    borderRadius: 4,
    marginInline: "auto",
    backgroundColor: "var(--separator)",
  },
  mobileColorRow: {
    display: "flex",
    gap: 16,
    paddingInlineStart: 16,
    overflowX: "auto",
    flexShrink: 0,
    scrollbarWidth: "none",
  },
  mobileControlRow: {
    display: "flex",
    gap: 16,
    paddingInline: 16,
    paddingBottom: 4,
    overflowX: "auto",
    flexShrink: 0,
    scrollbarWidth: "none",
  },
});
