import * as stylex from "@stylexjs/stylex";

export const finances = stylex.create({
  root: {
    containerType: "inline-size",
    containerName: "finances",
    display: "flex",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    width: "100%",
    backgroundColor: "var(--background)",
    color: "var(--foreground)",
    fontFamily: "var(--font-sans)",
    fontSize: 13,
    lineHeight: 1.5,
    textAlign: "start",
  },
  sidebar: {
    display: { default: "flex", "@container finances (width < 768px)": "none" },
    flexDirection: "column",
    flexShrink: 0,
    boxSizing: "border-box",
    height: "100%",
    minHeight: 0,
    width: { default: 240, "@container finances (768px <= width < 1200px)": 64 },
    borderInlineEnd: "1px solid var(--separator)",
    paddingInline: 12,
  },
  identity: { height: 64, flexShrink: 0, display: "flex", alignItems: "center", gap: 10 },
  railLabel: {
    display: { default: "block", "@container finances (768px <= width < 1200px)": "none" },
    minWidth: 0,
  },
  nav: { display: "flex", flexDirection: "column", gap: 4, paddingBlockStart: 20 },
  navButton: {
    justifyContent: "start",
    width: "100%",
    height: 36,
    minHeight: 36,
    paddingInline: 10,
    gap: 12,
    fontSize: 14,
  },
  selected: { backgroundColor: "var(--default)", color: "var(--default-foreground)" },
  sidebarFooter: {
    marginBlockStart: "auto",
    paddingBlock: 16,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  mobileNav: {
    display: { default: "none", "@container finances (width < 768px)": "block" },
    flexShrink: 0,
  },
  main: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    overflowY: "auto",
    paddingInline: 20,
    paddingBlockEnd: 20,
  },
  header: {
    minHeight: 64,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },
  headerTitle: { display: "flex", alignItems: "center", gap: 8, minWidth: 0, flex: "1 1 170px" },
  title: { margin: 0, fontSize: 20, fontWeight: 600, lineHeight: 1.3, overflowWrap: "anywhere" },
  note: { margin: 0, color: "var(--muted)", fontSize: 12, overflowWrap: "anywhere" },
  label: { fontSize: 11, color: "var(--muted)" },
  field: { display: "flex", flexDirection: "column", minWidth: 0, gap: 4 },
  select: {
    minWidth: 0,
    maxWidth: "100%",
    width: "100%",
    minHeight: 32,
    height: 32,
    fontSize: 12,
    borderRadius: 999,
  },
  number: { fontVariantNumeric: "tabular-nums" },
  summary: {
    display: "grid",
    gridTemplateColumns: {
      default: "repeat(4, minmax(0, 1fr))",
      "@container finances (480px < width < 1000px)": "repeat(2, minmax(0, 1fr))",
      "@container finances (width <= 480px)": "minmax(0, 1fr)",
    },
    gap: 12,
    margin: 0,
    marginBlockEnd: 16,
  },
  card: {
    backgroundColor: "var(--surface)",
    color: "var(--surface-foreground)",
    boxShadow: "var(--surface-shadow)",
    borderRadius: "var(--radius-2xl)",
    minWidth: 0,
  },
  stat: {
    height: 100,
    boxSizing: "border-box",
    padding: 16,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr)",
    gridTemplateRows: "20px 1fr auto",
    gap: 0,
    alignItems: "end",
  },
  metricLabel: { color: "var(--muted)", fontSize: 14, gridColumn: "1 / -1", alignSelf: "start" },
  statValue: {
    margin: 0,
    fontSize: 26,
    fontWeight: 600,
    lineHeight: 1.3,
    fontVariantNumeric: "tabular-nums",
    overflowWrap: "anywhere",
  },
  change: {
    margin: 0,
    fontSize: 11,
    color: "var(--success-soft-foreground)",
    backgroundColor: "var(--success-soft)",
    borderRadius: 999,
    paddingInline: 6,
    paddingBlock: 0,
    justifySelf: "start",
  },
  dangerChange: { color: "var(--danger-soft-foreground)", backgroundColor: "var(--danger-soft)" },
  overview: {
    display: "grid",
    gridTemplateColumns: {
      default: "minmax(0, 2fr) minmax(0, 1fr)",
      "@container finances (width < 1000px)": "minmax(0, 1fr)",
    },
    gap: 12,
    marginBlockEnd: 16,
    minWidth: 0,
  },
  chart: {
    margin: 0,
    height: 400,
    padding: 20,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  sectionHeading: { margin: 0, fontSize: 16, fontWeight: 600 },
  chartValue: {
    fontSize: 26,
    fontWeight: 600,
    fontVariantNumeric: "tabular-nums",
    overflowWrap: "anywhere",
  },
  plot: {
    display: "block",
    width: "100%",
    minWidth: 0,
    flex: 1,
    minHeight: 100,
    overflow: "hidden",
  },
  gridLine: { stroke: "var(--separator)", strokeWidth: 1 },
  tick: {
    fill: "var(--muted)",
    fontSize: 11,
    fontFamily: "var(--font-sans)",
    fontVariantNumeric: "tabular-nums",
  },
  series: {
    fill: "none",
    stroke: "var(--accent)",
    strokeWidth: 2.5,
    strokeLinejoin: "round",
    strokeLinecap: "round",
  },
  categories: {
    minHeight: 400,
    padding: 20,
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  categoryTableRoot: { width: "100%", minWidth: 0, backgroundColor: "transparent" },
  categoryTable: { width: "100%", minWidth: 0, fontSize: 12 },
  categoryHeader: { backgroundColor: "transparent" },
  categoryHeading: {
    paddingInline: 4,
    paddingBlock: 4,
    backgroundColor: "transparent",
    fontSize: 11,
    fontWeight: 400,
    "::after": { display: "none" },
  },
  categoryRow: { height: 40, backgroundColor: "transparent" },
  categoryCell: {
    paddingInline: 0,
    paddingBlock: 0,
    minWidth: 0,
    fontSize: 12,
    borderBottomWidth: 0,
  },
  categoryAmount: {
    paddingInline: 4,
    paddingBlock: 0,
    borderBottomWidth: 0,
    fontSize: 12,
    textAlign: "end",
    whiteSpace: "nowrap",
    fontVariantNumeric: "tabular-nums",
  },
  category: {
    width: "100%",
    minWidth: 0,
    minHeight: 40,
    height: 40,
    justifyContent: "start",
    gap: 8,
    paddingInline: 4,
    fontSize: 12,
  },
  categoryLabel: { flex: 1, minWidth: 0, textAlign: "start", overflowWrap: "anywhere" },
  toolbar: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "end",
    justifyContent: "space-between",
    gap: 12,
  },
  controls: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "end",
    gap: 8,
    minWidth: 0,
    maxWidth: "100%",
  },
  search: { flex: "1 1 180px", width: 220, maxWidth: "100%" },
  results: {
    display: "block",
    marginBlock: 8,
    minHeight: 18,
    fontSize: 12,
    color: "var(--muted)",
    overflowWrap: "anywhere",
  },
  tableRoot: { minWidth: 0, width: "100%" },
  tableScroll: {
    maxWidth: "100%",
    overflowX: "auto",
    outline: { default: null, ":focus-visible": "2px solid var(--focus)" },
    outlineOffset: 2,
  },
  table: { width: "100%", minWidth: 570, fontSize: 13 },
  columnHeading: {
    height: 36,
    boxSizing: "border-box",
    paddingBlock: 0,
    paddingInline: 12,
    fontSize: 11,
    textAlign: "start",
  },
  row: { height: 56 },
  cell: { paddingInline: 12, fontSize: 13 },
  amountHeading: { justifyContent: "end", gap: 4 },
  date: { whiteSpace: "nowrap", fontVariantNumeric: "tabular-nums", color: "var(--muted)" },
  description: { fontWeight: 500, overflowWrap: "anywhere" },
  amount: {
    textAlign: "end",
    whiteSpace: "nowrap",
    fontVariantNumeric: "tabular-nums",
    fontWeight: 500,
  },
  type: { fontSize: 11 },
  footnote: { margin: 0, marginTop: 12, fontSize: 11, color: "var(--muted)" },
  form: { display: "flex", flexDirection: "column", gap: 16 },
  actions: { flexWrap: "wrap", gap: 8 },
  error: { margin: 0, color: "var(--danger)", fontSize: 13 },
});
