import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";
import { motion } from "../shared/motion.stylex.js";

export const styles = stylex.create({
  backdrop: {
    backgroundColor: tokens.colorSurfaceScrim,
    inset: 0,
    opacity: 1,
    position: "fixed",
    transitionDuration: motion.durationOverlay,
    transitionProperty: "opacity",
    transitionTimingFunction: motion.easeOut,
    zIndex: 100,
    "[data-starting-style]": { opacity: 0 },
    "[data-ending-style]": { opacity: 0 },
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
  viewport: {
    alignItems: "center",
    display: "flex",
    inset: 0,
    justifyContent: "center",
    padding: tokens.space4,
    position: "fixed",
    zIndex: 101,
  },
  popup: {
    backgroundColor: tokens.colorSurfaceDialog,
    borderColor: tokens.colorBorderDialog,
    borderRadius: tokens.radiusPopover,
    borderStyle: "solid",
    borderWidth: tokens.sizeBorderDialog,
    boxShadow: `0 ${tokens.elevationDialogDetailY} ${tokens.elevationDialogDetailBlur} ${tokens.elevationDialogDetail}, 0 ${tokens.elevationDialogSoftY} ${tokens.elevationDialogSoftBlur} ${tokens.elevationDialogSoft}, 0 ${tokens.elevationDialogMidY} ${tokens.elevationDialogMidBlur} ${tokens.elevationDialogMid}, 0 ${tokens.elevationDialogKeyY} ${tokens.elevationDialogKeyBlur} ${tokens.elevationDialogKey}, 0 ${tokens.elevationDialogAmbientY} ${tokens.elevationDialogAmbientBlur} ${tokens.elevationDialogAmbient}`,
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    maxHeight: "calc(100vh - 32px)",
    maxWidth: "calc(100vw - 32px)",
    outline: "none",
    overflow: "auto",
    position: "relative",
    transform: "scale(1)",
    transitionDuration: motion.durationDialog,
    transitionProperty: "opacity, transform",
    transitionTimingFunction: motion.easeOut,
    width: tokens.sizeDialog,
    "[data-starting-style]": { opacity: 0, transform: "scale(0.96)" },
    "[data-ending-style]": { opacity: 0, transform: "scale(0.96)" },
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
  header: {
    alignItems: "center",
    boxSizing: "border-box",
    display: "flex",
    justifyContent: "space-between",
    overflow: "hidden",
    padding: tokens.space6,
    width: "100%",
  },
  body: {
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    gap: tokens.space4,
    overflow: "hidden",
    paddingBottom: tokens.space6,
    paddingInline: tokens.space6,
    width: "100%",
  },
  footer: {
    alignItems: "center",
    boxSizing: "border-box",
    display: "flex",
    gap: tokens.space2,
    justifyContent: "flex-end",
    overflow: "hidden",
    paddingBottom: tokens.space6,
    paddingInline: tokens.space6,
    width: "100%",
  },
  title: {
    color: tokens.colorContentPrimary,
    fontFamily: tokens.fontSans,
    fontSize: "15px",
    fontWeight: 600,
    lineHeight: "23px",
    margin: 0,
  },
  description: {
    color: tokens.colorContentSecondary,
    fontFamily: tokens.fontSans,
    fontSize: "12px",
    lineHeight: "18px",
    margin: 0,
  },
  close: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorSurfaceQuaternary,
    },
    borderColor: "transparent",
    borderStyle: "solid",
    borderWidth: 0,
    borderRadius: tokens.radiusRounded,
    color: tokens.colorContentSecondary,
    cursor: "pointer",
    display: "inline-flex",
    height: tokens.sizeIconButtonDefault,
    justifyContent: "center",
    outline: "none",
    padding: 0,
    position: "absolute",
    right: tokens.space6,
    top: "21.5px",
    transitionDuration: motion.durationFast,
    transitionProperty: "background-color, color, opacity",
    transitionTimingFunction: motion.easeHover,
    width: tokens.sizeIconButtonDefault,
  },
  closeIcon: {
    alignItems: "center",
    color: "currentColor",
    display: "inline-flex",
    height: tokens.space4,
    justifyContent: "center",
    width: tokens.space4,
  },
});
