// Adapted from HeroUI v3.2.6 pinned choice stories. SPDX-License-Identifier: Apache-2.0.
import * as stylex from "@stylexjs/stylex";

export const choiceStyles = stylex.create({
  column: { display: "flex", flexDirection: "column", gap: "1rem" },
  compact: { display: "flex", flexDirection: "column", gap: ".5rem" },
  row: { display: "flex", gap: "1.5rem", alignItems: "center" },
  customChecks: { display: "flex", gap: "1rem" },
  controlledColumn: { display: "flex", flexDirection: "column", gap: ".75rem" },
  roundedColumn: { display: "flex", flexDirection: "column", gap: "1.5rem" },
  variantsColumn: { display: "flex", flexDirection: "column", gap: "2rem" },
  icons: { display: "flex", gap: ".75rem" },
  padded: { paddingInline: "1rem" },
  status: { fontSize: ".875rem", color: "var(--muted)", marginTop: ".5rem" },
  heading: { fontSize: ".875rem", fontWeight: 500, color: "var(--muted)" },
  indent: { marginInlineStart: "1.5rem", display: "flex", flexDirection: "column", gap: ".5rem" },
  minWidth: { minWidth: "320px" },
  maxWidth: { maxWidth: "24rem" },
  overflow: { overflowX: "auto" },
  rounded: { borderRadius: "9999px", "::before": { borderRadius: "9999px" } },
  smallCheckmark: { "--checkbox-checkmark-size": ".5rem" },
  largeCheckmark: { "--checkbox-checkmark-size": "1rem" },
  largeIndicator: { width: "1rem", height: "1rem" },
  small: { width: ".75rem", height: ".75rem" },
  medium: { width: "1rem", height: "1rem" },
  large: { width: "1.25rem", height: "1.25rem" },
  extraLarge: { width: "1.5rem", height: "1.5rem" },
  customIndicator: { width: "100%", height: "100%" },
  customRadio: { color: "var(--background)", fontSize: ".75rem", lineHeight: 1 },
  showcase: {
    display: "flex",
    width: "100%",
    flexDirection: "column",
    alignItems: "center",
    gap: "2.5rem",
    paddingInline: "1rem",
    paddingBlock: "2rem",
  },
  section: {
    display: "flex",
    width: "100%",
    maxWidth: "32rem",
    flexDirection: "column",
    gap: "1rem",
  },
  deliveryGrid: {
    display: "grid",
    gap: "1rem",
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 768px)": "repeat(3, minmax(0, 1fr))",
    },
  },
  paymentGrid: {
    display: "grid",
    gap: "1rem",
    gridTemplateColumns: {
      default: "1fr",
      "@media (min-width: 768px)": "repeat(2, minmax(0, 1fr))",
    },
  },
  cardRoot: { width: "100%" },
  card: {
    position: "relative",
    display: "flex",
    width: "100%",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    gap: "1rem",
    borderRadius: "1.5rem",
    backgroundColor: {
      default: "var(--surface-tertiary)",
      ":is([data-checked] *)": "color-mix(in oklab, var(--accent) 10%, transparent)",
    },
    paddingInline: "1.25rem",
    paddingBlock: "1rem",
    paddingInlineEnd: "3rem",
    transition: {
      default: "background-color 150ms cubic-bezier(.4, 0, .2, 1)",
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  paymentCard: { borderRadius: ".75rem" },
  deliveryCard: {
    flexDirection: "column",
    gap: "1.5rem",
    borderRadius: ".75rem",
    backgroundColor: {
      default: "var(--surface-tertiary)",
      ":is([data-checked] *)": "color-mix(in oklab, var(--accent) 10%, transparent)",
      ":is([data-slot='radio']:focus-visible *)":
        "color-mix(in oklab, var(--accent) 10%, transparent)",
    },
  },
  cardControl: {
    position: "absolute",
    insetInlineEnd: "1rem",
    top: ".75rem",
    width: "1.25rem",
    height: "1.25rem",
  },
  cardText: { display: "flex", flexDirection: "column", gap: ".25rem" },
  price: { fontSize: ".875rem", fontWeight: 600 },
  cardIcon: { width: "1.25rem", height: "1.25rem", flexShrink: 0, color: "var(--accent)" },
  paymentIcon: { width: "1.5rem", height: "1.5rem", flexShrink: 0, color: "var(--accent)" },
  customSwitchControl: {
    height: "31px",
    width: "51px",
    "--switch-control-bg": "#3b82f6",
    "--switch-control-bg-hover": "#3b82f6",
    "--switch-control-bg-pressed": "#3b82f6",
    "--switch-control-bg-checked": "#06b6d4",
    "--switch-control-bg-checked-hover": "#06b6d4",
    boxShadow: { default: "none", ":is([data-checked] *)": "0 0 12px rgb(6 182 212 / .5)" },
  },
  customSwitchThumb: {
    width: "27px",
    height: "27px",
    backgroundColor: { default: "white", ":is([data-checked])": "white" },
    marginInlineStart: { default: "2px", ":is([data-checked])": "22px" },
  },
  customSwitchIcon: {
    width: "1rem",
    height: "1rem",
    color: { default: "#2563eb", ":is([data-checked] *)": "#0891b2" },
  },
  switchIcon: {
    width: ".75rem",
    height: ".75rem",
    opacity: { default: 0.7, ":is([data-checked] *)": 1 },
  },
  blue: {
    "--switch-control-bg-checked": "#3b82f6",
    "--switch-control-bg-checked-hover": "#3b82f6",
  },
  red: { "--switch-control-bg-checked": "#ef4444", "--switch-control-bg-checked-hover": "#ef4444" },
  green: {
    "--switch-control-bg-checked": "#22c55e",
    "--switch-control-bg-checked-hover": "#22c55e",
  },
  purple: {
    "--switch-control-bg-checked": "#a855f7",
    "--switch-control-bg-checked-hover": "#a855f7",
  },
  blueIcon: { color: "#2563eb" },
  redIcon: { color: "#dc2626" },
  greenIcon: { color: "#16a34a" },
  purpleIcon: { color: "#9333ea" },
  sliderFrame: { width: "24rem", padding: "2rem" },
  verticalFrame: { height: "24rem", padding: "2rem" },
});
