import * as stylex from "@stylexjs/stylex";

// HeroUI v3.2.6 story layout adaptation (Apache-2.0).
export const collectionStyles = stylex.create({
  wrapper: { width: "100%", maxWidth: 896, minWidth: 0 },
  stack3: { display: "flex", flexDirection: "column", gap: 12 },
  stack4: { display: "flex", flexDirection: "column", gap: 16 },
  stack6: { display: "flex", flexDirection: "column", gap: 24 },
  stack8: { display: "flex", flexDirection: "column", gap: 32 },
  small: { width: "min(384px, calc(100vw - 32px))", maxWidth: "100%" },
  medium: { width: "min(448px, calc(100vw - 32px))", maxWidth: "100%" },
  min800: { minWidth: 800 },
  min700: { minWidth: 700 },
  min650: { minWidth: 650 },
  min600: { minWidth: 600 },
  min520: { minWidth: 520 },
  emptyTable: { minHeight: 200, width: "min(600px, calc(100vw - 32px))", maxWidth: "100%" },
  fullHeight: { height: "100%" },
  virtualCell: { height: 42, paddingBlock: 10, lineHeight: "21px" },
  empty: { padding: 4 },
  emptyTableContent: {
    display: "flex",
    height: "100%",
    width: "100%",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    textAlign: "center",
  },
  scrollAsync: { height: 280, overflowY: "auto" },
  scrollVirtual: { height: 500, overflow: "auto" },
  sticky: { position: "sticky", top: 0, zIndex: 10, backgroundColor: "var(--surface-secondary)" },
  heading42: { height: 42 },
  row2: { display: "flex", alignItems: "center", gap: 8 },
  row3: { display: "flex", alignItems: "center", gap: 12 },
  row1: { display: "flex", alignItems: "center", gap: 4 },
  column: { display: "flex", flexDirection: "column" },
  textXs: { fontSize: 12 },
  mutedXs: { fontSize: 12, color: "var(--muted)" },
  mutedSm: { fontSize: 14, color: "var(--muted)" },
  weight: { fontWeight: 500 },
  end: { textAlign: "end" },
  role: { minWidth: 208 },
  status: { minWidth: 100 },
  noEndPadding: { paddingInlineEnd: 0 },
  noSeparator: { "::after": { content: "none" } },
  icon: { width: 16, height: 16, flexShrink: 0 },
  tray: { width: 24, height: 24, color: "var(--muted)" },
  mutedIcon: { width: 16, height: 16, color: "var(--muted)" },
  avatar: { width: 16, height: 16 },
  rotated: { transform: "rotate(90deg)" },
  chevron: {
    width: 16,
    height: 16,
    color: "var(--muted)",
    transitionProperty: "transform",
    transitionDuration: "150ms",
    transform: { default: "none", ":dir(rtl)": "rotate(180deg)" },
  },
  selected: { marginTop: 16, display: "flex", flexDirection: "column", gap: 8 },
  wrap: { display: "flex", flexWrap: "wrap", gap: 8 },
  selectedUser: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    borderRadius: 8,
    backgroundColor: "var(--surface-tertiary)",
    paddingInline: 8,
    paddingBlock: 4,
  },
  textSm: { fontSize: 14 },
});
