/**
 * HeroUI v3.2.6 story geometry adapted to compiled StyleX.
 * Copyright NextUI Inc. SPDX-License-Identifier: Apache-2.0
 */
import * as stylex from "@stylexjs/stylex";

export const colorStoryStyles = stylex.create({
  column: { display: "flex", flexDirection: "column", gap: 16 },
  column2: { display: "flex", flexDirection: "column", gap: 8 },
  column3: { display: "flex", flexDirection: "column", gap: 12 },
  column6: { display: "flex", flexDirection: "column", gap: 24 },
  column8: { display: "flex", flexDirection: "column", gap: 32 },
  row: { display: "flex", alignItems: "center", gap: 12 },
  row2: { display: "flex", alignItems: "center", gap: 8 },
  row4: { display: "flex", gap: 16 },
  row16: { display: "flex", gap: 64 },
  wrap: { flexWrap: "wrap" },
  field: { width: 280, maxWidth: "100%" },
  area: { width: 300, maxWidth: "100%" },
  full: { width: "100%" },
  width400: { width: 400, maxWidth: "100%" },
  width350: { width: 350, maxWidth: "100%" },
  width200: { width: 200, maxWidth: "100%" },
  width240: { width: 240, maxWidth: "100%" },
  width100: { width: 100 },
  width80: { width: 80 },
  width48: { width: 48 },
  width32: { width: 32 },
  palette: { maxWidth: 448 },
  sliderFrame: { width: 256, padding: 32, boxSizing: "content-box" },
  verticalFrame: { display: "flex", height: 256, gap: 32, padding: 32 },
  vertical: { height: 256 },
  flex: { flex: 1 },
  muted: { color: "var(--muted)", fontSize: 14 },
  small: { fontSize: 14 },
  tiny: { color: "var(--muted)", fontSize: 12 },
  medium: { fontWeight: 500 },
  heading: { color: "var(--muted)", fontSize: 14, fontWeight: 600 },
  capitalize: { textTransform: "capitalize" },
  mono: { fontFamily: "var(--font-mono)" },
  previewText: { display: "flex", flexDirection: "column", gap: 2 },
  swatch20: { width: 20, height: 20 },
  swatch32: { width: 32, height: 32 },
  marginTop: { marginTop: 12 },
  pickerArea: { maxWidth: "100%" },
  pickerGap: { gap: 8 },
  pickerNarrow: { maxWidth: 248, gap: 8 },
  pickerSliders: { maxWidth: 248, gap: 8, paddingInline: 8, paddingBlock: 12 },
  sliderCompact: { gap: 4, paddingInline: 4 },
  presets: { justifyContent: "center", paddingTop: 8 },
  presetsInline: { justifyContent: "center", paddingInline: 4 },
  channelGrid: {
    display: "grid",
    width: "100%",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    alignItems: "center",
    gap: 8,
  },
  tight: { gap: 4 },
  icon: { width: 16, height: 16 },
});
