// HeroUI v3.2.6 form story layouts, adapted to StyleX (Apache-2.0).
import * as stylex from "@stylexjs/stylex";

export const formWorkflowStyles = stylex.create({
  stack: { display: "flex", flexDirection: "column", gap: 16 },
  tight: { display: "flex", flexDirection: "column", gap: 8 },
  heading: { display: "flex", flexDirection: "column", gap: 4 },
  variants: { display: "flex", flexDirection: "column", gap: 24 },
  row: { display: "flex", alignItems: "center", gap: 8 },
  otp: { width: 280, maxWidth: "100%", display: "flex", flexDirection: "column", gap: 8 },
  form: { width: 280, maxWidth: "100%", display: "flex", flexDirection: "column", gap: 16 },
  full: { width: 400, maxWidth: "calc(100vw - 32px)" },
  search: { width: 280, maxWidth: "100%" },
  number: { width: 120 },
  grow: { flexGrow: 1, width: "100%" },
  wide: { width: "100%" },
  muted: { fontSize: 14, color: "var(--muted)", margin: 0 },
  underline: { color: "var(--foreground)", textDecorationLine: "underline", fontWeight: 500 },
  resend: { display: "flex", alignItems: "center", gap: 5, paddingInline: 4, paddingTop: 4 },
  backup: { display: "flex", alignItems: "center", justifyContent: "center", gap: 4 },
  chevronGroup: { display: "flex", height: 36, overflow: "hidden" },
  chevrons: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    borderInlineStartWidth: 1,
    borderInlineStartStyle: "solid",
    borderInlineStartColor: "color-mix(in oklab, var(--field-placeholder) 15%, transparent)",
  },
  chevronUp: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "50%",
    width: 24,
    borderRadius: 0,
    borderWidth: 0,
    paddingTop: 2,
  },
  chevronDown: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "50%",
    width: 24,
    borderRadius: 0,
    borderWidth: 0,
    paddingBottom: 2,
  },
  error: { color: "var(--danger)", fontSize: 14 },
  pending: { marginTop: 8, width: "100%" },
});
