// HeroUI v3.2.6 story geometry, Apache-2.0.
import * as stylex from "@stylexjs/stylex";

const historyEnter = stylex.keyframes({
  from: { opacity: 0, transform: "translateY(-8px)" },
  to: { opacity: 1, transform: "translateY(0)" },
});

export const menuToast = stylex.create({
  column: { display: "flex", flexDirection: "column" },
  centered: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    maxWidth: 576,
  },
  buttons: {
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    width: "100%",
  },
  placements: {
    display: "flex",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: 8,
    maxWidth: 320,
  },
  row: { display: "flex", alignItems: "center", gap: 8 },
  between: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    width: "100%",
  },
  gap6: { gap: 24 },
  callbacks: { maxWidth: 672 },
  queueRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    maxWidth: 896,
    height: "100%",
  },
  popup256: { minWidth: 256 },
  popup220: { minWidth: 220 },
  controlled: { minWidth: 384, display: "flex", flexDirection: "column", gap: 16 },
  muted: { color: "var(--muted)", fontSize: 14 },
  success: { color: "var(--success)" },
  warning: { color: "var(--warning)" },
  accent: { color: "var(--accent)" },
  danger: { color: "var(--danger)" },
  successAction: { backgroundColor: "var(--success)", color: "var(--success-foreground)" },
  warningAction: { backgroundColor: "var(--warning)", color: "var(--warning-foreground)" },
  shortcut: { marginInlineStart: "auto" },
  icon: { width: 16, height: 16, flexShrink: 0 },
  mutedIcon: { color: "var(--muted)" },
  smallIcon: { width: 14, height: 14 },
  largeIcon: { width: 20, height: 20 },
  iconBox: {
    display: "flex",
    height: 32,
    alignItems: "flex-start",
    justifyContent: "center",
    paddingTop: 1,
  },
  rounded: { borderRadius: 999 },
  profile: { paddingInline: 12, paddingTop: 12, paddingBottom: 4 },
  profileName: { fontSize: 14, lineHeight: "20px", fontWeight: 500 },
  profileEmail: { fontSize: 12, lineHeight: 1, color: "var(--muted)" },
  history: { width: "100%", display: "flex", flexDirection: "column", gap: 8 },
  historyPanel: {
    minHeight: 120,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    borderRadius: 8,
    border: "1px solid var(--border)",
    backgroundColor: "var(--surface)",
    padding: 16,
  },
  historyItem: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    borderRadius: 6,
    border: "1px solid var(--border)",
    backgroundColor: "var(--default)",
    paddingBlock: 8,
    paddingInline: 12,
    fontSize: 14,
    animationName: { default: historyEnter, "@media (prefers-reduced-motion: reduce)": "none" },
    animationDuration: "200ms",
    animationTimingFunction: "ease",
  },
  historyDelay: (delay: number) => ({ animationDelay: `${delay}ms` }),
  historyText: { flex: 1 },
  historyMessage: { fontWeight: 500 },
  historyClear: { height: 24, fontSize: 12 },
  historyHeading: { fontSize: 14, fontWeight: 500 },
  historyTime: { marginInlineStart: 8, fontSize: 12, color: "var(--muted)" },
  historyCheck: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 20,
    height: 20,
    flexShrink: 0,
    borderRadius: 999,
    backgroundColor: "color-mix(in oklch, var(--success) 10%, transparent)",
    color: "var(--success)",
  },
  customToast: { borderRadius: 12, border: "1px solid var(--border)" },
  toastViewport: { "--toast-width": "460px" },
  mobileAction: {
    display: { default: "inline-flex", "@media (min-width: 640px)": "none" },
    marginTop: 8,
  },
  desktopAction: {
    display: { default: "none", "@media (min-width: 640px)": "inline-flex" },
    marginTop: 0,
  },
  customText: { display: "flex", flexDirection: "column", paddingInlineEnd: 24 },
  customClose: {
    position: "absolute",
    insetInlineEnd: 8,
    top: "50%",
    transform: "translateY(-50%)",
    border: "none",
    backgroundColor: "transparent",
    opacity: 1,
  },
  modal: { maxWidth: 360 },
  modalIcon: { backgroundColor: "var(--default)", color: "var(--foreground)" },
  fullWidth: { width: "100%" },
});
