// HeroUI v3.2.6 source-story adaptation, Apache-2.0.
import * as stylex from "@stylexjs/stylex";

export const navigation = stylex.create({
  column: { display: "flex", flexDirection: "column", gap: 16 },
  row: { display: "flex", alignItems: "center", gap: 16 },
  smallRow: { display: "flex", alignItems: "center", gap: 8 },
  between: { display: "flex", alignItems: "center", justifyContent: "space-between" },
  width: { width: "100%", maxWidth: 448 },
  screen: {
    display: "flex",
    minHeight: "100vh",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  faq: {
    display: "flex",
    width: "100%",
    justifyContent: "center",
    paddingInline: 16,
    paddingBlock: 32,
  },
  faqInner: { width: "100%", maxWidth: 672 },
  categories: { display: "flex", flexDirection: "column", gap: 24, marginTop: 8 },
  faqTitle: { fontSize: 24, lineHeight: "32px", fontWeight: 700 },
  faqSubtitle: {
    fontSize: 18,
    lineHeight: "28px",
    fontWeight: 500,
    color: "var(--muted)",
    marginBottom: 16,
  },
  categoryTitle: { fontSize: 16, fontWeight: 500, color: "var(--muted)", marginBottom: 8 },
  icon: { width: 16, height: 16, flexShrink: 0 },
  itemIcon: { width: 16, height: 16, flexShrink: 0, marginInlineEnd: 12, color: "var(--muted)" },
  muted: { color: "var(--muted)", fontSize: 14, lineHeight: "20px" },
  heading: { fontSize: 18, fontWeight: 600 },
  surface: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    borderRadius: 24,
    backgroundColor: "var(--surface)",
    padding: 16,
    boxShadow: "var(--shadow-surface)",
  },
  qrBody: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    padding: 16,
    textAlign: "center",
  },
  standaloneBody: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    borderRadius: 24,
    backgroundColor: "var(--surface)",
    padding: 16,
    textAlign: "center",
    boxShadow: "var(--shadow-surface)",
  },
  qr: { aspectRatio: "1", width: "100%", maxWidth: 216, objectFit: "cover" },
  action: { marginTop: 16 },
  trigger: { width: "100%", justifyContent: "space-between" },
  contractWidth: (width: number) => ({ width }),
  groupTrigger: {
    width: "100%",
    borderWidth: 0,
    backgroundColor: { default: "transparent", ":is([data-panel-open])": "var(--default)" },
  },
  label: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  borderedTrigger: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 6,
    border: "1px solid #d1d5db",
    paddingInline: 16,
    paddingBlock: 8,
    textAlign: "start",
    backgroundColor: { default: "transparent", ":hover": "#f9fafb" },
  },
  borderBody: { border: "1px solid var(--border)", borderRadius: 8, padding: 16 },
  product: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 16,
  },
  grid: { display: "grid", gap: 8, fontSize: 14 },
  paddingTop: { paddingTop: 8 },
  underline: { textDecorationLine: "underline" },
  noUnderline: { textDecorationLine: { default: "none", ":hover": "none" } },
  offset1: { textUnderlineOffset: 1 },
  offset2: { textUnderlineOffset: 2 },
  offset3: { textUnderlineOffset: 3 },
  offset4: { textUnderlineOffset: 4 },
  linkButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 0,
    paddingInline: 12,
    paddingBlock: 2,
    textDecorationLine: { default: "none", ":hover": "none" },
  },
  icon8: { width: 8, height: 8 },
  icon12: { width: 12, height: 12 },
  linkSections: { display: "flex", flexDirection: "column", gap: 24 },
  linkSection: { display: "flex", flexDirection: "column", gap: 8 },
  offsets: { display: "flex", flexDirection: "column", gap: 12 },
  paginationWidth: { width: "100%", minWidth: 640 },
  sizes: { display: "flex", flexDirection: "column", gap: 32 },
  sizeLabel: { fontSize: 14, fontWeight: 600, color: "var(--muted)", textTransform: "capitalize" },
  tabs600: { width: 600, maxWidth: "calc(100vw - 32px)" },
  tabs400: { width: 400, maxWidth: "calc(100vw - 32px)" },
  tabs380: { width: 380, maxWidth: "calc(100vw - 32px)" },
  panel: { paddingTop: 16 },
  verticalPanel: { paddingInline: 16 },
  panelHeading: { marginBottom: 8, fontWeight: 600 },
  panelText: { fontSize: 14, color: "#4b5563" },
  selection: { marginBlock: 8 },
  customTab: {
    height: 24,
    width: "fit-content",
    paddingInline: 12,
    fontSize: 14,
    fontWeight: 400,
    color: { default: null, ":is([data-active])": "var(--accent-foreground)" },
  },
  customList: { width: "fit-content" },
  accentIndicator: { backgroundColor: "var(--accent)" },
  cameraRoot: { width: "100%" },
  cameraColumn: { display: "flex", flexDirection: "column", alignItems: "center" },
  cameraFrame: {
    position: "relative",
    aspectRatio: "7/5",
    width: "100%",
    maxWidth: 840,
    height: {
      default: null,
      "@media (min-width: 640px)": 400,
      "@media (min-width: 768px)": 500,
      "@media (min-width: 1024px)": 600,
    },
  },
  cameraImage: {
    position: "absolute",
    inset: 0,
    width: "100%",
    height: "100%",
    objectFit: "cover",
    opacity: { default: 0, ':is([data-selected="true"])': 1 },
    transitionProperty: "opacity",
    transitionDuration: { default: "800ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionDelay: { default: "200ms", ':is([data-selected="true"])': "0ms" },
    transitionTimingFunction: "ease-in-out",
  },
  cameraContainer: {
    marginBlock: { default: 16, "@media (min-width: 640px)": 24 },
    width: "100%",
    maxWidth: "100%",
    backgroundColor: "transparent",
  },
  cameraList: {
    width: "fit-content",
    minWidth: "min-content",
    borderRadius: 9999,
    backgroundColor: "#333336",
  },
  cameraTab: {
    height: { default: 32, "@media (min-width: 640px)": 36 },
    width: "fit-content",
    paddingInline: { default: 12, "@media (min-width: 640px)": 16 },
    fontSize: { default: 12, "@media (min-width: 640px)": 14 },
    fontWeight: 400,
    color: { default: "white", ":is([data-active])": "black" },
    opacity: { default: 0.8, ":hover": 1 },
  },
  capitalize: { textTransform: "capitalize" },
  cameraIndicator: {
    borderRadius: 9999,
    backgroundColor: "white",
    boxShadow: "none",
    transitionDuration: "320ms",
  },
  zoomFrame: { position: "relative", height: 40, width: 40 },
  zoom: {
    position: "absolute",
    insetInlineStart: "50%",
    top: "50%",
    transform: {
      default: "translate(-50%, -50%) scale(.75)",
      ':is([data-selected="true"])': "translate(-50%, -50%) scale(1)",
    },
    fontSize: 21,
    fontWeight: 500,
    color: "var(--foreground)",
    opacity: { default: 0, ':is([data-selected="true"])': 1 },
    transitionProperty: "transform,opacity",
    transitionDuration: { default: "300ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: "cubic-bezier(.33,1,.68,1)",
  },
  cameraFooter: {
    marginTop: 16,
    width: "100%",
    paddingInline: 16,
    textAlign: "center",
    fontSize: { default: 12, "@media (min-width: 640px)": 14 },
    color: "color-mix(in oklab, var(--muted) 30%, transparent)",
  },
  appleSection: {
    position: "relative",
    width: "100%",
    overflow: "hidden",
    backgroundColor: "var(--surface)",
    minHeight: 640,
  },
  appleLeft: { display: "flex", width: "100%", alignItems: "center", gap: 32, padding: 32 },
  appleControls: {
    zIndex: 1,
    display: { default: "none", "@media (min-width: 640px)": "flex" },
    flexDirection: "column",
    gap: 20,
    opacity: { default: 0, ':is([data-expanded="true"])': 1 },
    transform: {
      default: "translateY(120px) scale(.5)",
      ':is([data-expanded="true"])': "translateY(0) scale(1)",
    },
    transitionProperty: "transform,opacity",
    transitionDuration: { default: "300ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
  },
  appleDisclosure: { zIndex: 1, width: "100%", maxWidth: 448 },
  appleGroup: { display: "flex", flexDirection: "column", rowGap: 12 },
  appleButton: {
    height: 56,
    borderRadius: 9999,
    backgroundColor: { default: "#1e1e20", ":hover": "#272729" },
    color: "#f5f5f7",
    fontSize: 17,
  },
  appleSelected: { backgroundColor: "#272729" },
  swatch: {
    position: "relative",
    width: 24,
    height: 24,
    borderRadius: 8,
    backgroundColor: "#f77314",
    boxShadow: "inset 0 -1px 0 rgba(255,255,255,.5)",
  },
  appleBody: {
    marginTop: 12,
    display: "flex",
    maxWidth: 384,
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    borderRadius: 16,
    backgroundColor: "rgba(42,42,45,.72)",
    padding: 28,
    textAlign: "start",
    backdropFilter: "blur(20px)",
  },
  appleText: {
    fontSize: 17,
    fontWeight: 300,
    color: "#f5f5f7",
    opacity: { default: 0, ':is([data-expanded="true"])': 1 },
    transform: { default: "translateY(20px)", ':is([data-expanded="true"])': "translateY(0)" },
    transitionProperty: "opacity,transform",
    transitionDuration: { default: "800ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
  },
  appleImage: {
    pointerEvents: "none",
    position: "absolute",
    insetInlineEnd: "10%",
    top: "50%",
    zIndex: 0,
    display: { default: "none", "@media (min-width: 1024px)": "block" },
    width: "100%",
    maxWidth: 1152,
    transform: {
      default: "translate(10%,-50%) scale(1.5)",
      ':is([data-selected="true"])': "translate(0,-50%) scale(1.5)",
    },
    opacity: { default: 0, ':is([data-selected="true"])': 1 },
    transitionProperty: "opacity,transform",
    transitionDuration: { default: "900ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
  },
  round: { borderRadius: 9999 },
  appleNavigation: { display: "flex", flexDirection: "column", gap: 20 },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
});
