// HeroUI v3.2.6 source-story utility adaptations, Apache-2.0.
import * as stylex from "@stylexjs/stylex";

export const overlayStyles = stylex.create({
  row: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 16 },
  compactRow: { display: "flex", alignItems: "center", gap: 12 },
  column: { display: "flex", flexDirection: "column", gap: 16 },
  section: { display: "flex", flexDirection: "column", gap: 8 },
  examples: { display: "flex", flexDirection: "column", gap: 32, maxWidth: 448 },
  wideExamples: { display: "flex", flexDirection: "column", gap: 32, maxWidth: 672 },
  dismissExamples: { display: "flex", flexDirection: "column", gap: 24, maxWidth: 384 },
  muted: { color: "var(--muted)", fontSize: 14, lineHeight: "20px" },
  small: { color: "var(--muted)", fontSize: 12, lineHeight: "16px" },
  heading: { fontSize: 18, fontWeight: 600 },
  full: { width: "100%" },
  modalWidth: { maxWidth: { default: null, "@media (min-width: 640px)": 360 } },
  alertWidth: { maxWidth: { default: null, "@media (min-width: 640px)": 400 } },
  paragraph: { marginBottom: 12 },
  centered: { alignItems: "center", textAlign: "center" },
  reverse: { flexDirection: "column-reverse" },
  icon: { width: 20, height: 20, flexShrink: 0 },
  largeIcon: { width: 24, height: 24 },
  neutralIcon: { backgroundColor: "var(--default)", color: "var(--foreground)" },
  accent: { backgroundColor: "var(--accent-soft)", color: "var(--accent-soft-foreground)" },
  success: { backgroundColor: "var(--success-soft)", color: "var(--success-soft-foreground)" },
  warning: { backgroundColor: "var(--warning-soft)", color: "var(--warning-soft-foreground)" },
  danger: { backgroundColor: "var(--danger-soft)", color: "var(--danger-soft-foreground)" },
  customTrigger: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    borderRadius: 16,
    padding: 16,
    backgroundColor: { default: "var(--surface)", ":hover": "var(--surface-secondary)" },
    boxShadow: "var(--shadow-xs)",
    userSelect: "none",
  },
  triggerIcon: {
    width: 48,
    height: 48,
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
  },
  triggerText: { display: "flex", flexDirection: "column", flex: 1, gap: 2 },
  triggerTitle: { fontSize: 14, fontWeight: 600 },
  panel: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    borderRadius: 16,
    padding: 16,
    backgroundColor: "var(--surface)",
    boxShadow: "var(--shadow-sm)",
  },
  portalHost: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 380,
    width: "min(560px, calc(100vw - 32px))",
    overflow: "hidden",
    borderRadius: "var(--radius)",
    backgroundColor: "color-mix(in oklab, var(--muted) 20%, transparent)",
    transform: "translate(0)",
  },
  portalFill: { height: "100%", maxHeight: "100%" },
  portalPopup: { height: "100%", maxHeight: "100%", maxWidth: 448 },
  gradient: {
    backgroundImage: {
      default: "linear-gradient(to top, rgb(0 0 0 / .8), rgb(0 0 0 / .4), transparent)",
      ':where([data-theme="dark"]) &':
        "linear-gradient(to top, oklch(.274 .006 286.033 / .8), oklch(.274 .006 286.033 / .4), transparent)",
    },
  },
  kinematic: {
    transitionDuration: {
      default: "400ms",
      ":is([data-ending-style])": "200ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionTimingFunction: {
      default: "cubic-bezier(.16,1,.3,1)",
      ":is([data-ending-style])": "cubic-bezier(.7,0,.84,0)",
    },
    opacity: { default: 1, ":is([data-starting-style],[data-ending-style])": 0 },
    transform: {
      default: "scale(1)",
      ":is([data-starting-style],[data-ending-style])": "scale(.95)",
    },
  },
  kinematicBackdrop: {
    transitionDuration: {
      default: "400ms",
      ":is([data-ending-style])": "200ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionTimingFunction: {
      default: "cubic-bezier(.16,1,.3,1)",
      ":is([data-ending-style])": "cubic-bezier(.7,0,.84,0)",
    },
  },
  fluid: {
    transitionDuration: {
      default: "500ms",
      ":is([data-ending-style])": "200ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionTimingFunction: {
      default: "cubic-bezier(.25,1,.5,1)",
      ":is([data-ending-style])": "cubic-bezier(.5,0,.75,0)",
    },
    opacity: { default: 1, ":is([data-starting-style],[data-ending-style])": 0 },
    transform: {
      default: "translateY(0)",
      ":is([data-starting-style])": "translateY(16px)",
      ":is([data-ending-style])": "translateY(8px)",
    },
  },
  fluidBackdrop: {
    transitionDuration: {
      default: "500ms",
      ":is([data-ending-style])": "200ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionTimingFunction: {
      default: "cubic-bezier(.25,1,.5,1)",
      ":is([data-ending-style])": "cubic-bezier(.5,0,.75,0)",
    },
  },
  spring: {
    transitionDuration: {
      default: "600ms",
      ":is([data-ending-style])": "100ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionTimingFunction: {
      default: "cubic-bezier(.36,1.66,.04,1)",
      ":is([data-ending-style])": "var(--ease-smooth)",
    },
    transform: {
      default: "scale(1)",
      ":is([data-starting-style])": "scale(.9)",
      ":is([data-ending-style])": "scale(.95)",
    },
    opacity: { default: 1, ":is([data-starting-style],[data-ending-style])": 0 },
  },
  navigation: { display: "flex", flexDirection: "column", gap: 4 },
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    borderRadius: 12,
    paddingInline: 12,
    paddingBlock: 10,
    fontSize: 14,
    color: "var(--foreground)",
    backgroundColor: { default: "transparent", ":hover": "var(--default)" },
    transition: "background-color 150ms",
  },
  popoverProfile: { width: 290, display: "flex", flexDirection: "column", gap: 12 },
  between: { display: "flex", alignItems: "center", justifyContent: "space-between" },
  profileText: {
    display: "flex",
    flexDirection: "column",
    alignItems: "start",
    justifyContent: "center",
  },
  follow: { borderRadius: 9999, fontSize: 12, fontWeight: 400 },
  card400: { width: "min(400px, calc(100vw - 32px))" },
  card200: { width: 200 },
  help: { maxWidth: 200 },
  tooltipTrigger: { borderRadius: 9999, backgroundColor: "var(--accent-soft)", padding: 8 },
  round: { borderRadius: 9999 },
  cardTooltip: { display: "flex", alignItems: "center", justifyContent: "center", padding: 24 },
  springStage: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 32,
    padding: 32,
  },
  springTitle: { fontSize: 20, fontWeight: 600 },
  code: {
    borderRadius: "var(--radius)",
    backgroundColor: "var(--surface)",
    paddingInline: 8,
    paddingBlock: 4,
    fontSize: 12,
  },
});
