import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  trigger: {
    alignItems: "center",
    backgroundColor: {
      default: tokens.colorSurfacePopover,
      ":hover": tokens.colorSurfaceInteractiveHover,
      ":active": tokens.colorSurfaceLevel3,
      "[data-popup-open]": tokens.colorSurfaceLevel3,
      '[data-visual-state="default"]': tokens.colorSurfacePopover,
      '[data-visual-state="hover"]': tokens.colorSurfaceInteractiveHover,
      '[data-visual-state="pressed"]': tokens.colorSurfaceLevel3,
      '[data-visual-state="focus-visible"]': tokens.colorSurfacePopover,
      '[data-visual-state="open"]': tokens.colorSurfaceLevel3,
    },
    borderColor: tokens.colorBorderPopover,
    borderRadius: tokens.radiusRounded,
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    gap: "6px",
    height: "28px",
    justifyContent: "center",
    lineHeight: "20px",
    outline: {
      default: "none",
      ":focus-visible": `1px solid ${tokens.colorFocusRing}`,
      '[data-visual-state="focus-visible"]': `1px solid ${tokens.colorFocusRing}`,
    },
    outlineOffset: "1px",
    paddingInline: "8px",
    whiteSpace: "nowrap",
    width: "132px",
  },
  positioner: { outline: 0, zIndex: 50 },
  popup: {
    backgroundColor: tokens.colorSurfacePopover,
    borderColor: tokens.colorBorderPopover,
    borderRadius: tokens.radiusPopover,
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow:
      "0 1px 1px rgba(0,0,0,0.04), 0 3px 9px rgba(0,0,0,0.04), 0 6px 18px rgba(0,0,0,0.02)",
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    minHeight: "108px",
    outline: 0,
    overflow: "hidden",
    paddingBlock: "5px",
    transform: "scale(1)",
    transformOrigin: "var(--transform-origin)",
    transitionDuration: "120ms",
    transitionProperty: "opacity, transform",
    transitionTimingFunction: "ease-out",
    width: "225px",
    "[data-starting-style]": { opacity: 0, transform: "scale(0.98)" },
    "[data-ending-style]": { opacity: 0, transform: "scale(0.98)" },
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
  arrow: {
    alignItems: "center",
    display: "flex",
    height: "8px",
    justifyContent: "center",
    width: "16px",
  },
  arrowShape: {
    backgroundColor: tokens.colorSurfacePopover,
    borderColor: tokens.colorBorderPopover,
    borderStyle: "solid",
    borderWidth: "0.5px 0 0 0.5px",
    boxSizing: "border-box",
    height: "8px",
    transform: "rotate(45deg)",
    width: "8px",
  },
  arrowPreview: {
    backgroundColor: tokens.colorSurfacePopover,
    borderColor: tokens.colorBorderPopover,
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxSizing: "border-box",
    height: "8px",
    position: "absolute",
    transform: "rotate(45deg)",
    width: "8px",
  },
  item: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorSurfaceLevel3,
      ":focus-visible": tokens.colorSurfaceLevel3,
      '[data-visual-state="highlighted"]': tokens.colorSurfaceLevel3,
    },
    borderRadius: tokens.radiusControl,
    borderStyle: "none",
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    cursor: "pointer",
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    height: "32px",
    lineHeight: "19.5px",
    marginInline: "6px",
    outline: "none",
    paddingInline: "8px",
    textAlign: "left",
    width: "212px",
  },
  itemDanger: { color: tokens.colorActionDanger },
});
