import { defineDocsMeta } from "@lenso/docs";

export default defineDocsMeta({
  pages: [
    "button",
    "icon-button",
    "text-field",
    "text-area",
    "select",
    "combobox",
    "checkbox",
    "radio",
    "switch",
    "slider",
    "segmented-control",
    "tabs",
    "menu",
    "command-menu",
    "popover",
    "dialog",
    "toast",
    "tooltip",
    "breadcrumb",
    "disclosure",
    "avatar",
    "label",
    "inline-alert",
    "content-state",
    "description-list",
    "status-marker",
    "shimmer-text",
    "data-table",
    "data-grid",
    "selection-toolbar",
    "resize-handle",
  ],
});
