/**
 * Derived from HeroUI v3.2.6. Copyright 2026 HeroUI.
 * SPDX-License-Identifier: Apache-2.0
 * Modified: StyleX styles and Base UI state/anchor properties.
 */
import * as stylex from "@stylexjs/stylex";
import { tokens } from "../../tokens.stylex.const.js";

export const selectStyles = stylex.create({
  trigger: {
    position: "relative",
    isolation: "isolate",
    display: "inline-flex",
    alignItems: "center",
    minHeight: "2.25rem",
    gap: ".5rem",
    paddingBlock: ".5rem",
    paddingInlineStart: ".75rem",
    paddingInlineEnd: "1.75rem",
    borderRadius: tokens.fieldRadius,
    borderWidth: tokens.borderWidthField,
    borderStyle: "solid",
    borderColor: {
      default: tokens.fieldBorder,
      ":hover": tokens.fieldBorderHover,
      ":focus-visible": tokens.fieldBorderFocus,
      ":is([data-invalid])": tokens.danger,
    },
    backgroundColor: {
      default: tokens.fieldBackground,
      ":hover": tokens.fieldHover,
      ":focus-visible": tokens.fieldFocus,
    },
    color: tokens.fieldForeground,
    boxShadow: tokens.fieldShadow,
    fontSize: ".875rem",
    lineHeight: "1.25rem",
    outline: { default: "none", ":focus-visible": `2px solid ${tokens.focus}` },
    outlineOffset: 2,
    userSelect: "none",
    cursor: { default: "pointer", ":is([data-disabled])": "default" },
    opacity: { default: 1, ":is([data-disabled])": tokens.disabledOpacity },
    transition: {
      default: `border-color 150ms ${tokens.easeSmooth}, background-color 150ms ${tokens.easeSmooth}`,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  secondary: {
    backgroundColor: { default: tokens.default, ":hover": tokens.defaultHover },
    boxShadow: "none",
  },
  value: {
    flex: 1,
    textAlign: "start",
    overflowWrap: "break-word",
    color: { default: "inherit", ":is([data-placeholder])": tokens.fieldPlaceholder },
    fontSize: { default: "1rem", "@media (min-width: 640px)": ".875rem" },
  },
  indicator: {
    position: "absolute",
    insetBlock: 0,
    insetInlineEnd: ".5rem",
    marginBlock: "auto",
    display: "flex",
    width: "1rem",
    height: "1rem",
    alignItems: "center",
    justifyContent: "center",
    color: tokens.fieldPlaceholder,
    transform: { default: "rotate(0deg)", ":is([data-popup-open])": "rotate(180deg)" },
    transition: {
      default: `transform 150ms ${tokens.easeSmooth}`,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  positioner: { zIndex: tokens.zIndexOverlay, outline: "none" },
  popover: {
    minWidth: "var(--anchor-width)",
    maxWidth: "var(--available-width)",
    maxHeight: "var(--available-height)",
    transformOrigin: "var(--transform-origin)",
    overflowY: "auto",
    overscrollBehavior: "contain",
    scrollPaddingBlock: ".25rem",
    backgroundColor: tokens.overlay,
    color: tokens.overlayForeground,
    borderRadius: `min(32px, ${tokens.radius3xl})`,
    boxShadow: tokens.shadowOverlay,
    padding: 0,
    fontSize: ".875rem",
    outline: "none",
    opacity: { default: 1, ":is([data-starting-style])": 0, ":is([data-ending-style])": 0 },
    transform: {
      default: "scale(1)",
      ":is([data-starting-style])": "scale(.95)",
      ":is([data-starting-style][data-side='top'])": "translateY(.25rem) scale(.95)",
      ":is([data-starting-style][data-side='bottom'])": "translateY(-.25rem) scale(.95)",
      ":is([data-starting-style][data-side='left'])": "translateX(.25rem) scale(.95)",
      ":is([data-starting-style][data-side='right'])": "translateX(-.25rem) scale(.95)",
      ":is([data-ending-style])": "scale(.95)",
    },
    pointerEvents: { default: "auto", ":is([data-ending-style])": "none" },
    transition: {
      default: `opacity 150ms ${tokens.easeSmooth}, transform 150ms ${tokens.easeSmooth}`,
      ":is([data-ending-style])": `opacity 100ms ${tokens.easeSmooth}, transform 100ms ${tokens.easeSmooth}`,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  list: { padding: ".375rem", outline: "none" },
  item: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    gap: ".75rem",
    paddingBlock: ".375rem",
    paddingInline: ".625rem",
    paddingInlineEnd: "1.75rem",
    width: "100%",
    borderRadius: tokens.radius2xl,
    minHeight: "2.25rem",
    outline: { default: "none", ":focus-visible": `2px solid ${tokens.focus}` },
    outlineOffset: -2,
    cursor: "pointer",
    userSelect: "none",
    backgroundColor: { default: "transparent", ":is([data-highlighted])": tokens.default },
    color: tokens.overlayForeground,
    opacity: { default: 1, ":is([data-disabled])": tokens.disabledOpacity },
    transform: { default: "scale(1)", ":active": "scale(.98)" },
    transition: {
      default: `transform 250ms ${tokens.easeOutQuart}`,
      "@media (prefers-reduced-motion: reduce)": "none",
    },
  },
  itemText: { flex: 1, minWidth: 0 },
  itemIndicator: {
    position: "absolute",
    insetInlineEnd: ".5rem",
    top: "50%",
    transform: "translateY(-50%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "1rem",
    height: "1rem",
    color: tokens.defaultForeground,
  },
  label: { fontSize: ".875rem", fontWeight: 500, color: tokens.foreground },
  groupLabel: { padding: ".5rem", fontSize: ".75rem", color: tokens.muted },
  separator: { height: 1, backgroundColor: tokens.separator, marginBlock: ".25rem" },
  arrow: { fill: tokens.overlay },
  fullWidth: { width: "100%" },
});
