import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";
import { motion } from "../shared/motion.stylex.js";

export const styles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.space2,
    maxWidth: "304px",
    width: "100%",
  },
  label: {
    color: tokens.colorContentPrimary,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 500,
    lineHeight: "16px",
  },
  control: {
    backgroundColor: {
      default: tokens.colorSurfaceControl,
      "[data-read-only]": tokens.colorSurfaceReadOnly,
      ":disabled": tokens.colorSurfaceInteractive,
    },
    borderColor: {
      default: tokens.colorBorderControl,
      ":hover": {
        default: null,
        "@media (hover: hover) and (pointer: fine)": tokens.colorBorderControlFocus,
      },
      "[data-invalid]": tokens.colorStatusErrorBorder,
      '[data-visual-state="hover"]': tokens.colorBorderControlFocus,
      ":disabled": tokens.colorBorderTertiary,
      "[data-read-only]": tokens.colorBorderTertiary,
    },
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    lineHeight: "16px",
    minWidth: 0,
    width: "100%",
    "::placeholder": { color: tokens.colorContentTertiary },
  },
  standaloneControl: {
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: tokens.sizeBorderControl,
    outlineColor: {
      default: "transparent",
      ":focus-visible": tokens.colorFocusRing,
      '[data-visual-state="active"]': tokens.colorFocusRing,
      '[data-visual-state="focus-visible"]': tokens.colorFocusRing,
    },
    outlineOffset: "-1px",
    outlineStyle: "solid",
    outlineWidth: {
      default: 0,
      ":focus-visible": "2px",
      '[data-visual-state="active"]': "2px",
      '[data-visual-state="focus-visible"]': "2px",
    },
    paddingBlock: "6px",
    paddingInline: tokens.space3,
    transitionDuration: motion.durationFast,
    transitionProperty: "background-color, border-color, outline-color",
    transitionTimingFunction: motion.easeHover,
  },
  groupedControl: {
    appearance: "none",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    flex: 1,
    height: "100%",
    outline: "none",
    padding: 0,
    "::-webkit-search-cancel-button": { display: "none" },
  },
  defaultControl: {
    height: tokens.sizeInputDefault,
  },
  compactControl: {
    height: tokens.sizeControlCompact,
    paddingBlock: "4px",
  },
  inputGroup: {
    alignItems: "center",
    backgroundColor: {
      default: tokens.colorSurfaceControl,
      "[data-disabled]": tokens.colorSurfaceInteractive,
      ":has(:disabled)": tokens.colorSurfaceInteractive,
      ":has([data-read-only])": tokens.colorSurfaceReadOnly,
    },
    borderColor: {
      default: tokens.colorBorderControl,
      ":hover": {
        default: null,
        "@media (hover: hover) and (pointer: fine)": tokens.colorBorderControlFocus,
      },
      "[data-invalid]": tokens.colorStatusErrorBorder,
      ":has([data-invalid])": tokens.colorStatusErrorBorder,
      ':has([data-visual-state="hover"])': tokens.colorBorderControlFocus,
      "[data-disabled]": tokens.colorBorderTertiary,
      ":has(:disabled)": tokens.colorBorderTertiary,
      ":has([data-read-only])": tokens.colorBorderTertiary,
    },
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: tokens.sizeBorderControl,
    boxSizing: "border-box",
    color: tokens.colorContentTertiary,
    display: "flex",
    gap: "6px",
    outlineColor: {
      default: "transparent",
      ":focus-within": tokens.colorFocusRing,
      ':has([data-visual-state="active"])': tokens.colorFocusRing,
      ':has([data-visual-state="focus-visible"])': tokens.colorFocusRing,
    },
    outlineOffset: "-1px",
    outlineStyle: "solid",
    outlineWidth: {
      default: 0,
      ":focus-within": "2px",
      ':has([data-visual-state="active"])': "2px",
      ':has([data-visual-state="focus-visible"])': "2px",
    },
    paddingInline: "8px",
    transitionDuration: motion.durationFast,
    transitionProperty: "border-color, background-color, outline-color",
    transitionTimingFunction: motion.easeHover,
    width: "100%",
  },
  defaultInputGroup: {
    height: tokens.sizeInputDefault,
  },
  compactInputGroup: {
    height: tokens.sizeControlCompact,
  },
  leading: {
    alignItems: "center",
    color: tokens.colorContentTertiary,
    display: "inline-flex",
    flexShrink: 0,
    height: tokens.sizeIconDefault,
    justifyContent: "center",
    lineHeight: 0,
    width: tokens.sizeIconDefault,
  },
  trailing: {
    alignItems: "center",
    color: tokens.colorContentTertiary,
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: tokens.fontSans,
    fontSize: "12px",
    lineHeight: "16px",
  },
  clear: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": {
        default: null,
        "@media (hover: hover) and (pointer: fine)": tokens.colorSurfaceInteractiveHover,
      },
    },
    borderRadius: tokens.radiusRounded,
    borderStyle: "none",
    color: tokens.colorContentTertiary,
    cursor: { default: "pointer", ":disabled": "default" },
    display: "inline-flex",
    flexShrink: 0,
    height: tokens.sizeIconButtonCompact,
    justifyContent: "center",
    opacity: { default: 1, ":disabled": tokens.opacityDisabled },
    outlineColor: { default: "transparent", ":focus-visible": tokens.colorFocusRing },
    outlineOffset: "-1px",
    outlineStyle: "solid",
    outlineWidth: { default: 0, ":focus-visible": "2px" },
    padding: 0,
    width: tokens.sizeIconButtonCompact,
  },
  clearIcon: {
    height: tokens.sizeIconDefault,
    strokeWidth: "1.5px",
    width: tokens.sizeIconDefault,
  },
  description: {
    color: tokens.colorContentTertiary,
    fontFamily: tokens.fontSans,
    fontSize: "12px",
    lineHeight: "16px",
    margin: 0,
  },
  error: {
    color: tokens.colorStatusErrorContent,
    fontFamily: tokens.fontSans,
    fontSize: "12px",
    lineHeight: "16px",
    margin: 0,
  },
});
