import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  root: {
    backgroundColor: tokens.colorSurfaceCanvas,
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    fontFamily: tokens.fontSans,
    position: "relative",
    width: "100%",
  },
  team: { height: "87.5px" },
  simple: { height: "32px" },
  row: {
    alignItems: "center",
    boxSizing: "border-box",
    display: "flex",
    width: "100%",
  },
  teamRow: {
    borderBottomColor: tokens.colorBorderSecondary,
    borderBottomStyle: "solid",
    borderBottomWidth: "0.5px",
    height: "44px",
    paddingInline: "18px 8px",
  },
  simpleRow: { height: "32px", overflow: "hidden", paddingInline: "16px" },
  leading: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    marginRight: "8px",
    width: "16px",
  },
  title: {
    color: tokens.colorContentPrimary,
    fontFamily: tokens.fontSans,
    fontWeight: 500,
    margin: 0,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  teamTitle: { fontSize: "13px", lineHeight: "15.5px" },
  simpleTitle: { flex: 1, fontSize: "24px", lineHeight: "32px" },
  actions: { alignItems: "center", display: "flex", gap: "4px", marginLeft: "8px" },
  spacer: { flex: 1 },
  tabsRoot: { width: "100%" },
  tabsRow: {
    alignItems: "center",
    boxSizing: "border-box",
    display: "flex",
    height: "43.5px",
    paddingInline: "8px",
    width: "100%",
  },
  tabsList: { alignItems: "center", display: "flex", gap: "4px", height: "28px" },
  tab: {
    alignItems: "center",
    backgroundColor: {
      default: tokens.colorSurfaceCanvas,
      ":hover": tokens.colorSurfaceSelected,
      ":active": tokens.colorSurfaceLevel3,
      "[data-active]": tokens.colorSurfaceSelected,
    },
    borderColor: {
      default: tokens.colorBorderTranslucent,
      ":hover": tokens.colorBorderSecondary,
      ":active": tokens.colorBorderSecondary,
    },
    borderRadius: tokens.radiusRounded,
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxSizing: "border-box",
    color: { default: tokens.colorContentTertiary, "[data-active]": tokens.colorContentPrimary },
    cursor: { default: "pointer", ":disabled": "default" },
    display: "inline-flex",
    fontFamily: tokens.fontSans,
    fontSize: "12px",
    fontWeight: 500,
    height: "28px",
    justifyContent: "center",
    lineHeight: "16px",
    opacity: { default: 1, ":disabled": tokens.opacityDisabled },
    outline: { default: "none", ":focus-visible": `1px solid ${tokens.colorFocusRing}` },
    outlineOffset: "-1px",
    paddingInline: "10px",
    transitionDuration: "150ms",
    transitionProperty: "background-color, border-color, color",
    transitionTimingFunction: "ease-out",
    whiteSpace: "nowrap",
  },
  panel: { outline: "none" },
});
