import * as stylex from "@stylexjs/stylex";
export const nativeReferenceStyles = stylex.create({
  root: { width: "100%", maxWidth: 448 },
  basicCard: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
    backgroundColor: "transparent",
    padding: 16,
  },
  card: { display: "flex", flexDirection: "column", gap: 16, borderRadius: 24, padding: 16 },
  heading: {
    marginBottom: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  title: { fontSize: 18, fontWeight: 600 },
  actions: { display: "flex", gap: 8 },
  trigger: { width: "100%", borderWidth: 0 },
  closed: { backgroundColor: "transparent" },
  label: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 8,
  },
  indicator: { color: "var(--muted)" },
  body: {
    marginInline: 8,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    padding: 16,
    textAlign: "center",
  },
  muted: { fontSize: 14, color: "var(--muted)" },
  qr: { aspectRatio: "1", width: "100%", maxWidth: 216, objectFit: "cover" },
  action: { marginTop: 16 },
  separator: { marginBlock: 8 },
  expo: { fill: "var(--accent-foreground)" },
});
