import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  lab: {
    display: "flex",
    flexDirection: "column",
    height: "100%",
    minHeight: "0",
    overflow: "hidden",
    width: "100%",
    "@media (max-width: 980px)": { height: "auto", overflow: "visible" },
  },
  labToolbar: {
    alignItems: "center",
    borderBottom: "0.5px solid var(--color-border-tertiary)",
    display: "flex",
    flex: "none",
    height: "40px",
    justifyContent: "space-between",
    paddingInline: "8px 4px",
    "@media (max-width: 680px)": {
      gap: "8px",
      overflowX: "auto",
    },
  },
  labActions: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    "@media (max-width: 680px)": { flexWrap: "wrap" },
  },
  headerButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    height: "24px",
    borderStyle: "none",
    borderWidth: 0,
    color: "var(--color-content-secondary)",
    fontFamily: "inherit",
    fontSize: "11px",
    cursor: "pointer",
    gap: "5px",
    padding: "0 9px",
    borderRadius: "var(--radius-rounded)",
    backgroundColor: "var(--color-surface-control)",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-control)",
    ":hover": {
      backgroundColor: "var(--color-surface-interactive-hover)",
      color: "var(--color-content-primary)",
    },
    ":focus-visible": { boxShadow: "inset 0 0 0 1px var(--color-focus-ring)", outline: "none" },
  },
  workspace: {
    display: "grid",
    flex: "1 1 auto",
    gridTemplateColumns: "238px minmax(360px, 1fr) 288px",
    minHeight: "0",
    "@media (max-width: 1220px)": { gridTemplateColumns: "220px minmax(340px, 1fr) 256px" },
    "@media (max-width: 980px)": { display: "flex", flexDirection: "column" },
  },
  workArea: {
    display: "flex",
    flexDirection: "column",
    minHeight: "0",
    minWidth: "0",
    "@media (max-width: 980px)": {
      borderBottom: "0.5px solid var(--color-border-tertiary)",
      borderTop: "0.5px solid var(--color-border-tertiary)",
      minHeight: "520px",
    },
  },
  inspector: {
    alignSelf: "stretch",
    backgroundColor: "var(--color-surface-panel)",
    borderRadius: "var(--radius-panel)",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-translucent)",
    display: "flex",
    flexDirection: "column",
    margin: "8px 0 8px 12px",
    minHeight: "0",
    minWidth: "0",
    overflow: "hidden",
    "@media (max-width: 980px)": {
      margin: "12px 0 0",
      minHeight: "520px",
    },
  },
  controls: {
    backgroundColor: "transparent",
    borderRight: "0.5px solid var(--color-border-tertiary)",
    display: "flex",
    flexDirection: "column",
    minHeight: "0",
    minWidth: "0",
    "@media (max-width: 980px)": { borderWidth: 0 },
  },
  panelHeading: {
    alignItems: "center",
    borderBottom: "0.5px solid var(--color-border-tertiary)",
    display: "flex",
    flex: "none",
    height: "40px",
    justifyContent: "space-between",
    padding: "0 12px",
  },
  headingCopy: { minWidth: 0 },
  headingTitle: {
    color: "var(--color-content-primary)",
    fontSize: "12px",
    fontWeight: "600",
    lineHeight: "17px",
    margin: "0",
  },
  panelCount: {
    backgroundColor: "var(--color-surface-subtle)",
    borderRadius: "var(--radius-rounded)",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-tertiary)",
    color: "var(--color-content-tertiary)",
    fontSize: "9px",
    fontWeight: "600",
    lineHeight: "13px",
    padding: "2px 7px",
    textTransform: "capitalize",
  },
  previewHeading: {
    display: "flex",
    flex: "none",
    alignItems: "center",
    justifyContent: "space-between",
    height: "40px",
    padding: "0 12px",
    borderBottom: "0.5px solid var(--color-border-tertiary)",
  },
  previewHeadingCode: {
    color: "var(--color-content-tertiary)",
    fontFamily: '"IBM Plex Mono", monospace',
    fontSize: "10px",
  },
  sectionLabel: {
    color: "var(--color-content-tertiary)",
    fontSize: "9px",
    fontWeight: "600",
    lineHeight: "13px",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  controlSection: {
    borderBottom: "0.5px solid var(--color-border-tertiary)",
    display: "flex",
    flex: "none",
    flexDirection: "column",
    gap: "10px",
    padding: "12px",
  },
  advancedSection: { gap: 0, padding: 0 },
  advancedTrigger: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--color-content-secondary)",
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    justifyContent: "space-between",
    minHeight: "48px",
    padding: "7px 12px",
    textAlign: "left",
    width: "100%",
    ":hover": { backgroundColor: "var(--color-surface-interactive-hover)" },
    ":focus-visible": {
      boxShadow: "inset 0 0 0 1px var(--color-focus-ring)",
      outline: "none",
    },
  },
  advancedTitle: {
    color: "var(--color-content-primary)",
    display: "block",
    fontSize: "11px",
    fontWeight: 500,
    lineHeight: "16px",
    marginTop: "1px",
  },
  advancedIcon: {
    color: "var(--color-content-tertiary)",
    transform: "rotate(0deg)",
    transition: "transform 120ms ease-out",
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
  advancedIconOpen: { transform: "rotate(180deg)" },
  advancedFields: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    padding: "4px 12px 12px",
  },
  fieldText: {
    color: "var(--color-content-secondary)",
    fontSize: "11px",
    lineHeight: "16px",
  },
  rangeField: {
    display: "flex",
    flexDirection: "column",
    gap: "6px",
  },
  colorField: {
    display: "grid",
    gridTemplateColumns: "72px minmax(0, 1fr)",
    gap: "8px",
    alignItems: "center",
  },
  colorControl: {
    position: "relative",
    display: "flex",
    gap: "7px",
    alignItems: "center",
    width: "100%",
    height: "30px",
    minWidth: "0",
    padding: "0 8px",
    borderRadius: "var(--radius-control)",
    boxShadow:
      "inset 0 0 0 0.5px color-mix(in srgb, var(--theme-color-field-content) 24%, transparent),\n    0 1px 1px #0000001f",
    color: "var(--theme-color-field-content)",
    cursor: "pointer",
    ":focus-within": {
      boxShadow: "inset 0 0 0 1px var(--color-focus-ring),\n    0 1px 1px #0000001f",
    },
  },
  colorControlIcon: { flex: "none" },
  colorControlTrailingIcon: { marginLeft: "auto", opacity: "0.8" },
  colorValue: {
    minWidth: "0",
    overflow: "hidden",
    fontFamily: '"IBM Plex Mono", monospace',
    fontSize: "10px",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  colorPicker: {
    position: "absolute",
    inset: "0",
    width: "100%",
    height: "100%",
    margin: "0",
    padding: "0",
    borderStyle: "none",
    borderWidth: 0,
    opacity: "0",
    backgroundColor: "transparent",
    cursor: "pointer",
  },
  rangeLabel: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  rangeOutput: {
    color: "var(--color-content-primary)",
    fontFamily: '"IBM Plex Mono", monospace',
  },
  derivedField: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) 52px 52px",
    gap: "6px",
    alignItems: "center",
    minHeight: "30px",
    color: "var(--color-content-secondary)",
    fontSize: "11px",
  },
  numericLabel: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-control)",
    borderRadius: "6px",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-control)",
    display: "flex",
    height: "28px",
    paddingLeft: "7px",
  },
  numericLabelCode: {
    color: "var(--color-content-tertiary)",
    fontFamily: '"IBM Plex Mono", monospace',
    fontSize: "9px",
  },
  numericInput: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    color: "var(--color-content-primary)",
    fontFamily: '"IBM Plex Mono", monospace',
    fontSize: "10px",
    height: "26px",
    minWidth: "0",
    outline: "none",
    padding: "0 5px",
    textAlign: "right",
    width: "100%",
  },
  contrastGrid: {
    display: "grid",
    gap: "4px",
  },
  contrastBadge: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto 34px",
    gap: "8px",
    alignItems: "center",
    height: "25px",
    color: "var(--color-content-tertiary)",
    fontSize: "10px",
  },
  contrastValue: {
    color: "var(--color-content-primary)",
    fontFamily: '"IBM Plex Mono", monospace',
    fontSize: "10px",
    fontWeight: "500",
  },
  contrastStatus: {
    alignItems: "center",
    borderRadius: "var(--radius-rounded)",
    color: "var(--color-status-error-content)",
    display: "inline-flex",
    fontSize: "9px",
    height: "18px",
    justifyContent: "center",
  },
  contrastPass: { color: "var(--color-status-success-content)" },
  previewTheme: {
    flex: "1 1 auto",
    minHeight: "0",
    margin: "8px 12px 12px",
    overflow: "hidden",
    borderRadius: "var(--radius-panel)",
    backgroundColor: "var(--color-surface-canvas)",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-dialog),\n    0 10px 28px #00000014",
    color: "var(--color-content-primary)",
  },
  previewApp: {
    display: "grid",
    gridTemplateColumns: "126px minmax(260px, 1fr) 150px",
    width: "100%",
    height: "100%",
    minHeight: "390px",
    backgroundColor: "var(--color-surface-canvas)",
    "@media (max-width: 1220px)": { gridTemplateColumns: "110px minmax(240px, 1fr)" },
    "@media (max-width: 680px)": { gridTemplateColumns: "1fr" },
  },
  previewSidebar: {
    display: "flex",
    flexDirection: "column",
    minWidth: "0",
    padding: "10px 8px",
    backgroundColor: "var(--color-surface-surface)",
    borderRight: "0.5px solid var(--color-border-dialog)",
    "@media (max-width: 680px)": { display: "none" },
  },
  previewWorkspaceName: {
    display: "flex",
    gap: "6px",
    alignItems: "center",
    height: "26px",
    padding: "0 4px",
    color: "var(--color-content-primary)",
    fontSize: "11px",
    fontWeight: "600",
  },
  previewWorkspaceIcon: { color: "var(--color-content-tertiary)", marginLeft: "auto" },
  previewMark: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "18px",
    height: "18px",
    borderRadius: "5px",
    backgroundColor: "var(--color-action-primary)",
    color: "var(--color-action-primary-content)",
    fontSize: "9px",
  },
  previewSelectedNav: {
    backgroundColor: "var(--color-surface-selected)",
    color: "var(--color-content-primary)",
  },
  previewNav: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    marginTop: "8px",
  },
  previewNavButton: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": "var(--color-surface-interactive-hover)",
    },
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--radius-rounded)",
    color: { default: "var(--color-content-secondary)", ":hover": "var(--color-content-primary)" },
    cursor: "pointer",
    display: "flex",
    fontFamily: "inherit",
    fontSize: "10px",
    gap: "7px",
    height: "25px",
    overflow: "hidden",
    padding: "0 7px",
    textAlign: "left",
    whiteSpace: "nowrap",
  },
  previewNavTrailing: {
    color: "var(--color-content-tertiary)",
    fontFamily: "inherit",
    fontSize: "8px",
    marginLeft: "auto",
  },
  previewSidebarLabel: {
    margin: "18px 7px 0",
    color: "var(--color-content-tertiary)",
    fontSize: "8px",
    fontWeight: "600",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  previewMain: {
    display: "flex",
    flexDirection: "column",
    minWidth: "0",
    minHeight: "0",
    backgroundColor: "var(--color-surface-canvas)",
  },
  previewHeader: {
    display: "flex",
    flex: "none",
    alignItems: "center",
    justifyContent: "space-between",
    height: "48px",
    padding: "0 12px",
    borderBottom: "0.5px solid var(--color-border-dialog)",
  },
  previewHeaderLead: { alignItems: "center", display: "flex", gap: "6px", minWidth: "0" },
  previewHeaderMeta: { color: "var(--color-content-tertiary)", fontSize: "10px" },
  previewHeaderTitle: {
    color: "var(--color-content-primary)",
    fontSize: "11px",
    fontWeight: "600",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  previewHeaderActions: {
    display: "flex",
    gap: "6px",
    alignItems: "center",
  },
  previewHeaderButton: {
    minWidth: "auto",
    whiteSpace: "nowrap",
  },
  previewToolbar: {
    display: "flex",
    flex: "none",
    gap: "6px",
    alignItems: "center",
    padding: "10px 12px",
  },
  previewSearch: {
    flex: "1 1 auto",
    minWidth: "80px",
  },
  previewList: {
    margin: "0 12px 12px",
    overflow: "hidden",
    borderRadius: "var(--radius-control)",
    backgroundColor: "var(--color-surface-panel)",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-dialog)",
  },
  previewGroupHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "28px",
    padding: "0 10px",
    borderBottom: "0.5px solid var(--color-border-dialog)",
    color: "var(--color-content-tertiary)",
    fontSize: "9px",
    fontWeight: "600",
    textTransform: "uppercase",
  },
  previewSelectedRow: {
    display: "grid",
    gridTemplateColumns: "14px 42px minmax(90px, 1fr) auto 14px",
    gap: "7px",
    alignItems: "center",
    height: "34px",
    padding: "0 9px",
    color: "var(--color-content-primary)",
    fontSize: "9px",
    backgroundColor: "var(--color-surface-selected)",
    "@media (max-width: 680px)": { gridTemplateColumns: "14px 40px minmax(80px, 1fr) 14px" },
  },
  previewRow: {
    alignItems: "center",
    color: "var(--color-content-secondary)",
    display: "grid",
    fontSize: "9px",
    gap: "7px",
    gridTemplateColumns: "14px 42px minmax(90px, 1fr) auto 14px",
    height: "34px",
    padding: "0 9px",
    ":hover": {
      backgroundColor: "var(--color-surface-interactive-hover)",
    },
    "@media (max-width: 680px)": { gridTemplateColumns: "14px 40px minmax(80px, 1fr) 14px" },
  },
  previewRowBorder: { borderTop: "0.5px solid var(--color-border-dialog)" },
  previewRowMeta: {
    color: "var(--color-content-tertiary)",
    fontFamily: '"IBM Plex Mono", monospace',
    fontSize: "8px",
  },
  previewRowTitle: {
    fontSize: "10px",
    fontWeight: "500",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  previewRowPill: {
    backgroundColor: "var(--color-surface-control)",
    borderRadius: "var(--radius-rounded)",
    color: "var(--color-content-tertiary)",
    fontSize: "8px",
    padding: "2px 6px",
    whiteSpace: "nowrap",
    "@media (max-width: 680px)": { display: "none" },
  },
  previewInspector: {
    minWidth: "0",
    backgroundColor: "var(--color-surface-panel)",
    borderLeft: "0.5px solid var(--color-border-dialog)",
    "@media (max-width: 1220px)": { display: "none" },
  },
  previewInspectorHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "48px",
    padding: "0 10px",
    borderBottom: "0.5px solid var(--color-border-dialog)",
    color: "var(--color-content-secondary)",
    fontSize: "10px",
    fontWeight: "600",
  },
  previewInspectorBody: {
    padding: "13px 11px",
  },
  previewInspectorEyebrow: {
    color: "var(--color-content-tertiary)",
    fontSize: "8px",
    margin: "0",
    textTransform: "uppercase",
  },
  previewInspectorTitle: {
    color: "var(--color-content-primary)",
    fontSize: "12px",
    lineHeight: "17px",
    margin: "5px 0 0",
  },
  previewInspectorList: { display: "grid", gap: "10px", margin: "18px 0 0" },
  previewInspectorListRow: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    minWidth: "0",
  },
  previewInspectorTerm: {
    color: "var(--color-content-tertiary)",
    fontSize: "9px",
    margin: "0",
  },
  previewInspectorDefinition: {
    color: "var(--color-content-secondary)",
    fontSize: "9px",
    margin: "0",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  previewSwitchValue: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    minHeight: "26px",
    marginInlineEnd: "-6px",
    overflow: "visible",
  },
  tokenList: {
    flex: "1 1 auto",
    minHeight: "0",
    overflowY: "auto",
    padding: "4px",
    scrollbarWidth: "thin",
    "@media (max-width: 980px)": { maxHeight: "420px" },
  },
  tokenRow: {
    display: "grid",
    gridTemplateColumns: "16px minmax(0, 1fr) auto",
    gap: "7px",
    alignItems: "center",
    width: "100%",
    minHeight: "38px",
    padding: "4px 7px",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "7px",
    backgroundColor: "transparent",
    color: "var(--color-content-secondary)",
    fontFamily: "inherit",
    fontSize: "inherit",
    fontStyle: "inherit",
    fontWeight: "inherit",
    lineHeight: "inherit",
    textAlign: "left",
    cursor: "pointer",
    ":hover": {
      backgroundColor: "var(--color-surface-interactive-hover)",
    },
    ":focus-visible": { boxShadow: "inset 0 0 0 1px var(--color-focus-ring)", outline: "none" },
  },
  selectedTokenRow: {
    backgroundColor: "var(--color-surface-selected)",
  },
  tokenCopy: { minWidth: "0" },
  tokenName: {
    color: "var(--color-content-primary)",
    display: "block",
    fontSize: "10px",
    fontWeight: "500",
    lineHeight: "14px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tokenPath: {
    color: "var(--color-content-tertiary)",
    display: "block",
    fontSize: "8px",
    lineHeight: "12px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  tokenCode: {
    color: "var(--color-content-tertiary)",
    fontFamily: '"IBM Plex Mono", monospace',
    fontSize: "9px",
  },
  tokenSwatch: {
    width: "14px",
    height: "14px",
    borderRadius: "4px",
    boxShadow: "inset 0 0 0 0.5px #80808066,\n    0 0 0 0.5px #00000012",
  },
  adjustmentPanel: {
    flex: "none",
    padding: "10px 11px 12px",
    borderTop: "0.5px solid var(--color-border-tertiary)",
  },
  adjustmentHeading: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "3px",
    color: "var(--color-content-tertiary)",
    fontSize: "9px",
    textTransform: "uppercase",
  },
  adjustmentButton: {
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "var(--radius-rounded)",
    color: "var(--color-content-secondary)",
    cursor: "pointer",
    fontFamily: "inherit",
    fontSize: "9px",
    height: "20px",
    padding: "0 6px",
    textTransform: "none",
    ":disabled": { cursor: "default", opacity: "0.4" },
    ":focus-visible": { boxShadow: "inset 0 0 0 1px var(--color-focus-ring)", outline: "none" },
  },
  adjustmentName: {
    color: "var(--color-content-primary)",
    fontSize: "11px",
    fontWeight: "500",
  },
  adjustmentGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "6px",
    marginTop: "8px",
  },
});
