import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  page: { marginInline: "auto", maxWidth: "980px", width: "100%" },
  intro: {
    maxWidth: "650px",
    paddingBlock: "10px 56px",
    "@media (max-width: 720px)": { paddingBlock: "0 32px" },
  },
  eyebrow: {
    color: "var(--color-content-tertiary)",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "18px",
    margin: "0 0 15px",
  },
  title: {
    color: "var(--docs-fg-primary)",
    fontSize: "30px",
    fontWeight: 600,
    lineHeight: "38px",
    margin: 0,
    maxWidth: "600px",
    "@media (max-width: 720px)": { fontSize: "25px", lineHeight: "32px" },
  },
  description: {
    color: "var(--color-content-secondary)",
    fontSize: "14px",
    lineHeight: "23px",
    margin: "14px 0 0",
    maxWidth: "640px",
  },
  directory: { borderTop: "1px solid var(--docs-structural-border)" },
  group: {
    borderBottom: "1px solid var(--docs-structural-border)",
    display: "grid",
    gap: "48px",
    gridTemplateColumns: "220px minmax(0, 1fr)",
    paddingBlock: "26px",
    scrollMarginTop: "24px",
    "@media (max-width: 720px)": { gap: "16px", gridTemplateColumns: "minmax(0, 1fr)" },
  },
  groupIntro: { maxWidth: "230px" },
  groupTitle: {
    color: "var(--color-content-primary)",
    fontSize: "15px",
    fontWeight: 600,
    lineHeight: "22px",
    margin: 0,
  },
  groupDescription: {
    color: "var(--color-content-tertiary)",
    fontSize: "12px",
    lineHeight: "19px",
    margin: "7px 0 0",
  },
  links: { display: "flex", flexDirection: "column", minWidth: 0 },
  link: {
    alignItems: "center",
    borderRadius: "9px",
    color: "var(--color-content-primary)",
    display: "grid",
    gap: "18px",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1.2fr)",
    minHeight: "40px",
    paddingInline: "12px",
    textDecoration: "none",
    ":hover": { backgroundColor: "var(--docs-sidebar-hover)" },
    ":focus-visible": { outline: "2px solid var(--color-focus-ring)", outlineOffset: "-2px" },
    "@media (max-width: 560px)": {
      alignItems: "start",
      gap: "2px",
      gridTemplateColumns: "minmax(0, 1fr)",
      paddingBlock: "8px",
    },
  },
  linkLabel: { fontSize: "13px", fontWeight: 500, lineHeight: "20px" },
  linkDetail: { color: "var(--color-content-tertiary)", fontSize: "12px", lineHeight: "18px" },
});
