import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  overview: {
    display: "grid",
    gap: "80px",
    gridTemplateColumns: "580px 420px",
    height: "200px",
    "@media (max-width: 1100px)": { gridTemplateColumns: "minmax(0, 1fr)", height: "auto" },
  },
  overviewCopy: { height: "200px" },
  title: {
    color: "var(--docs-fg-primary)",
    fontSize: "30px",
    fontWeight: 600,
    lineHeight: "38px",
    margin: 0,
    width: "560px",
    "@media (max-width: 720px)": { width: "100%" },
  },
  description: {
    color: "var(--color-content-secondary)",
    fontSize: "12px",
    lineHeight: "20px",
    margin: "8px 0 0",
    width: "560px",
    "@media (max-width: 720px)": { width: "100%" },
  },
  metadata: { display: "flex", gap: "8px", marginTop: "12px" },
  metadataPill: {
    alignItems: "center",
    backgroundColor: "var(--color-surface-translucent)",
    borderRadius: "var(--radius-rounded)",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-translucent)",
    color: "var(--color-content-secondary)",
    display: "inline-flex",
    fontSize: "10px",
    height: "22px",
    lineHeight: "14px",
    paddingInline: "9px",
  },
  preview: {
    alignSelf: "start",
    backgroundColor: "var(--color-surface-panel)",
    borderRadius: "var(--radius-panel)",
    boxShadow: "inset 0 0 0 0.5px var(--docs-structural-border)",
    height: "176px",
    marginTop: "12px",
    padding: "41px 20px 0",
    width: "420px",
    "@media (max-width: 1100px)": { display: "none" },
  },
  previewHeader: {
    alignItems: "center",
    display: "flex",
    height: "20px",
    justifyContent: "space-between",
  },
  previewTitle: { fontSize: "12px", fontWeight: 400, lineHeight: "16px", margin: 0 },
  previewControls: {
    alignItems: "center",
    display: "flex",
    gap: "10px",
    height: "28px",
    marginTop: "16px",
  },
  previewButton: { width: "86px" },
  previewDescription: {
    color: "var(--color-content-secondary)",
    fontSize: "10px",
    lineHeight: "14px",
    margin: "12px 0 0",
  },
  densitySelect: {
    fontSize: "13px",
    gap: "8px",
    height: "28px",
    minHeight: "28px",
    paddingBlock: "6px",
    paddingInline: "10.5px",
    width: "120px",
  },
  densityPopup: { height: "auto", minHeight: 0 },
  section: { width: "100%" },
  foundations: {
    height: "160px",
    marginTop: "48px",
    "@media (max-width: 1100px)": { height: "auto" },
  },
  components: {
    height: "200px",
    marginTop: "48px",
    "@media (max-width: 1100px)": { height: "auto" },
  },
  sectionCopy: { height: "40px" },
  sectionTitle: { fontSize: "14px", fontWeight: 500, lineHeight: "20px", margin: 0 },
  sectionDescription: {
    color: "var(--color-content-secondary)",
    fontSize: "11px",
    lineHeight: "16px",
    margin: "4px 0 0",
  },
  grid: {
    backgroundColor: "var(--color-surface-panel)",
    borderRadius: "var(--radius-panel)",
    boxShadow: "inset 0 0 0 0.5px var(--docs-structural-border)",
    display: "grid",
    gap: 0,
    marginTop: "16px",
    overflow: "hidden",
  },
  fourColumns: {
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    "@media (max-width: 1100px)": { gridTemplateColumns: "repeat(2, minmax(0, 1fr))" },
    "@media (max-width: 720px)": { gridTemplateColumns: "minmax(0, 1fr)" },
  },
  threeColumns: {
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    marginTop: "8px",
    "@media (max-width: 720px)": { gridTemplateColumns: "minmax(0, 1fr)" },
  },
  indexCard: {
    backgroundColor: { default: "transparent", ":hover": "var(--color-surface-interactive-hover)" },
    borderRadius: 0,
    boxShadow: "inset -0.5px 0 0 var(--docs-structural-border)",
    color: "inherit",
    display: "flex",
    flexDirection: "column",
    height: "88px",
    justifyContent: "center",
    padding: "14px 16px",
    textDecoration: "none",
    transition: "background-color 120ms ease-out, color 120ms ease-out",
    ":focus-visible": { outline: "1px solid var(--color-focus-ring)", outlineOffset: "1px" },
  },
  lastCard: { boxShadow: "none" },
  cardTitle: {
    color: "var(--color-content-primary)",
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "16px",
    margin: 0,
  },
  cardDescription: {
    color: "var(--color-content-secondary)",
    fontSize: "11px",
    lineHeight: "16px",
    margin: "6px 0 0",
  },
  componentCard: {
    backgroundColor: "transparent",
    borderRadius: 0,
    boxShadow: "inset -0.5px 0 0 var(--docs-structural-border)",
    height: "144px",
    overflow: "hidden",
    padding: "14px",
  },
  componentStage: {
    alignItems: "center",
    display: "flex",
    height: "88px",
    justifyContent: "center",
    marginTop: "12px",
    width: "100%",
  },
  gappedStage: { gap: "8px" },
  navigationStage: {
    color: "var(--color-content-secondary)",
    fontFamily: "var(--font-sans)",
    fontSize: "13px",
    fontWeight: 500,
    gap: "6px",
    justifyContent: "flex-start",
    lineHeight: "19.5px",
    paddingInline: "10px",
  },
  sidebarItem: { boxSizing: "border-box", flex: 1, minWidth: 0 },
  densityLabel: {
    color: "var(--color-content-secondary)",
    fontSize: "10px",
    lineHeight: "14px",
    width: "43px",
  },
  patterns: {
    height: "120px",
    marginTop: "48px",
    "@media (max-width: 1100px)": { height: "auto" },
  },
  patternsHeading: { alignItems: "center", display: "flex", gap: "10px", height: "24px" },
  patternsTitle: { fontSize: "13px", fontWeight: 500, lineHeight: "18px", margin: 0 },
  patternsDescription: {
    color: "var(--color-content-secondary)",
    fontSize: "11px",
    lineHeight: "16px",
    margin: 0,
  },
  startLinks: { marginTop: "48px", paddingBottom: "40px", width: "100%" },
});
