import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  trigger: {
    alignItems: "center",
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    cursor: { default: "pointer", "[data-disabled]": "default" },
    display: "inline-flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    gap: "8px",
    height: "32px",
    lineHeight: "16px",
    outline: "none",
    paddingBlock: "6px",
    paddingInline: "10.5px",
    position: "relative",
    whiteSpace: "nowrap",
  },
  triggerDisabled: { opacity: tokens.opacityDisabled },
  value: { position: "relative" },
  icon: {
    alignItems: "center",
    color: tokens.colorContentSecondary,
    display: "inline-flex",
    height: "5px",
    justifyContent: "center",
    position: "relative",
    width: "10px",
  },
  iconSvg: { height: "10px", strokeWidth: "1.5px", width: "10px" },
  positioner: { outline: 0, zIndex: 50 },
  popup: {
    backgroundColor: tokens.colorSurfacePopover,
    borderColor: tokens.colorBorderPopover,
    borderRadius: tokens.radiusPopover,
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow: `0 1px 0.5px ${tokens.elevationOverlayDetail}, 0 ${tokens.elevationOverlayKeyY} calc(${tokens.elevationOverlayKeyBlur} / 2) ${tokens.elevationOverlayKey}, 0 ${tokens.elevationOverlayAmbientY} calc(${tokens.elevationOverlayAmbientBlur} / 2) ${tokens.elevationOverlayAmbient}`,
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    height: "168px",
    minWidth: "180px",
    outline: 0,
    paddingBlock: "4px",
    transformOrigin: "var(--transform-origin)",
  },
  list: { outline: 0 },
  item: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      "[data-highlighted]": tokens.colorSurfaceOverlayHover,
      '[data-highlighted][data-visual-state="default"]': "transparent",
    },
    borderRadius: tokens.radiusControl,
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    cursor: { default: "default", "[data-disabled]": "not-allowed" },
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    height: "32px",
    justifyContent: "space-between",
    lineHeight: "19.5px",
    marginInline: "4px",
    outline: 0,
    paddingLeft: "8px",
    paddingRight: "4px",
    userSelect: "none",
  },
  itemSelected: { backgroundColor: tokens.colorSurfaceSelected },
  itemDisabled: { opacity: tokens.opacityDisabled },
  itemIndicator: {
    alignItems: "center",
    display: "inline-flex",
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  indicatorSvg: { height: "16px", strokeWidth: "1.5px", width: "16px" },
  groupLabel: {
    color: tokens.colorContentTertiary,
    fontFamily: tokens.fontSans,
    fontSize: "11px",
    lineHeight: "16px",
    padding: "6px 12px 2px",
  },
  separator: {
    backgroundColor: tokens.colorBorderTertiary,
    height: "0.5px",
    marginBlock: "4px",
    marginInline: "8px",
  },
  scrollArrow: {
    alignItems: "center",
    backgroundColor: tokens.colorSurfacePopover,
    color: tokens.colorContentSecondary,
    display: "flex",
    height: "24px",
    justifyContent: "center",
  },
});
