import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  trigger: {
    alignItems: "center",
    backgroundColor: tokens.colorSurfaceSurface,
    border: 0,
    borderRadius: tokens.radiusControl,
    boxShadow:
      "0 1px 1px rgba(0,0,0,0.04), 0 3px 6px -2px rgba(0,0,0,0.02), 0 0 0 0.5px rgba(0,0,0,0.09)",
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    gap: tokens.space2,
    height: tokens.sizeControlDefault,
    justifyContent: "space-between",
    lineHeight: "16px",
    minWidth: "84px",
    outlineColor: {
      default: "transparent",
      ":focus-visible": tokens.colorFocusRing,
    },
    outlineOffset: "1px",
    outlineStyle: "solid",
    outlineWidth: {
      default: 0,
      ":focus-visible": "1px",
    },
    paddingInline: "10px",
    transitionDuration: "120ms",
    transitionProperty: "background-color, color, opacity",
    transitionTimingFunction: "ease-out",
    userSelect: "none",
    whiteSpace: "nowrap",
    "[data-disabled]": {
      cursor: "not-allowed",
      opacity: tokens.opacityDisabled,
    },
  },
  value: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  icon: {
    alignItems: "center",
    color: tokens.colorContentTertiary,
    display: "inline-flex",
    flexShrink: 0,
    height: "14px",
    justifyContent: "center",
    width: "14px",
  },
  iconSvg: {
    height: "14px",
    strokeWidth: 1.75,
    width: "14px",
  },
  positioner: {
    maxHeight: "var(--available-height)",
    maxWidth: "var(--available-width)",
    outline: "none",
    zIndex: 50,
  },
  popup: {
    backgroundColor: tokens.colorSurfaceElevated,
    borderColor: tokens.colorBorderSecondary,
    borderRadius: tokens.radiusPopover,
    borderStyle: "solid",
    borderWidth: tokens.sizeBorderControl,
    boxShadow:
      "0 6px 18px rgba(0,0,0,0.02), 0 3px 9px rgba(0,0,0,0.04), 0 1px 1px rgba(0,0,0,0.04)",
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    minWidth: "180px",
    opacity: 1,
    overflow: "hidden",
    transform: "scale(1)",
    transformOrigin: "var(--transform-origin)",
    transitionDuration: "120ms",
    transitionProperty: "opacity, transform",
    transitionTimingFunction: "ease-out",
    "[data-ending-style]": {
      opacity: 0,
      transform: "scale(0.98)",
    },
    "[data-starting-style]": {
      opacity: 0,
      transform: "scale(0.98)",
    },
  },
  list: {
    maxHeight: "min(320px, var(--available-height))",
    overflowY: "auto",
    paddingBlock: tokens.space1,
  },
  item: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: tokens.radiusControl,
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    cursor: "default",
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    height: tokens.sizeControlDefault,
    justifyContent: "space-between",
    lineHeight: "20px",
    marginInline: tokens.space1,
    outline: "none",
    paddingLeft: tokens.space3,
    paddingRight: tokens.space2,
    userSelect: "none",
  },
  itemInteractive: {
    backgroundColor: tokens.colorSurfaceInteractiveHover,
  },
  itemSelected: {
    backgroundColor: tokens.colorSurfaceSelected,
  },
  itemDisabled: {
    color: tokens.colorContentTertiary,
    opacity: tokens.opacityDisabled,
  },
  itemText: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  itemIndicator: {
    alignItems: "center",
    color: "currentColor",
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  indicatorSvg: {
    height: "16px",
    strokeWidth: 2,
    width: "16px",
  },
  groupLabel: {
    color: tokens.colorContentTertiary,
    fontFamily: tokens.fontSans,
    fontSize: "11px",
    fontWeight: 500,
    lineHeight: "16px",
    paddingBlock: tokens.space1,
    paddingInline: tokens.space3,
  },
  separator: {
    backgroundColor: tokens.colorBorderTertiary,
    height: tokens.sizeBorderControl,
    marginBlock: tokens.space1,
  },
});
