import * as stylex from "@stylexjs/stylex";
import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  root: {
    backgroundColor: tokens.colorSurfaceCanvas,
    fontFamily: tokens.fontSans,
    maxWidth: "100%",
    overflow: "auto",
    position: "relative",
    userSelect: "none",
  },
  table: {
    borderCollapse: "separate",
    borderSpacing: 0,
    color: tokens.colorContentPrimary,
    fontSize: tokens.typeLabelSize,
    lineHeight: tokens.typeBodyLineHeight,
    tableLayout: "fixed",
  },
  row: {
    backgroundColor: tokens.colorSurfaceCanvas,
    ":hover": { backgroundColor: tokens.colorSurfaceInteractiveHover },
  },
  selectedRow: {
    backgroundColor: tokens.colorSurfaceSelected,
    ":hover": { backgroundColor: tokens.colorSurfaceSelected },
  },
  cell: {
    backgroundColor: "inherit",
    borderBottomColor: `color-mix(in srgb, ${tokens.colorBorderTertiary} 35%, transparent)`,
    borderBottomStyle: "solid",
    borderBottomWidth: tokens.sizeBorderControl,
    borderRightColor: `color-mix(in srgb, ${tokens.colorBorderTertiary} 28%, transparent)`,
    borderRightStyle: "solid",
    borderRightWidth: tokens.sizeBorderControl,
    boxSizing: "border-box",
    height: "48px",
    maxWidth: 0,
    overflow: "hidden",
    paddingBlock: 0,
    paddingInline: tokens.space3,
    position: "relative",
    textAlign: "left",
    verticalAlign: "middle",
    whiteSpace: "nowrap",
    ":focus-visible": {
      outlineColor: tokens.colorFocusRing,
      outlineOffset: "-2px",
      outlineStyle: "solid",
      outlineWidth: "2px",
    },
  },
  head: {
    backgroundColor: tokens.colorSurfaceCanvas,
    boxSizing: "border-box",
    color: tokens.colorContentTertiary,
    fontSize: tokens.typeMetadataSize,
    fontWeight: 400,
    height: "32px",
    maxWidth: 0,
    paddingBlock: 0,
    paddingInline: tokens.space3,
    position: "sticky",
    textAlign: "left",
    top: 0,
    verticalAlign: "middle",
    whiteSpace: "nowrap",
    zIndex: 20,
  },
  lead: { position: "sticky", zIndex: 10 },
  pinnedHead: { position: "sticky", zIndex: 30 },
  center: { paddingInline: 0, textAlign: "center" },
  muted: { color: tokens.colorContentTertiary },
  selectedCell: { backgroundColor: tokens.colorSurfaceSelected },
  focusedCell: { boxShadow: `inset 0 0 0 1px ${tokens.colorFocusRing}` },
  editingCell: {
    backgroundColor: tokens.colorSurfaceCanvas,
    overflow: "visible",
    zIndex: 25,
  },
  headContent: { alignItems: "center", display: "flex", gap: tokens.space2, minWidth: 0 },
  icon: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  sortButton: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": tokens.colorSurfaceInteractiveHover },
    borderRadius: tokens.radiusRounded,
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "inline-flex",
    font: "inherit",
    gap: tokens.space2,
    height: "28px",
    marginLeft: `calc(-1 * ${tokens.space2})`,
    minWidth: 0,
    paddingInline: tokens.space2,
    textAlign: "left",
    ":focus-visible": {
      backgroundColor: tokens.colorSurfaceInteractiveHover,
      outlineColor: tokens.colorFocusRing,
      outlineStyle: "solid",
      outlineWidth: "2px",
    },
  },
  ellipsis: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  resizeHandle: {
    position: "absolute",
    right: 0,
    top: 0,
  },
  editorWrap: {
    alignItems: "center",
    backgroundColor: tokens.colorSurfaceCanvas,
    boxShadow: `inset 0 0 0 2px ${tokens.colorFocusRing}`,
    display: "flex",
    inset: 0,
    paddingInline: tokens.space3,
    position: "absolute",
    userSelect: "text",
  },
  editorWrapInvalid: { boxShadow: `inset 0 0 0 2px ${tokens.colorStatusErrorBorder}` },
  editor: {
    backgroundColor: "transparent",
    borderWidth: 0,
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    flex: 1,
    font: "inherit",
    height: "100%",
    minWidth: 0,
    outline: "none",
    padding: 0,
    userSelect: "text",
    width: "100%",
  },
  editorError: {
    backgroundColor: tokens.colorStatusErrorSurface,
    borderColor: tokens.colorStatusErrorBorder,
    borderRadius: tokens.radiusControl,
    borderStyle: "solid",
    borderWidth: tokens.sizeBorderControl,
    color: tokens.colorStatusErrorContent,
    fontSize: tokens.typeBodySize,
    left: 0,
    paddingBlock: tokens.space2,
    paddingInline: tokens.space3,
    position: "absolute",
    top: "calc(100% + 4px)",
    whiteSpace: "nowrap",
    zIndex: 50,
  },
  error: {
    backgroundColor: tokens.colorSurfaceCanvas,
    bottom: 0,
    color: tokens.colorContentPrimary,
    fontSize: tokens.typeBodySize,
    padding: tokens.space2,
    position: "sticky",
  },
});
