import * as stylex from "@stylexjs/stylex";
import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  root: {
    backgroundColor: tokens.colorSurfaceCanvas,
    borderColor: tokens.colorBorderTertiary,
    borderStyle: "solid",
    borderWidth: tokens.sizeBorderControl,
    fontFamily: tokens.fontSans,
    maxWidth: "100%",
    overflow: "auto",
    position: "relative",
  },
  table: {
    borderCollapse: "separate",
    borderSpacing: 0,
    color: tokens.colorContentPrimary,
    fontSize: tokens.typeBodySize,
    lineHeight: tokens.typeBodyLineHeight,
    tableLayout: "fixed",
  },
  row: {
    backgroundColor: tokens.colorSurfaceCanvas,
    ":hover": { backgroundColor: tokens.colorSurfaceInteractiveHover },
  },
  cell: {
    backgroundColor: "inherit",
    borderBottomColor: tokens.colorBorderTertiary,
    borderBottomStyle: "solid",
    borderBottomWidth: tokens.sizeBorderControl,
    borderRightColor: tokens.colorBorderTertiary,
    borderRightStyle: "solid",
    borderRightWidth: tokens.sizeBorderControl,
    boxSizing: "border-box",
    height: "40px",
    maxWidth: 0,
    overflow: "hidden",
    paddingBlock: 0,
    paddingInline: tokens.space3,
    textAlign: "left",
    verticalAlign: "middle",
    whiteSpace: "nowrap",
    ":focus-visible": {
      outlineColor: tokens.colorFocusRing,
      outlineOffset: "-2px",
      outlineStyle: "solid",
      outlineWidth: "2px",
    },
  },
  head: {
    backgroundColor: tokens.colorSurfaceCanvas,
    borderBottomColor: tokens.colorBorderTertiary,
    borderBottomStyle: "solid",
    borderBottomWidth: tokens.sizeBorderControl,
    borderRightColor: tokens.colorBorderTertiary,
    borderRightStyle: "solid",
    borderRightWidth: tokens.sizeBorderControl,
    boxSizing: "border-box",
    color: tokens.colorContentTertiary,
    fontWeight: 400,
    height: "40px",
    maxWidth: 0,
    paddingBlock: 0,
    paddingInline: tokens.space3,
    position: "sticky",
    textAlign: "left",
    top: 0,
    verticalAlign: "middle",
    whiteSpace: "nowrap",
    zIndex: 20,
  },
  lead: { position: "sticky", zIndex: 10 },
  pinnedHead: { position: "sticky", zIndex: 30 },
  center: { paddingInline: 0, textAlign: "center" },
  muted: { color: tokens.colorContentTertiary },
  selectedCell: { backgroundColor: tokens.colorSurfaceSelected },
  focusedCell: { boxShadow: `inset 0 0 0 1px ${tokens.colorFocusRing}` },
  headContent: { alignItems: "center", display: "flex", gap: tokens.space2, minWidth: 0 },
  icon: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  sortButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "inherit",
    cursor: "pointer",
    display: "inline-flex",
    font: "inherit",
    gap: tokens.space2,
    minWidth: 0,
    padding: 0,
    textAlign: "left",
  },
  ellipsis: {
    display: "block",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  resizeHandle: {
    borderWidth: 0,
    bottom: 0,
    cursor: "col-resize",
    margin: 0,
    position: "absolute",
    right: 0,
    top: 0,
    width: "6px",
    ":hover": { backgroundColor: tokens.colorFocusRing },
    ":focus-visible": { backgroundColor: tokens.colorFocusRing, outline: "none" },
  },
  editorWrap: { height: "100%", marginInline: `-${tokens.space3}` },
  editor: {
    backgroundColor: tokens.colorSurfaceCanvas,
    borderWidth: 0,
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    font: "inherit",
    height: "100%",
    outline: "none",
    paddingInline: tokens.space3,
    width: "100%",
  },
  error: {
    backgroundColor: tokens.colorSurfaceCanvas,
    bottom: 0,
    color: tokens.colorContentPrimary,
    fontSize: tokens.typeBodySize,
    padding: tokens.space2,
    position: "sticky",
  },
});
