// Adapted from HeroUI v3.2.6 (Apache-2.0).
// StyleX owns values and compilation; this adapter only assigns semantic descendant targets.
import { readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { runInNewContext } from "node:vm";
import * as stylex from "@stylexjs/stylex";

const require = createRequire(import.meta.url);
const compilerRequire = createRequire(require.resolve("@stylexjs/unplugin"));
const { transformSync } = compilerRequire("@babel/core");
const babelRequire = createRequire(compilerRequire.resolve("@babel/core"));
const generate = babelRequire("@babel/generator").default;
const stylexPlugin = compilerRequire("@stylexjs/babel-plugin");
const directory = new URL("./", import.meta.url);
const sourceUrl = new URL("typography.styles.ts", directory);
const tokensUrl = new URL("../../tokens.stylex.const.ts", directory);
function compile(source, filename) {
  return transformSync(source, {
    filename,
    ast: true,
    configFile: false,
    babelrc: false,
    plugins: [
      [
        stylexPlugin,
        {
          dev: false,
          useCSSLayers: false,
          unstable_moduleResolution: {
            type: "commonJS",
            rootDir: fileURLToPath(new URL("../../../", directory)),
          },
        },
      ],
    ],
    parserOpts: { plugins: ["typescript"] },
  });
}
const tokenResult = compile(await readFile(tokensUrl, "utf8"), fileURLToPath(tokensUrl));
const result = compile(await readFile(sourceUrl, "utf8"), fileURLToPath(sourceUrl));
const constants = new Map(tokenResult.metadata.stylex.map(([name, rule]) => [name, rule.constVal]));
const compiled = {};
for (const statement of result.ast.program.body) {
  if (
    statement.type !== "ExportNamedDeclaration" ||
    statement.declaration?.type !== "VariableDeclaration"
  )
    continue;
  for (const declaration of statement.declaration.declarations) {
    if (declaration.id.type !== "Identifier" || declaration.init?.type !== "ObjectExpression")
      continue;
    compiled[declaration.id.name] = runInNewContext(`(${generate(declaration.init).code})`);
  }
}
const { typographyTypes, proseElements } = compiled;
const targets = {
  ...Object.fromEntries(
    ["h1", "h2", "h3", "h4", "h5", "h6", "code"].map((tag) => [tag, typographyTypes[tag]]),
  ),
  p: typographyTypes.body,
  ...Object.fromEntries(
    Object.entries(proseElements).map(([tag, value]) => [tag === "link" ? "a" : tag, value]),
  ),
};
const rules = new Map(result.metadata.stylex.map(([name, rule]) => [name, rule]));
const output = [];
for (const [tag, styles] of Object.entries(targets)) {
  for (const name of stylex.props(styles).className.split(" ")) {
    const rule = rules.get(name);
    if (!rule) throw new Error(`Missing compiled Prose rule for ${tag}: ${name}`);
    const target = `:where([data-prose-root]) ${tag}:not(:where([data-prose="off"], [data-prose="off"] *, .not-prose, .not-prose *))`;
    for (const [emitted, selector] of [
      [rule.ltr, target],
      [rule.rtl, `${target}:dir(rtl)`],
    ]) {
      if (!emitted) continue;
      let css = emitted.replace(new RegExp(`(?:\\.${name})+`, "g"), selector);
      css = css.replace(/var\(--([a-z0-9]+)\)/g, (match, key) => constants.get(key) ?? match);
      output.push(css);
    }
  }
}
const css = output
  .join("\n")
  .replaceAll("\\", "\\\\")
  .replaceAll("`", "\\`")
  .replaceAll("${", "\\${");
const artifact = `// Generated by generate-prose.mjs from StyleX typographyTypes and proseElements. Do not edit.\n// HeroUI v3.2.6 adaptation (Apache-2.0); property authority: typography.styles.ts.\nexport const proseCss = \`\n${css}\n\`;\n`;
const destination = new URL("prose.generated.ts", directory);
if (process.argv.includes("--check")) {
  if ((await readFile(destination, "utf8")) !== artifact) {
    throw new Error(
      "Prose CSS is stale; run packages/styles/src/components/typography/generate-prose.mjs",
    );
  }
} else {
  await writeFile(destination, artifact);
}
