import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: {
    "--console-bg": "#1a1a1a",
    "--console-raised": "#222",
    "--console-active": "#242424",
    "--console-line": "#292929",
    "--console-text": "#f2f2f2",
    "--console-secondary": "#b8b8b8",
    "--console-muted": "#898989",
    "--console-accent": "#b9b5ff",
    backgroundColor: "var(--console-bg)",
    color: "var(--console-text)",
    display: "flex",
    flexDirection: "column",
    fontFamily: "var(--font-sans)",
    fontSize: "13px",
    height: "100%",
    minHeight: 0,
    minWidth: 0,
    overflow: "hidden",
    position: "relative",
    width: "100%",
  },
  lightRoot: {
    "--console-bg": "#fafafa",
    "--console-raised": "#f0f0f0",
    "--console-active": "#ebebeb",
    "--console-line": "#e3e3e3",
    "--console-text": "#202020",
    "--console-secondary": "#525252",
    "--console-muted": "#777",
    "--console-accent": "#5952ae",
  },
  header: {
    alignItems: "center",
    backgroundColor: "var(--console-bg)",
    borderBottomColor: "var(--console-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    flex: "0 0 54px",
    height: "54px",
    minWidth: 0,
    paddingInline: "16px",
    position: "relative",
    zIndex: 4,
    "@media (max-width: 720px)": {
      alignItems: "flex-start",
      flexBasis: "90px",
      height: "90px",
      paddingInline: "8px",
    },
  },
  headerLeading: {
    alignItems: "center",
    display: "flex",
    gap: "4px",
    minWidth: 0,
    "@media (max-width: 720px)": { height: "46px" },
  },
  workspaceAnchor: { flex: "none", position: "relative" },
  workspaceTrigger: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: "9px",
    color: "var(--console-text)",
    cursor: "pointer",
    display: "flex",
    gap: "6px",
    height: "32px",
    paddingInline: "7px 3px",
    whiteSpace: "nowrap",
    ":hover": { backgroundColor: "var(--console-raised)" },
  },
  mark: { fontSize: "20px", lineHeight: 1 },
  mobileWorkspaceName: {
    display: "none",
    fontSize: "12px",
    fontWeight: 600,
    maxWidth: "100px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    "@media (max-width: 720px)": { display: "inline" },
  },
  assistantTrigger: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: "9px",
    color: "var(--console-secondary)",
    cursor: "pointer",
    display: "flex",
    flex: "none",
    gap: "7px",
    height: "32px",
    paddingInline: "9px",
    whiteSpace: "nowrap",
    ":hover": { backgroundColor: "var(--console-raised)", color: "var(--console-text)" },
    "@media (max-width: 720px)": { justifyContent: "center", padding: 0, width: "32px" },
  },
  assistantLabel: { "@media (max-width: 720px)": { display: "none" } },
  accentIcon: { color: "var(--console-accent)" },
  divider: {
    backgroundColor: "var(--console-line)",
    flex: "0 0 1px",
    height: "22px",
    marginInline: "5px",
    "@media (max-width: 720px)": { display: "none" },
  },
  tabs: {
    alignItems: "center",
    display: "flex",
    gap: "2px",
    minWidth: 0,
    overflowX: "auto",
    scrollbarWidth: "none",
    "@media (max-width: 720px)": {
      borderTopColor: "var(--console-line)",
      borderTopStyle: "solid",
      borderTopWidth: "1px",
      height: "44px",
      insetBlockStart: "46px",
      insetInline: 0,
      paddingInline: "10px",
      position: "absolute",
    },
  },
  tab: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: "9px",
    color: "var(--console-secondary)",
    cursor: "pointer",
    display: "flex",
    flex: "none",
    gap: "7px",
    height: "32px",
    paddingInline: "10px",
    whiteSpace: "nowrap",
    ":hover": { backgroundColor: "var(--console-raised)", color: "var(--console-text)" },
    "@media (max-width: 720px)": { fontSize: "12px", height: "30px", paddingInline: "9px" },
  },
  activeTab: { backgroundColor: "var(--console-active)", color: "var(--console-text)" },
  searchTrigger: {
    alignItems: "center",
    backgroundColor: "var(--console-raised)",
    borderColor: "var(--console-line)",
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: "9px",
    color: "var(--console-muted)",
    cursor: "pointer",
    display: "flex",
    gap: "9px",
    height: "32px",
    insetInlineStart: "50%",
    paddingInline: "11px",
    position: "absolute",
    transform: "translateX(-50%)",
    width: "220px",
    ":hover": { color: "var(--console-text)" },
    "@media (max-width: 1050px)": {
      insetInlineEnd: "12px",
      insetInlineStart: "auto",
      justifyContent: "center",
      padding: 0,
      transform: "none",
      width: "32px",
    },
    "@media (max-width: 720px)": {
      backgroundColor: "transparent",
      borderWidth: 0,
      height: "32px",
      insetBlockStart: "7px",
      insetInlineEnd: "8px",
    },
  },
  searchLabel: { flex: 1, textAlign: "left", "@media (max-width: 1050px)": { display: "none" } },
  compactSearchTrigger: {
    insetInlineEnd: "12px",
    insetInlineStart: "auto",
    justifyContent: "center",
    padding: 0,
    transform: "none",
    width: "32px",
  },
  compactSearchCopy: { display: "none" },
  shortcut: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--console-muted)",
    fontFamily: "inherit",
    fontSize: "10px",
    "@media (max-width: 1050px)": { display: "none" },
  },
  iconButton: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: "9px",
    color: "var(--console-secondary)",
    cursor: "pointer",
    display: "inline-flex",
    height: "32px",
    justifyContent: "center",
    padding: 0,
    width: "32px",
    ":hover": { backgroundColor: "var(--console-raised)" },
  },
  mobileNavTrigger: { display: "none", "@media (max-width: 720px)": { display: "inline-flex" } },
  body: { display: "flex", flex: 1, minHeight: 0, minWidth: 0, position: "relative" },
  sidebar: {
    backgroundColor: "var(--console-bg)",
    borderInlineEndColor: "var(--console-line)",
    borderInlineEndStyle: "solid",
    borderInlineEndWidth: "1px",
    flex: "0 0 218px",
    overflowX: "hidden",
    overflowY: "auto",
    padding: "12px 12px 18px",
    width: "218px",
    "@media (max-width: 720px)": { display: "none" },
  },
  openMobileSidebar: {
    "@media (max-width: 720px)": {
      boxShadow: "12px 0 30px #0007",
      display: "block",
      insetBlock: 0,
      insetInlineStart: 0,
      position: "absolute",
      width: "min(250px, 82%)",
      zIndex: 3,
    },
  },
  mobileScrim: {
    display: "none",
    "@media (max-width: 720px)": {
      backgroundColor: "#0008",
      borderWidth: 0,
      display: "block",
      inset: 0,
      position: "absolute",
      zIndex: 2,
    },
  },
  sidebarItem: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: "9px",
    color: "var(--console-secondary)",
    cursor: "pointer",
    display: "flex",
    gap: "8px",
    height: "32px",
    overflow: "hidden",
    paddingInline: "9px",
    textAlign: "left",
    whiteSpace: "nowrap",
    width: "100%",
    ":hover": { backgroundColor: "var(--console-raised)", color: "var(--console-text)" },
  },
  sidebarItemLabel: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  activeSidebarItem: { backgroundColor: "var(--console-active)", color: "var(--console-text)" },
  sidebarSection: {
    display: "grid",
    gap: "2px",
    marginBlockStart: "25px",
  },
  firstSidebarSection: { marginBlockStart: "4px" },
  sidebarSectionTitle: {
    color: "var(--console-muted)",
    fontSize: "11px",
    fontWeight: 400,
    lineHeight: "16px",
    margin: "0 9px 8px",
  },
  main: {
    backgroundColor: "var(--console-bg)",
    flex: 1,
    minHeight: 0,
    minWidth: 0,
    overflow: "auto",
    position: "relative",
  },
  workspaceMenu: {
    backgroundColor: "var(--console-bg)",
    borderColor: "var(--console-line)",
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: "10px",
    boxShadow: "0 16px 32px #0008",
    insetBlockStart: "38px",
    insetInlineStart: 0,
    padding: "6px",
    position: "absolute",
    width: "260px",
    zIndex: 10,
  },
  menuCaption: {
    color: "var(--console-muted)",
    display: "block",
    fontSize: "11px",
    padding: "6px 9px 7px",
  },
  workspaceOption: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: "7px",
    color: "var(--console-text)",
    cursor: "pointer",
    display: "flex",
    gap: "10px",
    minHeight: "50px",
    padding: "7px 9px",
    textAlign: "left",
    width: "100%",
    ":hover": { backgroundColor: "var(--console-active)" },
  },
  selectedOption: { backgroundColor: "var(--console-active)" },
  optionIcon: {
    color: "var(--console-accent)",
    fontSize: "17px",
    textAlign: "center",
    width: "20px",
  },
  optionCopy: {
    display: "grid",
    flex: 1,
    gap: "1px",
    minWidth: 0,
  },
  optionTitle: { fontSize: "13px", fontWeight: 550 },
  optionDetail: {
    color: "var(--console-muted)",
    fontSize: "11px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  optionCheck: { color: "var(--console-accent)" },
  assistantDrawer: {
    backgroundColor: "var(--console-bg)",
    borderInlineStartColor: "var(--console-line)",
    borderInlineStartStyle: "solid",
    borderInlineStartWidth: "1px",
    bottom: 0,
    boxShadow: "-12px 0 30px #0005",
    display: "flex",
    flexDirection: "column",
    position: "absolute",
    right: 0,
    top: "54px",
    width: "min(340px, 100%)",
    zIndex: 5,
    "@media (max-width: 720px)": { top: "90px" },
  },
  drawerHeader: {
    alignItems: "center",
    borderBottomColor: "var(--console-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    display: "flex",
    fontWeight: 600,
    height: "48px",
    justifyContent: "space-between",
    paddingInline: "15px",
  },
  drawerTitle: { alignItems: "center", display: "flex", gap: "8px" },
  drawerCopy: { color: "var(--console-secondary)", lineHeight: 1.55, margin: "25px 18px" },
  drawerContext: {
    borderTopColor: "var(--console-line)",
    borderTopStyle: "solid",
    borderTopWidth: "1px",
    color: "var(--console-muted)",
    fontSize: "11px",
    marginTop: "auto",
    padding: "14px 18px",
  },
  searchOverlay: { inset: 0, position: "absolute", zIndex: 8 },
  overlayBackdrop: {
    backgroundColor: "#0009",
    borderWidth: 0,
    inset: 0,
    position: "absolute",
    width: "100%",
  },
  searchDialog: {
    backgroundColor: "var(--console-bg)",
    borderColor: "var(--console-line)",
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: "11px",
    boxShadow: "0 18px 40px #0008",
    left: "50%",
    padding: "7px",
    position: "absolute",
    top: "70px",
    transform: "translateX(-50%)",
    width: "min(450px, calc(100% - 28px))",
  },
  searchField: {
    alignItems: "center",
    borderBottomColor: "var(--console-line)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    color: "var(--console-muted)",
    display: "flex",
    gap: "10px",
    padding: "0 9px 6px",
  },
  searchInput: {
    backgroundColor: "transparent",
    borderWidth: 0,
    color: "var(--console-text)",
    flex: 1,
    fontSize: "13px",
    height: "34px",
    minWidth: 0,
    outline: 0,
  },
  searchResults: { maxHeight: "270px", overflowY: "auto", paddingTop: "5px" },
  searchResult: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: "7px",
    color: "var(--console-text)",
    cursor: "pointer",
    display: "flex",
    justifyContent: "space-between",
    minHeight: "36px",
    paddingInline: "10px",
    textAlign: "left",
    width: "100%",
    ":hover": { backgroundColor: "var(--console-active)" },
  },
  searchResultScope: { color: "var(--console-muted)" },
  emptySearch: { color: "var(--console-muted)", margin: "16px 10px" },
  profilePage: {
    display: "flex",
    height: "100%",
    minHeight: "100%",
    padding: "28px",
    "@media (max-width: 720px)": { padding: "18px" },
  },
  profileContent: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    margin: "auto",
    maxWidth: "600px",
    minHeight: "100%",
    width: "100%",
  },
  profileIntro: {
    marginBottom: "26px",
    textAlign: "center",
  },
  profileTitle: { fontSize: "23px", fontWeight: 550, lineHeight: 1.3, margin: 0 },
  profileDescription: {
    color: "var(--console-muted)",
    fontSize: "12px",
    lineHeight: 1.55,
    margin: "7px 0 0",
  },
  composerDock: { width: "100%" },
  composerSurface: {
    backgroundColor: "var(--console-raised)",
    borderColor: "var(--console-line)",
    borderStyle: "solid",
    borderWidth: "1px",
    borderRadius: "14px",
    boxShadow: "none",
  },
  composer: { gap: "8px", minHeight: "106px", padding: "13px" },
  composerInput: { color: "var(--console-text)", fontSize: "13px", minHeight: "48px" },
  composerToolbar: { minHeight: "27px" },
  composerQuiet: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderRadius: "7px",
    color: "var(--console-muted)",
    cursor: "pointer",
    display: "flex",
    height: "27px",
    justifyContent: "center",
    padding: 0,
    width: "27px",
  },
  sendButton: {
    alignItems: "center",
    backgroundColor: "var(--console-text)",
    borderWidth: 0,
    borderRadius: "9px",
    color: "var(--console-bg)",
    cursor: "pointer",
    display: "flex",
    height: "27px",
    justifyContent: "center",
    padding: 0,
    width: "27px",
    ":disabled": { opacity: 0.35 },
  },
  message: {
    alignSelf: "flex-end",
    backgroundColor: "var(--console-active)",
    borderRadius: "12px",
    marginBottom: "20px",
    maxWidth: "80%",
    padding: "10px 13px",
  },
});
