import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";
import { motion } from "../shared/motion.stylex.js";

export const styles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    maxWidth: "100%",
    width: "220px",
  },
  item: { overflow: "hidden", width: "100%" },
  header: { margin: 0 },
  trigger: {
    "--disclosure-icon-rotation": {
      default: "0deg",
      "[data-open]": "90deg",
    },
    alignItems: "center",
    appearance: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorSurfaceInteractiveHover,
      "[data-visual-state=hover]": tokens.colorSurfaceInteractiveHover,
    },
    borderColor: "transparent",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: 0,
    color: tokens.colorContentSecondary,
    cursor: "pointer",
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: "12px",
    fontWeight: 500,
    gap: "6px",
    height: "28px",
    lineHeight: "14.5px",
    margin: 0,
    outline: {
      default: "none",
      ":focus-visible": `1px solid ${tokens.colorFocusRing}`,
      "[data-visual-state=focus-visible]": `1px solid ${tokens.colorFocusRing}`,
    },
    outlineOffset: "-1px",
    paddingBlock: 0,
    paddingInline: "10px",
    textAlign: "left",
    transitionDuration: motion.durationFast,
    transitionProperty: "background-color, color, opacity",
    transitionTimingFunction: motion.easeHover,
    width: "100%",
    ":disabled": { cursor: "default", opacity: tokens.opacityDisabled },
    "[data-disabled]": { cursor: "default", opacity: tokens.opacityDisabled },
  },
  icon: {
    alignItems: "center",
    color: tokens.colorContentTertiary,
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    marginInlineStart: "auto",
    transform: "rotate(var(--disclosure-icon-rotation, 0deg))",
    transitionDuration: motion.durationFast,
    transitionProperty: "transform",
    transitionTimingFunction: motion.easeHover,
    width: "16px",
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
  panel: {
    boxSizing: "border-box",
    color: tokens.colorContentSecondary,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    height: "var(--accordion-panel-height)",
    lineHeight: "19.5px",
    overflow: "hidden",
    paddingBlock: "8px",
    paddingInlineEnd: "12px",
    paddingInlineStart: "28px",
    transitionDuration: motion.durationBase,
    transitionProperty: "height, padding",
    transitionTimingFunction: motion.easeInOut,
    width: "100%",
    "[data-starting-style]": { height: 0, paddingBlock: 0 },
    "[data-ending-style]": { height: 0, paddingBlock: 0 },
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
});
