import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    width: "220px",
  },
  item: { overflow: "hidden", width: "220px" },
  header: { margin: 0 },
  trigger: {
    alignItems: "center",
    appearance: "none",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorSurfaceInteractiveHover,
      "[data-visual-state=hover]": tokens.colorSurfaceInteractiveHover,
    },
    borderColor: "transparent",
    borderRadius: "8px",
    borderStyle: "solid",
    borderWidth: 0,
    color: tokens.colorContentSecondary,
    cursor: "pointer",
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: "12px",
    fontWeight: 500,
    gap: "2px",
    height: "28px",
    lineHeight: "14.5px",
    margin: 0,
    outline: "none",
    paddingBlock: 0,
    paddingInline: "4px",
    textAlign: "left",
    width: "215px",
    ":focus-visible": { boxShadow: `0 0 0 2px ${tokens.colorFocusRing}` },
    "[data-visual-state=focus-visible]": {
      boxShadow: `0 0 0 2px ${tokens.colorFocusRing}`,
    },
    ":disabled": { cursor: "default", opacity: 0.45 },
  },
  icon: {
    alignItems: "center",
    color: tokens.colorContentSecondary,
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    transform: "rotate(var(--disclosure-icon-rotation, 0deg))",
    transition: "transform 160ms ease",
    width: "16px",
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
  iconGlyph: {
    backgroundColor: "currentColor",
    display: "block",
    height: "5.38548px",
    maskPosition: "center",
    maskRepeat: "no-repeat",
    maskSize: "contain",
    width: "4.7577px",
  },
  panel: {
    color: tokens.colorContentSecondary,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    height: "var(--accordion-panel-height)",
    lineHeight: "19.5px",
    overflow: "hidden",
    paddingBlock: "8px",
    paddingLeft: "20px",
    paddingRight: "12px",
    transition: "height 160ms ease, padding 160ms ease",
    width: "220px",
    "[data-starting-style]": { height: 0, paddingBlock: 0 },
    "[data-ending-style]": { height: 0, paddingBlock: 0 },
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
});
