import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  root: { height: "auto", marginTop: "24px", width: "100%" },
  heading: {
    alignItems: "center",
    display: "flex",
    height: "28px",
    justifyContent: "space-between",
    width: "100%",
    "@media (max-width: 560px)": { alignItems: "flex-start", height: "auto" },
  },
  title: {
    color: "var(--color-content-primary)",
    fontSize: "16px",
    fontWeight: 600,
    lineHeight: "24px",
    margin: 0,
  },
  actions: {
    alignItems: "center",
    display: "flex",
    flex: "0 0 auto",
    gap: "8px",
    height: "28px",
    justifyContent: "flex-end",
    marginLeft: "auto",
    width: "auto",
    "@media (max-width: 560px)": { flexWrap: "wrap", height: "auto" },
  },
  body: {
    display: "grid",
    gap: "16px",
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 360px)",
    height: "256px",
    marginTop: "12px",
    width: "100%",
    "@media (max-width: 1100px)": { gridTemplateColumns: "minmax(0, 1fr)", height: "auto" },
  },
  dataBody: { gridTemplateColumns: "minmax(0, 1fr)", height: "auto" },
  dataBodyWithControls: {
    gridTemplateColumns: "minmax(0, 1fr) minmax(0, 320px)",
    "@media (max-width: 1100px)": { gridTemplateColumns: "minmax(0, 1fr)" },
  },
  templateBody: {
    gridTemplateColumns: "minmax(0, 1fr)",
    gridTemplateRows: "548px 200px",
    height: "764px",
    "@media (max-width: 1100px)": { gridTemplateRows: "auto", height: "auto" },
  },
  sidebarBody: { height: "790px" },
  commandMenuBody: { height: "420px" },
  stage: {
    backgroundColor: "var(--color-surface-canvas)",
    border: 0,
    borderRadius: "8px",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-translucent)",
    height: "256px",
    overflow: "hidden",
    padding: "14px 16px",
    width: "100%",
    "@media (max-width: 560px)": { padding: "12px" },
  },
  dataStage: {
    height: "auto",
    minWidth: 0,
    overflowX: "auto",
    paddingBlock: "18px 20px",
  },
  templateStage: { height: "548px", "@media (max-width: 1100px)": { height: "auto" } },
  sidebarStage: { height: "790px" },
  commandMenuStage: { height: "420px" },
  inspector: {
    alignItems: "stretch",
    backgroundColor: "var(--color-surface-translucent)",
    border: 0,
    borderRadius: "8px",
    boxShadow: "inset 0 0 0 0.5px var(--color-border-translucent)",
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    height: "256px",
    overflow: "hidden",
    padding: "12px 16px",
    width: "100%",
    "@media (max-width: 1100px)": {
      height: "fit-content",
      minHeight: 0,
    },
  },
  dataInspector: { height: "fit-content", minHeight: 0 },
  templateInspector: { height: "200px", "@media (max-width: 1100px)": { height: "auto" } },
  sidebarInspector: {
    height: "790px",
    "@media (max-width: 1100px)": { height: "fit-content" },
  },
  commandMenuInspector: { height: "fit-content", minHeight: 0 },
});
