import { playwright } from "@vitest/browser-playwright";
import stylex from "@stylexjs/unplugin/vite";
import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: { dedupe: ["react", "react-dom"] },
  // Docs TSX intentionally preserves JSX for Next; this browser harness must lower it too.
  oxc: { jsx: { runtime: "automatic" } },
  optimizeDeps: {
    include: [
      "@base-ui/react/accordion",
      "@base-ui/react/alert-dialog",
      "@base-ui/react/avatar",
      "@base-ui/react/button",
      "@base-ui/react/checkbox",
      "@base-ui/react/checkbox-group",
      "@base-ui/react/collapsible",
      "@base-ui/react/combobox",
      "@base-ui/react/dialog",
      "@base-ui/react/direction-provider",
      "@base-ui/react/drawer",
      "@base-ui/react/field",
      "@base-ui/react/fieldset",
      "@base-ui/react/form",
      "@base-ui/react/input",
      "@base-ui/react/menu",
      "@base-ui/react/merge-props",
      "@base-ui/react/meter",
      "@base-ui/react/number-field",
      "@base-ui/react/otp-field",
      "@base-ui/react/popover",
      "@base-ui/react/progress",
      "@base-ui/react/radio",
      "@base-ui/react/radio-group",
      "@base-ui/react/select",
      "@base-ui/react/slider",
      "@base-ui/react/switch",
      "@base-ui/react/tabs",
      "@base-ui/react/toast",
      "@base-ui/react/toggle",
      "@base-ui/react/toggle-group",
      "@base-ui/react/toolbar",
      "@base-ui/react/tooltip",
      "@base-ui/react/use-render",
      "react-aria",
      "react-aria-components",
      "react-aria-components/Button",
      "react-aria-components/Calendar",
      "react-aria-components/ColorArea",
      "react-aria-components/ColorField",
      "react-aria-components/ColorPicker",
      "react-aria-components/ColorSlider",
      "react-aria-components/ColorSwatch",
      "react-aria-components/ColorSwatchPicker",
      "react-aria-components/DateField",
      "react-aria-components/DatePicker",
      "react-aria-components/DateRangePicker",
      "react-aria-components/Dialog",
      "react-aria-components/Input",
      "react-aria-components/Popover",
      "react-aria-components/RangeCalendar",
      "react-aria-components/TimeField",
    ],
  },
  plugins: [
    stylex({
      devMode: "full",
      useCSSLayers: false,
      // Lightning CSS Features.DirSelector: preserve dir, not a language approximation.
      lightningcssOptions: { exclude: 4 },
    }),
  ],
  test: {
    include: ["src/**/*.test.tsx"],
    setupFiles: ["src/test-setup.ts"],
    browser: {
      enabled: true,
      headless: true,
      provider: playwright(),
      instances: [{ browser: "chromium" }],
      viewport: { width: 1280, height: 900 },
      fileParallelism: false,
    },
  },
});
