import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

const darkTheme = ':where([data-theme="dark"] *)';

export const checkboxState = stylex.defineVars({
  focus: "transparent",
  pressed: "transparent",
});

export const checkboxColor = stylex.defineVars({
  border: "#d4d4d4",
  content: "#000000",
  inverse: "#ffffff",
  tertiary: "#707172",
});

export const styles = stylex.create({
  root: {
    [checkboxColor.border]: "#d4d4d4",
    [checkboxColor.content]: "#000000",
    [checkboxColor.inverse]: "#ffffff",
    [checkboxColor.tertiary]: "#707172",
    [checkboxState.focus]: {
      default: null,
      ":focus-visible": tokens.colorFocusRing,
      '[data-visual-state="focus-visible"]': tokens.colorFocusRing,
    },
    [checkboxState.pressed]: {
      default: null,
      ":active": tokens.colorInteractionPressedOverlay,
      '[data-visual-state="pressed"]': tokens.colorInteractionPressedOverlay,
    },
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    boxSizing: "border-box",
    color: {
      default: checkboxColor.content,
      "[data-disabled]": checkboxColor.tertiary,
    },
    cursor: { default: "pointer", "[data-disabled]": "default" },
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    gap: tokens.space2,
    height: "28px",
    lineHeight: "16px",
    outline: "none",
    paddingBlock: 0,
    paddingLeft: "3px",
    paddingRight: 0,
    position: "relative",
    transitionDuration: "80ms",
    transitionProperty: "color, opacity",
    transitionTimingFunction: "ease-out",
    userSelect: "none",
    whiteSpace: "nowrap",
    [darkTheme]: {
      [checkboxColor.border]: "#333333",
      [checkboxColor.content]: "#ffffff",
      [checkboxColor.inverse]: "#000000",
    },
  },
  indicator: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      "[data-checked]": checkboxColor.content,
      "[data-indeterminate]": checkboxColor.content,
      "[data-disabled][data-checked]": checkboxColor.tertiary,
      "[data-disabled][data-indeterminate]": checkboxColor.tertiary,
    },
    borderColor: {
      default: checkboxColor.border,
      "[data-disabled]": checkboxColor.tertiary,
      "[data-checked]": "transparent",
      "[data-indeterminate]": "transparent",
    },
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: { default: "1px", "[data-checked]": 0, "[data-indeterminate]": 0 },
    boxSizing: "border-box",
    color: { default: checkboxColor.inverse, "[data-disabled]": checkboxColor.tertiary },
    display: "inline-flex",
    flexShrink: 0,
    height: "14px",
    justifyContent: "center",
    opacity: {
      default: 1,
      "[data-checked]": 0.9,
      "[data-indeterminate]": 0.9,
      "[data-disabled]": 0.5,
      "[data-disabled][data-checked]": 0.45,
      "[data-disabled][data-indeterminate]": 0.45,
    },
    position: "relative",
    transitionDuration: "80ms",
    transitionProperty: "background-color, border-color, border-width, opacity",
    transitionTimingFunction: "ease-out",
    width: "14px",
  },
  checkedMark: {
    "::before": {
      backgroundColor: "currentColor",
      borderRadius: "999px",
      content: "''",
      height: "1.7px",
      left: "3px",
      position: "absolute",
      top: "6.15px",
      transform: "rotate(45deg)",
      transformOrigin: "0.85px 50%",
      width: "4.67px",
    },
    "::after": {
      backgroundColor: "currentColor",
      borderRadius: "999px",
      content: "''",
      height: "1.7px",
      left: "5.1px",
      position: "absolute",
      top: "8.25px",
      transform: "rotate(-45deg)",
      transformOrigin: "0.85px 50%",
      width: "7.64px",
    },
  },
  indeterminateMark: {
    "::after": {
      backgroundColor: "currentColor",
      borderRadius: "999px",
      content: "''",
      height: "1.7px",
      left: "3.35px",
      position: "absolute",
      top: "6.15px",
      width: "7.3px",
    },
  },
  disabledMark: {
    "::before": {
      display: "none",
    },
    "::after": {
      display: "none",
    },
  },
  pressedLayer: {
    backgroundColor: checkboxState.pressed,
    borderRadius: "3px",
    height: "14px",
    left: "-4px",
    pointerEvents: "none",
    position: "absolute",
    top: "-1px",
    width: "14px",
  },
  focusLayer: {
    borderColor: checkboxState.focus,
    borderRadius: "5px",
    borderStyle: "solid",
    borderWidth: "1px",
    inset: "-3px",
    pointerEvents: "none",
    position: "absolute",
  },
  label: {
    color: "inherit",
    display: "inline-block",
    font: "inherit",
    lineHeight: "16px",
  },
});
