import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const checkboxState = stylex.defineVars({
  focus: "transparent",
});

export const styles = stylex.create({
  root: {
    [checkboxState.focus]: {
      default: null,
      ":focus-visible": tokens.colorFocusRing,
      '[data-visual-state="focus-visible"]': tokens.colorFocusRing,
    },
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    boxSizing: "border-box",
    color: {
      default: tokens.colorContentPrimary,
      "[data-disabled]": tokens.colorContentTertiary,
    },
    cursor: { default: "pointer", "[data-disabled]": "default" },
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    gap: tokens.space2,
    height: "28px",
    lineHeight: "16px",
    outline: "none",
    paddingBlock: 0,
    paddingLeft: "3px",
    paddingRight: 0,
    position: "relative",
    transitionDuration: "80ms",
    transitionProperty: "color, opacity",
    transitionTimingFunction: "ease-out",
    userSelect: "none",
    whiteSpace: "nowrap",
  },
  indicator: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      "[data-checked]": tokens.colorContentPrimary,
      "[data-indeterminate]": tokens.colorContentPrimary,
      "[data-disabled][data-checked]": tokens.colorContentTertiary,
      "[data-disabled][data-indeterminate]": tokens.colorContentTertiary,
    },
    borderColor: {
      default: tokens.colorBorderSecondary,
      "[data-disabled]": tokens.colorContentTertiary,
      "[data-checked]": "transparent",
      "[data-indeterminate]": "transparent",
    },
    borderRadius: "3px",
    borderStyle: "solid",
    borderWidth: 0,
    boxSizing: "border-box",
    boxShadow: {
      default: `inset 0 0 0 1px ${tokens.colorBorderSecondary}`,
      "[data-checked]": "none",
      "[data-indeterminate]": "none",
      "[data-disabled]": `inset 0 0 0 1px ${tokens.colorContentTertiary}`,
      "[data-disabled][data-checked]": "none",
      "[data-disabled][data-indeterminate]": "none",
    },
    color: { default: tokens.colorContentInverse, "[data-disabled]": tokens.colorContentTertiary },
    display: "inline-flex",
    flexShrink: 0,
    height: "14px",
    justifyContent: "center",
    opacity: {
      default: 1,
      "[data-checked]": 0.9,
      "[data-indeterminate]": 0.9,
      "[data-disabled]": 0.5,
      "[data-disabled][data-checked]": 0.45,
      "[data-disabled][data-indeterminate]": 0.45,
    },
    position: "relative",
    transitionDuration: "80ms",
    transitionProperty: "background-color, box-shadow, opacity",
    transitionTimingFunction: "ease-out",
    width: "14px",
  },
  checkedMark: {
    "::before": {
      backgroundColor: "currentColor",
      borderRadius: "999px",
      content: "''",
      height: "1.7px",
      left: "3px",
      position: "absolute",
      top: "6.15px",
      transform: "rotate(45deg)",
      transformOrigin: "0.85px 50%",
      width: "4.67px",
    },
    "::after": {
      backgroundColor: "currentColor",
      borderRadius: "999px",
      content: "''",
      height: "1.7px",
      left: "5.1px",
      position: "absolute",
      top: "8.25px",
      transform: "rotate(-45deg)",
      transformOrigin: "0.85px 50%",
      width: "7.64px",
    },
  },
  indeterminateMark: {
    "::after": {
      backgroundColor: "currentColor",
      borderRadius: "999px",
      content: "''",
      height: "1.7px",
      left: "3.35px",
      position: "absolute",
      top: "6.15px",
      width: "7.3px",
    },
  },
  disabledMark: {
    "::before": {
      display: "none",
    },
    "::after": {
      display: "none",
    },
  },
  focusLayer: {
    borderRadius: "5px",
    height: "18px",
    left: "1px",
    outlineColor: checkboxState.focus,
    outlineStyle: "solid",
    outlineWidth: "1px",
    pointerEvents: "none",
    position: "absolute",
    top: "5px",
    width: "18px",
  },
  label: {
    color: "inherit",
    display: "inline-block",
    font: "inherit",
    lineHeight: "16px",
  },
});
