import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const checkboxState = stylex.defineVars({
  focus: "transparent",
  pressed: "transparent",
});

export const styles = stylex.create({
  root: {
    [checkboxState.focus]: {
      default: null,
      ":focus-visible": tokens.colorFocusRing,
      '[data-visual-state="focus-visible"]': tokens.colorFocusRing,
    },
    [checkboxState.pressed]: {
      default: null,
      ":active": tokens.colorInteractionPressedOverlay,
      '[data-visual-state="pressed"]': tokens.colorInteractionPressedOverlay,
    },
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    boxSizing: "border-box",
    color: {
      default: tokens.colorContentPrimary,
      "[data-disabled]": tokens.colorContentTertiary,
    },
    cursor: { default: "pointer", "[data-disabled]": "default" },
    display: "inline-flex",
    flexShrink: 0,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    gap: tokens.space2,
    height: "28px",
    lineHeight: "16px",
    outline: "none",
    paddingBlock: 0,
    paddingLeft: "3px",
    paddingRight: 0,
    position: "relative",
    transitionDuration: "80ms",
    transitionProperty: "color, opacity",
    transitionTimingFunction: "ease-out",
    userSelect: "none",
    whiteSpace: "nowrap",
  },
  indicator: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      "[data-checked]": tokens.colorContentPrimary,
      "[data-indeterminate]": tokens.colorContentPrimary,
      "[data-disabled][data-checked]": tokens.colorContentTertiary,
      "[data-disabled][data-indeterminate]": tokens.colorContentTertiary,
    },
    borderRadius: "3px",
    boxShadow: {
      default: `inset 0 0 0 1px ${tokens.colorBorderSecondary}`,
      "[data-checked]": "none",
      "[data-indeterminate]": "none",
      "[data-disabled]": `inset 0 0 0 1px ${tokens.colorContentTertiary}`,
      "[data-disabled][data-checked]": "none",
      "[data-disabled][data-indeterminate]": "none",
    },
    boxSizing: "border-box",
    color: { default: tokens.colorContentInverse, "[data-disabled]": tokens.colorContentTertiary },
    display: "inline-flex",
    flexShrink: 0,
    height: "14px",
    justifyContent: "center",
    opacity: {
      default: 1,
      "[data-checked]": 0.9,
      "[data-indeterminate]": 0.9,
      "[data-disabled]": 0.5,
      "[data-disabled][data-checked]": 0.45,
      "[data-disabled][data-indeterminate]": 0.45,
    },
    position: "relative",
    transitionDuration: "80ms",
    transitionProperty: "background-color, box-shadow, opacity",
    transitionTimingFunction: "ease-out",
    width: "14px",
  },
  checkedMark: {
    "::after": {
      borderColor: "currentColor",
      borderStyle: "solid",
      borderWidth: "0 2px 2px 0",
      content: "''",
      display: "block",
      height: "7px",
      transform: "translateY(-1px) rotate(45deg)",
      width: "3.5px",
    },
  },
  indeterminateMark: {
    "::after": {
      backgroundColor: "currentColor",
      borderRadius: "1px",
      content: "''",
      display: "block",
      height: "2px",
      width: "6px",
    },
  },
  disabledMark: {
    "::after": {
      display: "none",
    },
  },
  pressedLayer: {
    backgroundColor: checkboxState.pressed,
    borderRadius: "3px",
    inset: 0,
    pointerEvents: "none",
    position: "absolute",
  },
  focusLayer: {
    borderColor: checkboxState.focus,
    borderRadius: "5px",
    borderStyle: "solid",
    borderWidth: "1px",
    inset: "-2px",
    pointerEvents: "none",
    position: "absolute",
  },
  label: {
    color: "inherit",
    display: "inline-block",
    font: "inherit",
    lineHeight: "16px",
  },
});
