// Adapted from HeroUI v3.2.6 drawer examples (Apache-2.0).
import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  row: { display: "flex", flexWrap: "wrap", gap: 16 },
  form: { display: "flex", flexDirection: "column", gap: 16 },
  cornerClose: { position: "absolute", top: 16, insetInlineEnd: 16 },
  paragraph: { marginBottom: 12 },
  navigation: { display: "flex", flexDirection: "column", gap: 4 },
  navButton: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    borderWidth: 0,
    borderRadius: 12,
    paddingInline: 12,
    paddingBlock: 10,
    fontSize: 14,
    color: "var(--foreground)",
    backgroundColor: { default: "transparent", ":hover": "var(--default)" },
    cursor: "pointer",
    transitionProperty: "background-color",
    transitionDuration: "150ms",
  },
  icon: { width: 20, height: 20, color: "var(--muted)" },
  filters: {
    borderLeftWidth: 1,
    borderLeftStyle: "solid",
    borderLeftColor: "color-mix(in oklab, var(--border) 80%, transparent)",
    backgroundColor: "var(--surface)",
  },
  muted: { fontSize: 14, color: "var(--muted)" },
  fullWidth: { width: "100%" },
  controlled: { display: "flex", flexDirection: "column", gap: 32, maxWidth: 448 },
  section: { display: "flex", flexDirection: "column", gap: 12 },
  heading: { fontSize: 18, fontWeight: 600, color: "var(--foreground)" },
  explanation: { fontSize: 14, lineHeight: 1.625, textWrap: "pretty", color: "var(--muted)" },
  stateCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 12,
    borderRadius: 16,
    backgroundColor: "var(--surface)",
    padding: 16,
    boxShadow: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
  },
  status: { fontSize: 12, color: "var(--muted)" },
  statusValue: { fontFamily: "monospace", fontWeight: 500, color: "var(--foreground)" },
  actions: { display: "flex", gap: 8 },
});
