// Adapted from HeroUI v3.2.6 (e385ac2), Apache-2.0.
import * as stylex from "@stylexjs/stylex";
import { tokens } from "../../tokens.stylex.const.js";

export const modalStyles = stylex.create({
  trigger: {
    display: "inline-block",
    cursor: tokens.cursorInteractive,
    outline: "none",
    transitionProperty: "transform, background-color, box-shadow",
    transitionDuration: {
      default: "250ms, 150ms, 150ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionTimingFunction: tokens.easeOutQuart,
    transform: { default: "scale(1)", ":active": "scale(.97)" },
    opacity: {
      default: 1,
      ":disabled": tokens.disabledOpacity,
      ':is([aria-disabled="true"])': tokens.disabledOpacity,
    },
    boxShadow: {
      default: "none",
      ":focus-visible": "0 0 0 2px var(--background), 0 0 0 4px var(--focus)",
    },
  },
  backdrop: {
    position: "fixed",
    inset: 0,
    zIndex: tokens.zIndexOverlay,
    backgroundColor: tokens.backdrop,
    opacity: { default: 1, ":is([data-starting-style],[data-ending-style])": 0 },
    transitionProperty: "opacity",
    transitionDuration: {
      default: "150ms",
      ":is([data-ending-style])": "100ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
  },
  viewport: {
    boxSizing: "border-box",
    position: "fixed",
    inset: 0,
    zIndex: tokens.zIndexOverlay,
    display: "flex",
    alignItems: {
      default: "safe flex-end",
      "@media (min-width: 640px)": {
        default: "safe center",
        ':has([data-placement="top"])': "flex-start",
        ':has([data-placement="bottom"])': "safe flex-end",
      },
      ':has([data-placement="center"])': "safe center",
      ':has([data-placement="top"])': "flex-start",
      ':has([data-placement="bottom"])': "safe flex-end",
    },
    justifyContent: "center",
    padding: {
      default: 16,
      "@media (min-width: 640px)": { default: 40, ':has([data-size="full"])': 0 },
      ':has([data-size="full"])': 0,
    },
    overflowY: "auto",
    height: "var(--visual-viewport-height, 100dvh)",
  },
  popup: {
    boxSizing: "border-box",
    position: "relative",
    display: "flex",
    flexDirection: "column",
    width: "100%",
    maxWidth: 448,
    maxHeight: "100%",
    padding: 24,
    backgroundColor: tokens.overlay,
    color: tokens.overlayForeground,
    borderRadius: "min(32px, var(--radius-3xl))",
    boxShadow: tokens.shadowOverlay,
    outline: "none",
    minHeight: 0,
    opacity: { default: 1, ":is([data-starting-style],[data-ending-style])": 0 },
    transform: {
      default: "scale(1)",
      ":is([data-starting-style])": "scale(1.05)",
      ":is([data-ending-style])": "scale(.95)",
    },
    transitionProperty: "opacity, transform",
    transitionDuration: {
      default: "250ms",
      ":is([data-ending-style])": "100ms",
      "@media (prefers-reduced-motion: reduce)": "0ms",
    },
    transitionTimingFunction: tokens.easeOutQuad,
  },
  header: { display: "flex", flexDirection: "column", gap: 12 },
  title: { margin: 0, fontSize: 16, fontWeight: 500, color: tokens.foreground },
  description: { margin: 0, fontSize: 14, lineHeight: 1.43, color: tokens.muted },
  body: {
    minHeight: 0,
    flexGrow: 1,
    overflowY: "auto",
    overscrollBehavior: "contain",
    marginTop: 8,
    marginInline: -3,
    padding: 3,
    fontSize: 14,
    lineHeight: 1.43,
    color: tokens.muted,
  },
  footer: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 8,
    marginTop: 20,
  },
  icon: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
    flexShrink: 0,
    userSelect: "none",
    borderRadius: tokens.radius3xl,
  },
  close: { position: "absolute", insetInlineEnd: 16, top: 16, cursor: tokens.cursorInteractive },
  xs: { maxWidth: 320 },
  sm: { maxWidth: 384 },
  md: { maxWidth: 448 },
  lg: { maxWidth: 512 },
  cover: { maxWidth: "100%", height: "100%", minHeight: "100%" },
  full: {
    maxWidth: "100%",
    height: "100%",
    minHeight: "100%",
    borderRadius: 0,
    boxShadow: "none",
    transform: "none",
  },
  inside: { maxHeight: "100%", overflow: "clip" },
  outside: { maxHeight: "none", flexShrink: 0, height: "auto" },
  bodyOutside: { overflowY: "visible" },
  transparent: { backgroundColor: "transparent" },
  opaque: { backgroundColor: tokens.backdrop },
  blur: { backgroundColor: tokens.backdrop, backdropFilter: "blur(12px)" },
});
