import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  root: {
    borderRadius: tokens.radiusRounded,
    display: "inline-flex",
    flexShrink: 0,
    overflow: "hidden",
    position: "relative",
    verticalAlign: "middle",
  },
  compact: { height: "18px", width: "18px" },
  default: { height: "24px", width: "24px" },
  large: { height: "32px", width: "32px" },
  xlarge: { height: "40px", width: "40px" },
  image: {
    borderRadius: "inherit",
    height: "100%",
    objectFit: "cover",
    width: "100%",
  },
  fallback: {
    alignItems: "center",
    backgroundColor: tokens.colorSurfaceOverlayHover,
    borderRadius: "inherit",
    color: tokens.colorContentPrimary,
    display: "flex",
    fontFamily: tokens.fontSans,
    fontWeight: 500,
    height: "100%",
    justifyContent: "center",
    lineHeight: 1,
    width: "100%",
  },
  fallbackCompact: { fontSize: "9px" },
  fallbackDefault: { fontSize: "9.12px" },
  fallbackLarge: { fontSize: "12.16px" },
  fallbackXlarge: { fontSize: "15.2px" },
  status: {
    borderColor: tokens.colorSurfaceCanvas,
    borderRadius: tokens.radiusRounded,
    borderStyle: "solid",
    borderWidth: "2px",
    boxSizing: "border-box",
    display: "inline-flex",
    flexShrink: 0,
  },
  statusAttached: {
    bottom: "-4px",
    position: "absolute",
    right: "-4px",
    zIndex: 1,
  },
  statusSmall: { height: "10px", width: "10px" },
  statusDefault: { height: "12px", width: "12px" },
  online: { backgroundColor: tokens.colorStatusPresenceOnline },
  away: { backgroundColor: tokens.colorStatusPresenceAway },
  busy: { backgroundColor: tokens.colorStatusPresenceBusy },
  offline: { backgroundColor: tokens.colorStatusPresenceOffline },
  group: { alignItems: "center", display: "inline-flex" },
  groupItem: {
    borderRadius: tokens.radiusRounded,
    boxShadow: `0 0 0 1.5px ${tokens.colorSurfaceCanvas}`,
    display: "inline-flex",
    marginLeft: "-6px",
  },
  groupFirst: { marginLeft: 0 },
  visuallyHidden: {
    clip: "rect(0 0 0 0)",
    clipPath: "inset(50%)",
    height: "1px",
    overflow: "hidden",
    position: "absolute",
    whiteSpace: "nowrap",
    width: "1px",
  },
});
