import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";
import { motion } from "../shared/motion.stylex.js";

export const styles = stylex.create({
  panel: {
    backgroundColor: tokens.colorSurfaceSidebar,
    boxSizing: "border-box",
    color: tokens.colorContentSecondary,
    display: { default: "flex", "[hidden]": "none" },
    flexDirection: "column",
    fontFamily: tokens.fontSans,
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
    paddingBlock: "16px 10px",
    width: tokens.sizeSidebar,
  },
  header: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: "4px",
    height: "28px",
    marginBottom: "17px",
    paddingInline: "12px",
  },
  workspace: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "10px",
    color: tokens.colorContentPrimary,
    cursor: "pointer",
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: tokens.typeBodySize,
    fontWeight: 500,
    gap: "6px",
    height: "28px",
    minWidth: 0,
    outline: { default: "none", ":focus-visible": `1px solid ${tokens.colorFocusRing}` },
    outlineOffset: "-1px",
    paddingInline: "5px 9px",
    transitionDuration: motion.durationFast,
    transitionProperty: "background-color, color",
    transitionTimingFunction: motion.easeHover,
  },
  workspaceMark: {
    alignItems: "center",
    backgroundColor: tokens.colorSurfaceSelected,
    borderRadius: "6px",
    color: tokens.colorContentPrimary,
    display: "inline-flex",
    flexShrink: 0,
    fontSize: "8px",
    height: "20px",
    justifyContent: "center",
    lineHeight: "10px",
    width: "20px",
  },
  workspaceLabel: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  workspaceChevron: { color: tokens.colorContentTertiary, display: "inline-flex", flexShrink: 0 },
  headerSpacer: { flex: 1 },
  content: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: 0,
    overflowY: "auto",
    paddingInline: "12px",
    scrollbarWidth: "none",
  },
  footer: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    height: "24px",
    marginTop: "auto",
    paddingInline: "10px",
  },
  menu: {
    display: "flex",
    flexDirection: "column",
    gap: "1px",
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  menuItem: { listStyle: "none", margin: 0, padding: 0 },
  item: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": tokens.colorSidebarItemHover },
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: tokens.radiusRow,
    color: tokens.colorContentSecondary,
    cursor: "pointer",
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: tokens.typeBodySize,
    fontWeight: 500,
    gap: "6px",
    minHeight: tokens.sizeNavigationRow,
    lineHeight: tokens.typeBodyLineHeight,
    outline: { default: "none", ":focus-visible": `1px solid ${tokens.colorFocusRing}` },
    outlineOffset: "-1px",
    paddingInline: "10px 9px",
    textAlign: "left",
    textDecoration: "none",
    transitionDuration: motion.durationFast,
    transitionProperty: "background-color, color",
    transitionTimingFunction: motion.easeHover,
    width: "100%",
  },
  compactItem: {
    borderRadius: tokens.radiusNavigation,
    color: tokens.colorSidebarItemText,
    flex: "0 0 32px",
    fontSize: tokens.typeLabelSize,
    fontWeight: 400,
    gap: tokens.spaceInlineIconGap,
    height: "32px",
    lineHeight: tokens.typeLabelLineHeight,
    minHeight: "32px",
    paddingInline: "9px",
  },
  nestedItem: { paddingInline: "6px 9px" },
  selectedItem: {
    backgroundColor: {
      default: tokens.colorSidebarItemActive,
      ":hover": tokens.colorSidebarItemActive,
    },
    color: tokens.colorContentPrimary,
  },
  icon: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  nestedIcon: { height: "14px", width: "14px" },
  compactIcon: { height: "14px", width: "14px" },
  label: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  badge: { color: tokens.colorContentTertiary, flexShrink: 0, fontSize: tokens.typeMetadataSize },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: tokens.spaceHalf,
    marginTop: tokens.spaceGroupSectionGap,
  },
  sectionHeader: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.colorSidebarItemHover,
    },
    borderRadius: tokens.radiusRow,
    display: "flex",
    height: "28px",
    paddingInline: "5px 2px",
    position: "relative",
    transitionDuration: motion.durationFast,
    transitionProperty: "background-color",
    transitionTimingFunction: motion.easeHover,
  },
  sectionLabel: {
    color: tokens.colorContentSecondary,
    fontSize: tokens.typeMetadataSize,
    fontWeight: 500,
    lineHeight: "14.5px",
  },
  sectionTrigger: { backgroundColor: "transparent" },
  sectionAction: { position: "absolute", right: "2px" },
  sectionContent: {
    margin: "-8px -12px -8px -20px",
  },
  submenu: {
    display: "flex",
    flexDirection: "column",
    gap: "1px",
    listStyle: "none",
    margin: 0,
    padding: "0 0 0 19px",
  },
});
