import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  panel: {
    backgroundColor: tokens.colorSurfaceSidebar,
    boxSizing: "border-box",
    color: tokens.colorContentSecondary,
    display: "flex",
    flexDirection: "column",
    fontFamily: tokens.fontSans,
    height: "100%",
    minHeight: 0,
    overflow: "hidden",
    paddingBlock: "16px 10px",
    width: tokens.sizeSidebar,
  },
  header: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    gap: "4px",
    height: "28px",
    marginBottom: "17px",
    paddingInline: "12px",
  },
  workspace: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: "10px",
    color: tokens.colorContentPrimary,
    cursor: "pointer",
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 500,
    gap: "6px",
    height: "28px",
    minWidth: 0,
    paddingInline: "5px 9px",
  },
  workspaceMark: {
    alignItems: "center",
    backgroundColor: "#adab2e",
    borderRadius: "6px",
    color: "#fff",
    display: "inline-flex",
    flexShrink: 0,
    fontSize: "8px",
    height: "20px",
    justifyContent: "center",
    lineHeight: "10px",
    width: "20px",
  },
  workspaceLabel: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  workspaceChevron: { color: tokens.colorContentTertiary, display: "inline-flex", flexShrink: 0 },
  headerSpacer: { flex: 1 },
  content: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minHeight: 0,
    overflowY: "auto",
    paddingInline: "12px",
    scrollbarWidth: "none",
  },
  footer: {
    alignItems: "center",
    display: "flex",
    flexShrink: 0,
    height: "24px",
    marginTop: "auto",
    paddingInline: "10px",
  },
  menu: { display: "flex", flexDirection: "column", listStyle: "none", margin: 0, padding: 0 },
  menuItem: { listStyle: "none", margin: 0, padding: 0 },
  item: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": tokens.colorSidebarItemHover },
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: tokens.radiusControl,
    color: tokens.colorContentSecondary,
    cursor: "pointer",
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 500,
    gap: "6px",
    height: tokens.sizeControlCompact,
    lineHeight: "19.5px",
    outline: { default: "none", ":focus-visible": `1px solid ${tokens.colorFocusRing}` },
    outlineOffset: "1px",
    paddingInline: "10px 9px",
    textAlign: "left",
    textDecoration: "none",
    width: "100%",
  },
  nestedItem: { paddingInline: "6px 9px" },
  selectedItem: {
    backgroundColor: {
      default: tokens.colorSidebarItemActive,
      ":hover": tokens.colorSidebarItemActive,
    },
    color: tokens.colorContentPrimary,
  },
  icon: {
    alignItems: "center",
    display: "inline-flex",
    flexShrink: 0,
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  nestedIcon: { height: "14px", width: "14px" },
  label: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  badge: { color: tokens.colorContentTertiary, flexShrink: 0, fontSize: "11px" },
  section: { display: "flex", flexDirection: "column", marginTop: "12px" },
  sectionHeader: {
    alignItems: "center",
    display: "flex",
    height: "28px",
    paddingInline: "5px 2px",
  },
  sectionLabel: {
    color: tokens.colorContentSecondary,
    fontSize: "12px",
    fontWeight: 500,
    lineHeight: "14.5px",
  },
  sectionAction: { marginLeft: "auto" },
  submenu: {
    display: "flex",
    flexDirection: "column",
    listStyle: "none",
    margin: 0,
    padding: "0 0 0 19px",
  },
});
