import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  trigger: {
    alignItems: "center",
    backgroundColor: "transparent",
    borderStyle: "none",
    color: tokens.colorContentPrimary,
    cursor: "pointer",
    display: "inline-flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    gap: "8px",
    height: "32px",
    outline: "none",
    paddingInline: "12px",
  },
  positioner: { outline: 0, zIndex: 60 },
  popup: {
    backgroundColor: tokens.colorSurfacePopover,
    borderColor: tokens.colorBorderPopover,
    borderRadius: "12px",
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxShadow:
      "0 1px 0.5px rgba(0,0,0,0.13), 0 2px 2.5px rgba(0,0,0,0.13), 0 3px 4px rgba(0,0,0,0.13)",
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    minWidth: "210px",
    outline: 0,
    paddingBottom: "5px",
    paddingTop: "6px",
    transformOrigin: "var(--transform-origin)",
    width: "210px",
  },
  submenuPopup: {
    boxShadow:
      "0 1px 0.5px rgba(0,0,0,0.04), 0 2px 4px rgba(0,0,0,0.04), 0 1px 0.5px rgba(0,0,0,0.04), 0 6px 12px rgba(0,0,0,0.10), 0 9px 24px rgba(0,0,0,0.08)",
    minWidth: "232px",
    width: "232px",
  },
  item: {
    alignItems: "center",
    backgroundColor: {
      default: "transparent",
      "[data-highlighted]": tokens.colorSurfaceOverlayHover,
      '[data-visual-state="hover"]': tokens.colorSurfaceOverlayHover,
      '[data-visual-state="pressed"]': tokens.colorSurfaceOverlayHover,
    },
    borderRadius: "8px",
    boxSizing: "border-box",
    color: tokens.colorContentPrimary,
    cursor: "default",
    display: "flex",
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 400,
    gap: "8px",
    height: "32px",
    lineHeight: "19.5px",
    marginInline: "6px",
    outline: 0,
    paddingLeft: "8px",
    paddingRight: "12px",
    textDecoration: "none",
    userSelect: "none",
  },
  danger: {
    backgroundColor: {
      default: "transparent",
      "[data-highlighted]": tokens.colorStatusErrorSurface,
      '[data-visual-state="hover"]': tokens.colorStatusErrorSurface,
      '[data-visual-state="pressed"]': tokens.colorStatusErrorSurface,
    },
    color: tokens.colorStatusErrorContent,
  },
  disabled: { cursor: "not-allowed", opacity: 0.42 },
  leading: {
    alignItems: "center",
    color: "currentColor",
    display: "inline-flex",
    flex: "0 0 16px",
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  label: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  trailing: {
    alignItems: "center",
    color: tokens.colorContentSecondary,
    display: "inline-flex",
    flexShrink: 0,
    gap: "6px",
  },
  shortcut: { fontFamily: tokens.fontSans, fontSize: "11px", fontWeight: 500, lineHeight: "16px" },
  submenuIcon: { height: "16px", strokeWidth: "1.5px", width: "16px" },
  submenuIconSlot: {
    alignItems: "center",
    display: "inline-flex",
    flex: "0 0 16px",
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  separator: {
    backgroundImage: `linear-gradient(to bottom, transparent 5.75px, ${tokens.colorBorderTertiary} 5.75px, ${tokens.colorBorderTertiary} 6.25px, transparent 6.25px)`,
    borderWidth: 0,
    height: "12px",
    marginInline: "8px",
  },
  separatorLine: { backgroundColor: tokens.colorBorderTertiary, height: "0.5px", width: "100%" },
  groupLabel: {
    color: tokens.colorContentTertiary,
    fontFamily: tokens.fontSans,
    fontSize: "11px",
    lineHeight: "16px",
    padding: "6px 14px 2px",
  },
  hint: {
    color: tokens.colorContentTertiary,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    lineHeight: "19.5px",
    margin: 0,
    padding: "3px 14px 7px",
  },
  indicator: {
    alignItems: "center",
    display: "inline-flex",
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
});
