/** HeroUI v3.2.6 derived work. Copyright NextUI Inc. Apache-2.0. Modified for StyleX. */
import * as stylex from "@stylexjs/stylex";
import { focusRing } from "../../focus-ring.stylex.const.js";
import { tokens } from "../../tokens.stylex.const.js";
export const calendarYearPickerStyles = stylex.create({
  trigger: {
    display: "flex",
    flex: 1,
    alignItems: "center",
    justifyContent: "start",
    gap: 4,
    borderRadius: tokens.radiusLg,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: tokens.foreground,
    padding: 0,
    outline: "none",
    cursor: "pointer",
    touchAction: "manipulation",
  },
  heading: { fontSize: 14, fontWeight: 500 },
  indicator: { display: "inline-flex", fontSize: 12, color: tokens.accentSoftForeground },
  openIndicator: { transform: "rotate(90deg)" },
  grid: {
    position: "absolute",
    insetInline: 0,
    display: "grid",
    gridTemplateColumns: "repeat(3,1fr)",
    alignContent: "start",
    gap: 4,
    overflowY: "auto",
    padding: 4,
    opacity: 1,
    transitionProperty: "opacity",
    transitionDuration: { default: "200ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionDelay: { default: "50ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: tokens.easeSmooth,
  },
  hidden: {
    visibility: "hidden",
    pointerEvents: "none",
    opacity: 0,
    transitionDuration: "0ms",
    transitionDelay: "0ms",
  },
  cell: {
    position: "relative",
    display: "inline-flex",
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: tokens.radius3xl,
    paddingInline: 10,
    fontSize: 14,
    fontWeight: 500,
    borderWidth: 0,
    backgroundColor: "transparent",
    color: tokens.foreground,
    outline: "none",
    cursor: "pointer",
    userSelect: "none",
    touchAction: "manipulation",
  },
  hovered: { backgroundColor: tokens.default, color: tokens.defaultForeground },
  selected: { backgroundColor: tokens.accent, color: tokens.accentForeground },
  selectedHovered: { backgroundColor: tokens.accentHover },
  focused: { outline: "none", boxShadow: focusRing.outer },
});
