/** HeroUI v3.2.6 derived work. Copyright NextUI Inc. Apache-2.0. Modified for StyleX. */
import * as stylex from "@stylexjs/stylex";
import { focusRing } from "../../focus-ring.stylex.const.js";
import { tokens } from "../../tokens.stylex.const.js";
export const colorSwatchPickerStyles = stylex.create({
  root: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8 },
  stack: { flexDirection: "column" },
  item: {
    position: "relative",
    display: "flex",
    width: 32,
    height: 32,
    boxSizing: "border-box",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: tokens.radius2xl,
    borderWidth: 2,
    borderStyle: "solid",
    borderColor: "transparent",
    "--lenso-focus-elevation": "0 0 #0000",
    outline: "none",
    cursor: "pointer",
  },
  selected: { "--lenso-focus-elevation": tokens.fieldShadow, boxShadow: focusRing.elevation },
  focused: { outline: "none", boxShadow: focusRing.outerElevated },
  disabled: { opacity: tokens.disabledOpacity },
  xs: { width: 16, height: 16, borderRadius: tokens.radiusLg, borderWidth: 1 },
  sm: { width: 24, height: 24, borderRadius: tokens.radiusXl },
  md: { width: 32, height: 32 },
  lg: { width: 36, height: 36, borderRadius: tokens.radius3xl, borderWidth: 3 },
  xl: { width: 40, height: 40, borderRadius: tokens.radius3xl, borderWidth: 3 },
  square: { borderRadius: tokens.radiusXl },
  swatch: {
    display: "block",
    width: "100%",
    height: "100%",
    borderRadius: "inherit",
    transitionProperty: "transform",
    transitionDuration: { default: "100ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: tokens.easeSmooth,
  },
  selectedSwatch: { transform: "scale(.77)" },
  indicator: {
    pointerEvents: "none",
    position: "absolute",
    inset: 0,
    zIndex: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
  },
  lightIndicator: { color: "black" },
  hidden: { visibility: "hidden" },
});
