/** HeroUI v3.2.6 demo utilities, adapted to StyleX. Apache-2.0. */
import * as stylex from "@stylexjs/stylex";

export const styles = stylex.create({
  column: { display: "flex", flexDirection: "column", gap: 16 },
  column2: { display: "flex", flexDirection: "column", gap: 8 },
  column6: { display: "flex", flexDirection: "column", gap: 24 },
  column8: { display: "flex", flexDirection: "column", gap: 32 },
  centeredColumn: { display: "flex", flexDirection: "column", alignItems: "center", gap: 24 },
  row: { display: "flex", alignItems: "center", gap: 12 },
  row2: { display: "flex", alignItems: "center", gap: 8 },
  row4: { display: "flex", alignItems: "center", gap: 16 },
  controls: { display: "flex", gap: 16 },
  xs: { width: "100%", maxWidth: 320 },
  sm: { width: "100%", maxWidth: 384 },
  width280: { width: 280, maxWidth: "100%" },
  width300: { width: 300, maxWidth: "100%" },
  width320: { width: 320, maxWidth: "100%" },
  width400: { width: 400, maxWidth: "100%" },
  width100: { width: 100 },
  width128: { width: 128 },
  width144: { width: 144 },
  width32: { width: 32 },
  full: { width: "100%" },
  muted: { fontSize: 14, lineHeight: "20px", color: "var(--muted)" },
  small: { fontSize: 14, lineHeight: "20px" },
  medium: { fontWeight: 500 },
  label: { fontWeight: 500, color: "var(--foreground)" },
  mono: { fontFamily: "var(--font-mono)" },
  uppercase: { textTransform: "uppercase" },
  capitalize: { textTransform: "capitalize" },
  output: { color: "var(--muted)" },
  area: { maxWidth: "100%" },
  slider: { gap: 4, paddingInline: 4 },
  swatches: { justifyContent: "center", paddingInline: 4 },
  presets: { justifyContent: "center", paddingTop: 8 },
  popover: { gap: 8 },
  narrowPopover: { maxWidth: 248, gap: 8 },
  slidersPopover: { maxWidth: 248, gap: 8, paddingInline: 8, paddingBlock: 12 },
  channelGrid: {
    display: "grid",
    width: "100%",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    alignItems: "center",
    gap: 8,
  },
  hueRow: { display: "flex", alignItems: "center", gap: 8, paddingInline: 4 },
  flex1: { flex: 1 },
  icon: { width: 16, height: 16 },
  selected: { width: 240, fontSize: 14, color: "var(--muted)" },
  trigger: {
    borderRadius: 12,
    backgroundColor: "var(--default-soft)",
    paddingInline: 12,
    paddingBlock: 8,
  },
  surface: { backgroundColor: "var(--surface)" },
  selectPositioner: { zIndex: 100001 },
  vertical: { display: "flex", height: 192, gap: 16 },
  areaCustom: { width: 176, height: 176, borderRadius: 24 },
  areaThumb: { width: 20, height: 20, borderRadius: "50%", borderWidth: 4, borderColor: "white" },
  preview: {
    width: 32,
    height: 32,
    borderRadius: 6,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--default)",
  },
  code: {
    borderRadius: 4,
    backgroundColor: "color-mix(in oklab,var(--default) 50%,transparent)",
    paddingInline: 8,
    paddingBlock: 4,
    fontSize: 14,
  },
  track: {
    height: 16,
    borderRadius: 0,
    boxShadow: "0 0 0 1px var(--border)",
    "::before": { borderTopLeftRadius: 2, borderBottomLeftRadius: 2 },
    "::after": { borderTopRightRadius: 2, borderBottomRightRadius: 2 },
  },
  thumb: {
    width: 16,
    height: 16,
    borderRadius: 2,
    borderWidth: 2,
    borderColor: "var(--background)",
    boxShadow: "var(--shadow-md), 0 0 0 1px light-dark(rgb(0 0 0 / .1),rgb(255 255 255 / .2))",
  },
  tabular: { color: "var(--muted)", fontVariantNumeric: "tabular-nums" },
  customField: { width: "100%", maxWidth: 320, gap: 6 },
  customGroup: {
    borderRadius: 12,
    backgroundColor: "var(--default)",
    boxShadow: {
      default: "none",
      ":focus-within": "0 0 0 2px color-mix(in oklab,var(--accent) 15%,transparent)",
    },
  },
  square: { borderRadius: 6 },
  customInput: {
    fontFamily: "var(--font-mono)",
    fontSize: 14,
    color: "var(--foreground)",
    "::placeholder": { color: "var(--muted)" },
  },
  padded: { padding: 16 },
  pickerCustom: {
    borderRadius: 16,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "color-mix(in oklab,var(--border) 80%,transparent)",
    backgroundColor: "var(--surface)",
    padding: 16,
    boxShadow: "var(--shadow-sm),0 0 0 1px color-mix(in oklab,var(--accent) 5%,transparent)",
  },
});
