import * as stylex from "@stylexjs/stylex";
import { focusRing } from "../../focus-ring.stylex.const.js";
import { tokens } from "../../tokens.stylex.const.js";
export const tabsStyles = stylex.create({
  root: { display: "flex", gap: 8, minWidth: 0 },
  horizontal: { flexDirection: "column" },
  vertical: { flexDirection: "row" },
  listContainer: {
    position: "relative",
    minWidth: 0,
    backgroundColor: tokens.default,
    borderRadius: `calc(${tokens.radiusLg} * 2.5)`,
  },
  scroller: {
    height: { default: "auto", ':is([data-orientation="vertical"])': "100%" },
  },
  list: { position: "relative", isolation: "isolate", display: "inline-flex", padding: 4 },
  listHorizontal: { width: "max-content", minWidth: "100%", flexDirection: "row" },
  listVertical: { flexDirection: "column", gap: 4 },
  tab: {
    position: "relative",
    display: "flex",
    height: 32,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 0,
    borderRadius: tokens.radius3xl,
    paddingInline: 16,
    textAlign: "center",
    fontFamily: tokens.fontSans,
    fontSize: 14,
    lineHeight: "20px",
    fontWeight: 500,
    color: { default: tokens.muted, ":is([data-active])": tokens.segmentForeground },
    backgroundColor: "transparent",
    outlineStyle: "none",
    cursor: {
      default: tokens.cursorInteractive,
      ":disabled": tokens.cursorDisabled,
      ":is([data-disabled])": tokens.cursorDisabled,
    },
    pointerEvents: { default: "auto", ":disabled": "none", ":is([data-disabled])": "none" },
    WebkitTapHighlightColor: "transparent",
    zIndex: 1,
    transitionProperty: "color, background-color, box-shadow, opacity",
    transitionDuration: { default: "150ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: tokens.easeSmooth,
    opacity: {
      default: 1,
      ":is([data-disabled])": tokens.disabledOpacity,
      ":disabled": tokens.disabledOpacity,
      "@media (hover: hover)": {
        default: null,
        ":hover:not([data-active]):not([data-disabled])": 0.7,
      },
    },
    boxShadow: {
      default: "none",
      ":focus-visible": focusRing.outer,
    },
  },
  tabVertical: { minWidth: 80 },
  alignStart: { justifyContent: "start", textAlign: "start" },
  alignEnd: { justifyContent: "end", textAlign: "end" },
  separator: {
    position: "absolute",
    pointerEvents: "none",
    borderRadius: tokens.radiusSm,
    backgroundColor: `color-mix(in srgb, ${tokens.muted} 25%, transparent)`,
    opacity: {
      default: 1,
      ":is([data-active] *)": 0,
      ':is([data-active] + [data-slot="tabs-tab"] *)': 0,
    },
    transitionProperty: "opacity",
    transitionDuration: { default: "150ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: tokens.easeSmooth,
  },
  separatorHorizontal: { insetInlineStart: 0, top: "25%", height: "50%", width: 1 },
  separatorVertical: { insetInlineStart: "5%", top: 0, height: 1, width: "90%" },
  panel: { width: "100%", padding: 8, outlineStyle: "none" },
  panelHorizontal: { marginTop: 16 },
  panelVertical: { marginInlineStart: 16 },
  indicator: {
    position: "absolute",
    left: 0,
    top: 0,
    width: "var(--active-tab-width)",
    height: "var(--active-tab-height)",
    translate: "var(--active-tab-left) var(--active-tab-top)",
    borderRadius: tokens.radius3xl,
    backgroundColor: tokens.segment,
    boxShadow: tokens.shadowSurface,
    zIndex: 0,
    pointerEvents: "none",
    transitionProperty: "translate, width, height",
    transitionDuration: { default: "250ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: "cubic-bezier(0.32, 0.72, 0, 1)",
  },
  secondaryContainer: {
    borderRadius: 0,
    backgroundColor: "transparent",
    borderColor: tokens.border,
    borderStyle: "solid",
    borderWidth: 0,
  },
  secondaryHorizontal: { borderBottomWidth: 1 },
  secondaryVertical: { borderInlineStartWidth: 1 },
  secondaryList: { padding: 0 },
  secondaryTab: {
    borderRadius: 0,
    color: { default: tokens.muted, ":is([data-active])": tokens.foreground },
  },
  secondaryIndicator: { borderRadius: 0, backgroundColor: tokens.accent, boxShadow: "none" },
  secondaryIndicatorHorizontal: {
    top: "auto",
    bottom: 0,
    height: 2,
    translate: "var(--active-tab-left) 0",
  },
  secondaryIndicatorVertical: {
    left: { default: 0, ":dir(rtl)": "auto" },
    right: { default: "auto", ":dir(rtl)": 0 },
    width: 2,
    translate: "0 var(--active-tab-top)",
  },
  hidden: { display: "none" },
  showPrevious: {
    display: {
      default: "none",
      ':is([data-slot="tabs-list-container"]:has(> :is([data-left-scroll="true"], [data-left-right-scroll="true"], [data-top-scroll="true"], [data-top-bottom-scroll="true"])) > *)':
        "inline-flex",
    },
  },
  showNext: {
    display: {
      default: "none",
      ':is([data-slot="tabs-list-container"]:has(> :is([data-right-scroll="true"], [data-left-right-scroll="true"], [data-bottom-scroll="true"], [data-top-bottom-scroll="true"])) > *)':
        "inline-flex",
    },
  },
  scrollButton: {
    position: "absolute",
    zIndex: 2,
    display: "inline-flex",
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "50%",
    borderWidth: 0,
    backgroundColor: "transparent",
    padding: 0,
    color: tokens.foreground,
    cursor: tokens.cursorInteractive,
    outlineStyle: "none",
    boxShadow: {
      default: "none",
      ":focus-visible": focusRing.outer,
    },
    opacity: { default: 1, "@media (hover: hover)": { default: null, ":hover": 0.7 } },
    transitionProperty: "opacity",
    transitionDuration: { default: "150ms", "@media (prefers-reduced-motion: reduce)": "0ms" },
    transitionTimingFunction: tokens.easeSmooth,
  },
  previousHorizontal: {
    insetInlineStart: 4,
    top: "50%",
    translate: "0 -50%",
    rotate: { default: "0deg", ":dir(rtl)": "180deg" },
  },
  nextHorizontal: {
    insetInlineEnd: 4,
    top: "50%",
    translate: "0 -50%",
    rotate: { default: "0deg", ":dir(rtl)": "180deg" },
  },
  previousVertical: { top: 4, left: "50%", translate: "-50% 0", rotate: "90deg" },
  nextVertical: { bottom: 4, left: "50%", translate: "-50% 0", rotate: "90deg" },
});
