import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

const darkTheme = ':where([data-theme="dark"] *)';

// Figma Toast 256:11 Dark mode values resolved from its Color and Elevation modes.
const darkToastSurface = "#212122";
const darkToastContentPrimary = "#ffffff";
const darkToastContentSecondary = "#d4d4d4";
const darkToastSuccess = "#00a63e";
const darkToastError = "#e5484d";
const toastInnerRadius = `calc(${tokens.radiusPopover} - 0.5px)`;
const lightToastShadow = `0 0 0 0.5px ${tokens.elevationToastRing}, 0 1px 1px ${tokens.elevationToastDetail}, 0 ${tokens.elevationToastKeyY} ${tokens.elevationToastKeyBlur} ${tokens.elevationToastKey}, 0 ${tokens.elevationToastAmbientY} ${tokens.elevationToastAmbientBlur} ${tokens.elevationToastAmbient}`;
const darkToastShadow = `0 0 0 0.5px #ffffff26, 0 1px 1px #00000020, 0 2px 5px #00000020, 0 3px 8px #00000020`;

export const styles = stylex.create({
  viewport: {
    bottom: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    maxWidth: "calc(100vw - 32px)",
    outline: "none",
    position: "fixed",
    right: "24px",
    width: "384px",
    zIndex: 100,
  },
  root: {
    alignItems: "center",
    backgroundColor: tokens.colorSurfaceDialog,
    borderColor: tokens.colorBorderTransparent,
    borderRadius: tokens.radiusPopover,
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxSizing: "border-box",
    color: tokens.colorContentSecondary,
    display: "flex",
    fontFamily: tokens.fontSans,
    gap: "8px",
    height: "41px",
    opacity: 1,
    outline: {
      default: "none",
      ":focus-visible": `1px solid ${tokens.colorFocusRing}`,
    },
    paddingBlock: "8px",
    paddingLeft: "12px",
    paddingRight: "40px",
    position: "relative",
    touchAction: "none",
    transform: "translateX(var(--toast-swipe-movement-x, 0))",
    transitionDuration: "180ms",
    transitionProperty: "opacity, transform",
    transitionTimingFunction: "ease-out",
    width: "384px",
    [darkTheme]: {
      backgroundColor: darkToastSurface,
      color: darkToastContentSecondary,
    },
    "::before": {
      backgroundColor: tokens.colorSurfaceDialog,
      borderRadius: toastInnerRadius,
      boxShadow: lightToastShadow,
      content: "''",
      height: "40px",
      left: 0,
      pointerEvents: "none",
      position: "absolute",
      top: 0,
      width: "383px",
      [darkTheme]: {
        backgroundColor: darkToastSurface,
        boxShadow: darkToastShadow,
      },
    },
    "[data-starting-style]": { opacity: 0, transform: "translateY(8px)" },
    "[data-ending-style]": { opacity: 0, transform: "translateY(8px)" },
    "[data-swipe-direction='right']": {
      transform: "translateX(calc(var(--toast-swipe-movement-x, 0px) + 110%))",
    },
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
  content: {
    alignItems: "center",
    display: "flex",
    gap: "8px",
    minWidth: 0,
    width: "100%",
    zIndex: 1,
  },
  icon: {
    alignItems: "center",
    display: "inline-flex",
    flex: "0 0 16px",
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  infoIcon: {
    alignItems: "center",
    backgroundColor: tokens.colorContentSecondary,
    borderRadius: tokens.radiusRounded,
    color: tokens.colorContentInverse,
    display: "inline-flex",
    fontFamily: tokens.fontSans,
    fontSize: "9px",
    fontStyle: "normal",
    fontWeight: 500,
    height: "14px",
    justifyContent: "center",
    lineHeight: "10px",
    width: "14px",
    [darkTheme]: {
      backgroundColor: darkToastContentSecondary,
      color: darkToastSurface,
    },
  },
  success: { color: tokens.colorStatusSuccessContent, [darkTheme]: { color: darkToastSuccess } },
  error: { color: tokens.colorStatusErrorContent, [darkTheme]: { color: darkToastError } },
  statusGlyph: {
    fontFamily: tokens.fontSans,
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "16px",
  },
  text: {
    color: tokens.colorContentSecondary,
    flex: 1,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 500,
    lineHeight: "15px",
    margin: 0,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  textStack: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  title: { color: "#000000", [darkTheme]: { color: darkToastContentPrimary } },
  close: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": tokens.colorSurfaceQuaternary },
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: tokens.radiusRounded,
    color: tokens.colorContentSecondary,
    cursor: "pointer",
    display: "inline-flex",
    height: "24px",
    justifyContent: "center",
    outline: { default: "none", ":focus-visible": `1px solid ${tokens.colorFocusRing}` },
    outlineOffset: "0px",
    padding: 0,
    position: "absolute",
    right: "7.5px",
    top: "7.5px",
    width: "24px",
    [darkTheme]: { color: darkToastContentSecondary },
  },
  closeIcon: {
    alignItems: "center",
    display: "inline-flex",
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  action: {
    background: "transparent",
    border: 0,
    color: "#000000",
    cursor: "pointer",
    font: "inherit",
    outline: { default: "none", ":focus-visible": `1px solid ${tokens.colorFocusRing}` },
    outlineOffset: "0px",
    padding: 0,
    [darkTheme]: { color: darkToastContentPrimary },
  },
});
