import * as stylex from "@stylexjs/stylex";

import { tokens } from "../tokens.stylex.js";

export const styles = stylex.create({
  viewport: {
    bottom: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    maxWidth: "calc(100vw - 32px)",
    outline: "none",
    position: "fixed",
    right: "24px",
    width: "384px",
    zIndex: 100,
  },
  root: {
    alignItems: "center",
    backgroundColor: tokens.colorSurfaceDialog,
    borderColor: tokens.colorBorderTransparent,
    borderRadius: tokens.radiusPopover,
    borderStyle: "solid",
    borderWidth: "0.5px",
    boxSizing: "border-box",
    color: tokens.colorContentSecondary,
    display: "flex",
    fontFamily: tokens.fontSans,
    gap: "8px",
    height: "41px",
    opacity: 1,
    outline: {
      default: "none",
      ":focus-visible": `1px solid ${tokens.colorFocusRing}`,
    },
    paddingBlock: "8px",
    paddingLeft: "12px",
    paddingRight: "40px",
    position: "relative",
    touchAction: "none",
    transform: "translateX(var(--toast-swipe-movement-x, 0))",
    transitionDuration: "180ms",
    transitionProperty: "opacity, transform",
    transitionTimingFunction: "ease-out",
    width: "384px",
    "::before": {
      backgroundColor: tokens.colorSurfaceDialog,
      borderRadius: tokens.radiusPopover,
      boxShadow: `0 0 0 0.5px ${tokens.elevationToastRing}, 0 1px 1px ${tokens.elevationToastDetail}, 0 ${tokens.elevationToastKeyY} ${tokens.elevationToastKeyBlur} ${tokens.elevationToastKey}, 0 ${tokens.elevationToastAmbientY} ${tokens.elevationToastAmbientBlur} ${tokens.elevationToastAmbient}`,
      content: "''",
      height: "40px",
      left: 0,
      pointerEvents: "none",
      position: "absolute",
      top: 0,
      width: "383px",
    },
    "[data-starting-style]": { opacity: 0, transform: "translateY(8px)" },
    "[data-ending-style]": { opacity: 0, transform: "translateY(8px)" },
    "[data-swipe-direction='right']": {
      transform: "translateX(calc(var(--toast-swipe-movement-x, 0px) + 110%))",
    },
    "@media (prefers-reduced-motion: reduce)": { transitionDuration: "0ms" },
  },
  content: {
    alignItems: "center",
    display: "flex",
    gap: "8px",
    minWidth: 0,
    position: "relative",
    width: "100%",
    zIndex: 1,
  },
  icon: {
    alignItems: "center",
    display: "inline-flex",
    flex: "0 0 16px",
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  infoIcon: {
    alignItems: "center",
    backgroundColor: tokens.colorContentPrimary,
    borderRadius: tokens.radiusRounded,
    color: tokens.colorContentInverse,
    display: "inline-flex",
    fontFamily: tokens.fontSans,
    fontSize: "9px",
    fontStyle: "normal",
    fontWeight: 500,
    height: "14px",
    justifyContent: "center",
    lineHeight: "10px",
    width: "14px",
  },
  success: { color: tokens.colorStatusSuccessContent },
  error: { color: tokens.colorStatusErrorContent },
  statusGlyph: {
    fontFamily: tokens.fontSans,
    fontSize: "14px",
    fontWeight: 500,
    lineHeight: "16px",
  },
  text: {
    color: tokens.colorContentSecondary,
    flex: 1,
    fontFamily: tokens.fontSans,
    fontSize: "13px",
    fontWeight: 500,
    lineHeight: "15px",
    margin: 0,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  textStack: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    minWidth: 0,
  },
  title: { color: tokens.colorContentPrimary },
  close: {
    alignItems: "center",
    backgroundColor: { default: "transparent", ":hover": tokens.colorSurfaceQuaternary },
    borderStyle: "none",
    borderWidth: 0,
    borderRadius: tokens.radiusRounded,
    color: tokens.colorContentSecondary,
    cursor: "pointer",
    display: "inline-flex",
    height: "24px",
    justifyContent: "center",
    padding: 0,
    position: "absolute",
    right: "8px",
    top: "8px",
    width: "24px",
  },
  closeIcon: {
    alignItems: "center",
    display: "inline-flex",
    height: "16px",
    justifyContent: "center",
    width: "16px",
  },
  action: {
    background: "transparent",
    border: 0,
    color: tokens.colorContentPrimary,
    cursor: "pointer",
    font: "inherit",
    padding: 0,
  },
});
